<div style="background-color: black;">
    <hr style="border: 4px solid skyblue;">
    <div style="text-align: center; margin-left: 0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color: skyblue">
    Techno - Economic Parameters Data Proscessing
</div>
    <div style="text-align: center; margin-left: 0em; font-weight: bold; font-size: 22px; font-family: TimesNewRoman; color: skyblue;     font-style: italic;">
    POWER PLANTS
</div>
    <div style="text-align: center; margin-left: 0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color: skyblue">
        Main Formatting Notebook
    </div>
    <table style="
        font-weight: bold;
        font-size: 16px;
        font-family: 'Times New Roman';
        color: skyblue;
        margin-left: auto;
        margin-right: auto;
        text-align: left;
        border: none;
        background-color: black;
        border-collapse: collapse;
    ">
        <tr>
            <td style="padding-right: 60px; border: none; background-color: black;">from</td>
            <td style="border: none; background-color: black;">to</td>
        </tr>
        <tr>
            <td style="padding-right: 60px; border: none; background-color: black; font-style: italic; font-size: 20px;">PYPSA | négaWatt</td>
            <td style="border: none; background-color: black; font-style: italic; font-size: 20px;">DISPA-SET | Unleash</td>
        </tr>
    </table>
<div style="text-align: justify; margin-left: 0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The following script processes raw data from the PyPSA model simulation results, specifically focusing on power plant units for the Dispa-SET_Unleash project.
    <br>
Please refer to the explanatory text cells for a step-by-step guide to the data processing workflow and the derivation of the final results.
</div>
<br>
<hr style="border: 2px dashed skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    1. Notebook Set Up
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Importing needed libraries.
<hr style="border: 1px solid skyblue;">
</div>
</div>

In [1]:
import os
import csv
from datetime import datetime
import requests
import pandas as pd
from shutil import move
import numpy as np
import shutil
from bs4 import BeautifulSoup
import re
import io
import plotly.graph_objects as go
from typing import List, Dict, Tuple
import re
from IPython.display import HTML
from difflib import get_close_matches
from pathlib import Path
import json

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Auxiliar Code
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cell has the purpose to create the correponding folders with the name of all the EU countries available in the ENTSOE data base.
    <br>
    Uncomment it to use it just if needed.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [2]:
"""
# List of countries with their acronyms in parentheses
countries = [
    "Albania       (AL)", "Armenia        (AM)", "Austria          (AT)", "Azerbaijan (AZ)",
    "Belarus       (BY)", "Belgium        (BE)", "Bosnia and Herz. (BA)", "Bulgaria   (BG)",
    "Croatia       (HR)", "Cyprus         (CY)", "Czech Republic   (CZ)", "Denmark    (DK)",
    "Estonia       (EE)", "Finland        (FI)", "France           (FR)", "Georgia    (GE)",
    "Germany       (DE)", "Greece         (EL)", "Hungary          (HU)", "Iceland    (IS)",
    "Ireland       (IE)", "Italy          (IT)", "Kosovo           (XK)", "Latvia     (LV)",
    "Lithuania     (LT)", "Luxembourg     (LU)", "Malta            (MT)", "Moldova    (MD)",
    "Montenegro    (ME)", "Netherlands    (NL)", "North Macedonia  (MK)", "Norway     (NO)",
    "Poland        (PL)", "Portugal       (PT)", "Romania          (RO)", "Russia     (RU)",
    "Russia Legacy (RU)", "Serbia         (RS)", "Slovakia         (SK)", "Slovenia   (SI)",
    "Spain         (ES)", "Sweden         (SE)", "Switzerland      (CH)", "Turkey     (TR)",
    "Ukraine       (UA)", "United Kingdom (UK)"
]

# Set the path where you want to create the folders
base_path = '/home/ray/Dispa-SET_Unleash/Database_PyPSA/Suficiency_Scenario/PowerPlants'

# Ensure the base path exists
os.makedirs(base_path, exist_ok=True)

# Loop through the list of countries
for country_string in countries:
    # Use a regular expression to find the acronym inside the parentheses
    match = re.search(r'\((.*?)\)', country_string)

    # If a match is found, extract the acronym
    if match:
        acronym = match.group(1).strip()  # Use strip() to remove any extra whitespace
        folder_path = os.path.join(base_path, acronym)

        # Check if the folder already exists to avoid errors
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
            print(f"Created folder: {folder_path}")
        else:
            print(f"Folder already exists: {folder_path}")
    else:
        print(f"Could not extract acronym from: {country_string}")

print("\nAll folders created successfully!")
"""

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
/tmp/ipykernel_294897/535168893.py:1: SyntaxWarning: invalid escape sequence '\('
  """

'\n# List of countries with their acronyms in parentheses\ncountries = [\n    "Albania       (AL)", "Armenia        (AM)", "Austria          (AT)", "Azerbaijan (AZ)",\n    "Belarus       (BY)", "Belgium        (BE)", "Bosnia and Herz. (BA)", "Bulgaria   (BG)",\n    "Croatia       (HR)", "Cyprus         (CY)", "Czech Republic   (CZ)", "Denmark    (DK)",\n    "Estonia       (EE)", "Finland        (FI)", "France           (FR)", "Georgia    (GE)",\n    "Germany       (DE)", "Greece         (EL)", "Hungary          (HU)", "Iceland    (IS)",\n    "Ireland       (IE)", "Italy          (IT)", "Kosovo           (XK)", "Latvia     (LV)",\n    "Lithuania     (LT)", "Luxembourg     (LU)", "Malta            (MT)", "Moldova    (MD)",\n    "Montenegro    (ME)", "Netherlands    (NL)", "North Macedonia  (MK)", "Norway     (NO)",\n    "Poland        (PL)", "Portugal       (PT)", "Romania          (RO)", "Russia     (RU)",\n    "Russia Legacy (RU)", "Serbia         (RS)", "Slovakia         (SK)", "Slovenia   (SI)",\n    "Spain         (ES)", "Sweden         (SE)", "Switzerland      (CH)", "Turkey     (TR)",\n    "Ukraine       (UA)", "United Kingdom (UK)"\n]\n\n# Set the path where you want to create the folders\nbase_path = \'/home/ray/Dispa-SET_Unleash/Database_PyPSA/Suficiency_Scenario/PowerPlants\'\n\n# Ensure the base path exists\nos.makedirs(base_path, exist_ok=True)\n\n# Loop through the list of countries\nfor country_string in countries:\n    # Use a regular expression to find the acronym inside the parentheses\n    match = re.search(r\'\\((.*?)\\)\', country_string)\n\n    # If a match is found, extract the acronym\n    if match:\n        acronym = match.group(1).strip()  # Use strip() to remove any extra whitespace\n        folder_path = os.path.join(base_path, acronym)\n\n        # Check if the folder already exists to avoid errors\n        if not os.path.exists(folder_path):\n            os.makedirs(folder_path)\n            print(f"Created folder: {folder_path}")\n        else:\n            print(f"Folder already exists: {folder_path}")\n    else:\n        print(f"Could not extract acronym from: {country_string}")\n\nprint("\nAll folders created successfully!")\n'

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    2. Dispa-SET_Unleash Folder Path
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Determinning dynamically the zone_folder_path based on the location of the "Dispa-SET_Unleash" folder relative to the current working directory. 
<br>
    If the "Dispa-SET_Unleash" folder is copied to a different machine or location, the dispaSET_unleash_folder_path variable will automatically adjust accordingly.
</div>
<hr style="border: 1px solid skyblue;">
</div>

In [3]:
# 1. ******************************************************************************** Get the current working directory 
current_directory = os.getcwd()

# 2. ********************************************************** Navigate to the parent directory of "Dispa-SET_Unleash" 
dispaSET_unleash_parent_directory = os.path.dirname(current_directory)

# 3. ******************************************************************* Get the path to the "Dispa-SET_Unleash" folder 
dispaSET_unleash_folder_path = os.path.dirname(dispaSET_unleash_parent_directory)

# 4. ************************************************************** Construct the dispaSET_unleash_folder_name variable 
dispaSET_unleash_folder_name = os.path.basename(dispaSET_unleash_folder_path)

# 5. ************************************************************************************************************* Done
print("dispaSET_unleash_folder_name:", dispaSET_unleash_folder_name)
print("dispaSET_unleash_folder_path:", dispaSET_unleash_folder_path)

dispaSET_unleash_folder_name: Dispa-SET_Unleash
dispaSET_unleash_folder_path: /home/ray/Dispa-SET_Unleash

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
2.1. PyPSA Source Scenario
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
There are two sccenarios as source of PyPSA power plants raw data.
</div>
<div style="text-align: justify; margin-left: 2.0em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman; color:skyblue">
<li>
Reference_Scenario
<li>
Suficiency_Scenario
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The scenario variable must be selected before proceeding to the next processing steps
</div>
<hr style="border: 1px solid skyblue;">
</div>

In [4]:
# 1. ****************************************************************************************** Set the needed scenatio 
#pypsa_scenario = "Reference_Scenario"
pypsa_scenario = "Sufficiency_Scenario"

# 2. ************************************************************************************************************* Done 
print("PyPSA Chosen Scenario:", pypsa_scenario)

PyPSA Chosen Scenario: Sufficiency_Scenario

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
2.2. Secondary Folders Path
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The many subfolders within the Unleash directory require their location paths to be defined for correct access during processing.
<br>
All of these are dependent on the chosen scenario.
</div>
<hr style="border: 1px solid skyblue;">
</div>

In [5]:
# 1. ***************************** Get the path to the "Dispa-SET_Unleash_Power_Plants" folder of the data used as base 
additional_path_1 = "/Database/PowerPlants"
power_plants_base_data_folder_path = dispaSET_unleash_folder_path + additional_path_1

# 2. ******************* Construct the dispaSET_unleash_power_plants_folder_name variable of the data used as reference 
power_plants_base_data_folder_name = os.path.basename(power_plants_base_data_folder_path)

# 3. ************************************************************************************************************* Done 
print("power_plants_base_data_folder_name:", power_plants_base_data_folder_name)
print("power_plants_base_data_folder_path:", power_plants_base_data_folder_path)
# *********************************************************************************************************************************************

# 1. ******************************** Get the path to the "Dispa-SET_Unleash_Power_Plants" folder of the PyPSA raw data 
additional_path_2 = os.path.join("RawData_PyPSA", pypsa_scenario, "PowerPlants")
power_plants_pypsa_raw_data_folder_path = dispaSET_unleash_folder_path + '/' + additional_path_2

# 2. *************************** Construct the dispaSET_unleash_power_plants_folder_name variable of the PyPSA raw data 
power_plants_pypsa_raw_data_folder_name = os.path.basename(power_plants_pypsa_raw_data_folder_path)

# 3. ************************************************************************************************************* Done 
print("power_plants_pypsa_raw_data_folder_name:", power_plants_pypsa_raw_data_folder_name)
print("power_plants_pypsa_raw_data_folder_path:", power_plants_pypsa_raw_data_folder_path)
# *********************************************************************************************************************************************

# 1. *************************** Get the path to the "Dispa-SET_Unleash_Power_Plants" folder of the PyPSA formated data 
additional_path_3 = os.path.join("Database_PyPSA", pypsa_scenario, "PowerPlants")
power_plants_pypsa_formated_data_folder_path = dispaSET_unleash_folder_path + '/' + additional_path_3

# 2. ********************** Construct the dispaSET_unleash_power_plants_folder_name variable of the PyPSA formated data 
power_plants_pypsa_formated_data_folder_name = os.path.basename(power_plants_pypsa_formated_data_folder_path)

# 3. ************************************************************************************************************* Done 
print("power_plants_pypsa_formated_data_folder_name:", power_plants_pypsa_formated_data_folder_name)
print("power_plants_pypsa_formated_data_folder_path:", power_plants_pypsa_formated_data_folder_path)

power_plants_base_data_folder_name: PowerPlants
power_plants_base_data_folder_path: /home/ray/Dispa-SET_Unleash/Database/PowerPlants
power_plants_pypsa_raw_data_folder_name: PowerPlants
power_plants_pypsa_raw_data_folder_path: /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants
power_plants_pypsa_formated_data_folder_name: PowerPlants
power_plants_pypsa_formated_data_folder_path: /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    3. Zone(s) Creation
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Entering the zone name or names (comment those ones that are not available data) where all data related to the corresponding zone are going to be storage
<br>
For European country names use the ISO 3166-1 standars i.e. AT, BE, BG, CH.... etc. to give the zone_name.
</div>
<hr style="border: 1px solid skyblue;">

In [6]:
# 1. ***************************************************************************** List of folder names to be addressed 
zone_names = [
                #"AL",
                #"AM",
                #"AT",
                #"AZ",
                #"BY",
                "BE",
                #"BA",
                #"BG",
                #"HR",
                #"CY",
                #"CZ",
                #"DK",
                #"EE",
                #"FI",
                "FR",
                #"GE",
                "DE",
                #"EL",
                #"HU",
                #"IS",
                #"IE",
                #"IT",
                #"XK",
                #"LV",
                #"LT",
                #"LU",
                #"MT",
                #"MD",
                #"ME",
                "NL",
                #"MK",
                #"NO",
                #"PL",
                #"PT",
                #"RO",
                #"RU",
                #"RS",
                #"SK",
                #"SI",
                #"ES",
                #"SE",
                #"CH",
                #"TR",
                #"UA",
                "UK"
             ]

# 2. ************************************************************************************************************* Done 
print("Selected Zones:", zone_names)

Selected Zones: ['BE', 'FR', 'DE', 'NL', 'UK']

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The following dictionary specifies the possible alternative names—or synonyms/aliases—used in international nomenclature for the EU countries.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [7]:
# 1. ********************************************************** Set the list of the alternative acronyms per EU country 
zone_names_equivalences_dict = {

"AL"  :  {"Acronym": ["  "       ] ,   "name": ["Albania   "       ]},  
"AM"  :  {"Acronym": ["  "       ] ,   "name": ["Armenia   "       ]},
"AT"  :  {"Acronym": ["  "       ] ,   "name": ["Austria   "       ]},
"AZ"  :  {"Acronym": ["  "       ] ,   "name": ["Azerbaijan"       ]},
"BY"  :  {"Acronym": ["  "       ] ,   "name": ["Belarus"          ]},
"BE"  :  {"Acronym": ["  "       ] ,   "name": ["Belgium"          ]},
"BA"  :  {"Acronym": ["  "       ] ,   "name": ["Bosnia and Herz." ]},
"BG"  :  {"Acronym": ["  "       ] ,   "name": ["Bulgaria"         ]},
"HR"  :  {"Acronym": ["  "       ] ,   "name": ["Croatia"          ]},
"CY"  :  {"Acronym": ["  "       ] ,   "name": ["Cyprus"           ]},
"CZ"  :  {"Acronym": ["  "       ] ,   "name": ["Czech Republic"   ]},
"DK"  :  {"Acronym": ["  "       ] ,   "name": ["Denmark"          ]},
"EE"  :  {"Acronym": ["  "       ] ,   "name": ["Estonia"          ]},
"FI"  :  {"Acronym": ["  "       ] ,   "name": ["Finland"          ]},
"FR"  :  {"Acronym": ["  "       ] ,   "name": ["France"           ]},
"GE"  :  {"Acronym": ["  "       ] ,   "name": ["Georgia"          ]}, 
"DE"  :  {"Acronym": ["  "       ] ,   "name": ["Germany"          ]},
"EL"  :  {"Acronym": ["GR"       ] ,   "name": ["Greece"           ]},
"HU"  :  {"Acronym": ["  "       ] ,   "name": ["Hungary"          ]},
"IS"  :  {"Acronym": ["  "       ] ,   "name": ["Iceland"          ]},
"IE"  :  {"Acronym": ["  "       ] ,   "name": ["Ireland"          ]},
"IT"  :  {"Acronym": ["  "       ] ,   "name": ["Italy"            ]},
"XK"  :  {"Acronym": ["  "       ] ,   "name": ["Kosovo"           ]},
"LV"  :  {"Acronym": ["  "       ] ,   "name": ["Latvia"           ]},
"LT"  :  {"Acronym": ["  "       ] ,   "name": ["Lithuania"        ]},
"LU"  :  {"Acronym": ["  "       ] ,   "name": ["Luxembourg"       ]},
"MT"  :  {"Acronym": ["  "       ] ,   "name": ["Malta"            ]},
"MD"  :  {"Acronym": ["  "       ] ,   "name": ["Moldova"          ]},
"ME"  :  {"Acronym": ["  "       ] ,   "name": ["Montenegro"       ]},
"NL"  :  {"Acronym": ["  "       ] ,   "name": ["Netherlands"      ]},
"MK"  :  {"Acronym": ["  "       ] ,   "name": ["North Macedonia"  ]},
"NO"  :  {"Acronym": ["  "       ] ,   "name": ["Norway"           ]},
"PL"  :  {"Acronym": ["  "       ] ,   "name": ["Poland"           ]},
"PT"  :  {"Acronym": ["  "       ] ,   "name": ["Portugal"         ]},
"RO"  :  {"Acronym": ["  "       ] ,   "name": ["Romania"          ]},
"RU"  :  {"Acronym": ["  "       ] ,   "name": ["Russia"           ]},
"RS"  :  {"Acronym": ["  "       ] ,   "name": ["Serbia"           ]},
"SK"  :  {"Acronym": ["  "       ] ,   "name": ["Slovakia"         ]},
"SI"  :  {"Acronym": ["  "       ] ,   "name": ["Slovenia"         ]},
"ES"  :  {"Acronym": ["  "       ] ,   "name": ["Spain"            ]},
"SE"  :  {"Acronym": ["  "       ] ,   "name": ["Sweden"           ]},
"CH"  :  {"Acronym": ["  "       ] ,   "name": ["Switzerland"      ]},
"TR"  :  {"Acronym": ["  "       ] ,   "name": ["Turkey"           ]},
"UA"  :  {"Acronym": ["  "       ] ,   "name": ["Ukraine"          ]},
"UK"  :  {"Acronym": ["GB"       ] ,   "name": ["United Kingdom"   ]},
       
}

# 2. ************************************************* Create a new dictionary with only the keys present in zone_names
selected_zone_names_equivalences_dict = {
    key: zone_names_equivalences_dict[key]
    for key in zone_names
    if key in zone_names_equivalences_dict
}

# 3. ************************************************************************************************************* Done 
for key, value in selected_zone_names_equivalences_dict.items():
    if any(acronym.strip() for acronym in value["Acronym"]):
        print(f"Key: {key};    Acronym: {value['Acronym']};    Name: {value['name']}\n")

Key: UK;    Acronym: ['GB'];    Name: ['United Kingdom']

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    4. Data Reference Year 
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Setting the variable on the target year which formatting data is wanted to
</div>
<hr style="border: 1px solid skyblue;">

In [8]:
# 1. ******************************************************************************* Year to which data is formating to 
data_target_year = '2050'

# 2. ************************************************************************************************************* Done 
print("Selected Year:", data_target_year)

Selected Year: 2050

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    5. Power Plant Data Frame
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Creating the data frame with all the corresponding headers according the Dispa-SET nomenclature.
</div>
<hr style="border: 1px solid skyblue;">

In [9]:
# 1. ************************************************************************************* convert data year to integer 
data_target_year = int(data_target_year)  

# 2. *************************************************************************** Dictionary to store created DataFrames 
power_plants_dfs_dict = {}

for zone in zone_names:
    zone_folder = os.path.join(power_plants_base_data_folder_path, zone)
    if not os.path.isdir(zone_folder):
        continue  # skip if zone folder doesn't exist

# 2.1. ******************************************************************************* List all csv files in the folder 
    csv_files = [f for f in os.listdir(zone_folder) if f.endswith(".csv")]

# 2.2. ************************************************************** Extract years from filenames (must be digits only
    available_years = []
    for f in csv_files:
        name, ext = os.path.splitext(f)
        if name.isdigit():  # e.g., "2004"
            available_years.append(int(name))

    if not available_years:
        continue  # skip if no year-based CSVs exist

# 2.3. ************************************************************************************ Find closest year to target 
    closest_year = min(available_years, key=lambda y: abs(y - data_target_year))

# 2.4. **************************************************************************************** Path to the chosen file 
    chosen_file = os.path.join(zone_folder, f"{closest_year}.csv")

# 2.5. ******************************************************************************************* Read only the header 
    headers = pd.read_csv(chosen_file, nrows=0).columns.tolist()

# 2.6. ******************************************************************* Create an empty DataFrame with those headers 
    df_name = f"{zone}_{data_target_year}"
    power_plants_dfs_dict[df_name] = pd.DataFrame(columns=headers)

# 2.7. *************************************************** Optionally, assign to globals() if you want actual variables 
    globals()[df_name] = power_plants_dfs_dict[df_name]

# 3. ************************************************************************************************************* Done 
    print(f"Zone {zone}: picked {closest_year}.csv for target {data_target_year}")
print("Power Plant DataFrames:", list(power_plants_dfs_dict.keys()))

Zone BE: picked 2024.csv for target 2050
Zone FR: picked 2024.csv for target 2050
Zone DE: picked 2024.csv for target 2050
Zone NL: picked 2024.csv for target 2050
Zone UK: picked 2024.csv for target 2050
Power Plant DataFrames: ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables.
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [10]:
print (f"Name of the DispaSET Unleash folder:                       {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                       {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                 {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                 {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:            {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                         {zone_names}")
print (f"Name of the zone_names_equivalences_dictionary):           {[value['Acronym'] for value in selected_zone_names_equivalences_dict.values()]}\n")
print (f"Target year:                                               {data_target_year}")
print (f"Name of the Power Plant DataFrames (dictionary):           {list(power_plants_dfs_dict.keys())}")

Name of the DispaSET Unleash folder:                       Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                       /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                 PowerPlants

Path to the Power Plants Base data folder:                 /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                PowerPlants

Path to the Power Plants_Pypsa Raw data folder:            /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:       PowerPlants

Path to the Power Plants_Pypsa Formated data folder:       /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                         ['BE', 'FR', 'DE', 'NL', 'UK']
Name of the zone_names_equivalences_dictionary):           [['  '], ['  '], ['  '], ['  '], ['GB']]

Target year:                                               2050
Name of the Power Plant DataFrames (dictionary):           ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
6. Nomenclature Technology Dictionary creation
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
This is the equivalence table between PyPSA and Dispa-SET technologies nomenclature
</div>
<hr style="border: 2px dashed skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
6.1. Dispa-SET Technologies Nomenclature
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The dispa-SET technologies nomenclature are loaded from "<a href="https://github.com/energy-modelling-toolkit/Dispa-SET/blob/master/dispaset/common.py" style="color:skyblue">https://github.com/energy-modelling-toolkit/Dispa-SET/blob/master/dispaset/common.py</a>"
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [11]:
# 1. ******************** Define all the Dispa-SET technology lists from the common.py script of Dispa-SET core scripts 
tech_master_list =         []

tech_renewables =          ['HROR' , 'PHOT' , 'WAVE' , 'WTOF' , 'WTON' , 'SOTH']

tech_conventional =        ['HDAM' , 'COMC' , 'GTUR' , 'STUR' , 'BATS' , 'ICEN']

tech_batteries =           ['BATS']

tech_storage =             ['BATS' , 'HDAM' , 'HPHS' , 'BEVS' , 'CAES' , 'SCSP' , 'H2ST' , 'HPHSC', 'THMS']

tech_p2bs =                ['P2GS' , 'ALKE' , 'PEME' , 'SOXE' , 'P2BS' , 'PEFC' , 'DMFC' , 'ALFC' , 'PAFC' , 'MCFC' , 'SOFC' ,
                            'REFC' , 'HDAMC', 'HRORC', 'HDLZ' , 'COMCX', 'GTURX', 'ICENX', 'STURX', 'P2HT' , 'ASHP' , 'GSHP' , 
                            'HYHP' , 'WSHP' , 'REHE']

tech_bs2p =                ['BSPG']

tech_boundary_sector =     ['BSPG' , 'GETH' , 'HOBO' , 'SOTH' , 'ABHP' , 'HOBOX', 'P2BS' , 'HBBS' , 'WHEN']

# 2. ********************************************************* Combine all lists into a single set to get unique values 
all_technologies_set = set(tech_master_list + tech_renewables + tech_conventional +
                           tech_batteries + tech_storage + tech_p2bs + tech_bs2p +
                           tech_boundary_sector)

# 3. **************************************************************************** Convert the set back to a sorted list 
all_technologies_list = sorted(list(all_technologies_set))

# 4. ************************************************************************ Create a DataFrame with the single column 
dispaSET_tech_list = pd.DataFrame(all_technologies_list, columns=['Dispa-SET Technologies'])

# 5. ************************************************************************************************************* Done
print(dispaSET_tech_list)
#dispaSET_tech_list

   Dispa-SET Technologies
0                    ABHP
1                    ALFC
2                    ALKE
3                    ASHP
4                    BATS
5                    BEVS
6                    BSPG
7                    CAES
8                    COMC
9                   COMCX
10                   DMFC
11                   GETH
12                   GSHP
13                   GTUR
14                  GTURX
15                   H2ST
16                   HBBS
17                   HDAM
18                  HDAMC
19                   HDLZ
20                   HOBO
21                  HOBOX
22                   HPHS
23                  HPHSC
24                   HROR
25                  HRORC
26                   HYHP
27                   ICEN
28                  ICENX
29                   MCFC
30                   P2BS
31                   P2GS
32                   P2HT
33                   PAFC
34                   PEFC
35                   PEME
36                   PHOT
37                   REFC
38                   REHE
39                   SCSP
40                   SOFC
41                   SOTH
42                   SOXE
43                   STUR
44                  STURX
45                   THMS
46                   WAVE
47                   WHEN
48                   WSHP
49                   WTOF
50                   WTON

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
6.2. Dispa-SET Fuels Nomenclature
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Additionally the dispa-SET fuelss nomenclature are loaded from "<a href="https://github.com/energy-modelling-toolkit/Dispa-SET/blob/master/dispaset/common.py" style="color:skyblue">https://github.com/energy-modelling-toolkit/Dispa-SET/blob/master/dispaset/common.py</a>"
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [12]:
# 1. ************************** Define all the Dispa-SET fuel lists from the common.py script of Dispa-SET core scripts 
dispaSET_fuel_list =      [ 'AIR', 'AMO', 'BIO', 'GAS', 'HRD', 'LIG', 'NUC', 'OIL', 'PEA', 'SUN', 
                            'WAT', 'WIN', 'WST', 'OTH', 'GEO', 'HYD', 'WHT', 'ELE', 'THE', 'UNK'  ]

# 2. ************************************************************************ Create a DataFrame with the single column 
dispaSET_fuel_list = pd.DataFrame(dispaSET_fuel_list, columns=['Dispa-SET Fuels'])

# 3. ************************************************************************************************************* Done
print(dispaSET_fuel_list)
#dispaSET_fuel_list

   Dispa-SET Fuels
0              AIR
1              AMO
2              BIO
3              GAS
4              HRD
5              LIG
6              NUC
7              OIL
8              PEA
9              SUN
10             WAT
11             WIN
12             WST
13             OTH
14             GEO
15             HYD
16             WHT
17             ELE
18             THE
19             UNK

<div style="background-color: black;">
<hr style="border: 2px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman', serif; color: skyblue;">
6.2. PyPSA vs Dispaset Nomenclature
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman', serif; color: skyblue;">
All those technologies from PyPSA which can be represented in Dispa-SET have to be identified.
</div>
<hr style="border: 2.0px dashed skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: 'Times New Roman', serif; color: skyblue;">
6.2.1. PyPSA Energy System Flow Diagram
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman', serif; color: skyblue;">
The next chart represents graphically how all the Energy sector inside PyPSA is structured.<br>
This is used to get the equivalent diagram for Dispaset.
</div>
<div style="text-align: center; margin: 20px 0;">
  <img src="Images/PyPSA_multisector_figure_1.png" 
       alt="PyPSA Multisector Flow Diagram" 
       style="max-width:35%; height: auto;">
</div>
<div style="text-align: center; margin-top: 10px; font-size: 12px; font-family: 'Times New Roman', serif; color: skyblue;">
  Source: <a href="https://pypsa-eur.readthedocs.io/en/latest/" target="_blank" style="color: skyblue; text-decoration: underline;">PyPSA-Eur Documentation</a>
</div>
<hr style="border: 2.0px dashed skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: 'Times New Roman', serif; color: skyblue;">
6.2.2. Equivalent Dispa-SET Energy System Flow Diagram
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman', serif; color:skyblue">
A correlation has been established between the PyPSA parameters and their corresponding Dispa-SET equivalents:
</div>
<div style="text-align: center; margin: 20px 0;">
  <img src="Images/PyPSA_sectors_as_Dispaset_Flow_work_1.svg" 
       alt="Equivalent Dispa-SET Energy System Flow Diagram" 
       style="max-width: auto; height: auto;">
</div>
<div style="text-align: center; margin-top: 10px; font-size: 12px; font-family: 'Times New Roman', serif; color: skyblue;">
  Source: Adapted for Dispa-SET_Unleash
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman', serif; color:skyblue">
Due to feature limitations, not all elements from PyPSA can be represented in Dispa-SET.
<br>
However, for those compatible technologies, the following chart graphically illustrates how they are connected within the Dispa-SET environment logic:
</div>
<div style="text-align: center; margin: 20px 0;">
  <img src="Images/PyPSA_sectors_as_Dispaset_Flow_work_Filtered_1.svg" 
       alt="Equivalent Dispa-SET Energy System Flow Diagram" 
       style="max-width: auto; height: auto;">
</div>
<div style="text-align: center; margin-top: 10px; font-size: 12px; font-family: 'Times New Roman', serif; color: skyblue;">
  Source: Adapted for Dispa-SET_Unleash
</div>
<hr style="border: 2.0px dashed skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman', serif; color: skyblue;">
6.2.3. Technologies & Demmands Nomenclature - PyPSA vs Dispaset 
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The PyPSA technologies and demmands nomenclature and their correlation with their homologous from Dispa-SET are described as follows:
</div>
<table style="width: 95%; margin: auto; font-family: TimesNewRoman; font-size: 12px; color: skyblue; table-layout: fixed;">
  <colgroup>
    <col style="width: 8%;">
    <col style="width: 14%;">
    <col style="width: 8%;">
    <col style="width: 28%;">
    <col style="width: 8%;">
    <col style="width: 20%;">
    <col style="width: 6%;">
    <col style="width: 8%;">
  </colgroup>
  <thead>
    <tr style="background-color: #111111; color: skyblue">
      <th colspan="4" style="text-align: center; border-top: 2px solid skyblue; border-bottom: 2px solid skyblue;">PyPSA</th>
      <th colspan="1" style="text-align: center; border-top: 2px solid skyblue;"> </th>
      <th colspan="3" style="text-align: center; border-top: 2px solid skyblue; border-bottom: 2px solid skyblue">Dispa-SET</th>
    </tr>      
    <tr style="background-color: #111111; color: skyblue">
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">PyPSA Element</th>
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">Technology</th>
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">Sector Classification</th>
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">Description</th>
      <th style="padding: 8px; text-align: left; ">Sector Relation</th>
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">Dispa-SET Element</th>
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">Element Type</th>
      <th style="padding: 8px; text-align: left; border-bottom: 1px solid skyblue">May Modeled?</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">DC</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Represents the DC (HVDC) transmission network for electricity</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">NTC / NTC</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">OCGT</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Open-Cycle Gas Turbine producing electricity from gas.</td>
      <td style="padding: 8px;border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(P\&X) <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">CCGT</td>
      <td style="padding: 8px;">Power Sector</td>
      <td style="padding: 8px;">Combined-Cycle Gas Turbine</td>
      <td style="padding: 8px;border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(P\&X) <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">EV charger</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Interface between the grid and electric vehicles</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2S <br> P&S / P&S</td>
      <td style="padding: 8px;">PowerCapacity, STOCapacity STOMaxChargingPower / --- id. ---</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">V2G</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Vehicle-to-Grid—allows EVs to discharge electricity</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">S2P <br> P&S / P&S</td>
      <td style="padding: 8px;">STOMaxChargingPower PowerCapacity, STOCapacity / - id. -</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">battery charger</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Converts electricity to stored energy in batteries (charging link)</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2S <br> P&S / P&S</td>
      <td style="padding: 8px;">PowerCapacity, STOCapacity STOMaxChargingPower / --- id. ---</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">BioSNG</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Synthetic Nat. Gas. (bio-methane)-fuel synthesis process</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(X&X) <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">DAC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Direct Air Capture—captures CO<sub>2</sub> for storage or utilization</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">(HT&P)2X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">Fischer-Tropsch</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts H<sub>2</sub> + CO<sub>2</sub> to liquid hydrocarbons; fuel synthesis</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">(X&X)2X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">H<sub>2</sub> Electrolysis</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electricity into hydrogen cross-sector conversion</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2X <br> P2X / P2X</td>
      <td style="padding: 8px;">PowerCapacity, STOCapacity, STOMaxPower / --- id. ---</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">H<sub>2</sub> Fuel Cell</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts hydrogen back to electricity</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2P <br> X2P / X2P</td>
      <td style="padding: 8px;">STOMaxPower, <br> PowerCapacity, STOCapacity / - id. -</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">H<sub>2</sub> pipeline</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Transports hydrogen between regions or sectors</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> X / X</td>
      <td style="padding: 8px;">BS_NTC / BS_NTC</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">H<sub>2</sub> pipeline retrofitted</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Existing pipelines adapted for H<sub>2</sub> transport</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> X / X</td>
      <td style="padding: 8px;">BS_NTC / BS_NTC</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">H<sub>2</sub> turbine</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Generates electricity or heat from hydrogen—boundary technology</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2P <br> X2P / X2P</td>
      <td style="padding: 8px;">STOMaxPower, <br> PowerCapacity, STOCapacity / - id. -</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">Haber-Bosch</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts H<sub>2</sub> + N<sub>2</sub> into ammonia—chemical / fertilizer Ind.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">(P&X)2X <br> P2X / P2X</td>
      <td style="padding: 8px;">PowerCapacity, STOCapacity, STOMaxPower / --- id. ---</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">SMR</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Steam Methane Reforming—gas to hydrogen conversion</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(X&X) <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">SMR CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">SMR with Carbon Capture</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(X&X) <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">Sabatier</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">H<sub>2</sub> + CO<sub>2</sub> → CH<sub>4</sub>—synthetic methane production</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">(X&X)2X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">agriculture machinery oil</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Oil used in agricultural machinery—transport/fuel</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">ammonia cracker</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts ammonia back into hydrogen</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">(P&X)2X <br> P2X / P2X</td>
      <td style="padding: 8px;">PowerCapacity, STOCapacity, STOMaxPower / --- id. ---</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">battery discharger</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Discharges stored electricity from batteries</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">S2P <br> P&S / P&S</td>
      <td style="padding: 8px;">STOMaxChargingPower PowerCapacity, STOCapacity / - id. -</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">electricity distribution grid</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Represents distribution-level power flow—low voltage</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">coal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Represents coal-based electricity generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(P&X) <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">lignite</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Represents coal-based electricity generation or conversion node</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">S2(P&X) <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">nuclear</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Nuclear-to-electricity conversion within the power system.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">S2P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">oil</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Oil-fired electricity generation or conversion node</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(P&X) <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">biogas to gas</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Upgrades raw biogas into pipeline-quality methane</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(X&X) <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">biogas to gas CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Biogas upgrading with carbon capture—industrial fuel conversion</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(X&X) <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">biomass to liquid</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts biomass into liquid fuels—synthetic fuel process.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2(X&X) <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">CO<sub>2</sub> sequestered</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Represents captured Tons of CO<sub>2</sub> / hour transported or stored</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">gas for industry CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Industrial gas use with carbon capture</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">gas pipeline</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Transports natural gas—energy carrier infrastructure</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;">BS_NTC</td>
      <td style="padding: 8px;">input</td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">gas pipeline new</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Expansion of natural gas transport capacity</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;">BS_NTC</td>
      <td style="padding: 8px;">input</td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">methanolisation</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Synthesizes methanol (CO<sub>2</sub> + H<sub>2</sub> → CH<sub>3</sub>OH)</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">(P&X&X)2X <br> P2X / P2X</td>
      <td style="padding: 8px;">PowerCapacity, STOCapacity, STOMaxPower / --- id. ---</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">process emissions</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Industrial process CO<sub>2</sub> emissions. Tons of CO<sub>2</sub> / hour</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> P / P</td>
      <td style="padding: 8px;">OutputEmissions / OutputEmissions</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">process emissions CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Industrial CO<sub>2</sub> emissions with capture — Tons of CO<sub>2</sub> / hour</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> P / P</td>
      <td style="padding: 8px;">OutputEmissions / OutputEmissions</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural air heat pump</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Converts electricity to heat for rural homes</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural ground heat pump</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Electric heat using stable ground temperature</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural biomass boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts biomass to heat—residential fuel use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Burns gas for heating—non-electric final energy use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural oil boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Burns oil for household heating—outside power generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural resistive heater</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Uses electricity directly for heating—part of demand side</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential rural water tanks discharger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Discharges stored heat — part of residential heating loop</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral air heat pump</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Decentralized air-source heat pump for urban buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral biomass boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Biomass-to-heat conversion for urban residential areas</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Urban gas boilers—distributed thermal devices</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral oil boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Decentralized oil boilers for urban homes</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral resistive heater</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electric heating devices—boundary heat sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral water tanks charger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Transfers electric energy to thermal storage (heat)</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Urban gas boilers—distributed thermal devices</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral water tanks discharger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Discharges heat from thermal storage</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural air heat pump</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Service sector rural building heat pump</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural biomass boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Provides space or process heat for service buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Burns gas for heating—final energy use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural ground heat pump</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electricity-to-heat for service buildings—heat sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural oil boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Oil heating in rural service buildings.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural resistive heater</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electric heating for service buildings—final energy use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural water tanks charger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts electricity to heat for service‐sector thermal storage</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural water tanks discharger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Discharges stored heat to buildings—part of the heat sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Urban gas boilers—distributed thermal devices</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">residential urban decentral water tanks discharger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Discharges heat from thermal storage</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural air heat pump</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Service sector rural building heat pump</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural biomass boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Provides space or process heat for service buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Burns gas for heating—final energy use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural ground heat pump</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electricity-to-heat for service buildings—heat sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural oil boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Oil heating in rural service buildings.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural resistive heater</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electric heating for service buildings—final energy use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural water tanks charger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts electricity to heat for service‐sector thermal storage</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">services rural water tanks discharger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Discharges stored heat to buildings—part of the heat sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">solid biomass for industry CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Same as above but with carbon capture</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">solid biomass transport</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Represents biomass logistics between regions/sectors</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central air heat pump</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Centralized district heat pump—heat sector interfac.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central gas CHP</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Combined heat + power supplying district heating</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2CHP <br> CHP / CHP</td>
      <td style="padding: 8px;">PowerCapacity, CHPType, CHPMaxHeat / -- id. --</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central gas CHP CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Gas CHP with carbon capture—district heating system</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2CHP <br> CHP / CHP</td>
      <td style="padding: 8px;">PowerCapacity, CHPType, CHPMaxHeat / -- id. --</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central gas boiler</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Centralized gas heating for urban networks</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central resistive heater</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Electric boiler for district heating—end-use conversion</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P2HT <br> P2HT / P2X</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity, STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central solid biomass CHP</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Biomass combined heat + power—heat boundary process</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2CHP <br> CHP / CHP</td>
      <td style="padding: 8px;">PowerCapacity, CHPType, CHPMaxHeat / -- id. --</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central solid biomass CHP CC</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Same with carbon capture—boundary sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X2CHP <br> CHP / CHP</td>
      <td style="padding: 8px;">PowerCapacity, CHPType, CHPMaxHeat / -- id. --</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central water tanks charger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Converts electricity to heat in district storage</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">link</td>
      <td style="padding: 8px;">urban central water tanks discharger</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Discharges stored heat to the district network</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D; border-top: 1px solid skyblue;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">coal</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Fossil fuel-based electricity generation</td>
      <td style="padding: 8px; border-top: 1px solid #4D4D4D; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;">OutputPower / OutputPower</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">gas</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Natural gas–fired power generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;">OutputPower / OutputPower</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">lignite</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Coal variant used for power generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;">OutputPower / OutputPower</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">oil</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Oil-fired electricity generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;">OutputPower / OutputPower</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">onwind</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Onshore wind turbine generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">offwind</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Offshore wind turbine generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">offwind-ac</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Offshore wind with AC connection</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">offwind-dc</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Offshore wind with DC connection</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">solar</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Utility-scale photovoltaic generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">solar rooftop</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Distributed PV connected to power grid</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">ror</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Run-of-river hydro power plant</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">uranium</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Nuclear fuel input for electricity generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> ---- / ----</td>
      <td style="padding: 8px;">OutputPower / OutputPower</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">residential rural solar thermal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Produces heat for households (not electricity)</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">residential urban decentral solar thermal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Decentralized solar heating for buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">services rural solar thermal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Solar thermal for service-sector heat demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">services urban decentral solar thermal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Urban service-sector solar heating</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">urban central solar thermal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Centralized solar thermal for district heating</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / P2X</td>
      <td style="padding: 8px;">------------------- / OutputSectorXStorageInput</td>
      <td style="padding: 8px;">---- / output</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">generator</td>
      <td style="padding: 8px;">load</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Represents total shredding energy</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">Load Shedding</td>
      <td style="padding: 8px;">output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D; border-top: 1px solid skyblue;">
      <td style="padding: 8px;">storage_units</td>
      <td style="padding: 8px;">PHS</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Pumped Hydro Storage, a grid-scale electricity storage technology</td>
      <td style="padding: 8px; border-top: 1px solid #4D4D4D; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P&S <br> P&S / P&S</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">storage_units</td>
      <td style="padding: 8px;">hydro</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Conventional hydro reservoir</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P&S <br> P&S / P&S</td>
      <td style="padding: 8px;">PowerCapacity / PowerCapacity</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D; border-top: 1px solid skyblue;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">battery</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Electrical energy storage — directly coupled with the grid.</td>
      <td style="padding: 8px; border-top: 1px solid #4D4D4D; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P&S <br> P&S / P&S</td>
      <td style="padding: 8px;">STOCapacity, STOMaxChargingPower / -- id --</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">uranium</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Nuclear fuel stock for electricity generation</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">H<sub>2</sub></td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Hydrogen storage—chemical energy carrier</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> X&S / X&S</td>
      <td style="padding: 8px;">STOCapacity, STOMaxPower / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">NH<sub>3</sub></td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Ammonia chemical/fertilizer storage or fuel vector.</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> X&S / X&S</td>
      <td style="padding: 8px;">STOCapacity, STOMaxPower / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">biogas</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Biomethane stock for heating or industry</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">CO<sub>2</sub></td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Captured CO<sub>2</sub> pool—used in synthesis or stored</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> P / P</td>
      <td style="padding: 8px;">OutputEmissions / OutputEmissions</td>
      <td style="padding: 8px;">output / output</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">CO<sub>2</sub> sequestered</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Permanent CO<sub>2</sub> storage—Tons of CO<sub>2</sub></td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">CO<sub>2</sub> stored</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Intermediate or final CO<sub>2</sub> reservoir—Tons of CO<sub>2</sub></td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">coal</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Coal stock for industrial/fuel processes</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">gas</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Natural gas (CH<sub>4</sub>) stock — cross-sector energy carrier</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">lignite</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Fuel storage for thermal use — outside grid operations</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">methanol</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Liquid fuel stock — used in transport or synthesis chains</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> X&S / X&S</td>
      <td style="padding: 8px;">STOCapacity, STOMaxPower / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">oil</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Oil (synthetic hydrocarbons) stock for transport/industrial fuels</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">solid biomass</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Biomass stock for heating/industrial use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X&S <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">residential rural water tanks</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Thermal storage for rural households — heat sector</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT&S <br> ---- / X&S</td>
      <td style="padding: 8px;">------------------- / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">---- / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">residential urban decentral water tanks</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Distributed heat storage in urban residences</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT&S <br> ---- / X&S</td>
      <td style="padding: 8px;">------------------- / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">---- / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">services rural water tanks</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Heat storage for rural service buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT&S <br> ---- / X&S</td>
      <td style="padding: 8px;">------------------- / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">---- / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">services urban decentral water tanks</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Thermal storage for urban service buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT&S <br> ---- / X&S</td>
      <td style="padding: 8px;">------------------- / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">---- / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">stores</td>
      <td style="padding: 8px;">urban central water tanks</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">District heating storage — boundary heat network</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT&S <br> ---- / X&S</td>
      <td style="padding: 8px;">------------------- / STOCapacity, STOMaxPower</td>
      <td style="padding: 8px;">---- / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333; border-top: 1px solid skyblue;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">agriculture electricity</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Agro-activities consumption; i.e. irrigation, lighting, ventilation, etc.</td>
      <td style="padding: 8px; border-top: 1px solid #333333; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">Demand / Demand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">agriculture heat</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Crop drying, greenhouse heating, others processes thermal demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> ---- / X</td>
      <td style="padding: 8px;">------------------- / SectorXDemand</td>
      <td style="padding: 8px;">---- / input</td>
      <td style="padding: 8px;">N / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">agriculture machinery oil</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Agro-machinery and vehicles diesel and lubricants consumption</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">Electricity demand residential and tertiary</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Residential and service sector appliance and lighting load</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">Demand / Demand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">industry electricity</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Electrified industrial processes and production demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">Demand / Demand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">gas for industry</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Heat and feedstock industrial natural and synthetic gas demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">land transport EV</td>
      <td style="padding: 8px;">Sector Power</td>
      <td style="padding: 8px;">Battery electric vehicles in road transport consumption</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">P <br> P / P</td>
      <td style="padding: 8px;">Demand / Demand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">land transport oil</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Gasoline and diesel vehicles conventional land transport demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">residential rural heat</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Decentralized space/water heating rural residential buildings demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> HT / X</td>
      <td style="padding: 8px;">HeatDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">services rural heat</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Rural service-sector buildings space/water heating demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> HT / X</td>
      <td style="padding: 8px;">HeatDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">residential urban decentral heat</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Urban residential buildings decentralized space/water demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> HT / X</td>
      <td style="padding: 8px;">HeatDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">services urban decentral heat</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Decentralized heat demand in urban service-sector buildings</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> HT / X</td>
      <td style="padding: 8px;">HeatDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">urban central heat</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Urban district heating residential and service demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> HT / X</td>
      <td style="padding: 8px;">HeatDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">solid biomass for industry</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Industrial solid biomass heat and material Use</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">H<sub>2</sub> for industry</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Steel making, refining, and chemicals hydrogen demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> X / X</td>
      <td style="padding: 8px;">SectorXDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">H<sub>2</sub> for shipping</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Fuel-cell and combustion maritime hydrogen demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> X / X</td>
      <td style="padding: 8px;">SectorXDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">shipping methanol</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Methanol demand as a maritime fuel for shipping applications</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> X / X</td>
      <td style="padding: 8px;">SectorXDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">shipping oil</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Maritime transport conventional marine oil fuel demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">naphtha for industry</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Industrial naphtha non-energy feedstock</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">kerosene for aviation</td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Jet fuel (kerosene) demand for aviation transport</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;"></td>
      <td style="padding: 8px;">N / N</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">low-temperature heat for industry</td>
      <td style="padding: 8px;">Sector Heat</td>
      <td style="padding: 8px;">Boilers, heat pumps, and waste heat low-temp industrial heat demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">HT <br> HT / X</td>
      <td style="padding: 8px;">HeatDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #4D4D4D;">
      <td style="padding: 8px;">loads</td>
      <td style="padding: 8px;">NH<sub>3</sub></td>
      <td style="padding: 8px;">Sector X</td>
      <td style="padding: 8px;">Fertilizers and industrial/energy use Ammonia demand</td>
      <td style="padding: 8px; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> X / X</td>
      <td style="padding: 8px;">SectorXDemand / SectorXDemand</td>
      <td style="padding: 8px;">input / input</td>
      <td style="padding: 8px;">Y / Y</td>
    </tr>
    <tr style="background-color: #333333;">
      <td style="padding: 8px; border-bottom: 2px solid skyblue;">loads</td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue;">coal for industry</td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue;">Sector X</td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue;">Industrial heat, power generation, or metallurgical processes demand</td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue; border-right: 1px dashed skyblue; border-left: 1px dashed skyblue;">X <br> ---- / ----</td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue;"></td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue;"></td>
      <td style="padding: 8px; border-bottom: 2px solid skyblue;">N / N</td>
    </tr>
 </tbody>
</table>
<div style="text-align: center; margin-top: 10px; font-size: 12px; font-family: 'Times New Roman', serif; color: skyblue;">
  Source: Adapted for Dispa-SET_Unleash
</div>
<hr style="border: 0.5px dashed skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman', serif; color: skyblue;">
6.3. Dispa-SET vs PyPSA Technologies Equivalences Dictionary
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman', serif; color: skyblue;">
A dictionary of Dispa-SET and PyPSA technology equivalences for power plant units is developed based on the specifications in the last table</div>
<div style="text-align: justify; margin-left:2em; font-weight: unbold; font-size: 12px; font-family: TimesNewRoman; color:skyblue">
    * Notes: &nbsp;&nbsp; keep values of the first column identical to the 'dispaSET_tech_list' list, since it depends of the Dipsa-SET core code.
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    If the list in the <code>commons.py</code> script changes, the 'tech_equivalences' list has to be updated accordingly.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [13]:
# 1. ******************************************************** Dictionary mapping Dispa-SET acronyms to PyPSA tech names 

tech_equivalences_dict = {
    
# -----------------------
# Renewable Power Units
# -----------------------
"generators offwind"                                  :  {"tech": ["WTOF"                                                    ] ,   "fuel": ["WIN"                                                     ]}  ,
"generators offwind-ac"                               :  {"tech": ["WTOF"                                                    ] ,   "fuel": ["WIN"                                                     ]}  ,
"generators offwind-dc"                               :  {"tech": ["WTOF"                                                    ] ,   "fuel": ["WIN"                                                     ]}  ,
    
"generators onwind"                                   :  {"tech": ["WTON"                                                    ] ,   "fuel": ["WIN"                                                     ]}  ,

"generators solar"                                    :  {"tech": ["PHOT"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,
"generators solar rooftop"                            :  {"tech": ["PHOT"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,

"generators ror"                                      :  {"tech": ["HROR"                                                    ] ,   "fuel": ["WAT"                                                     ]}  ,
# -----------------------
# Conventional Power Units
# -----------------------
"links Lignite"                                       :  {"tech": ["STUR"                                                    ] ,   "fuel": ["LIG"                                                     ]}  ,
    
"links nuclear"                                       :  {"tech": ["STUR"                                                    ] ,   "fuel": ["NUC"                                                     ]}  ,

"links CCGT"                                          :  {"tech": ["COMC"                                                    ] ,   "fuel": ["GAS"  , "HYD"  , "BIO"                                   ]}  ,
    
"links OCGT"                                          :  {"tech": ["GTUR"                                                    ] ,   "fuel": ["GAS"  , "HYD"  , "OIL"  , "AMO" , "BIO" , "WST" , "OTH"  ]}  ,

"links oil"                                           :  {"tech": ["GTUR"  , "ICEN"  , "STUR"                                ] ,   "fuel": ["OIL"                                                     ]}  ,

"links coal"                                          :  {"tech": ["STUR"  , "COMC"  , "GTUR"                                ] ,   "fuel": ["HRD"  , "PEA"                                            ]}  ,
# -----------------------
# Storage Units
# -----------------------
"links V2G"                                           :  {"tech": ["BEVS"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
    
"links battery discharger"                            :  {"tech": ["BATS"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
    
"storage_units hydro"                                 :  {"tech": ["HDAM"                                                    ] ,   "fuel": ["WAT"                                                     ]}  ,
    
"storage_units PHS"                                   :  {"tech": ["HPHS"                                                    ] ,   "fuel": ["WAT"                                                     ]}  ,
# -----------------------
# Combined Heat and Power Units
# -----------------------
"links urban central gas CHP"                         :  {"tech": ["COMC"  , "GTUR"  , "STUR"  , "ICEN"                      ] ,   "fuel": ["GAS"                                                     ]}  ,
"links urban central gas CHP CC"                      :  {"tech": ["COMC"                                                    ] ,   "fuel": ["GAS"                                                     ]}  ,

"links urban central solid biomass CHP"               :  {"tech": ["STUR"  , "ICEN"                                          ] ,   "fuel": ["BIO"                                                     ]}  ,
"links urban central solid biomass CHP CC"            :  {"tech": ["STUR"  , "ICEN"                                          ] ,   "fuel": ["BIO"                                                     ]}  ,
# -----------------------
# Sector Heat Units
# -----------------------
"links residential rural air heat pump"               :  {"tech": ["ASHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links services rural air heat pump"                  :  {"tech": ["ASHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links residential urban decentral air heat pump"     :  {"tech": ["ASHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links services urban decentral air heat pump"        :  {"tech": ["ASHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links urban central air heat pump"                   :  {"tech": ["ASHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,

"links residential rural ground heat pump"            :  {"tech": ["GSHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links services rural ground heat pump"               :  {"tech": ["GSHP"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
    
"links residential rural resistive heater"            :  {"tech": ["REHE"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links services rural resistive heater"               :  {"tech": ["REHE"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links residential urban decentral resistive heater"  :  {"tech": ["REHE"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links services urban decentral resistive heater"     :  {"tech": ["REHE"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
"links urban central resistive heater"                :  {"tech": ["REHE"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
# -----------------------
# VPP units - Unleash Scenarios
# -----------------------
#"links residential rural biomass boiler"              :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["BIO"                                                     ]}  ,
#"links services rural biomass boiler"                 :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["BIO"                                                     ]}  ,
#"links residential urban decentral biomass boiler"    :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["BIO"                                                     ]}  ,
#"links services urban decentral biomass boiler"       :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["BIO"                                                     ]}  ,

#"links residential rural gas boiler"                  :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["GAS"                                                     ]}  ,
#"links residential urban decentral gas boiler"        :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["GAS"                                                     ]}  ,
#"links services urban decentral gas boiler"           :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["GAS"                                                     ]}  ,
#"links urban central gas boiler"                      :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["GAS"                                                     ]}  ,

#"links residential rural oil boiler"                  :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["OIL"                                                     ]}  ,
#"links services rural oil boiler"                     :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["OIL"                                                     ]}  ,
#"links residential urban decentral oil boiler"        :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["OIL"                                                     ]}  ,
#"links services urban decentral oil boiler"           :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["OIL"                                                     ]}  ,

#"links residential rural solar thermal                :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,
#"links services rural solar thermal                   :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,
#"links residential urban decentral solar thermal      :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,
#"links services urban decentral solar thermal         :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,
#"links urban central solar thermal                    :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["SUN"                                                     ]}  ,
# -----------------------
# Sector X Units
# -----------------------
"links H2 Electrolysis"                               :  {"tech": ["PEME"  , "ALKE"  , "SOXE"                                ] ,   "fuel": ["ELE"                                                     ]}  ,
    
"links H2 Fuel Cell"                                  :  {"tech": ["PEFC"  , "SOFC"  , "MCFC"  , "PAFC"  , "ALFC"  , "REFC"  ] ,   "fuel": ["HYD"                                                     ]}  ,
"links H2 turbine"                                    :  {"tech": ["GTUR"  , "COMC"  , "ICEN"                                ] ,   "fuel": ["HYD"                                                     ]}  ,

"links Haber-Bosch"                                   :  {"tech": ["HBBS"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,
    
"links ammonia cracker"                               :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["ELE"                                                     ]}  ,

"links methanolisation"                               :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["ELE"                                                     ]}

}

# 2. ************************************************************************************************************* Done
print(json.dumps(tech_equivalences_dict, indent=4))

{
    "generators offwind": {
        "tech": [
            "WTOF"
        ],
        "fuel": [
            "WIN"
        ]
    },
    "generators offwind-ac": {
        "tech": [
            "WTOF"
        ],
        "fuel": [
            "WIN"
        ]
    },
    "generators offwind-dc": {
        "tech": [
            "WTOF"
        ],
        "fuel": [
            "WIN"
        ]
    },
    "generators onwind": {
        "tech": [
            "WTON"
        ],
        "fuel": [
            "WIN"
        ]
    },
    "generators solar": {
        "tech": [
            "PHOT"
        ],
        "fuel": [
            "SUN"
        ]
    },
    "generators solar rooftop": {
        "tech": [
            "PHOT"
        ],
        "fuel": [
            "SUN"
        ]
    },
    "generators ror": {
        "tech": [
            "HROR"
        ],
        "fuel": [
            "WAT"
        ]
    },
    "links Lignite": {
        "tech": [
            "STUR"
        ],
        "fuel": [
            "LIG"
        ]
    },
    "links nuclear": {
        "tech": [
            "STUR"
        ],
        "fuel": [
            "NUC"
        ]
    },
    "links CCGT": {
        "tech": [
            "COMC"
        ],
        "fuel": [
            "GAS",
            "HYD",
            "BIO"
        ]
    },
    "links OCGT": {
        "tech": [
            "GTUR"
        ],
        "fuel": [
            "GAS",
            "HYD",
            "OIL",
            "AMO",
            "BIO",
            "WST",
            "OTH"
        ]
    },
    "links oil": {
        "tech": [
            "GTUR",
            "ICEN",
            "STUR"
        ],
        "fuel": [
            "OIL"
        ]
    },
    "links coal": {
        "tech": [
            "STUR",
            "COMC",
            "GTUR"
        ],
        "fuel": [
            "HRD",
            "PEA"
        ]
    },
    "links V2G": {
        "tech": [
            "BEVS"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links battery discharger": {
        "tech": [
            "BATS"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "storage_units hydro": {
        "tech": [
            "HDAM"
        ],
        "fuel": [
            "WAT"
        ]
    },
    "storage_units PHS": {
        "tech": [
            "HPHS"
        ],
        "fuel": [
            "WAT"
        ]
    },
    "links urban central gas CHP": {
        "tech": [
            "COMC",
            "GTUR",
            "STUR",
            "ICEN"
        ],
        "fuel": [
            "GAS"
        ]
    },
    "links urban central gas CHP CC": {
        "tech": [
            "COMC"
        ],
        "fuel": [
            "GAS"
        ]
    },
    "links urban central solid biomass CHP": {
        "tech": [
            "STUR",
            "ICEN"
        ],
        "fuel": [
            "BIO"
        ]
    },
    "links urban central solid biomass CHP CC": {
        "tech": [
            "STUR",
            "ICEN"
        ],
        "fuel": [
            "BIO"
        ]
    },
    "links residential rural air heat pump": {
        "tech": [
            "ASHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links services rural air heat pump": {
        "tech": [
            "ASHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links residential urban decentral air heat pump": {
        "tech": [
            "ASHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links services urban decentral air heat pump": {
        "tech": [
            "ASHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links urban central air heat pump": {
        "tech": [
            "ASHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links residential rural ground heat pump": {
        "tech": [
            "GSHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links services rural ground heat pump": {
        "tech": [
            "GSHP"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links residential rural resistive heater": {
        "tech": [
            "REHE"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links services rural resistive heater": {
        "tech": [
            "REHE"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links residential urban decentral resistive heater": {
        "tech": [
            "REHE"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links services urban decentral resistive heater": {
        "tech": [
            "REHE"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links urban central resistive heater": {
        "tech": [
            "REHE"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links H2 Electrolysis": {
        "tech": [
            "PEME",
            "ALKE",
            "SOXE"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links H2 Fuel Cell": {
        "tech": [
            "PEFC",
            "SOFC",
            "MCFC",
            "PAFC",
            "ALFC",
            "REFC"
        ],
        "fuel": [
            "HYD"
        ]
    },
    "links H2 turbine": {
        "tech": [
            "GTUR",
            "COMC",
            "ICEN"
        ],
        "fuel": [
            "HYD"
        ]
    },
    "links Haber-Bosch": {
        "tech": [
            "HBBS"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links ammonia cracker": {
        "tech": [
            "P2BS"
        ],
        "fuel": [
            "ELE"
        ]
    },
    "links methanolisation": {
        "tech": [
            "P2BS"
        ],
        "fuel": [
            "ELE"
        ]
    }
}

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman', serif; color: skyblue;">
6.4. Dispa-SET Technology - Fuel matching Table
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    In Dispa-SET, each unit must be defined with the pair of values (technology,fuel). The following data is an updated version—Fuel-type proportions table—of its homologous one from the documentation in:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <a href=https://www.dispaset.eu/en/latest/data.html style="color:skyblue">https://www.dispaset.eu/en/latest/data.html</a>
</div>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The items provided in the Dispa-SET core scripts—i.e., <code>commons.py</code>—and further refined using recently compiled and estimated data derived from publicly available sources.
<br>
These sources include datasets and reports from:
</div>

<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            The Dispa-SET documentation.
            <br>
            <a href="https://www.dispaset.eu/en/latest/data.html" style="color:skyblue">https://www.dispaset.eu/en/latest/data.html</a>
        </li>
        <li>
            The European Energy Storage Inventory by the Joint Research Centre (JRC) of the European Commission.
            <br>
            <a href="https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/new-tool-maps-europes-real-time-sustainable-energy-storage-data-2025-03-20_en" style="color:skyblue">https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/new-tool-maps-europes-real-time-sustainable-energy-storage-data-2025-03-20_en</a>
        </li>
        <li>
            The IEA Energy Statistics Data Browser.
            <br>
            <a href="https://www.iea.org/data-and-statistics/data-tools/energy-statistics-data-browser" style="color:skyblue">https://www.iea.org/data-and-statistics/data-tools/energy-statistics-data-browser</a>
        </li>
        <li>
            The EU Energy Statistical Pocketbook.
            <br>
            <a href="https://energy.ec.europa.eu/data-and-analysis/eu-energy-statistical-pocketbook-and-country-datasheets_en" style="color:skyblue">https://energy.ec.europa.eu/data-and-analysis/eu-energy-statistical-pocketbook-and-country-datasheets_en</a>
        </li>
        <li>
            The European Electricity Review by Ember.
            <br>
            <a href="https://www.ember-climate.org/publications/european-electricity-review-2025/" style="color:skyblue">https://www.ember-climate.org/publications/european-electricity-review-2025/</a>
        </li>
    </ol>
</div>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The technology-to-fuel mappings were additionally informed by modeling frameworks and literature such as:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;" start="6">
        <li>
            ETSAP-TIMES.
            <br>
            <a href="https://iea-etsap.org/index.php/etsap-tools/model-generator/times" style="color:skyblue">https://iea-etsap.org/index.php/etsap-tools/model-generator/times</a>
        </li>
        <li>
            Dispa-SET technical documentation.
            <br>
            <a href="https://www.dispaset.eu/en/latest/" style="color:skyblue">https://www.dispaset.eu/en/latest/</a>
        </li>
    </ol>
</div>

<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    And the following sources:
</div>

<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;" start="8">
        <li>
            IEA Hydrogen Roadmap (2023).
            <br>
            <a href="https://www.iea.org/reports/technology-roadmap-hydrogen-and-fuel-cells" style="color:skyblue">https://www.iea.org/reports/technology-roadmap-hydrogen-and-fuel-cells</a>
        </li>
        <li>
            IRENA Electrolyzers (2023).
            <br>
            <a href="https://www.irena.org/publications" style="color:skyblue">https://www.irena.org/publications</a>
        </li>
        <li>
            US DOE Electrolysis (2023).
            <br>
            <a href="https://www.energy.gov/eere/fuelcells/hydrogen-production-electrolysis" style="color:skyblue">https://www.energy.gov/eere/fuelcells/hydrogen-production-electrolysis</a>
        </li>
        <li>
            EC Electrolyzers (2023).
            <br>
            <a href="https://energy.ec.europa.eu/topics/eus-energy-system/hydrogen_en" style="color:skyblue">https://energy.ec.europa.eu/topics/eus-energy-system/hydrogen_en</a>
        </li>
        <li>
            US DOE Air-Source Heat Pumps (2024).
            <br>
            <a href="https://www.energy.gov/energysaver/air-source-heat-pumps" style="color:skyblue">https://www.energy.gov/energysaver/air-source-heat-pumps</a>
        </li>
        <li>
            Minnesota Air Source Heat Pump Report (2011).
            <br>
            <a href="https://www.leg.mn.gov/docs/2014/other/141021.pdf" style="color:skyblue">https://www.leg.mn.gov/docs/2014/other/141021.pdf</a>
        </li>
        <li>
            North NJ HVAC (2025).
            <br>
            <a href="https://northnjhvac.com/common-sources-thermal-energy-heat-pumps-explained/" style="color:skyblue">https://northnjhvac.com/common-sources-thermal-energy-heat-pumps-explained/</a>
        </li>
        <li>
            US DOE Battery Storage (2024).
            <br>
            <a href="https://www.energy.gov/sites/default/files/2025-01/BESSIE_supply-chain-battery-report_111124_OPENRELEASE_SJ_1.pdf" style="color:skyblue">https://www.energy.gov/sites/default/files/2025-01/BESSIE_supply-chain-battery-report_111124_OPENRELEASE_SJ_1.pdf</a>
        </li>
        <li>
            EIA Battery Storage (2024).
            <br>
            <a href="https://www.eia.gov/todayinenergy/detail.php?id=63025" style="color:skyblue">https://www.eia.gov/todayinenergy/detail.php?id=63025</a>
        </li>
        <li>
            IEA Batteries (2024).
            <br>
            <a href="https://www.iea.org/reports/batteries-and-secure-energy-transitions/executive-summary" style="color:skyblue">https://www.iea.org/reports/batteries-and-secure-energy-transitions/executive-summary</a>
        </li>
        <li>
            Vehicle-to-Grid (2025).
            <br>
            <a href="https://www.mdpi.com/2032-6653/16/3/142" style="color:skyblue">https://www.mdpi.com/2032-6653/16/3/142</a>
        </li>
        <li>
            EIA Transportation Energy (2024).
            <br>
            <a href="https://www.eia.gov/energyexplained/use-of-energy/transportation-in-depth.php" style="color:skyblue">https://www.eia.gov/energyexplained/use-of-energy/transportation-in-depth.php</a>
        </li>
        <li>
            Solar PV Systems (2023).
            <br>
            <a href="https://www.frontiersin.org/articles/10.3389/fenrg.2023.1164494/full" style="color:skyblue">https://www.frontiersin.org/articles/10.3389/fenrg.2023.1164494/full</a>
        </li>
        <li>
            US DOE Solar Opportunities (2024).
            <br>
            <a href="https://www.energy.gov/eere/solar/articles/expanding-solar-energy-opportunities-rooftops-building-integration" style="color:skyblue">https://www.energy.gov/eere/solar/articles/expanding-solar-energy-opportunities-rooftops-building-integration</a>
        </li>
        <li>
            US DOE CAES (2023).
            <br>
            <a href="https://www.energy.gov/sites/default/files/2023-07/Technology%20Strategy%20Assessment%20-%20Compressed%20Air%20Energy%20Storage_0.pdf" style="color:skyblue">https://www.energy.gov/sites/default/files/2023-07/Technology%20Strategy%20Assessment%20-%20Compressed%20Air%20Energy%20Storage_0.pdf</a>
        </li>
        <li>
            Net Zero CAES (2025).
            <br>
            <a href="https://urbanao.com/post/compressed-air-energy-storage-caes-a-comprehensive-2025-overview" style="color:skyblue">https://urbanao.com/post/compressed-air-energy-storage-caes-a-comprehensive-2025-overview</a>
        </li>
        <li>
            EPA CHP Emissions (2021).
            <br>
            <a href="https://www.epa.gov/sites/production/files/2015-07/documents/fuel_and_carbon_dioxide_emissions_savings_calculation_methodology_for_combined_heat_and_power_systems.pdf" style="color:skyblue">https://www.epa.gov/sites/production/files/2015-07/documents/fuel_and_carbon_dioxide_emissions_savings_calculation_methodology_for_combined_heat_and_power_systems.pdf</a>
        </li>
        <li>
            US DOE CHP Guide (2015).
            <br>
            <a href="https://www.energy.gov/sites/default/files/2019/01/f58/CHPGuide2015.pdf" style="color:skyblue">https://www.energy.gov/sites/default/files/2019/01/f58/CHPGuide2015.pdf</a>
        </li>
        <li>
            EIA CHP (2012).
            <br>
            <a href="https://www.eia.gov/todayinenergy/detail.php?id=8250" style="color:skyblue">https://www.eia.gov/todayinenergy/detail.php?id=8250</a>
        </li>
        <li>
            Direct Methanol Fuel Cells (2003).
            <br>
            <a href="https://www1.eere.energy.gov/hydrogenandfuelcells//pdfs/ive16_zelenay.pdf" style="color:skyblue">https://www1.eere.energy.gov/hydrogenandfuelcells//pdfs/ive16_zelenay.pdf</a>
        </li>
        <li>
            Direct Methanol Fuel Cells Review (2015).
            <br>
            <a href="https://link.springer.com/article/10.1557/mre.2015.4" style="color:skyblue">https://link.springer.com/article/10.1557/mre.2015.4</a>
        </li>
        <li>
            Methanol Fuel for DMFC (2023).
            <br>
            <a href="https://www.intechopen.com/chapters/1157844" style="color:skyblue">https://www.intechopen.com/chapters/1157844</a>
        </li>
        <li>
            World Bank Geothermal (2022).
            <br>
            <a href="https://www.esmap.org/sites/default/files/esmap-files/16103-WB_ESMAP%20Direct%20Use-WEB.pdf" style="color:skyblue">https://www.esmap.org/sites/default/files/esmap-files/16103-WB_ESMAP%20Direct%20Use-WEB.pdf</a>
        </li>
        <li>
            UMich Geothermal (2023).
            <br>
            <a href="https://css.umich.edu/publications/factsheets/energy/geothermal-energy-factsheet" style="color:skyblue">https://css.umich.edu/publications/factsheets/energy/geothermal-energy-factsheet</a>
        </li>
        <li>
            ORNL Geothermal (2024).
            <br>
            <a href="https://www.ornl.gov/news/ornl-study-projects-geothermal-heat-pumps-impact-carbon-emissions-and-electrical-grid-2050" style="color:skyblue">https://www.ornl.gov/news/ornl-study-projects-geothermal-heat-pumps-impact-carbon-emissions-and-electrical-grid-2050</a>
        </li>
        <li>
            US DOE Geothermal Heat Pumps (2023).
            <br>
            <a href="https://www.energy.gov/sites/prod/files/guide_to_geothermal_heat_pumps.pdf" style="color:skyblue">https://www.energy.gov/sites/prod/files/guide_to_geothermal_heat_pumps.pdf</a>
        </li>
        <li>
            EnergySage Geothermal (2023).
            <br>
            <a href="https://www.energysage.com/heat-pumps/pros-cons-geothermal-heat-pumps/" style="color:skyblue">https://www.energysage.com/heat-pumps/pros-cons-geothermal-heat-pumps/</a>
        </li>
        <li>
            Wikipedia GSHP (2023).
            <br>
            <a href="https://en.wikipedia.org/wiki/Ground_source_heat_pump" style="color:skyblue">https://en.wikipedia.org/wiki/Ground_source_heat_pump</a>
        </li>
        <li>
            Hydrogen in Gas Turbines (2022).
            <br>
            <a href="https://doi.org/10.1093/ijlct/ctac025" style="color:skyblue">https://doi.org/10.1093/ijlct/ctac025</a>
        </li>
        <li>
            Fuel Composition Impact (2019).
            <br>
            <a href="https://doi.org/10.1115/1.4044238" style="color:skyblue">https://doi.org/10.1115/1.4044238</a>
        </li>
        <li>
            US DOE Hydrogen Review (2022).
            <br>
            <a href="https://www.netl.doe.gov/sites/default/files/publication/A-Literature-Review-of-Hydrogen-and-Natural-Gas-Turbines-081222.pdf" style="color:skyblue">https://www.netl.doe.gov/sites/default/files/publication/A-Literature-Review-of-Hydrogen-and-Natural-Gas-Turbines-081222.pdf</a>
        </li>
        <li>
            Modernizing Gas-Fired District Heating (2024).
            <br>
            <a href="https://doi.org/10.3390/su16041401" style="color:skyblue">https://doi.org/10.3390/su16041401</a>
        </li>
        <li>
            Hydrogen Storage Review (2023).
            <br>
            <a href="https://doi.org/10.4236/wjet.2023.113033" style="color:skyblue">https://doi.org/10.4236/wjet.2023.113033</a>
        </li>
        <li>
            Hydrogen Energy Storage (2022).
            <br>
            <a href="https://www.sandia.gov/app/uploads/sites/163/2022/03/ESHB_Ch11_Hydrogen_Headley.pdf" style="color:skyblue">https://www.sandia.gov/app/uploads/sites/163/2022/03/ESHB_Ch11_Hydrogen_Headley.pdf</a>
        </li>
        <li>
            Biomass for Energy (2024).
            <br>
            <a href="https://www.energy.gov/sites/default/files/2024-03/beto-2023-billion-ton-report_2-current_0.pdf" style="color:skyblue">https://www.energy.gov/sites/default/files/2024-03/beto-2023-billion-ton-report_2-current_0.pdf</a>
        </li>
        <li>
            Sustainable Biomass in Residential Sector (2018).
            <br>
            <a href="https://publications.jrc.ec.europa.eu/repository/bitstream/JRC113417/kjna29542enn.pdf" style="color:skyblue">https://publications.jrc.ec.europa.eu/repository/bitstream/JRC113417/kjna29542enn.pdf</a>
        </li>
        <li>
            EIA Hydropower (2023).
            <br>
            <a href="https://www.eia.gov/energyexplained/hydropower/index.php" style="color:skyblue">https://www.eia.gov/energyexplained/hydropower/index.php</a>
        </li>
        <li>
            Britannica Hydroelectric (2025).
            <br>
            <a href="https://www.britannica.com/science/hydroelectric-power" style="color:skyblue">https://www.britannica.com/science/hydroelectric-power</a>
        </li>
        <li>
            Pumped Hydroelectric Storage (2024).
            <br>
            <a href="https://www.sandia.gov/app/uploads/sites/163/2024/08/ESHB_Ch9_PHS_Bera.pdf" style="color:skyblue">https://www.sandia.gov/app/uploads/sites/163/2024/08/ESHB_Ch9_PHS_Bera.pdf</a>
        </li>
        <li>
            EPA Fuel Oil Combustion (2020).
            <br>
            <a href="https://www.epa.gov/sites/production/files/2020-09/documents/1.3_fuel_oil_combustion.pdf" style="color:skyblue">https://www.epa.gov/sites/production/files/2020-09/documents/1.3_fuel_oil_combustion.pdf</a>
        </li>
        <li>
            Pumped Storage Hydropower (2022).
            <br>
            <a href="https://www.esmap.org/sites/default/files/ESP/WB_PSH_16Jun22.pdf" style="color:skyblue">https://www.esmap.org/sites/default/files/ESP/WB_PSH_16Jun22.pdf</a>
        </li>
        <li>
            Combustion Efficiency (Engineering Toolbox).
            <br>
            <a href="https://www.engineeringtoolbox.com/boiler-combustion-efficiency-d_271.html" style="color:skyblue">https://www.engineeringtoolbox.com/boiler-combustion-efficiency-d_271.html</a>
        </li>
        <li>
            EIA Hydropower Generation (2023).
            <br>
            <a href="https://www.eia.gov/energyexplained/hydropower/where-hydropower-is-generated.php" style="color:skyblue">https://www.eia.gov/energyexplained/hydropower/where-hydropower-is-generated.php</a>
        </li>
        <li>
            Run-of-River Hydropower Design (2019).
            <br>
            <a href="https://doi.org/10.1016/j.envsoft.2018.08.018" style="color:skyblue">https://doi.org/10.1016/j.envsoft.2018.08.018</a>
        </li>
        <li>
            Hybrid Heat Pump System (2020).
            <br>
            <a href="https://qsel.columbia.edu/assets/uploads/blog/2020/publications/cost-optimal-sizing-and-operation-of-a-hybrid-heat-pump-system-using-numerical-simulation.pdf" style="color:skyblue">https://qsel.columbia.edu/assets/uploads/blog/2020/publications/cost-optimal-sizing-and-operation-of-a-hybrid-heat-pump-system-using-numerical-simulation.pdf</a>
        </li>
        <li>
            Biomass CHP Technologies (2007).
            <br>
            <a href="https://www.epa.gov/sites/production/files/2015-07/documents/biomass_combined_heat_and_power_catalog_of_technologies_v.1.1.pdf" style="color:skyblue">https://www.epa.gov/sites/production/files/2015-07/documents/biomass_combined_heat_and_power_catalog_of_technologies_v.1.1.pdf</a>
        </li>
        <li>
            CHP Internal Combustion Engines (2017).
            <br>
            <a href="https://www.wef.org/globalassets/assets-wef/direct-download-library/public/03---resources/wsec-2017-tr-002-rbc-internal-combustion-engines---9.2017.pdf" style="color:skyblue">https://www.wef.org/globalassets/assets-wef/direct-download-library/public/03---resources/wsec-2017-tr-002-rbc-internal-combustion-engines---9.2017.pdf</a>
        </li>
        <li>
            Molten Carbonate Fuel Cell Analysis (2015).
            <br>
            <a href="https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/progress15/ix_4_ahmed_2015.pdf" style="color:skyblue">https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/progress15/ix_4_ahmed_2015.pdf</a>
        </li>
        <li>
            Electrolyzer-Methanation Integration (2022).
            <br>
            <a href="https://doi.org/10.1016/j.apenergy.2022.120268" style="color:skyblue">https://doi.org/10.1016/j.apenergy.2022.120268</a>
        </li>
        <li>
            Electric Resistance Heating (2020).
            <br>
            <a href="https://www.energy.gov/energysaver/electric-resistance-heating" style="color:skyblue">https://www.energy.gov/energysaver/electric-resistance-heating</a>
        </li>
        <li>
            Regenerative Fuel Cell Analysis (2020).
            <br>
            <a href="https://ntrs.nasa.gov/api/citations/20205000357/downloads/TM-20205000357.pdf" style="color:skyblue">https://ntrs.nasa.gov/api/citations/20205000357/downloads/TM-20205000357.pdf</a>
        </li>
        <li>
            Reversible Fuel Cells (2025).
            <br>
            <a href="https://doi.org/10.4236/jpee.2025.136001" style="color:skyblue">https://doi.org/10.4236/jpee.2025.136001</a>
        </li>
        <li>
            Solar PV Energy (2024).
            <br>
            <a href="https://css.umich.edu/publications/factsheets/energy/solar-pv-energy-factsheet" style="color:skyblue">https://css.umich.edu/publications/factsheets/energy/solar-pv-energy-factsheet</a>
        </li>
        <li>
            PEM Electrolysis Targets (2022).
            <br>
            <a href="https://www.energy.gov/eere/fuelcells/technical-targets-proton-exchange-membrane-electrolysis" style="color:skyblue">https://www.energy.gov/eere/fuelcells/technical-targets-proton-exchange-membrane-electrolysis</a>
        </li>
        <li>
            Phosphoric Acid Fuel Cells (2024).
            <br>
            <a href="https://fuelcellz.com/phosphoric-acid-fuel-cells-pafc/" style="color:skyblue">https://fuelcellz.com/phosphoric-acid-fuel-cells-pafc/</a>
        </li>
        <li>
            PEM Fuel Cell Review (2022).
            <br>
            <a href="https://pubs.rsc.org/en/content/articlelanding/2022/ee/d2ee00790h" style="color:skyblue">https://pubs.rsc.org/en/content/articlelanding/2022/ee/d2ee00790h</a>
        </li>
        <li>
            High-Temperature Electrolysis (2024).
            <br>
            <a href="https://www.energy.gov/eere/fuelcells/technical-targets-high-temperature-electrolysis" style="color:skyblue">https://www.energy.gov/eere/fuelcells/technical-targets-high-temperature-electrolysis</a>
        </li>
        <li>
            Solar Thermal for Urban Sustainability (2025).
            <br>
            <a href="https://doi.org/10.3389/frsc.2025.1583316" style="color:skyblue">https://doi.org/10.3389/frsc.2025.1583316</a>
        </li>
        <li>
            Solid Oxide Fuel Cells (2025).
            <br>
            <a href="https://doi.org/10.3390/pr13041145" style="color:skyblue">https://doi.org/10.3390/pr13041145</a>
        </li>
        <li>
            Solar Thermal Energy (2023).
            <br>
            <a href="https://www.energysage.com/about-clean-energy/solar/solar-thermal-what-you-need-to-know/" style="color:skyblue">https://www.energysage.com/about-clean-energy/solar/solar-thermal-what-you-need-to-know/</a>
        </li>
        <li>
            Solar Heating for Residential/Industrial (2015).
            <br>
            <a href="https://energy.mit.edu/wp-content/uploads/2015/04/MITEI-WP-2015-04.pdf" style="color:skyblue">https://energy.mit.edu/wp-content/uploads/2015/04/MITEI-WP-2015-04.pdf</a>
        </li>
        <li>
            Biomass Combustion in Steam Power Plants (2023).
            <br>
            <a href="https://doi.org/10.1093/ce/zkad049" style="color:skyblue">https://doi.org/10.1093/ce/zkad049</a>
        </li>
        <li>
            Waste Heat to Power Systems (2015).
            <br>
            <a href="https://www.epa.gov/sites/default/files/2015-07/documents/waste_heat_to_power_systems.pdf" style="color:skyblue">https://www.epa.gov/sites/default/files/2015-07/documents/waste_heat_to_power_systems.pdf</a>
        </li>
        <li>
            Thermal Hot Water Storage (2025).
            <br>
            <a href="https://www.energystoragenl.nl/wp-content/uploads/2025/01/Thermische-HotWater.pdf" style="color:skyblue">https://www.energystoragenl.nl/wp-content/uploads/2025/01/Thermische-HotWater.pdf</a>
        </li>
        <li>
            Wave Power (2024).
            <br>
            <a href="https://www.eia.gov/energyexplained/hydropower/wave-power.php" style="color:skyblue">https://www.eia.gov/energyexplained/hydropower/wave-power.php</a>
        </li>
        <li>
            Water-Source Heat Pumps (2007).
            <br>
            <a href="https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/education-training/engineers-newsletters/energy-environment/admapn024en_0507.pdf" style="color:skyblue">https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/education-training/engineers-newsletters/energy-environment/admapn024en_0507.pdf</a>
        </li>
        <li>
            Offshore Wind Market Report (2023).
            <br>
            <a href="https://www.energy.gov/sites/default/files/2023-09/doe-offshore-wind-market-report-2023-edition.pdf" style="color:skyblue">https://www.energy.gov/sites/default/files/2023-09/doe-offshore-wind-market-report-2023-edition.pdf</a>
        </li>
        <li>
            IEA Wind Electricity (2024).
            <br>
            <a href="https://www.iea.org/energy-system/renewables/wind" style="color:skyblue">https://www.iea.org/energy-system/renewables/wind</a>
        </li>
        <li>
            Decarbonizing Building Thermal Systems (2024).
            <br>
            <a href="https://www.nrel.gov/docs/fy24osti/87812.pdf" style="color:skyblue">https://www.nrel.gov/docs/fy24osti/87812.pdf</a>
        </li>
    </ol>
</div>

<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    This matrix—where rows correspond to different Energy Technologies and columns correspond to different Fuel Types—shows the values as fractions (ranging from 0.0000 to 1.0000), indicating the proportional contribution of each fuel/resource to the total energy input for a specific technology.
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [14]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
overal_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0.00201207243460765, 0, 0, 0, 0, 0.00343642611683849, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0.00687285223367698, 0, 0, 1, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0.136986301369863, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0668924640135478, 0.15, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 0, 1, 1, 1, 0, 0, 0.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.75, 0.9, 0, 1, 0, 0, 0.95, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.975855130784708, 0.75, 0, 0, 0, 0.646048109965636, 0.98, 0, 0, 0, 0, 0, 0.60, 0.9, 0, 0, 0, 0, 0, 0.383561643835616, 0.7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0821337849280271, 0.7, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00846740050804403, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.00804828973843059, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.329381879762913, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.00343642611683849, 0.02, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0.25, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0.000846740050804403, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.210838272650296, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.116850127011008, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.0140845070422535, 0.1, 0, 0, 0, 0.323024054982818, 0, 0, 0, 0, 0, 0, 0.15, 0.1, 0, 0, 0, 0, 0, 0.36986301369863, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.123624047417443, 0.15, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00687285223367698, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0136986301369863, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.000846740050804403, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0143945808636749, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0.00592718035563082, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.000846740050804403, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0103092783505155, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0958904109589041, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0389500423370025, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame 
overal_fuel_technologies_match_df = pd.DataFrame(overal_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(overal_fuel_technologies_match_df)
overal_fuel_technologies_match_df

        AIR       AMO       BIO   ELE       GAS       GEO       HRD       HYD  \
ABHP   0.05  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
ALFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
ALKE   0.00  0.000000  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
ASHP   0.00  0.000000  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
BATS   0.00  0.000000  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
BEVS   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
BSPG   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
CAES   0.25  0.000000  0.000000  0.75  0.000000  0.000000  0.000000  0.000000
COMC   0.00  0.002012  0.000000  0.00  0.975855  0.000000  0.008048  0.000000
COMCX  0.00  0.000000  0.150000  0.00  0.750000  0.000000  0.000000  0.000000
DMFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
GETH   0.00  0.000000  0.000000  0.00  0.000000  1.000000  0.000000  0.000000
GSHP   0.00  0.000000  0.000000  0.00  0.000000  1.000000  0.000000  0.000000
GTUR   0.00  0.003436  0.006873  0.00  0.646048  0.000000  0.000000  0.003436
GTURX  0.00  0.000000  0.000000  0.00  0.980000  0.000000  0.000000  0.020000
H2ST   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
HBBS   0.00  0.000000  1.000000  0.00  0.000000  0.000000  0.000000  0.000000
HDAM   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HDAMC  0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HDLZ   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HOBO   0.00  0.000000  0.200000  0.00  0.600000  0.000000  0.010000  0.000000
HOBOX  0.00  0.000000  0.000000  0.00  0.900000  0.000000  0.000000  0.000000
HPHS   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HPHSC  0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HROR   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HRORC  0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HYHP   0.75  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
ICEN   0.00  0.000000  0.136986  0.00  0.383562  0.000000  0.000000  0.000000
ICENX  0.00  0.000000  0.150000  0.00  0.700000  0.000000  0.000000  0.000000
MCFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
PAFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
P2BS   0.00  0.000000  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
P2GS   0.00  0.000000  0.000000  0.75  0.000000  0.000000  0.000000  0.250000
P2HT   0.00  0.000000  0.000000  0.90  0.000000  0.000000  0.000000  0.000000
PEFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
PEME   0.00  0.000000  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
PHOT   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
REFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
REHE   0.00  0.000000  0.000000  0.95  0.000000  0.000000  0.000000  0.000000
SCSP   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
SOFC   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
SOTH   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
SOXE   0.00  0.000000  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
STUR   0.00  0.000000  0.066892  0.00  0.082134  0.008467  0.329382  0.000847
STURX  0.00  0.000000  0.150000  0.00  0.700000  0.000000  0.000000  0.000000
THMS   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WAVE   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WHEN   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WTOF   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WSHP   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WTON   0.00  0.000000  0.000000  0.00  0.000000  0.000000  0.000000  0.000000

            LIG      NUC       OIL       OTH       PEA       SUN   THE  \
ABHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.95
ALFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
ALKE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
ASHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
BATS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
BEVS   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000  0.00
BSPG   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000  0.00
CAES   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
COMC   0.000000  0.00000  0.014085  0.000000  0.000000  0.000000  0.00
COMCX  0.000000  0.00000  0.100000  0.000000  0.000000  0.000000  0.00
DMFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
GETH   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
GSHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
GTUR   0.000000  0.00000  0.323024  0.006873  0.000000  0.000000  0.00
GTURX  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
H2ST   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HBBS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HDAM   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HDAMC  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HDLZ   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HOBO   0.010000  0.00000  0.150000  0.000000  0.030000  0.000000  0.00
HOBOX  0.000000  0.00000  0.100000  0.000000  0.000000  0.000000  0.00
HPHS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HPHSC  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HROR   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HRORC  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
HYHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.25
ICEN   0.000000  0.00000  0.369863  0.013699  0.000000  0.000000  0.00
ICENX  0.000000  0.00000  0.150000  0.000000  0.000000  0.000000  0.00
MCFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
PAFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
P2BS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
P2GS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
P2HT   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.10
PEFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
PEME   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
PHOT   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000  0.00
REFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
REHE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.05
SCSP   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000  0.00
SOFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
SOTH   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000  0.00
SOXE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
STUR   0.210838  0.11685  0.123624  0.000847  0.014395  0.005927  0.00
STURX  0.000000  0.00000  0.150000  0.000000  0.000000  0.000000  0.00
THMS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  1.00
WAVE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
WHEN   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
WTOF   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00
WSHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  1.00
WTON   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000  0.00

            WAT  WHT  WIN       WST
ABHP   0.000000    0    0  0.000000
ALFC   0.000000    0    0  0.000000
ALKE   0.000000    0    0  0.000000
ASHP   0.000000    0    0  0.000000
BATS   0.000000    0    0  0.000000
BEVS   0.000000    0    0  0.000000
BSPG   0.000000    0    0  0.000000
CAES   0.000000    0    0  0.000000
COMC   0.000000    0    0  0.000000
COMCX  0.000000    0    0  0.000000
DMFC   0.000000    0    0  0.000000
GETH   0.000000    0    0  0.000000
GSHP   0.000000    0    0  0.000000
GTUR   0.000000    0    0  0.010309
GTURX  0.000000    0    0  0.000000
H2ST   0.000000    0    0  0.000000
HBBS   0.000000    0    0  0.000000
HDAM   1.000000    0    0  0.000000
HDAMC  1.000000    0    0  0.000000
HDLZ   1.000000    0    0  0.000000
HOBO   0.000000    0    0  0.000000
HOBOX  0.000000    0    0  0.000000
HPHS   1.000000    0    0  0.000000
HPHSC  1.000000    0    0  0.000000
HROR   1.000000    0    0  0.000000
HRORC  1.000000    0    0  0.000000
HYHP   0.000000    0    0  0.000000
ICEN   0.000000    0    0  0.095890
ICENX  0.000000    0    0  0.000000
MCFC   0.000000    0    0  0.000000
PAFC   0.000000    0    0  0.000000
P2BS   0.000000    0    0  0.000000
P2GS   0.000000    0    0  0.000000
P2HT   0.000000    0    0  0.000000
PEFC   0.000000    0    0  0.000000
PEME   0.000000    0    0  0.000000
PHOT   0.000000    0    0  0.000000
REFC   0.000000    0    0  0.000000
REHE   0.000000    0    0  0.000000
SCSP   0.000000    0    0  0.000000
SOFC   0.000000    0    0  0.000000
SOTH   0.000000    0    0  0.000000
SOXE   0.000000    0    0  0.000000
STUR   0.000847    0    0  0.038950
STURX  0.000000    0    0  0.000000
THMS   0.000000    0    0  0.000000
WAVE   1.000000    0    0  0.000000
WHEN   0.000000    1    0  0.000000
WTOF   0.000000    0    1  0.000000
WSHP   0.000000    0    0  0.000000
WTON   0.000000    0    1  0.000000

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.95,0.000000,0,0,0.000000
ALFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
ALKE,0.00,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
ASHP,0.00,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
BATS,0.00,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
BEVS,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.00,0.000000,0,0,0.000000
BSPG,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.00,0.000000,0,0,0.000000
CAES,0.25,0.000000,0.000000,0.75,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
COMC,0.00,0.002012,0.000000,0.00,0.975855,0.000000,0.008048,0.000000,0.000000,0.00000,0.014085,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
COMCX,0.00,0.000000,0.150000,0.00,0.750000,0.000000,0.000000,0.000000,0.000000,0.00000,0.100000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
DMFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
GETH,0.00,0.000000,0.000000,0.00,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
GSHP,0.00,0.000000,0.000000,0.00,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
GTUR,0.00,0.003436,0.006873,0.00,0.646048,0.000000,0.000000,0.003436,0.000000,0.00000,0.323024,0.006873,0.000000,0.000000,0.00,0.000000,0,0,0.010309
GTURX,0.00,0.000000,0.000000,0.00,0.980000,0.000000,0.000000,0.020000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
H2ST,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
HBBS,0.00,0.000000,1.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
HDAM,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HDAMC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HDLZ,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HOBO,0.00,0.000000,0.200000,0.00,0.600000,0.000000,0.010000,0.000000,0.010000,0.00000,0.150000,0.000000,0.030000,0.000000,0.00,0.000000,0,0,0.000000
HOBOX,0.00,0.000000,0.000000,0.00,0.900000,0.000000,0.000000,0.000000,0.000000,0.00000,0.100000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
HPHS,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HPHSC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HROR,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HRORC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
HYHP,0.75,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.25,0.000000,0,0,0.000000
ICEN,0.00,0.000000,0.136986,0.00,0.383562,0.000000,0.000000,0.000000,0.000000,0.00000,0.369863,0.013699,0.000000,0.000000,0.00,0.000000,0,0,0.095890
ICENX,0.00,0.000000,0.150000,0.00,0.700000,0.000000,0.000000,0.000000,0.000000,0.00000,0.150000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
MCFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
PAFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
P2BS,0.00,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
P2GS,0.00,0.000000,0.000000,0.75,0.000000,0.000000,0.000000,0.250000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
P2HT,0.00,0.000000,0.000000,0.90,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.10,0.000000,0,0,0.000000
PEFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
PEME,0.00,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
PHOT,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.00,0.000000,0,0,0.000000
REFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
REHE,0.00,0.000000,0.000000,0.95,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.05,0.000000,0,0,0.000000
SCSP,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.00,0.000000,0,0,0.000000
SOFC,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
SOTH,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.00,0.000000,0,0,0.000000
SOXE,0.00,0.000000,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
STUR,0.00,0.000000,0.066892,0.00,0.082134,0.008467,0.329382,0.000847,0.210838,0.11685,0.123624,0.000847,0.014395,0.005927,0.00,0.000847,0,0,0.038950
STURX,0.00,0.000000,0.150000,0.00,0.700000,0.000000,0.000000,0.000000,0.000000,0.00000,0.150000,0.000000,0.000000,0.000000,0.00,0.000000,0,0,0.000000
THMS,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.00,0.000000,0,0,0.000000
WAVE,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000,0,0,0.000000
WHEN,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,1,0,0.000000
WTOF,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,1,0.000000
WSHP,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.00,0.000000,0,0,0.000000
WTON,0.00,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0,1,0.000000

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Albania.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Alba Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [15]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
AL_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
AL_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(AL_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(AL_fuel_technologies_match_df)
AL_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Armenia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Arme Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [16]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
AM_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
AM_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(AM_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(AM_fuel_technologies_match_df)
AM_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Azerbaijan.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Azer Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [17]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
AZ_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
AZ_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(AZ_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(AZ_fuel_technologies_match_df)
AZ_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Belarus.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Bela Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [18]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
BY_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
BY_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(BY_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(BY_fuel_technologies_match_df)
BY_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Belgium
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Belg Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            ELIA Group - Transparency platform (Accessed: 2024-11-27)
            <br>
            <a href="https://www.elia.be/en/grid-data" style="color:skyblue">https://www.elia.be/en/grid-data</a>
        </li>
        <li>
            International Energy Agency - Belgium (Accessed: 2024-11-27)
            <br>
            <a href="https://www.iea.org/countries/belgium" style="color:skyblue">https://www.iea.org/countries/belgium</a>
        </li>
        <li>
            FPS Economy - Energy (Accessed: 2024-11-27)
            <br>
            <a href="https://economie.fgov.be/en/themes/energy" style="color:skyblue">https://economie.fgov.be/en/themes/energy</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [19]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
BE_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.15, 0, 0, 0, 0.05, 0.1, 0, 1, 0, 0, 0, 0.10, 0.2, 0, 0, 0, 0, 0.1, 0.05, 0.1, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.95, 0.95, 0, 0, 0.9, 0, 0, 0, 0, 0.9, 1, 1, 0.1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0.8, 0, 0, 0, 0.9, 0.85, 0, 0, 0, 0, 0, 0.75, 0.65, 0, 0, 0, 0, 0, 0.6, 0.65, 0.85, 0.85, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.8, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0.15, 0.05, 0, 0, 0, 0, 0, 0.35, 0.25, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0.05, 0.05, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
BE_fuel_technologies_match_df = pd.DataFrame(BE_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(BE_fuel_technologies_match_df)
BE_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO  HRD  HYD  LIG  NUC   OIL  OTH  PEA  \
ABHP   0.05  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
ALFC   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
ALKE   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
ASHP   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
BATS   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
BEVS   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
BSPG   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
CAES   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
COMC   0.00  0.0  0.05  0.00  0.95    0    0    0    0  0.0  0.00    0    0
COMCX  0.00  0.0  0.15  0.00  0.80    0    0    0    0  0.0  0.00    0    0
DMFC   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    1    0
GETH   0.00  0.0  0.00  0.00  0.00    1    1    0    0  0.0  0.00    0    0
GSHP   0.00  0.0  0.00  0.00  0.00    1    0    0    0  0.0  0.00    0    0
GTUR   0.00  0.0  0.05  0.00  0.90    0    0    0    0  0.0  0.05    0    0
GTURX  0.00  0.0  0.10  0.00  0.85    0    0    0    0  0.0  0.05    0    0
H2ST   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
HBBS   0.00  0.0  1.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HDAM   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HDAMC  0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HDLZ   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HOBO   0.00  0.0  0.10  0.00  0.75    0    0    0    0  0.0  0.15    0    0
HOBOX  0.00  0.0  0.20  0.00  0.65    0    0    0    0  0.0  0.05    0    0
HPHS   0.00  0.0  0.00  0.95  0.00    0    0    0    0  0.0  0.00    0    0
HPHSC  0.00  0.0  0.00  0.95  0.00    0    0    0    0  0.0  0.00    0    0
HROR   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HRORC  0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HYHP   0.00  0.0  0.10  0.90  0.00    0    0    0    0  0.0  0.00    0    0
ICEN   0.00  0.0  0.05  0.00  0.60    0    0    0    0  0.0  0.35    0    0
ICENX  0.00  0.0  0.10  0.00  0.65    0    0    0    0  0.0  0.25    0    0
MCFC   0.00  0.0  0.10  0.00  0.85    0    0    0    0  0.0  0.05    0    0
PAFC   0.00  0.0  0.10  0.00  0.85    0    0    0    0  0.0  0.05    0    0
P2BS   0.00  0.1  0.00  0.90  0.00    0    0    0    0  0.0  0.00    0    0
P2GS   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
P2HT   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
PEFC   0.00  0.0  0.00  0.10  0.90    0    0    0    0  0.0  0.00    0    0
PEME   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
PHOT   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
REFC   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
REHE   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
SCSP   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
SOFC   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
SOTH   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
SOXE   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
STUR   0.00  0.0  0.00  0.00  0.10    0    0    0    0  0.8  0.05    0    0
STURX  0.00  0.0  0.00  0.00  0.20    0    0    0    0  0.8  0.00    0    0
THMS   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WAVE   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WHEN   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WTOF   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WSHP   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
WTON   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0

       SUN   THE   WAT  WHT  WIN   WST
ABHP     0  0.95  0.00    0    0  0.00
ALFC     0  0.00  0.00    0    0  0.00
ALKE     0  0.00  0.00    0    0  0.00
ASHP     0  0.00  0.00    0    0  0.00
BATS     0  0.00  0.00    0    0  0.00
BEVS     0  0.00  0.00    0    0  0.00
BSPG     1  0.00  0.00    0    0  0.00
CAES     0  0.00  0.00    0    0  0.00
COMC     0  0.00  0.00    0    0  0.00
COMCX    0  0.00  0.00    0    0  0.00
DMFC     0  0.00  0.00    0    0  0.00
GETH     0  0.00  0.00    0    0  0.00
GSHP     0  0.00  0.00    0    0  0.00
GTUR     0  0.00  0.00    0    0  0.00
GTURX    0  0.00  0.00    0    0  0.00
H2ST     0  0.00  0.00    0    0  0.00
HBBS     0  0.00  0.00    0    0  0.00
HDAM     0  0.00  1.00    0    0  0.00
HDAMC    0  0.00  1.00    0    0  0.00
HDLZ     0  0.00  1.00    0    0  0.00
HOBO     0  0.00  0.00    0    0  0.00
HOBOX    0  0.00  0.00    0    0  0.05
HPHS     0  0.00  0.05    0    0  0.00
HPHSC    0  0.00  0.05    0    0  0.00
HROR     0  0.00  1.00    0    0  0.00
HRORC    0  0.00  1.00    0    0  0.00
HYHP     0  0.00  0.00    0    0  0.00
ICEN     0  0.00  0.00    0    0  0.00
ICENX    0  0.00  0.00    0    0  0.00
MCFC     0  0.00  0.00    0    0  0.00
PAFC     0  0.00  0.00    0    0  0.00
P2BS     0  0.00  0.00    0    0  0.00
P2GS     0  0.00  0.00    0    0  0.00
P2HT     0  0.00  0.00    0    0  0.00
PEFC     0  0.00  0.00    0    0  0.00
PEME     0  0.00  0.00    0    0  0.00
PHOT     1  0.00  0.00    0    0  0.00
REFC     0  0.00  0.00    0    0  0.00
REHE     0  0.00  0.00    0    0  0.00
SCSP     1  0.00  0.00    0    0  0.00
SOFC     1  0.00  0.00    0    0  0.00
SOTH     1  0.00  0.00    0    0  0.00
SOXE     0  0.00  0.00    0    0  0.00
STUR     0  0.00  0.00    0    0  0.00
STURX    0  0.00  0.00    0    0  0.00
THMS     0  1.00  0.00    0    0  0.00
WAVE     0  0.00  1.00    0    0  0.00
WHEN     0  0.00  0.00    0    0  1.00
WTOF     0  0.00  0.00    0    1  0.00
WSHP     0  0.00  0.00    0    0  0.00
WTON     0  0.00  0.00    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.95,0.00,0,0,0.00
ALFC,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
ALKE,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
ASHP,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
BATS,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
BEVS,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
BSPG,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,1,0.00,0.00,0,0,0.00
CAES,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
COMC,0.00,0.0,0.05,0.00,0.95,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
COMCX,0.00,0.0,0.15,0.00,0.80,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
DMFC,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,1,0,0,0.00,0.00,0,0,0.00
GETH,0.00,0.0,0.00,0.00,0.00,1,1,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
GSHP,0.00,0.0,0.00,0.00,0.00,1,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
GTUR,0.00,0.0,0.05,0.00,0.90,0,0,0,0,0.0,0.05,0,0,0,0.00,0.00,0,0,0.00
GTURX,0.00,0.0,0.10,0.00,0.85,0,0,0,0,0.0,0.05,0,0,0,0.00,0.00,0,0,0.00
H2ST,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
HBBS,0.00,0.0,1.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
HDAM,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,1.00,0,0,0.00
HDAMC,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,1.00,0,0,0.00
HDLZ,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,1.00,0,0,0.00
HOBO,0.00,0.0,0.10,0.00,0.75,0,0,0,0,0.0,0.15,0,0,0,0.00,0.00,0,0,0.00
HOBOX,0.00,0.0,0.20,0.00,0.65,0,0,0,0,0.0,0.05,0,0,0,0.00,0.00,0,0,0.05
HPHS,0.00,0.0,0.00,0.95,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.05,0,0,0.00
HPHSC,0.00,0.0,0.00,0.95,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.05,0,0,0.00
HROR,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,1.00,0,0,0.00
HRORC,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,1.00,0,0,0.00
HYHP,0.00,0.0,0.10,0.90,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
ICEN,0.00,0.0,0.05,0.00,0.60,0,0,0,0,0.0,0.35,0,0,0,0.00,0.00,0,0,0.00
ICENX,0.00,0.0,0.10,0.00,0.65,0,0,0,0,0.0,0.25,0,0,0,0.00,0.00,0,0,0.00
MCFC,0.00,0.0,0.10,0.00,0.85,0,0,0,0,0.0,0.05,0,0,0,0.00,0.00,0,0,0.00
PAFC,0.00,0.0,0.10,0.00,0.85,0,0,0,0,0.0,0.05,0,0,0,0.00,0.00,0,0,0.00
P2BS,0.00,0.1,0.00,0.90,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
P2GS,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
P2HT,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
PEFC,0.00,0.0,0.00,0.10,0.90,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
PEME,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
PHOT,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,1,0.00,0.00,0,0,0.00
REFC,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
REHE,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
SCSP,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,1,0.00,0.00,0,0,0.00
SOFC,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,1,0.00,0.00,0,0,0.00
SOTH,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,1,0.00,0.00,0,0,0.00
SOXE,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
STUR,0.00,0.0,0.00,0.00,0.10,0,0,0,0,0.8,0.05,0,0,0,0.00,0.00,0,0,0.00
STURX,0.00,0.0,0.00,0.00,0.20,0,0,0,0,0.8,0.00,0,0,0,0.00,0.00,0,0,0.00
THMS,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,1.00,0.00,0,0,0.00
WAVE,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,1.00,0,0,0.00
WHEN,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,1.00
WTOF,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,1,0.00
WSHP,0.00,0.0,0.00,1.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,0,0.00
WTON,0.00,0.0,0.00,0.00,0.00,0,0,0,0,0.0,0.00,0,0,0,0.00,0.00,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Bosnia and Herzegovina.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Bosn Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [20]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
BA_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
BA_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(BA_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(BA_fuel_technologies_match_df)
BA_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Bulgaria.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Bulg Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [21]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
BG_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
BG_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(BG_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(BG_fuel_technologies_match_df)
BG_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Croatia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Croat Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [22]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
HR_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
HR_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(HR_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(HR_fuel_technologies_match_df)
HR_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Cyprus.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Cypru Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [23]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
CY_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
CY_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(CY_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(CY_fuel_technologies_match_df)
CY_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Czech Republic.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Cze Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [24]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
CZ_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
CZ_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(CZ_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(CZ_fuel_technologies_match_df)
CZ_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Denmark
    <br>
    <div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
        Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Danish Energy System.
        The same was built using the following additional sources:
    </div>
    <div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
        <ol style="margin-top: 0; padding-left: 1.5em;">
            <li>
                Statistics Denmark. (2024). <i>Energy statistics – Total 2023</i> (Report No. 2024-03-28).<br>
                <a href="https://www.dst.dk/en/Statistik/emner/energi-og-miljoe/energi" style="color:skyblue">https://www.dst.dk/en/Statistik/emner/energi-og-miljoe/energi</a>
            </li>
            <li>
                Danish Energy Agency. (2024). <i>Annual and monthly statistics</i>.<br>
                <a href="https://ens.dk/en/analyses-and-statistics/annual-and-monthly-statistics" style="color:skyblue">https://ens.dk/en/analyses-and-statistics/annual-and-monthly-statistics</a>
            </li>
            <li>
                International Energy Agency. (2023). <i>Denmark 2023: Energy policy review</i>.<br>
                <a href="https://www.iea.org/reports/denmark-2023" style="color:skyblue">https://www.iea.org/reports/denmark-2023</a>
            </li>
        </ol>
    </div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [25]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
DK_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.35, 0, 0, 0, 0, 0.4, 0, 1, 0, 0, 0.35, 0.85, 0.5, 0, 0, 0, 0, 0, 0.3, 0.4, 0, 0, 0.35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0.45, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.5, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.7, 0.55, 0, 0, 0, 0.75, 0.5, 0, 0, 0, 0, 0.55, 0.05, 0.4, 0, 0, 0, 0, 0, 0.25, 0.45, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.55, 0.45, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.25, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.15, 0, 0, 0.15, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.10, 0.1, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
DK_fuel_technologies_match_df = pd.DataFrame(DK_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(DK_fuel_technologies_match_df)
DK_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO  HRD   HYD  LIG  NUC  OIL  OTH  PEA  \
ABHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0    0  0.0    0    0
ALFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.0    0    0
ALKE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
ASHP   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
BATS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
BEVS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
BSPG   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
CAES   0.00    0  0.00  0.65  0.35    0    0  0.00    0    0  0.0    0    0
COMC   0.00    0  0.00  0.00  0.70    0    0  0.00    0    0  0.3    0    0
COMCX  0.00    0  0.35  0.00  0.55    0    0  0.00    0    0  0.1    0    0
DMFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.0    0    0
GETH   0.00    0  0.00  0.00  0.00    1    0  0.00    0    0  0.0    0    0
GSHP   0.00    0  0.00  0.00  0.00    1    0  0.00    0    0  0.0    0    0
GTUR   0.00    0  0.00  0.00  0.75    0    0  0.25    0    0  0.0    0    0
GTURX  0.00    0  0.40  0.00  0.50    0    0  0.10    0    0  0.0    0    0
H2ST   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
HBBS   0.00    0  1.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
HDAM   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
HDAMC  0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
HDLZ   0.00    0  0.35  0.00  0.55    0    0  0.00    0    0  0.1    0    0
HOBO   0.00    0  0.85  0.00  0.05    0    0  0.00    0    0  0.1    0    0
HOBOX  0.00    0  0.50  0.00  0.40    0    0  0.00    0    0  0.1    0    0
HPHS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
HPHSC  0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
HROR   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
HRORC  0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
HYHP   0.90    0  0.00  0.10  0.00    0    0  0.00    0    0  0.0    0    0
ICEN   0.00    0  0.30  0.00  0.25    0    0  0.15    0    0  0.3    0    0
ICENX  0.00    0  0.40  0.00  0.45    0    0  0.15    0    0  0.0    0    0
MCFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.0    0    0
PAFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.0    0    0
P2BS   0.00    0  0.35  0.50  0.00    0    0  0.15    0    0  0.0    0    0
P2GS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
P2HT   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
PEFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.0    0    0
PEME   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
PHOT   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
REFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.0    0    0
REHE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
SCSP   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
SOFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.0    0    0
SOTH   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
SOXE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
STUR   0.00    0  0.25  0.00  0.55    0    0  0.00    0    0  0.2    0    0
STURX  0.00    0  0.45  0.00  0.45    0    0  0.10    0    0  0.0    0    0
THMS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.0    0    0
WAVE   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
WHEN   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
WTOF   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0
WSHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0    0  0.0    0    0
WTON   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.0    0    0

       SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0
ALFC     0    0    0    0    0    0
ALKE     0    0    0    0    0    0
ASHP     0    0    0    0    0    0
BATS     0    0    0    0    0    0
BEVS     0    0    0    0    0    0
BSPG     1    0    0    0    0    0
CAES     0    0    0    0    0    0
COMC     0    0    0    0    0    0
COMCX    0    0    0    0    0    0
DMFC     0    0    0    0    0    0
GETH     0    0    0    0    0    0
GSHP     0    0    0    0    0    0
GTUR     0    0    0    0    0    0
GTURX    0    0    0    0    0    0
H2ST     0    0    0    0    0    0
HBBS     0    0    0    0    0    0
HDAM     0    0    1    0    0    0
HDAMC    0    0    1    0    0    0
HDLZ     0    0    0    0    0    0
HOBO     0    0    0    0    0    0
HOBOX    0    0    0    0    0    0
HPHS     0    0    0    0    0    0
HPHSC    0    0    0    0    0    0
HROR     0    0    1    0    0    0
HRORC    0    0    1    0    0    0
HYHP     0    0    0    0    0    0
ICEN     0    0    0    0    0    0
ICENX    0    0    0    0    0    0
MCFC     0    0    0    0    0    0
PAFC     0    0    0    0    0    0
P2BS     0    0    0    0    0    0
P2GS     0    0    0    0    0    0
P2HT     0    0    0    0    0    0
PEFC     0    0    0    0    0    0
PEME     0    0    0    0    0    0
PHOT     1    0    0    0    0    0
REFC     0    0    0    0    0    0
REHE     0    0    0    0    0    0
SCSP     1    0    0    0    0    0
SOFC     0    0    0    0    0    0
SOTH     1    0    0    0    0    0
SOXE     0    0    0    0    0    0
STUR     0    0    0    0    0    0
STURX    0    0    0    0    0    0
THMS     0    0    0    0    0    0
WAVE     0    0    1    0    0    0
WHEN     0    1    0    0    0    0
WTOF     0    0    0    0    1    0
WSHP     0    0    0    0    0    0
WTON     0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.0,0,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.65,0.35,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.70,0,0,0.00,0,0,0.3,0,0,0,0,0,0,0,0
COMCX,0.00,0,0.35,0.00,0.55,0,0,0.00,0,0,0.1,0,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.0,0,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.75,0,0,0.25,0,0,0.0,0,0,0,0,0,0,0,0
GTURX,0.00,0,0.40,0.00,0.50,0,0,0.10,0,0,0.0,0,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,1,0,0,0
HDLZ,0.00,0,0.35,0.00,0.55,0,0,0.00,0,0,0.1,0,0,0,0,0,0,0,0
HOBO,0.00,0,0.85,0.00,0.05,0,0,0.00,0,0,0.1,0,0,0,0,0,0,0,0
HOBOX,0.00,0,0.50,0.00,0.40,0,0,0.00,0,0,0.1,0,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
ICEN,0.00,0,0.30,0.00,0.25,0,0,0.15,0,0,0.3,0,0,0,0,0,0,0,0
ICENX,0.00,0,0.40,0.00,0.45,0,0,0.15,0,0,0.0,0,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
P2BS,0.00,0,0.35,0.50,0.00,0,0,0.15,0,0,0.0,0,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.0,0,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.0,0,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
STUR,0.00,0,0.25,0.00,0.55,0,0,0.00,0,0,0.2,0,0,0,0,0,0,0,0
STURX,0.00,0,0.45,0.00,0.45,0,0,0.10,0,0,0.0,0,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.0,0,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Estonia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Esto Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [26]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
EE_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
EE_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(EE_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(EE_fuel_technologies_match_df)
EE_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Finland
    <br>
    <div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
        Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Finnish Energy System.
        The same was built using the following additional sources:
    </div>
    <div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
        <ol style="margin-top: 0; padding-left: 1.5em;">
            <li>
                Business Finland. (2022). <i>Future Watch: Growth Opportunities in the Hydrogen Economy</i> (Report).<br>
                <a href="https://www.businessfinland.fi/4961e3/globalassets/julkaisut/future-watch-growth-opportunities-in-the-hydrogen-economy.pdf" style="color:skyblue">https://www.businessfinland.fi/4961e3/globalassets/julkaisut/future-watch-growth-opportunities-in-the-hydrogen-economy.pdf</a>
            </li>
            <li>
                Finnish Bioenergy Association (Bioenergia ry). <i>Tietopankki (Knowledge Bank)</i>.<br>
                <a href="https://www.bioenergia.fi/tietopankki/" style="color:skyblue">https://www.bioenergia.fi/tietopankki/</a>
            </li>
            <li>
                Finnish Energy. (2023). <i>Electricity generation</i>.<br>
                <a href="https://energia.fi/en/energy-sector-in-finland/energy-production/electricity-generation/" style="color:skyblue">https://energia.fi/en/energy-sector-in-finland/energy-production/electricity-generation/</a>
            </li>
            <li>
                Renewables Finland (Suomen uusiutuvat ry). (2024). <i>Finnish Wind Power Association expands its activities to solar power</i>.<br>
                <a href="https://suomenuusiutuvat.fi/en/finnish-wind-power-association-expands-its-activities-to-solar-power/" style="color:skyblue">https://suomenuusiutuvat.fi/en/finnish-wind-power-association-expands-its-activities-to-solar-power/</a>
            </li>
            <li>
                International Energy Agency (IEA). (2024). <i>Heat Pumps</i>.<br>
                <a href="https://www.iea.org/energy-system/buildings/heat-pumps" style="color:skyblue">https://www.iea.org/energy-system/buildings/heat-pumps</a>
            </li>
            <li>
                Statistics Finland. (2025). <i>Production of heat</i> (Survey description).<br>
                <a href="https://stat.fi/en/surveys/ene" style="color:skyblue">https://stat.fi/en/surveys/ene</a>
            </li>
            <li>
                Statistics Finland. (2024). <i>Energy supply and consumption</i> (Official Statistics of Finland).<br>
                <a href="https://stat.fi/en/statistics/ehk" style="color:skyblue">https://stat.fi/en/statistics/ehk</a>
            </li>
        </ol>
    </div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [27]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
FI_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0.45, 0, 1, 0, 0, 0, 0.55, 0.6, 0, 0, 0, 0, 0, 0.25, 0.4, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.5, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.45, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.6, 0.4, 0, 0, 0, 0.7, 0.45, 0, 0, 0, 0, 0, 0.03, 0.3, 0, 0, 0, 0, 0, 0.2, 0.45, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.25, 0.35, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.3, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.15, 0, 0, 0.15, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.4, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.1, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
FI_fuel_technologies_match_df = pd.DataFrame(FI_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(FI_fuel_technologies_match_df)
FI_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO  HRD   HYD  LIG   NUC  OIL   OTH  PEA  \
ABHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
ALFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.0  0.00  0.0
ALKE   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
ASHP   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
BATS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
BEVS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
BSPG   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
CAES   0.00    0  0.00  0.65  0.35    0    0  0.00    0  0.00  0.0  0.00  0.0
COMC   0.00    0  0.00  0.00  0.60    0    0  0.00    0  0.00  0.4  0.00  0.0
COMCX  0.00    0  0.50  0.00  0.40    0    0  0.00    0  0.00  0.1  0.00  0.0
DMFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.0  0.00  0.0
GETH   0.00    0  0.00  0.00  0.00    1    0  0.00    0  0.00  0.0  0.00  0.0
GSHP   0.00    0  0.00  0.00  0.00    1    0  0.00    0  0.00  0.0  0.00  0.0
GTUR   0.00    0  0.00  0.00  0.70    0    0  0.30    0  0.00  0.0  0.00  0.0
GTURX  0.00    0  0.45  0.00  0.45    0    0  0.10    0  0.00  0.0  0.00  0.0
H2ST   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HBBS   0.00    0  1.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HDAM   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HDAMC  0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HDLZ   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HOBO   0.00    0  0.55  0.00  0.03    0    0  0.00    0  0.00  0.2  0.02  0.2
HOBOX  0.00    0  0.60  0.00  0.30    0    0  0.00    0  0.00  0.1  0.00  0.0
HPHS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HPHSC  0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HROR   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HRORC  0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
HYHP   0.90    0  0.00  0.10  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
ICEN   0.00    0  0.25  0.00  0.20    0    0  0.15    0  0.00  0.4  0.00  0.0
ICENX  0.00    0  0.40  0.00  0.45    0    0  0.15    0  0.00  0.0  0.00  0.0
MCFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.0  0.00  0.0
PAFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.0  0.00  0.0
P2BS   0.00    0  0.40  0.45  0.00    0    0  0.15    0  0.00  0.0  0.00  0.0
P2GS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
P2HT   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
PEFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.0  0.00  0.0
PEME   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
PHOT   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
REFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.0  0.00  0.0
REHE   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
SCSP   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
SOFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.0  0.00  0.0
SOTH   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
SOXE   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
STUR   0.00    0  0.20  0.00  0.25    0    0  0.00    0  0.55  0.0  0.00  0.0
STURX  0.00    0  0.50  0.00  0.35    0    0  0.15    0  0.00  0.0  0.00  0.0
THMS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
WAVE   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
WHEN   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
WTOF   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
WSHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0
WTON   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.0  0.00  0.0

       SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0
ALFC     0    0    0    0    0    0
ALKE     0    0    0    0    0    0
ASHP     0    0    0    0    0    0
BATS     0    0    0    0    0    0
BEVS     0    0    0    0    0    0
BSPG     1    0    0    0    0    0
CAES     0    0    0    0    0    0
COMC     0    0    0    0    0    0
COMCX    0    0    0    0    0    0
DMFC     0    0    0    0    0    0
GETH     0    0    0    0    0    0
GSHP     0    0    0    0    0    0
GTUR     0    0    0    0    0    0
GTURX    0    0    0    0    0    0
H2ST     0    0    0    0    0    0
HBBS     0    0    0    0    0    0
HDAM     0    0    1    0    0    0
HDAMC    0    0    1    0    0    0
HDLZ     0    0    1    0    0    0
HOBO     0    0    0    0    0    0
HOBOX    0    0    0    0    0    0
HPHS     0    0    0    0    0    0
HPHSC    0    0    0    0    0    0
HROR     0    0    1    0    0    0
HRORC    0    0    1    0    0    0
HYHP     0    0    0    0    0    0
ICEN     0    0    0    0    0    0
ICENX    0    0    0    0    0    0
MCFC     0    0    0    0    0    0
PAFC     0    0    0    0    0    0
P2BS     0    0    0    0    0    0
P2GS     0    0    0    0    0    0
P2HT     0    0    0    0    0    0
PEFC     0    0    0    0    0    0
PEME     0    0    0    0    0    0
PHOT     1    0    0    0    0    0
REFC     0    0    0    0    0    0
REHE     0    0    0    0    0    0
SCSP     1    0    0    0    0    0
SOFC     0    0    0    0    0    0
SOTH     1    0    0    0    0    0
SOXE     0    0    0    0    0    0
STUR     0    0    0    0    0    0
STURX    0    0    0    0    0    0
THMS     0    0    0    0    0    0
WAVE     0    0    1    0    0    0
WHEN     0    1    0    0    0    0
WTOF     0    0    0    0    1    0
WSHP     0    0    0    0    0    0
WTON     0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.65,0.35,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.60,0,0,0.00,0,0.00,0.4,0.00,0.0,0,0,0,0,0,0
COMCX,0.00,0,0.50,0.00,0.40,0,0,0.00,0,0.00,0.1,0.00,0.0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.70,0,0,0.30,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
GTURX,0.00,0,0.45,0.00,0.45,0,0,0.10,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,1,0,0,0
HOBO,0.00,0,0.55,0.00,0.03,0,0,0.00,0,0.00,0.2,0.02,0.2,0,0,0,0,0,0
HOBOX,0.00,0,0.60,0.00,0.30,0,0,0.00,0,0.00,0.1,0.00,0.0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
ICEN,0.00,0,0.25,0.00,0.20,0,0,0.15,0,0.00,0.4,0.00,0.0,0,0,0,0,0,0
ICENX,0.00,0,0.40,0.00,0.45,0,0,0.15,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
P2BS,0.00,0,0.40,0.45,0.00,0,0,0.15,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
STUR,0.00,0,0.20,0.00,0.25,0,0,0.00,0,0.55,0.0,0.00,0.0,0,0,0,0,0,0
STURX,0.00,0,0.50,0.00,0.35,0,0,0.15,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.0,0.00,0.0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Georgia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Georg Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [28]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
GE_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
GE_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(GE_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(GE_fuel_technologies_match_df)
GE_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Germany
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the German Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            Bundesministerium für Wirtschaft und Klimaschutz (BMWK). (2023). Energiedaten: Gesamtausgabe [Energy Data: Complete Edition].
            <br>
            <a href="https://www.bmwk.de/Redaktion/DE/Artikel/Energie/energiedaten-gesamtausgabe.html" style="color:skyblue">https://www.bmwk.de/Redaktion/DE/Artikel/Energie/energiedaten-gesamtausgabe.html</a>
        </li>
        <li>
            Umweltbundesamt (UBA). (2023). Erneuerbare Energien in Zahlen [Renewable Energies in Figures].
            <br>
            <a href="https://www.umweltbundesamt.de/themen/klima-energie/erneuerbare-energien/erneuerbare-energien-in-zahlen" style="color:skyblue">https://www.umweltbundesamt.de/themen/klima-energie/erneuerbare-energien/erneuerbare-energien-in-zahlen</a>
        </li>
        <li>
            International Energy Agency. (2023). Germany 2023: Energy Policy Review. IEA.
            <br>
            <a href="https://www.iea.org/reports/germany-2025" style="color:skyblue">https://www.iea.org/reports/germany-2025</a>
        </li>
        <li>
            Fraunhofer Institute for Solar Energy Systems (ISE). (2024). Energy Charts.
            <br>
            <a href="https://www.energy-charts.info/index.html?l=en&c=DE" style="color:skyblue">https://www.energy-charts.info/index.html?l=en&c=DE</a>
        </li>
        <li>
            Eurostat. (2024). Energy database. European Commission.
            <br>
            <a href="https://ec.europa.eu/eurostat/web/energy/" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [29]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
DE_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0.08, 0.2, 0, 0, 0, 0.05, 0.15, 0, 1, 0, 0, 0, 0.17, 0.25, 0, 0, 0, 0, 0.15, 0.05, 0.1, 0.15, 0.15, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.95, 0.95, 0, 0, 0.85, 0, 0, 0, 0, 0.85, 1, 1, 0.1, 1, 0, 1, 1, 0, 0.1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.85, 0.7, 0, 0, 0, 0.8, 0.7, 0, 0, 0, 0, 0, 0.55, 0.5, 0, 0, 0, 0, 0, 0.25, 0.3, 0.8, 0.8, 0, 0, 0, 0.75, 0, 0, 0, 0, 0, 0.75, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.015, 0.1, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4, 0.5, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.015, 0.05, 0, 0, 0, 0, 0, 0.05, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.45, 0.3, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.15, 0, 0, 0, 0, 0, 0.24, 0.05, 0, 0, 0, 0, 0, 0.55, 0.35, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0.05, 0.05, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
DE_fuel_technologies_match_df = pd.DataFrame(DE_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(DE_fuel_technologies_match_df)
DE_fuel_technologies_match_df

        AIR   AMO   BIO   ELE   GAS  GEO    HRD  HYD    LIG  NUC   OIL   OTH  \
ABHP   0.05  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
ALFC   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
ALKE   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
ASHP   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
BATS   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
BEVS   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
BSPG   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
CAES   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
COMC   0.00  0.00  0.08  0.00  0.85    0  0.050    0  0.020    0  0.00  0.00
COMCX  0.00  0.00  0.20  0.00  0.70    0  0.050    0  0.050    0  0.00  0.00
DMFC   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  1.00
GETH   0.00  0.00  0.00  0.00  0.00    1  0.000    0  0.000    0  0.00  0.00
GSHP   0.00  0.00  0.00  0.00  0.00    1  0.000    0  0.000    0  0.00  0.00
GTUR   0.00  0.00  0.05  0.00  0.80    0  0.000    0  0.000    0  0.15  0.00
GTURX  0.00  0.00  0.15  0.00  0.70    0  0.000    0  0.000    0  0.15  0.00
H2ST   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HBBS   0.00  0.00  1.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HDAM   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HDAMC  0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HDLZ   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HOBO   0.00  0.00  0.17  0.00  0.55    0  0.015    0  0.015    0  0.24  0.01
HOBOX  0.00  0.00  0.25  0.00  0.50    0  0.100    0  0.050    0  0.05  0.00
HPHS   0.00  0.00  0.00  0.95  0.00    0  0.000    0  0.000    0  0.00  0.00
HPHSC  0.00  0.00  0.00  0.95  0.00    0  0.000    0  0.000    0  0.00  0.00
HROR   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HRORC  0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HYHP   0.00  0.00  0.15  0.85  0.00    0  0.000    0  0.000    0  0.00  0.00
ICEN   0.00  0.00  0.05  0.00  0.25    0  0.100    0  0.050    0  0.55  0.00
ICENX  0.00  0.00  0.10  0.00  0.30    0  0.150    0  0.100    0  0.35  0.00
MCFC   0.00  0.00  0.15  0.00  0.80    0  0.000    0  0.000    0  0.05  0.00
PAFC   0.00  0.00  0.15  0.00  0.80    0  0.000    0  0.000    0  0.05  0.00
P2BS   0.00  0.15  0.00  0.85  0.00    0  0.000    0  0.000    0  0.00  0.00
P2GS   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
P2HT   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
PEFC   0.00  0.00  0.15  0.10  0.75    0  0.000    0  0.000    0  0.00  0.00
PEME   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
PHOT   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
REFC   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
REHE   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
SCSP   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
SOFC   0.00  0.00  0.10  0.10  0.75    0  0.000    0  0.000    0  0.05  0.00
SOTH   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
SOXE   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
STUR   0.00  0.00  0.05  0.00  0.10    0  0.400    0  0.450    0  0.00  0.00
STURX  0.00  0.00  0.05  0.00  0.15    0  0.500    0  0.300    0  0.00  0.00
THMS   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WAVE   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WHEN   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WTOF   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WSHP   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WTON   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00

       PEA  SUN   THE   WAT  WHT  WIN   WST
ABHP     0    0  0.95  0.00    0    0  0.00
ALFC     0    0  0.00  0.00    0    0  0.00
ALKE     0    0  0.00  0.00    0    0  0.00
ASHP     0    0  0.00  0.00    0    0  0.00
BATS     0    0  0.00  0.00    0    0  0.00
BEVS     0    0  0.00  0.00    0    0  0.00
BSPG     0    1  0.00  0.00    0    0  0.00
CAES     0    0  0.00  0.00    0    0  0.00
COMC     0    0  0.00  0.00    0    0  0.00
COMCX    0    0  0.00  0.00    0    0  0.00
DMFC     0    0  0.00  0.00    0    0  0.00
GETH     0    0  0.00  0.00    0    0  0.00
GSHP     0    0  0.00  0.00    0    0  0.00
GTUR     0    0  0.00  0.00    0    0  0.00
GTURX    0    0  0.00  0.00    0    0  0.00
H2ST     0    0  0.00  0.00    0    0  0.00
HBBS     0    0  0.00  0.00    0    0  0.00
HDAM     0    0  0.00  1.00    0    0  0.00
HDAMC    0    0  0.00  1.00    0    0  0.00
HDLZ     0    0  0.00  1.00    0    0  0.00
HOBO     0    0  0.00  0.00    0    0  0.00
HOBOX    0    0  0.00  0.00    0    0  0.05
HPHS     0    0  0.00  0.05    0    0  0.00
HPHSC    0    0  0.00  0.05    0    0  0.00
HROR     0    0  0.00  1.00    0    0  0.00
HRORC    0    0  0.00  1.00    0    0  0.00
HYHP     0    0  0.00  0.00    0    0  0.00
ICEN     0    0  0.00  0.00    0    0  0.00
ICENX    0    0  0.00  0.00    0    0  0.00
MCFC     0    0  0.00  0.00    0    0  0.00
PAFC     0    0  0.00  0.00    0    0  0.00
P2BS     0    0  0.00  0.00    0    0  0.00
P2GS     0    0  0.00  0.00    0    0  0.00
P2HT     0    0  0.00  0.00    0    0  0.00
PEFC     0    0  0.00  0.00    0    0  0.00
PEME     0    0  0.00  0.00    0    0  0.00
PHOT     0    1  0.00  0.00    0    0  0.00
REFC     0    0  0.00  0.00    0    0  0.00
REHE     0    0  0.00  0.00    0    0  0.00
SCSP     0    1  0.00  0.00    0    0  0.00
SOFC     0    0  0.00  0.00    0    0  0.00
SOTH     0    1  0.00  0.00    0    0  0.00
SOXE     0    0  0.00  0.00    0    0  0.00
STUR     0    0  0.00  0.00    0    0  0.00
STURX    0    0  0.00  0.00    0    0  0.00
THMS     0    0  1.00  0.00    0    0  0.00
WAVE     0    0  0.00  1.00    0    0  0.00
WHEN     0    0  0.00  0.00    1    0  0.00
WTOF     0    0  0.00  0.00    0    1  0.00
WSHP     0    0  0.00  0.00    0    0  0.00
WTON     0    0  0.00  0.00    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.95,0.00,0,0,0.00
ALFC,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
ALKE,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
ASHP,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
BATS,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
BEVS,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
BSPG,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,1,0.00,0.00,0,0,0.00
CAES,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
COMC,0.00,0.00,0.08,0.00,0.85,0,0.050,0,0.020,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
COMCX,0.00,0.00,0.20,0.00,0.70,0,0.050,0,0.050,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
DMFC,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,1.00,0,0,0.00,0.00,0,0,0.00
GETH,0.00,0.00,0.00,0.00,0.00,1,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
GSHP,0.00,0.00,0.00,0.00,0.00,1,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
GTUR,0.00,0.00,0.05,0.00,0.80,0,0.000,0,0.000,0,0.15,0.00,0,0,0.00,0.00,0,0,0.00
GTURX,0.00,0.00,0.15,0.00,0.70,0,0.000,0,0.000,0,0.15,0.00,0,0,0.00,0.00,0,0,0.00
H2ST,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
HBBS,0.00,0.00,1.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
HDAM,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HDAMC,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HDLZ,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HOBO,0.00,0.00,0.17,0.00,0.55,0,0.015,0,0.015,0,0.24,0.01,0,0,0.00,0.00,0,0,0.00
HOBOX,0.00,0.00,0.25,0.00,0.50,0,0.100,0,0.050,0,0.05,0.00,0,0,0.00,0.00,0,0,0.05
HPHS,0.00,0.00,0.00,0.95,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.05,0,0,0.00
HPHSC,0.00,0.00,0.00,0.95,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.05,0,0,0.00
HROR,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HRORC,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HYHP,0.00,0.00,0.15,0.85,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
ICEN,0.00,0.00,0.05,0.00,0.25,0,0.100,0,0.050,0,0.55,0.00,0,0,0.00,0.00,0,0,0.00
ICENX,0.00,0.00,0.10,0.00,0.30,0,0.150,0,0.100,0,0.35,0.00,0,0,0.00,0.00,0,0,0.00
MCFC,0.00,0.00,0.15,0.00,0.80,0,0.000,0,0.000,0,0.05,0.00,0,0,0.00,0.00,0,0,0.00
PAFC,0.00,0.00,0.15,0.00,0.80,0,0.000,0,0.000,0,0.05,0.00,0,0,0.00,0.00,0,0,0.00
P2BS,0.00,0.15,0.00,0.85,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
P2GS,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
P2HT,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
PEFC,0.00,0.00,0.15,0.10,0.75,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
PEME,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
PHOT,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,1,0.00,0.00,0,0,0.00
REFC,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
REHE,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
SCSP,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,1,0.00,0.00,0,0,0.00
SOFC,0.00,0.00,0.10,0.10,0.75,0,0.000,0,0.000,0,0.05,0.00,0,0,0.00,0.00,0,0,0.00
SOTH,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,1,0.00,0.00,0,0,0.00
SOXE,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
STUR,0.00,0.00,0.05,0.00,0.10,0,0.400,0,0.450,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
STURX,0.00,0.00,0.05,0.00,0.15,0,0.500,0,0.300,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
THMS,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,1.00,0.00,0,0,0.00
WAVE,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,1.00,0,0,0.00
WHEN,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,1,0,0.00
WTOF,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,1,0.00
WSHP,0.00,0.00,0.00,1.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,0,0.00
WTON,0.00,0.00,0.00,0.00,0.00,0,0.000,0,0.000,0,0.00,0.00,0,0,0.00,0.00,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for France
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the French Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            RTE - Eco2mix Data: Detailed Electricity Generation by Technology (2025).
            <br>
            <a href="https://www.rte-france.com/en/eco2mix" style="color:skyblue">https://www.rte-france.com/en/eco2mix</a>
        </li>
        <li>
            Eurostat - Energy Balances for France (2025).
            <br>
            <a href="https://ec.europa.eu/eurostat/web/energy" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy</a>
        </li>
        <li>
            Ministère de la Transition Énergétique - Chiffres clés de l'énergie et Plan National Énergie-Climat (2025).
            <br>
            <a href="https://www.statistiques.developpement-durable.gouv.fr/energie" style="color:skyblue">https://www.statistiques.developpement-durable.gouv.fr/energie</a>
        </li>
        <li>
            International Energy Agency (IEA) - France Country Review and Energy Policy Analysis (2025).
            <br>
            <a href="https://www.iea.org/countries/france" style="color:skyblue">https://www.iea.org/countries/france</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [30]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
FR_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0.03, 0.1, 0, 0, 0, 0.05, 0.1, 0, 1, 0, 0, 0, 0.20, 0.2, 0, 0, 0, 0, 0.1, 0.05, 0.1, 0.1, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.95, 0.95, 0, 0, 0.9, 0, 0, 0, 0, 0.9, 1, 1, 0.1, 1, 0, 1, 1, 0, 0.1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0.4, 0.35, 0, 0, 0, 0, 0, 0.45, 0.25, 0, 0, 0, 0, 0, 0.25, 0.3, 0.7, 0.7, 0, 0, 0, 0.75, 0, 0, 0, 0, 0, 0.75, 0, 0, 0.05, 0.1, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.005, 0.05, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.1, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.005, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.1, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.65, 0, 0, 0, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.65, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0.30, 0.45, 0, 0, 0, 0, 0, 0.6, 0.45, 0.2, 0.2, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.04, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0.05, 0.05, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
FR_fuel_technologies_match_df = pd.DataFrame(FR_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(FR_fuel_technologies_match_df)
FR_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO    HRD  HYD    LIG   NUC   OIL   OTH  \
ABHP   0.05  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ALFC   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ALKE   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ASHP   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
BATS   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
BEVS   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
BSPG   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
CAES   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
COMC   0.00  0.0  0.03  0.00  0.10    0  0.020    0  0.000  0.80  0.05  0.00
COMCX  0.00  0.0  0.10  0.00  0.15    0  0.050    0  0.000  0.65  0.05  0.00
DMFC   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  1.00
GETH   0.00  0.0  0.00  0.00  0.00    1  0.000    0  0.000  0.00  0.00  0.00
GSHP   0.00  0.0  0.00  0.00  0.00    1  0.000    0  0.000  0.00  0.00  0.00
GTUR   0.00  0.0  0.05  0.00  0.40    0  0.000    0  0.000  0.50  0.05  0.00
GTURX  0.00  0.0  0.10  0.00  0.35    0  0.000    0  0.000  0.50  0.05  0.00
H2ST   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HBBS   0.00  0.0  1.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HDAM   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HDAMC  0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HDLZ   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HOBO   0.00  0.0  0.20  0.00  0.45    0  0.005    0  0.005  0.00  0.30  0.04
HOBOX  0.00  0.0  0.20  0.00  0.25    0  0.050    0  0.000  0.00  0.45  0.00
HPHS   0.00  0.0  0.00  0.95  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HPHSC  0.00  0.0  0.00  0.95  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HROR   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HRORC  0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HYHP   0.00  0.0  0.10  0.90  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ICEN   0.00  0.0  0.05  0.00  0.25    0  0.100    0  0.000  0.00  0.60  0.00
ICENX  0.00  0.0  0.10  0.00  0.30    0  0.150    0  0.000  0.00  0.45  0.00
MCFC   0.00  0.0  0.10  0.00  0.70    0  0.000    0  0.000  0.00  0.20  0.00
PAFC   0.00  0.0  0.10  0.00  0.70    0  0.000    0  0.000  0.00  0.20  0.00
P2BS   0.00  0.1  0.00  0.90  0.00    0  0.000    0  0.000  0.00  0.00  0.00
P2GS   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
P2HT   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
PEFC   0.00  0.0  0.10  0.10  0.75    0  0.000    0  0.000  0.00  0.05  0.00
PEME   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
PHOT   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
REFC   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
REHE   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
SCSP   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
SOFC   0.00  0.0  0.10  0.10  0.75    0  0.000    0  0.000  0.00  0.05  0.00
SOTH   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
SOXE   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
STUR   0.00  0.0  0.05  0.00  0.05    0  0.050    0  0.050  0.80  0.00  0.00
STURX  0.00  0.0  0.05  0.00  0.10    0  0.100    0  0.100  0.65  0.00  0.00
THMS   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WAVE   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WHEN   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WTOF   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WSHP   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WTON   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00

       PEA  SUN   THE   WAT  WHT  WIN   WST
ABHP     0    0  0.95  0.00    0    0  0.00
ALFC     0    0  0.00  0.00    0    0  0.00
ALKE     0    0  0.00  0.00    0    0  0.00
ASHP     0    0  0.00  0.00    0    0  0.00
BATS     0    0  0.00  0.00    0    0  0.00
BEVS     0    0  0.00  0.00    0    0  0.00
BSPG     0    1  0.00  0.00    0    0  0.00
CAES     0    0  0.00  0.00    0    0  0.00
COMC     0    0  0.00  0.00    0    0  0.00
COMCX    0    0  0.00  0.00    0    0  0.00
DMFC     0    0  0.00  0.00    0    0  0.00
GETH     0    0  0.00  0.00    0    0  0.00
GSHP     0    0  0.00  0.00    0    0  0.00
GTUR     0    0  0.00  0.00    0    0  0.00
GTURX    0    0  0.00  0.00    0    0  0.00
H2ST     0    0  0.00  0.00    0    0  0.00
HBBS     0    0  0.00  0.00    0    0  0.00
HDAM     0    0  0.00  1.00    0    0  0.00
HDAMC    0    0  0.00  1.00    0    0  0.00
HDLZ     0    0  0.00  1.00    0    0  0.00
HOBO     0    0  0.00  0.00    0    0  0.00
HOBOX    0    0  0.00  0.00    0    0  0.05
HPHS     0    0  0.00  0.05    0    0  0.00
HPHSC    0    0  0.00  0.05    0    0  0.00
HROR     0    0  0.00  1.00    0    0  0.00
HRORC    0    0  0.00  1.00    0    0  0.00
HYHP     0    0  0.00  0.00    0    0  0.00
ICEN     0    0  0.00  0.00    0    0  0.00
ICENX    0    0  0.00  0.00    0    0  0.00
MCFC     0    0  0.00  0.00    0    0  0.00
PAFC     0    0  0.00  0.00    0    0  0.00
P2BS     0    0  0.00  0.00    0    0  0.00
P2GS     0    0  0.00  0.00    0    0  0.00
P2HT     0    0  0.00  0.00    0    0  0.00
PEFC     0    0  0.00  0.00    0    0  0.00
PEME     0    0  0.00  0.00    0    0  0.00
PHOT     0    1  0.00  0.00    0    0  0.00
REFC     0    0  0.00  0.00    0    0  0.00
REHE     0    0  0.00  0.00    0    0  0.00
SCSP     0    1  0.00  0.00    0    0  0.00
SOFC     0    0  0.00  0.00    0    0  0.00
SOTH     0    1  0.00  0.00    0    0  0.00
SOXE     0    0  0.00  0.00    0    0  0.00
STUR     0    0  0.00  0.00    0    0  0.00
STURX    0    0  0.00  0.00    0    0  0.00
THMS     0    0  1.00  0.00    0    0  0.00
WAVE     0    0  0.00  1.00    0    0  0.00
WHEN     0    0  0.00  0.00    1    0  0.00
WTOF     0    0  0.00  0.00    0    1  0.00
WSHP     0    0  0.00  0.00    0    0  0.00
WTON     0    0  0.00  0.00    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.95,0.00,0,0,0.00
ALFC,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
ALKE,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
ASHP,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
BATS,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
BEVS,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
BSPG,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,1,0.00,0.00,0,0,0.00
CAES,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
COMC,0.00,0.0,0.03,0.00,0.10,0,0.020,0,0.000,0.80,0.05,0.00,0,0,0.00,0.00,0,0,0.00
COMCX,0.00,0.0,0.10,0.00,0.15,0,0.050,0,0.000,0.65,0.05,0.00,0,0,0.00,0.00,0,0,0.00
DMFC,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,1.00,0,0,0.00,0.00,0,0,0.00
GETH,0.00,0.0,0.00,0.00,0.00,1,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
GSHP,0.00,0.0,0.00,0.00,0.00,1,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
GTUR,0.00,0.0,0.05,0.00,0.40,0,0.000,0,0.000,0.50,0.05,0.00,0,0,0.00,0.00,0,0,0.00
GTURX,0.00,0.0,0.10,0.00,0.35,0,0.000,0,0.000,0.50,0.05,0.00,0,0,0.00,0.00,0,0,0.00
H2ST,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
HBBS,0.00,0.0,1.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
HDAM,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HDAMC,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HDLZ,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HOBO,0.00,0.0,0.20,0.00,0.45,0,0.005,0,0.005,0.00,0.30,0.04,0,0,0.00,0.00,0,0,0.00
HOBOX,0.00,0.0,0.20,0.00,0.25,0,0.050,0,0.000,0.00,0.45,0.00,0,0,0.00,0.00,0,0,0.05
HPHS,0.00,0.0,0.00,0.95,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.05,0,0,0.00
HPHSC,0.00,0.0,0.00,0.95,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.05,0,0,0.00
HROR,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HRORC,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,1.00,0,0,0.00
HYHP,0.00,0.0,0.10,0.90,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
ICEN,0.00,0.0,0.05,0.00,0.25,0,0.100,0,0.000,0.00,0.60,0.00,0,0,0.00,0.00,0,0,0.00
ICENX,0.00,0.0,0.10,0.00,0.30,0,0.150,0,0.000,0.00,0.45,0.00,0,0,0.00,0.00,0,0,0.00
MCFC,0.00,0.0,0.10,0.00,0.70,0,0.000,0,0.000,0.00,0.20,0.00,0,0,0.00,0.00,0,0,0.00
PAFC,0.00,0.0,0.10,0.00,0.70,0,0.000,0,0.000,0.00,0.20,0.00,0,0,0.00,0.00,0,0,0.00
P2BS,0.00,0.1,0.00,0.90,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
P2GS,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
P2HT,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
PEFC,0.00,0.0,0.10,0.10,0.75,0,0.000,0,0.000,0.00,0.05,0.00,0,0,0.00,0.00,0,0,0.00
PEME,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
PHOT,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,1,0.00,0.00,0,0,0.00
REFC,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
REHE,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
SCSP,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,1,0.00,0.00,0,0,0.00
SOFC,0.00,0.0,0.10,0.10,0.75,0,0.000,0,0.000,0.00,0.05,0.00,0,0,0.00,0.00,0,0,0.00
SOTH,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,1,0.00,0.00,0,0,0.00
SOXE,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
STUR,0.00,0.0,0.05,0.00,0.05,0,0.050,0,0.050,0.80,0.00,0.00,0,0,0.00,0.00,0,0,0.00
STURX,0.00,0.0,0.05,0.00,0.10,0,0.100,0,0.100,0.65,0.00,0.00,0,0,0.00,0.00,0,0,0.00
THMS,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,1.00,0.00,0,0,0.00
WAVE,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,1.00,0,0,0.00
WHEN,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,1,0,0.00
WTOF,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,1,0.00
WSHP,0.00,0.0,0.00,1.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,0,0.00
WTON,0.00,0.0,0.00,0.00,0.00,0,0.000,0,0.000,0.00,0.00,0.00,0,0,0.00,0.00,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Greece.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Gree Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [31]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
EL_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
EL_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(EL_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(EL_fuel_technologies_match_df)
EL_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Hungary.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Hunga Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [32]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
HU_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
HU_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(HU_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(HU_fuel_technologies_match_df)
HU_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Iceland.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Ice Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [33]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
IS_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
IS_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(IS_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(IS_fuel_technologies_match_df)
IS_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Ireland
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Irish Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            Department of the Environment, Climate and Communications. (2023, July 12). National Hydrogen Strategy. Government of Ireland.
            <br>
            <a href="https://assets.gov.ie/static/documents/national-hydrogen-strategy.pdf" style="color:skyblue">https://assets.gov.ie/static/documents/national-hydrogen-strategy.pdf</a>
        </li>
        <li>
            Environmental Protection Agency (EPA). (2024). Circular Economy and Waste Statistics Highlights Report 2022.
            <br>
            <a href="https://www.epa.ie/publications/monitoring--assessment/waste/national-waste-statistics/circular-economy-and-waste-statistics-highlights-report-2022.php" style="color:skyblue">https://www.epa.ie/publications/monitoring--assessment/waste/national-waste-statistics/circular-economy-and-waste-statistics-highlights-report-2022.php</a>
        </li>
        <li>
            EirGrid. (2024). Fuel Mix 2024 [Infographic].
            <br>
            <a href="https://cms.eirgrid.ie/sites/default/files/publications/Fuel-Mix-2024.png" style="color:skyblue">https://cms.eirgrid.ie/sites/default/files/publications/Fuel-Mix-2024.png</a>
        </li>
        <li>
            EirGrid. (n.d.). Generation data from the Smart Grid Dashboard. Retrieved October 10, 2025.
            <br>
            <a href="https://www.smartgriddashboard.com/all/generation/" style="color:skyblue">https://www.smartgriddashboard.com/all/generation/</a>
        </li>
        <li>
            SONI and EirGrid. (2024). Ten-Year Generation Capacity Statement 2023–2032.
            <br>
            <a href="https://cms.soni.ltd.uk/sites/default/files/media/documents/SONI-Generation-Capacity-Statement-2023-2032.pdf" style="color:skyblue">https://cms.soni.ltd.uk/sites/default/files/media/documents/SONI-Generation-Capacity-Statement-2023-2032.pdf</a>
        </li>
        <li>
            EirGrid. (2023). Annual Report 2022.
            <br>
            <a href="https://cms.eirgrid.ie/sites/default/files/publications/EirGrid-Annual-Report-2022.pdf" style="color:skyblue">https://cms.eirgrid.ie/sites/default/files/publications/EirGrid-Annual-Report-2022.pdf</a>
        </li>
        <li>
            ESB. (n.d.). Generation and trading. Retrieved October 10, 2025.
            <br>
            <a href="https://esb.ie/what-we-do/generation-and-trading" style="color:skyblue">https://esb.ie/what-we-do/generation-and-trading</a>
        </li>
        <li>
            International Energy Agency (IEA). (2025, January 24). Ireland. Retrieved October 10, 2025.
            <br>
            <a href="https://www.iea.org/countries/ireland" style="color:skyblue">https://www.iea.org/countries/ireland</a>
        </li>
        <li>
            Wind Energy Ireland. (n.d.). Wind energy reports (Monthly dashboard). Retrieved October 10, 2025.
            <br>
            <a href="https://windenergyireland.com/about-wind/more-resources/monthly-dashboard" style="color:skyblue">https://windenergyireland.com/about-wind/more-resources/monthly-dashboard</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2022). Annual Report 2021.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/SEAI-Annual-Report-2021.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/SEAI-Annual-Report-2021.pdf</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2023). Energy in Ireland 2022.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/Energy-in-Ireland-2022.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/Energy-in-Ireland-2022.pdf</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2024). Energy in Ireland 2024.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/energy-in-ireland-2024.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/energy-in-ireland-2024.pdf</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2025, August). First Look: Ireland's Energy Supply and Security of Supply in 2024.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/First-Look-Energy-Supply-and-Security-of-Supply.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/First-Look-Energy-Supply-and-Security-of-Supply.pdf</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2024). Energy in Ireland 2024 data and charts (Appendix 10) [Data set].
            <br>
            <a href="https://www.seai.ie/sites/default/files/2025-02/Energy-in-Ireland-2024-data-and-charts.xlsx" style="color:skyblue">https://www.seai.ie/sites/default/files/2025-02/Energy-in-Ireland-2024-data-and-charts.xlsx</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (n.d.). Sustainable biomass fuels in Ireland. Retrieved October 10, 2025.
            <br>
            <a href="https://www.seai.ie/renewable-energy/bioenergy/biomass-in-ireland" style="color:skyblue">https://www.seai.ie/renewable-energy/bioenergy/biomass-in-ireland</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2005). Tidal & current energy resources in Ireland.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/Tidal_Current_Energy_Resources_in_Ireland_Report.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/Tidal_Current_Energy_Resources_in_Ireland_Report.pdf</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (n.d.). Geothermal energy. Retrieved June 4, 2024.
            <br>
            <a href="https://www.seai.ie/technologies/geothermal-energy/" style="color:skyblue">https://www.seai.ie/technologies/geothermal-energy/</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2025). SEAI annual report 2024: English and Irish.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/SEAI-Annual-Report-2024-English-and-Irish.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/SEAI-Annual-Report-2024-English-and-Irish.pdf</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (n.d.). Offshore Renewable Energy. Retrieved October 10, 2025.
            <br>
            <a href="https://www.seai.ie/renewable-energy/Offshore-Renewable-Energy" style="color:skyblue">https://www.seai.ie/renewable-energy/Offshore-Renewable-Energy</a>
        </li>
        <li>
            Sustainable Energy Authority of Ireland (SEAI). (2011). Smart Grids Roadmap.
            <br>
            <a href="https://www.seai.ie/sites/default/files/publications/Smartgrid-Roadmap.pdf" style="color:skyblue">https://www.seai.ie/sites/default/files/publications/Smartgrid-Roadmap.pdf</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [34]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
IE_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0.5, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.9, 0.8, 0, 0, 0, 0.95, 0.85, 0, 0, 0, 0, 0.8, 0.4, 0.7, 0, 0, 0, 0, 0, 0.2, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0, 0, 0.45, 0.5, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.05, 0, 0, 0, 0.05, 0.15, 0, 0.1, 0, 0, 0.05, 0.40, 0.3, 0, 0, 0, 0, 0, 0.8, 0.75, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.45, 0.35, 0, 0, 0, 0, 0, 0]
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
IE_fuel_technologies_match_df = pd.DataFrame(IE_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(IE_fuel_technologies_match_df)
IE_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO   HRD   HYD  LIG  NUC   OIL   OTH  \
ABHP   0.95    0  0.00  0.05  0.00    0  0.00  0.00    0    0  0.00  0.00
ALFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00    0    0  0.00  0.00
ALKE   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
ASHP   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
BATS   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
BEVS   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
BSPG   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
CAES   0.00    0  0.00  0.65  0.35    0  0.00  0.00    0    0  0.00  0.00
COMC   0.00    0  0.00  0.00  0.90    0  0.00  0.00    0    0  0.10  0.00
COMCX  0.00    0  0.15  0.00  0.80    0  0.00  0.00    0    0  0.05  0.00
DMFC   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  1.00
GETH   0.00    0  0.00  0.00  0.00    1  0.00  0.00    0    0  0.00  0.00
GSHP   0.00    0  0.00  0.00  0.00    1  0.00  0.00    0    0  0.00  0.00
GTUR   0.00    0  0.00  0.00  0.95    0  0.00  0.00    0    0  0.05  0.00
GTURX  0.00    0  0.00  0.00  0.85    0  0.00  0.00    0    0  0.15  0.00
H2ST   0.00    0  0.00  0.00  0.00    0  0.00  1.00    0    0  0.00  0.00
HBBS   0.90    0  0.90  0.00  0.00    0  0.00  0.00    0    0  0.10  0.00
HDAM   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
HDAMC  0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
HDLZ   0.00    0  0.50  0.00  0.80    0  0.00  0.00    0    0  0.05  0.00
HOBO   0.00    0  0.05  0.00  0.40    0  0.03  0.00    0    0  0.40  0.02
HOBOX  0.00    0  0.00  0.00  0.70    0  0.00  0.00    0    0  0.30  0.00
HPHS   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
HPHSC  0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
HROR   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
HRORC  0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
HYHP   0.90    0  0.00  0.10  0.00    0  0.00  0.00    0    0  0.00  0.00
ICEN   0.00    0  0.00  0.00  0.20    0  0.00  0.00    0    0  0.80  0.00
ICENX  0.00    0  0.00  0.00  0.25    0  0.00  0.00    0    0  0.75  0.00
MCFC   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  1.00
PAFC   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  1.00
P2BS   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
P2GS   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
P2HT   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
PEFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00    0    0  0.00  0.00
PEME   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
PHOT   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
REFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00    0    0  0.00  0.00
REHE   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
SCSP   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
SOFC   0.00    0  0.00  0.00  0.95    0  0.00  0.05    0    0  0.00  0.00
SOTH   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  1.00
SOXE   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
STUR   0.00    0  0.00  0.00  0.45    0  0.00  0.00    0    0  0.10  0.00
STURX  0.00    0  0.00  0.00  0.50    0  0.00  0.00    0    0  0.15  0.00
THMS   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
WAVE   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
WHEN   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
WTOF   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00
WSHP   0.00    0  0.00  1.00  0.00    0  0.00  0.00    0    0  0.00  0.00
WTON   0.00    0  0.00  0.00  0.00    0  0.00  0.00    0    0  0.00  0.00

       PEA  SUN  THE  WAT  WHT  WIN   WST
ABHP   0.0    0    0    0    0    0  0.00
ALFC   0.0    0    0    0    0    0  0.00
ALKE   0.0    0    0    0    0    0  0.00
ASHP   0.0    0    0    0    0    0  0.00
BATS   0.0    0    0    0    0    0  0.00
BEVS   0.0    0    0    0    0    0  0.00
BSPG   0.0    1    0    0    0    0  0.00
CAES   0.0    0    0    0    0    0  0.00
COMC   0.0    0    0    0    0    0  0.00
COMCX  0.0    0    0    0    0    0  0.00
DMFC   0.0    0    0    0    0    0  0.00
GETH   0.0    0    0    0    0    0  0.00
GSHP   0.0    0    0    0    0    0  0.00
GTUR   0.0    0    0    0    0    0  0.00
GTURX  0.0    0    0    0    0    0  0.00
H2ST   0.0    0    0    0    0    0  0.00
HBBS   0.0    0    0    0    0    0  0.00
HDAM   0.0    0    0    1    0    0  0.00
HDAMC  0.0    0    0    1    0    0  0.00
HDLZ   0.0    0    0    0    0    0  0.00
HOBO   0.1    0    0    0    0    0  0.00
HOBOX  0.0    0    0    0    0    0  0.00
HPHS   0.0    0    0    0    0    0  0.00
HPHSC  0.0    0    0    0    0    0  0.00
HROR   0.0    0    0    1    0    0  0.00
HRORC  0.0    0    0    1    0    0  0.00
HYHP   0.0    0    0    0    0    0  0.00
ICEN   0.0    0    0    0    0    0  0.00
ICENX  0.0    0    0    0    0    0  0.00
MCFC   0.0    0    0    0    0    0  0.00
PAFC   0.0    0    0    0    0    0  0.00
P2BS   0.0    0    0    0    0    0  0.00
P2GS   0.0    0    0    0    0    0  0.00
P2HT   0.0    0    0    0    0    0  0.00
PEFC   0.0    0    0    0    0    0  0.00
PEME   0.0    0    0    0    0    0  0.00
PHOT   0.0    1    0    0    0    0  0.00
REFC   0.0    0    0    0    0    0  0.00
REHE   0.0    0    0    0    0    0  0.00
SCSP   0.0    1    0    0    0    0  0.00
SOFC   0.0    0    0    0    0    0  0.00
SOTH   0.0    0    0    0    0    0  0.00
SOXE   0.0    0    0    0    0    0  0.00
STUR   0.0    0    0    0    0    0  0.45
STURX  0.0    0    0    0    0    0  0.35
THMS   0.0    0    0    0    1    0  0.00
WAVE   0.0    0    0    1    0    0  0.00
WHEN   0.0    0    0    0    1    0  0.00
WTOF   0.0    0    0    0    0    1  0.00
WSHP   0.0    0    0    0    0    0  0.00
WTON   0.0    0    0    0    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
ALFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
ALKE,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
ASHP,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
BATS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
BEVS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
BSPG,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,1,0,0,0,0,0.00
CAES,0.00,0,0.00,0.65,0.35,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
COMC,0.00,0,0.00,0.00,0.90,0,0.00,0.00,0,0,0.10,0.00,0.0,0,0,0,0,0,0.00
COMCX,0.00,0,0.15,0.00,0.80,0,0.00,0.00,0,0,0.05,0.00,0.0,0,0,0,0,0,0.00
DMFC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,1.00,0.0,0,0,0,0,0,0.00
GETH,0.00,0,0.00,0.00,0.00,1,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
GSHP,0.00,0,0.00,0.00,0.00,1,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
GTUR,0.00,0,0.00,0.00,0.95,0,0.00,0.00,0,0,0.05,0.00,0.0,0,0,0,0,0,0.00
GTURX,0.00,0,0.00,0.00,0.85,0,0.00,0.00,0,0,0.15,0.00,0.0,0,0,0,0,0,0.00
H2ST,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
HBBS,0.90,0,0.90,0.00,0.00,0,0.00,0.00,0,0,0.10,0.00,0.0,0,0,0,0,0,0.00
HDAM,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,1,0,0,0.00
HDAMC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,1,0,0,0.00
HDLZ,0.00,0,0.50,0.00,0.80,0,0.00,0.00,0,0,0.05,0.00,0.0,0,0,0,0,0,0.00
HOBO,0.00,0,0.05,0.00,0.40,0,0.03,0.00,0,0,0.40,0.02,0.1,0,0,0,0,0,0.00
HOBOX,0.00,0,0.00,0.00,0.70,0,0.00,0.00,0,0,0.30,0.00,0.0,0,0,0,0,0,0.00
HPHS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
HPHSC,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
HROR,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,1,0,0,0.00
HRORC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,1,0,0,0.00
HYHP,0.90,0,0.00,0.10,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
ICEN,0.00,0,0.00,0.00,0.20,0,0.00,0.00,0,0,0.80,0.00,0.0,0,0,0,0,0,0.00
ICENX,0.00,0,0.00,0.00,0.25,0,0.00,0.00,0,0,0.75,0.00,0.0,0,0,0,0,0,0.00
MCFC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,1.00,0.0,0,0,0,0,0,0.00
PAFC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,1.00,0.0,0,0,0,0,0,0.00
P2BS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
P2GS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
P2HT,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
PEFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
PEME,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
PHOT,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,1,0,0,0,0,0.00
REFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
REHE,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
SCSP,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,1,0,0,0,0,0.00
SOFC,0.00,0,0.00,0.00,0.95,0,0.00,0.05,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
SOTH,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,1.00,0.0,0,0,0,0,0,0.00
SOXE,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
STUR,0.00,0,0.00,0.00,0.45,0,0.00,0.00,0,0,0.10,0.00,0.0,0,0,0,0,0,0.45
STURX,0.00,0,0.00,0.00,0.50,0,0.00,0.00,0,0,0.15,0.00,0.0,0,0,0,0,0,0.35
THMS,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,1,0,0.00
WAVE,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,1,0,0,0.00
WHEN,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,1,0,0.00
WTOF,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,1,0.00
WSHP,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,0,0.00
WTON,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0,0,0.00,0.00,0.0,0,0,0,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Kosovo.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Koso Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [35]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
XK_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
XK_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(XK_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(XK_fuel_technologies_match_df)
XK_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Latvia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Latv Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [36]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
LV_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
LV_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(LV_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(LV_fuel_technologies_match_df)
LV_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Lithuania.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Lith Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [37]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
LT_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
LT_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(LT_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(LT_fuel_technologies_match_df)
LT_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Malta.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Malt Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [38]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
MT_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
MT_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(MT_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(MT_fuel_technologies_match_df)
MT_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Moldova.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Mold Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [39]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
MD_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
MD_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(MD_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(MD_fuel_technologies_match_df)
MD_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Montenegro.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Mont Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [40]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
ME_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
ME_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(ME_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(ME_fuel_technologies_match_df)
ME_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Netherlands.
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Netherland Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            Centraal Bureau voor de Statistiek (CBS). (2023). Energiebalans; aanbod, omzetting en verbruik [Energy balance; supply, transformation and consumption].
            <br>
            <a href="https://www.cbs.nl/en-gb/figures/detail/83109ENG" style="color:skyblue">https://www.cbs.nl/en-gb/figures/detail/83109ENG</a>
        </li>
        <li>
            Netherlands Enterprise Agency (RVO). (2023). Energy and climate: Figures and reports.
            <br>
            <a href="https://english.rvo.nl/topics/energy-agreement/energy-and-climate-reports" style="color:skyblue">https://english.rvo.nl/topics/energy-agreement/energy-and-climate-reports</a>
        </li>
        <li>
            International Energy Agency. (2023). Netherlands 2023: Energy Policy Review. IEA.
            <br>
            <a href="https://www.iea.org/reports/the-netherlands-2024" style="color:skyblue">https://www.iea.org/reports/the-netherlands-2024</a>
        </li>
        <li>
            Eurostat. (2024). Energy database. European Commission.
            <br>
            <a href="https://ec.europa.eu/eurostat/web/energy/" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [41]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
NL_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2, 0, 0, 0, 0.05, 0.1, 0, 1, 0, 0, 0, 0.07, 0.15, 0, 0, 0, 0, 0.1, 0.05, 0.1, 0.1, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0.8, 1, 1, 0.05, 1, 0, 1, 1, 0, 0.05, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.85, 0.75, 0, 0, 0, 0.85, 0.75, 0, 0, 0, 0, 0, 0.875, 0.65, 0, 0, 0, 0, 0, 0.5, 0.6, 0.85, 0.85, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.85, 0.85, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0025, 0.05, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0025, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0.02, 0.1, 0, 0, 0, 0, 0, 0.35, 0.2, 0.05, 0.05, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
NL_fuel_technologies_match_df = pd.DataFrame(NL_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(NL_fuel_technologies_match_df)
NL_fuel_technologies_match_df

        AIR  AMO   BIO   ELE    GAS  GEO     HRD  HYD     LIG  NUC   OIL  \
ABHP   0.05  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
ALFC   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
ALKE   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
ASHP   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
BATS   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
BEVS   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
BSPG   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
CAES   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
COMC   0.00  0.0  0.10  0.00  0.850    0  0.0500    0  0.0000    0  0.00
COMCX  0.00  0.0  0.20  0.00  0.750    0  0.0500    0  0.0000    0  0.00
DMFC   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
GETH   0.00  0.0  0.00  0.00  0.000    1  0.0000    0  0.0000    0  0.00
GSHP   0.00  0.0  0.00  0.00  0.000    1  0.0000    0  0.0000    0  0.00
GTUR   0.00  0.0  0.05  0.00  0.850    0  0.0000    0  0.0000    0  0.10
GTURX  0.00  0.0  0.10  0.00  0.750    0  0.0000    0  0.0000    0  0.15
H2ST   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
HBBS   0.00  0.0  1.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HDAM   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HDAMC  0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HDLZ   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HOBO   0.00  0.0  0.07  0.00  0.875    0  0.0025    0  0.0025    0  0.02
HOBOX  0.00  0.0  0.15  0.00  0.650    0  0.0500    0  0.0000    0  0.10
HPHS   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HPHSC  0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HROR   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HRORC  0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HYHP   0.00  0.0  0.10  0.90  0.000    0  0.0000    0  0.0000    0  0.00
ICEN   0.00  0.0  0.05  0.00  0.500    0  0.1000    0  0.0000    0  0.35
ICENX  0.00  0.0  0.10  0.00  0.600    0  0.1000    0  0.0000    0  0.20
MCFC   0.00  0.0  0.10  0.00  0.850    0  0.0000    0  0.0000    0  0.05
PAFC   0.00  0.0  0.10  0.00  0.850    0  0.0000    0  0.0000    0  0.05
P2BS   0.00  0.2  0.00  0.80  0.000    0  0.0000    0  0.0000    0  0.00
P2GS   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
P2HT   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
PEFC   0.00  0.0  0.10  0.05  0.800    0  0.0000    0  0.0000    0  0.05
PEME   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
PHOT   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
REFC   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
REHE   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
SCSP   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
SOFC   0.00  0.0  0.10  0.05  0.800    0  0.0000    0  0.0000    0  0.05
SOTH   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
SOXE   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
STUR   0.00  0.0  0.05  0.00  0.850    0  0.0500    0  0.0500    0  0.00
STURX  0.00  0.0  0.05  0.00  0.850    0  0.0500    0  0.0500    0  0.00
THMS   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
WAVE   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
WHEN   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
WTOF   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
WSHP   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
WTON   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00

        OTH  PEA  SUN   THE  WAT  WHT  WIN   WST
ABHP   0.00    0    0  0.95    0    0    0  0.00
ALFC   0.00    0    0  0.00    0    0    0  0.00
ALKE   0.00    0    0  0.00    0    0    0  0.00
ASHP   0.00    0    0  0.00    0    0    0  0.00
BATS   0.00    0    0  0.00    0    0    0  0.00
BEVS   0.00    0    0  0.00    0    0    0  0.00
BSPG   0.00    0    1  0.00    0    0    0  0.00
CAES   0.00    0    0  0.00    0    0    0  0.00
COMC   0.00    0    0  0.00    0    0    0  0.00
COMCX  0.00    0    0  0.00    0    0    0  0.00
DMFC   1.00    0    0  0.00    0    0    0  0.00
GETH   0.00    0    0  0.00    0    0    0  0.00
GSHP   0.00    0    0  0.00    0    0    0  0.00
GTUR   0.00    0    0  0.00    0    0    0  0.00
GTURX  0.00    0    0  0.00    0    0    0  0.00
H2ST   0.00    0    0  0.00    0    0    0  0.00
HBBS   0.00    0    0  0.00    0    0    0  0.00
HDAM   0.00    0    0  0.00    1    0    0  0.00
HDAMC  0.00    0    0  0.00    1    0    0  0.00
HDLZ   0.00    0    0  0.00    1    0    0  0.00
HOBO   0.03    0    0  0.00    0    0    0  0.00
HOBOX  0.00    0    0  0.00    0    0    0  0.05
HPHS   0.00    0    0  0.00    1    0    0  0.00
HPHSC  0.00    0    0  0.00    1    0    0  0.00
HROR   0.00    0    0  0.00    1    0    0  0.00
HRORC  0.00    0    0  0.00    1    0    0  0.00
HYHP   0.00    0    0  0.00    0    0    0  0.00
ICEN   0.00    0    0  0.00    0    0    0  0.00
ICENX  0.00    0    0  0.00    0    0    0  0.00
MCFC   0.00    0    0  0.00    0    0    0  0.00
PAFC   0.00    0    0  0.00    0    0    0  0.00
P2BS   0.00    0    0  0.00    0    0    0  0.00
P2GS   0.00    0    0  0.00    0    0    0  0.00
P2HT   0.00    0    0  0.00    0    0    0  0.00
PEFC   0.00    0    0  0.00    0    0    0  0.00
PEME   0.00    0    0  0.00    0    0    0  0.00
PHOT   0.00    0    1  0.00    0    0    0  0.00
REFC   0.00    0    0  0.00    0    0    0  0.00
REHE   0.00    0    0  0.00    0    0    0  0.00
SCSP   0.00    0    1  0.00    0    0    0  0.00
SOFC   0.00    0    0  0.00    0    0    0  0.00
SOTH   0.00    0    1  0.00    0    0    0  0.00
SOXE   0.00    0    0  0.00    0    0    0  0.00
STUR   0.00    0    0  0.00    0    0    0  0.00
STURX  0.00    0    0  0.00    0    0    0  0.00
THMS   0.00    0    0  1.00    0    0    0  0.00
WAVE   0.00    0    0  0.00    1    0    0  0.00
WHEN   0.00    0    0  0.00    0    1    0  0.00
WTOF   0.00    0    0  0.00    0    0    1  0.00
WSHP   0.00    0    0  0.00    0    0    0  0.00
WTON   0.00    0    0  0.00    0    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.95,0,0,0,0.00
ALFC,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
ALKE,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
ASHP,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
BATS,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
BEVS,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
BSPG,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,1,0.00,0,0,0,0.00
CAES,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
COMC,0.00,0.0,0.10,0.00,0.850,0,0.0500,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
COMCX,0.00,0.0,0.20,0.00,0.750,0,0.0500,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
DMFC,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,1.00,0,0,0.00,0,0,0,0.00
GETH,0.00,0.0,0.00,0.00,0.000,1,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
GSHP,0.00,0.0,0.00,0.00,0.000,1,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
GTUR,0.00,0.0,0.05,0.00,0.850,0,0.0000,0,0.0000,0,0.10,0.00,0,0,0.00,0,0,0,0.00
GTURX,0.00,0.0,0.10,0.00,0.750,0,0.0000,0,0.0000,0,0.15,0.00,0,0,0.00,0,0,0,0.00
H2ST,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
HBBS,0.00,0.0,1.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
HDAM,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HDAMC,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HDLZ,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HOBO,0.00,0.0,0.07,0.00,0.875,0,0.0025,0,0.0025,0,0.02,0.03,0,0,0.00,0,0,0,0.00
HOBOX,0.00,0.0,0.15,0.00,0.650,0,0.0500,0,0.0000,0,0.10,0.00,0,0,0.00,0,0,0,0.05
HPHS,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HPHSC,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HROR,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HRORC,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
HYHP,0.00,0.0,0.10,0.90,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
ICEN,0.00,0.0,0.05,0.00,0.500,0,0.1000,0,0.0000,0,0.35,0.00,0,0,0.00,0,0,0,0.00
ICENX,0.00,0.0,0.10,0.00,0.600,0,0.1000,0,0.0000,0,0.20,0.00,0,0,0.00,0,0,0,0.00
MCFC,0.00,0.0,0.10,0.00,0.850,0,0.0000,0,0.0000,0,0.05,0.00,0,0,0.00,0,0,0,0.00
PAFC,0.00,0.0,0.10,0.00,0.850,0,0.0000,0,0.0000,0,0.05,0.00,0,0,0.00,0,0,0,0.00
P2BS,0.00,0.2,0.00,0.80,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
P2GS,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
P2HT,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
PEFC,0.00,0.0,0.10,0.05,0.800,0,0.0000,0,0.0000,0,0.05,0.00,0,0,0.00,0,0,0,0.00
PEME,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
PHOT,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,1,0.00,0,0,0,0.00
REFC,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
REHE,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
SCSP,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,1,0.00,0,0,0,0.00
SOFC,0.00,0.0,0.10,0.05,0.800,0,0.0000,0,0.0000,0,0.05,0.00,0,0,0.00,0,0,0,0.00
SOTH,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,1,0.00,0,0,0,0.00
SOXE,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
STUR,0.00,0.0,0.05,0.00,0.850,0,0.0500,0,0.0500,0,0.00,0.00,0,0,0.00,0,0,0,0.00
STURX,0.00,0.0,0.05,0.00,0.850,0,0.0500,0,0.0500,0,0.00,0.00,0,0,0.00,0,0,0,0.00
THMS,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,1.00,0,0,0,0.00
WAVE,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,1,0,0,0.00
WHEN,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,1,0,0.00
WTOF,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,1,0.00
WSHP,0.00,0.0,0.00,1.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,0,0.00
WTON,0.00,0.0,0.00,0.00,0.000,0,0.0000,0,0.0000,0,0.00,0.00,0,0,0.00,0,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for North Macedonia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Maced Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [42]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
MK_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
MK_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(MK_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(MK_fuel_technologies_match_df)
MK_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Norway.
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Norwegian Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            Statistics Norway. (2023). Energy balance and electricity.
            <br>
            <a href="https://www.ssb.no/en/energi-og-industri/statistikker/energibalanse" style="color:skyblue">https://www.ssb.no/en/energi-og-industri/statistikker/energibalanse</a>
        </li>
        <li>
            Norges vassdrags- og energidirektorat. (2023). Energy data and statistics.
            <br>
            <a href="https://www.nve.no/search/?term=energy%20data%20and%20statistics/" style="color:skyblue">https://www.nve.no/search/?term=energy%20data%20and%20statistics//</a>
        </li>
        <li>
            International Energy Agency. (2023). Norway 2023: Energy Policy Review. IEA.
            <br>
            <a href="https://www.iea.org/reports/norway-2022" style="color:skyblue">https://www.iea.org/reports/norway-2022</a>
        </li>
        <li>
            The Norwegian Ministry of Petroleum and Energy. (2021). Long-term perspectives for the Norwegian energy sector.
            <br>
            <a href="https://www.regjeringen.no/en/search/id86008/?isfilteropen=True&term=long-term-perspectives-for-the-norwegian-energy-sector" style="color:skyblue">https://www.regjeringen.no/en/search/id86008/?isfilteropen=True&term=long-term-perspectives-for-the-norwegian-energy-sector/</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [43]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
NO_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 0.35, 0, 1, 0, 0, 0, 0.6, 0.5, 0, 0, 0, 0, 0, 0.25, 0.35, 0, 0, 0.35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.4, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.5, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.9, 0.5, 0, 0, 0, 0.85, 0.55, 0, 0, 0, 0, 0, 0.25, 0.4, 0, 0, 0, 0, 0, 0.2, 0.45, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.6, 0.5, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.15, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.2, 0, 0, 0.15, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.1, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
NO_fuel_technologies_match_df = pd.DataFrame(NO_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(NO_fuel_technologies_match_df)
NO_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO  HRD   HYD  LIG  NUC   OIL  OTH  PEA  \
ABHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0    0  0.00    0    0
ALFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00    0    0
ALKE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
ASHP   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
BATS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
BEVS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
BSPG   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
CAES   0.00    0  0.00  0.65  0.35    0    0  0.00    0    0  0.00    0    0
COMC   0.00    0  0.00  0.00  0.90    0    0  0.00    0    0  0.10    0    0
COMCX  0.00    0  0.40  0.00  0.50    0    0  0.00    0    0  0.10    0    0
DMFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00    0    0
GETH   0.00    0  0.00  0.00  0.00    1    0  0.00    0    0  0.00    0    0
GSHP   0.00    0  0.00  0.00  0.00    1    0  0.00    0    0  0.00    0    0
GTUR   0.00    0  0.00  0.00  0.85    0    0  0.15    0    0  0.00    0    0
GTURX  0.00    0  0.35  0.00  0.55    0    0  0.10    0    0  0.00    0    0
H2ST   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
HBBS   0.00    0  1.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
HDAM   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
HDAMC  0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
HDLZ   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
HOBO   0.00    0  0.60  0.00  0.25    0    0  0.00    0    0  0.15    0    0
HOBOX  0.00    0  0.50  0.00  0.40    0    0  0.00    0    0  0.10    0    0
HPHS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
HPHSC  0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
HROR   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
HRORC  0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
HYHP   0.90    0  0.00  0.10  0.00    0    0  0.00    0    0  0.00    0    0
ICEN   0.00    0  0.25  0.00  0.20    0    0  0.15    0    0  0.40    0    0
ICENX  0.00    0  0.35  0.00  0.45    0    0  0.20    0    0  0.00    0    0
MCFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.00    0    0
PAFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.00    0    0
P2BS   0.00    0  0.35  0.50  0.00    0    0  0.15    0    0  0.00    0    0
P2GS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
P2HT   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
PEFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00    0    0
PEME   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
PHOT   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
REFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00    0    0
REHE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
SCSP   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
SOFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.00    0    0
SOTH   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
SOXE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
STUR   0.00    0  0.20  0.00  0.60    0    0  0.00    0    0  0.20    0    0
STURX  0.00    0  0.40  0.00  0.50    0    0  0.10    0    0  0.00    0    0
THMS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00    0    0
WAVE   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
WHEN   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
WTOF   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0
WSHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0    0  0.00    0    0
WTON   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00    0    0

       SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0
ALFC     0    0    0    0    0    0
ALKE     0    0    0    0    0    0
ASHP     0    0    0    0    0    0
BATS     0    0    0    0    0    0
BEVS     0    0    0    0    0    0
BSPG     1    0    0    0    0    0
CAES     0    0    0    0    0    0
COMC     0    0    0    0    0    0
COMCX    0    0    0    0    0    0
DMFC     0    0    0    0    0    0
GETH     0    0    0    0    0    0
GSHP     0    0    0    0    0    0
GTUR     0    0    0    0    0    0
GTURX    0    0    0    0    0    0
H2ST     0    0    0    0    0    0
HBBS     0    0    0    0    0    0
HDAM     0    0    1    0    0    0
HDAMC    0    0    1    0    0    0
HDLZ     0    0    1    0    0    0
HOBO     0    0    0    0    0    0
HOBOX    0    0    0    0    0    0
HPHS     0    0    0    0    0    0
HPHSC    0    0    0    0    0    0
HROR     0    0    1    0    0    0
HRORC    0    0    1    0    0    0
HYHP     0    0    0    0    0    0
ICEN     0    0    0    0    0    0
ICENX    0    0    0    0    0    0
MCFC     0    0    0    0    0    0
PAFC     0    0    0    0    0    0
P2BS     0    0    0    0    0    0
P2GS     0    0    0    0    0    0
P2HT     0    0    0    0    0    0
PEFC     0    0    0    0    0    0
PEME     0    0    0    0    0    0
PHOT     1    0    0    0    0    0
REFC     0    0    0    0    0    0
REHE     0    0    0    0    0    0
SCSP     1    0    0    0    0    0
SOFC     0    0    0    0    0    0
SOTH     1    0    0    0    0    0
SOXE     0    0    0    0    0    0
STUR     0    0    0    0    0    0
STURX    0    0    0    0    0    0
THMS     0    0    0    0    0    0
WAVE     0    0    1    0    0    0
WHEN     0    1    0    0    0    0
WTOF     0    0    0    0    1    0
WSHP     0    0    0    0    0    0
WTON     0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.65,0.35,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.90,0,0,0.00,0,0,0.10,0,0,0,0,0,0,0,0
COMCX,0.00,0,0.40,0.00,0.50,0,0,0.00,0,0,0.10,0,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.85,0,0,0.15,0,0,0.00,0,0,0,0,0,0,0,0
GTURX,0.00,0,0.35,0.00,0.55,0,0,0.10,0,0,0.00,0,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,1,0,0,0
HOBO,0.00,0,0.60,0.00,0.25,0,0,0.00,0,0,0.15,0,0,0,0,0,0,0,0
HOBOX,0.00,0,0.50,0.00,0.40,0,0,0.00,0,0,0.10,0,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
ICEN,0.00,0,0.25,0.00,0.20,0,0,0.15,0,0,0.40,0,0,0,0,0,0,0,0
ICENX,0.00,0,0.35,0.00,0.45,0,0,0.20,0,0,0.00,0,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
P2BS,0.00,0,0.35,0.50,0.00,0,0,0.15,0,0,0.00,0,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
STUR,0.00,0,0.20,0.00,0.60,0,0,0.00,0,0,0.20,0,0,0,0,0,0,0,0
STURX,0.00,0,0.40,0.00,0.50,0,0,0.10,0,0,0.00,0,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Portugal.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Portu Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [44]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
PT_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
PT_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(PT_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(PT_fuel_technologies_match_df)
PT_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Romania.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Roma Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [45]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
RO_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
RO_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(RO_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(RO_fuel_technologies_match_df)
RO_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Russian Federation.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Russ Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [46]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
RU_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
RU_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(RU_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(RU_fuel_technologies_match_df)
RU_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Serbia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Serb Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [47]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
RS_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
RS_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(RS_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(RS_fuel_technologies_match_df)
RS_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Slovakia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Slova Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [48]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
SK_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
SK_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(SK_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(SK_fuel_technologies_match_df)
SK_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Slovenia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Slove Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [49]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
SI_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
SI_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(SI_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(SI_fuel_technologies_match_df)
SI_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for United Kingdom.
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the United Kingdom Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <a href="https://www.gov.uk/government/collections/digest-of-uk-energy-statistics-dukes" style="color:skyblue">Department for Energy Security and Net Zero - Digest of UK Energy Statistics (DUKES) (Accessed: 2025-09-30)</a>
    <br>
    <a href="https://www.thecrownestate.co.uk/our-business/offshore-wind/" style="color:skyblue">The Crown Estate - Offshore wind (Accessed: 2025-09-30)</a>
    <br>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [50]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
UK_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0.08, 0.2, 0, 0, 0, 0.05, 0.15, 0, 1, 0, 0, 0, 0.05, 0.15, 0, 0, 0, 0, 0.1, 0.05, 0.1, 0.1, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.95, 0.95, 0, 0, 0.9, 0, 0, 0, 0, 0.85, 1, 1, 0.05, 1, 0, 1, 1, 0, 0.05, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.85, 0.7, 0, 0, 0, 0.85, 0.7, 0, 0, 0, 0, 0, 0.82, 0.82, 0, 0, 0, 0, 0, 0.4, 0.5, 0.8, 0.8, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.000001, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.75, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0.45, 0.3, 0.1, 0.1, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0.05, 0, 0, 0.03, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.000001, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0.05, 0.05, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
UK_fuel_technologies_match_df = pd.DataFrame(UK_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(UK_fuel_technologies_match_df)
UK_fuel_technologies_match_df

        AIR   AMO   BIO   ELE   GAS       GEO   HRD  HYD   LIG   NUC   OIL  \
ABHP   0.05  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
ALFC   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
ALKE   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
ASHP   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
BATS   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
BEVS   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
BSPG   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
CAES   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
COMC   0.00  0.00  0.08  0.00  0.85  0.000000  0.02    0  0.05  0.00  0.00
COMCX  0.00  0.00  0.20  0.00  0.70  0.000000  0.05    0  0.05  0.00  0.00
DMFC   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
GETH   0.00  0.00  0.00  0.00  0.00  0.000001  0.00    0  0.00  0.00  0.00
GSHP   0.00  0.00  0.00  0.00  0.00  1.000000  0.00    0  0.00  0.00  0.00
GTUR   0.00  0.00  0.05  0.00  0.85  0.000000  0.00    0  0.00  0.00  0.10
GTURX  0.00  0.00  0.15  0.00  0.70  0.000000  0.00    0  0.00  0.00  0.15
H2ST   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HBBS   0.00  0.00  1.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HDAM   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HDAMC  0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HDLZ   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HOBO   0.00  0.00  0.05  0.00  0.82  0.000000  0.02    0  0.00  0.00  0.10
HOBOX  0.00  0.00  0.15  0.00  0.82  0.000000  0.05    0  0.00  0.00  0.10
HPHS   0.00  0.00  0.00  0.95  0.00  0.000000  0.00    0  0.00  0.00  0.00
HPHSC  0.00  0.00  0.00  0.95  0.00  0.000000  0.00    0  0.00  0.00  0.00
HROR   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HRORC  0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
HYHP   0.00  0.00  0.10  0.90  0.00  0.000000  0.00    0  0.00  0.00  0.00
ICEN   0.00  0.00  0.05  0.00  0.40  0.000000  0.10    0  0.00  0.00  0.45
ICENX  0.00  0.00  0.10  0.00  0.50  0.000000  0.10    0  0.00  0.00  0.30
MCFC   0.00  0.00  0.10  0.00  0.80  0.000000  0.00    0  0.00  0.00  0.10
PAFC   0.00  0.00  0.10  0.00  0.80  0.000000  0.00    0  0.00  0.00  0.10
P2BS   0.00  0.15  0.00  0.85  0.00  0.000000  0.00    0  0.00  0.00  0.00
P2GS   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
P2HT   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
PEFC   0.00  0.00  0.10  0.05  0.80  0.000000  0.00    0  0.00  0.00  0.05
PEME   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
PHOT   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
REFC   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
REHE   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
SCSP   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
SOFC   0.00  0.00  0.10  0.05  0.80  0.000000  0.00    0  0.00  0.00  0.05
SOTH   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
SOXE   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
STUR   0.00  0.00  0.05  0.00  0.10  0.000000  0.02    0  0.00  0.80  0.03
STURX  0.00  0.00  0.05  0.00  0.15  0.000000  0.05    0  0.00  0.75  0.00
THMS   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
WAVE   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
WHEN   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
WTOF   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
WSHP   0.00  0.00  0.00  1.00  0.00  0.000000  0.00    0  0.00  0.00  0.00
WTON   0.00  0.00  0.00  0.00  0.00  0.000000  0.00    0  0.00  0.00  0.00

        OTH  PEA       SUN   THE   WAT  WHT  WIN   WST
ABHP   0.00    0  0.000000  0.95  0.00    0    0  0.00
ALFC   0.00    0  0.000000  0.00  0.00    0    0  0.00
ALKE   0.00    0  0.000000  0.00  0.00    0    0  0.00
ASHP   0.00    0  0.000000  0.00  0.00    0    0  0.00
BATS   0.00    0  0.000000  0.00  0.00    0    0  0.00
BEVS   0.00    0  0.000000  0.00  0.00    0    0  0.00
BSPG   0.00    0  1.000000  0.00  0.00    0    0  0.00
CAES   0.00    0  0.000000  0.00  0.00    0    0  0.00
COMC   0.00    0  0.000000  0.00  0.00    0    0  0.00
COMCX  0.00    0  0.000000  0.00  0.00    0    0  0.00
DMFC   1.00    0  0.000000  0.00  0.00    0    0  0.00
GETH   0.00    0  0.000000  0.00  0.00    0    0  0.00
GSHP   0.00    0  0.000000  0.00  0.00    0    0  0.00
GTUR   0.00    0  0.000000  0.00  0.00    0    0  0.00
GTURX  0.00    0  0.000000  0.00  0.00    0    0  0.00
H2ST   0.00    0  0.000000  0.00  0.00    0    0  0.00
HBBS   0.00    0  0.000000  0.00  0.00    0    0  0.00
HDAM   0.00    0  0.000000  0.00  1.00    0    0  0.00
HDAMC  0.00    0  0.000000  0.00  1.00    0    0  0.00
HDLZ   0.00    0  0.000000  0.00  1.00    0    0  0.00
HOBO   0.01    0  0.000000  0.00  0.00    0    0  0.00
HOBOX  0.00    0  0.000000  0.00  0.00    0    0  0.05
HPHS   0.00    0  0.000000  0.00  0.05    0    0  0.00
HPHSC  0.00    0  0.000000  0.00  0.05    0    0  0.00
HROR   0.00    0  0.000000  0.00  1.00    0    0  0.00
HRORC  0.00    0  0.000000  0.00  1.00    0    0  0.00
HYHP   0.00    0  0.000000  0.00  0.00    0    0  0.00
ICEN   0.00    0  0.000000  0.00  0.00    0    0  0.00
ICENX  0.00    0  0.000000  0.00  0.00    0    0  0.00
MCFC   0.00    0  0.000000  0.00  0.00    0    0  0.00
PAFC   0.00    0  0.000000  0.00  0.00    0    0  0.00
P2BS   0.00    0  0.000000  0.00  0.00    0    0  0.00
P2GS   0.00    0  0.000000  0.00  0.00    0    0  0.00
P2HT   0.00    0  0.000000  0.00  0.00    0    0  0.00
PEFC   0.00    0  0.000000  0.00  0.00    0    0  0.00
PEME   0.00    0  0.000000  0.00  0.00    0    0  0.00
PHOT   0.00    0  1.000000  0.00  0.00    0    0  0.00
REFC   0.00    0  0.000000  0.00  0.00    0    0  0.00
REHE   0.00    0  0.000000  0.00  0.00    0    0  0.00
SCSP   0.00    0  0.000001  0.00  0.00    0    0  0.00
SOFC   0.00    0  0.000000  0.00  0.00    0    0  0.00
SOTH   0.00    0  1.000000  0.00  0.00    0    0  0.00
SOXE   0.00    0  0.000000  0.00  0.00    0    0  0.00
STUR   0.00    0  0.000000  0.00  0.00    0    0  0.00
STURX  0.00    0  0.000000  0.00  0.00    0    0  0.00
THMS   0.00    0  0.000000  1.00  0.00    0    0  0.00
WAVE   0.00    0  0.000000  0.00  0.00    0    0  0.00
WHEN   0.00    0  0.000000  0.00  0.00    1    0  0.00
WTOF   0.00    0  0.000000  0.00  0.00    0    1  0.00
WSHP   0.00    0  0.000000  0.00  0.00    0    0  0.00
WTON   0.00    0  0.000000  0.00  0.00    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.95,0.00,0,0,0.00
ALFC,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
ALKE,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
ASHP,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
BATS,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
BEVS,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
BSPG,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,1.000000,0.00,0.00,0,0,0.00
CAES,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
COMC,0.00,0.00,0.08,0.00,0.85,0.000000,0.02,0,0.05,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
COMCX,0.00,0.00,0.20,0.00,0.70,0.000000,0.05,0,0.05,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
DMFC,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,1.00,0,0.000000,0.00,0.00,0,0,0.00
GETH,0.00,0.00,0.00,0.00,0.00,0.000001,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
GSHP,0.00,0.00,0.00,0.00,0.00,1.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
GTUR,0.00,0.00,0.05,0.00,0.85,0.000000,0.00,0,0.00,0.00,0.10,0.00,0,0.000000,0.00,0.00,0,0,0.00
GTURX,0.00,0.00,0.15,0.00,0.70,0.000000,0.00,0,0.00,0.00,0.15,0.00,0,0.000000,0.00,0.00,0,0,0.00
H2ST,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
HBBS,0.00,0.00,1.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
HDAM,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,1.00,0,0,0.00
HDAMC,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,1.00,0,0,0.00
HDLZ,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,1.00,0,0,0.00
HOBO,0.00,0.00,0.05,0.00,0.82,0.000000,0.02,0,0.00,0.00,0.10,0.01,0,0.000000,0.00,0.00,0,0,0.00
HOBOX,0.00,0.00,0.15,0.00,0.82,0.000000,0.05,0,0.00,0.00,0.10,0.00,0,0.000000,0.00,0.00,0,0,0.05
HPHS,0.00,0.00,0.00,0.95,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.05,0,0,0.00
HPHSC,0.00,0.00,0.00,0.95,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.05,0,0,0.00
HROR,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,1.00,0,0,0.00
HRORC,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,1.00,0,0,0.00
HYHP,0.00,0.00,0.10,0.90,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
ICEN,0.00,0.00,0.05,0.00,0.40,0.000000,0.10,0,0.00,0.00,0.45,0.00,0,0.000000,0.00,0.00,0,0,0.00
ICENX,0.00,0.00,0.10,0.00,0.50,0.000000,0.10,0,0.00,0.00,0.30,0.00,0,0.000000,0.00,0.00,0,0,0.00
MCFC,0.00,0.00,0.10,0.00,0.80,0.000000,0.00,0,0.00,0.00,0.10,0.00,0,0.000000,0.00,0.00,0,0,0.00
PAFC,0.00,0.00,0.10,0.00,0.80,0.000000,0.00,0,0.00,0.00,0.10,0.00,0,0.000000,0.00,0.00,0,0,0.00
P2BS,0.00,0.15,0.00,0.85,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
P2GS,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
P2HT,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
PEFC,0.00,0.00,0.10,0.05,0.80,0.000000,0.00,0,0.00,0.00,0.05,0.00,0,0.000000,0.00,0.00,0,0,0.00
PEME,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
PHOT,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,1.000000,0.00,0.00,0,0,0.00
REFC,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
REHE,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
SCSP,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000001,0.00,0.00,0,0,0.00
SOFC,0.00,0.00,0.10,0.05,0.80,0.000000,0.00,0,0.00,0.00,0.05,0.00,0,0.000000,0.00,0.00,0,0,0.00
SOTH,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,1.000000,0.00,0.00,0,0,0.00
SOXE,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
STUR,0.00,0.00,0.05,0.00,0.10,0.000000,0.02,0,0.00,0.80,0.03,0.00,0,0.000000,0.00,0.00,0,0,0.00
STURX,0.00,0.00,0.05,0.00,0.15,0.000000,0.05,0,0.00,0.75,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
THMS,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,1.00,0.00,0,0,0.00
WAVE,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
WHEN,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,1,0,0.00
WTOF,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,1,0.00
WSHP,0.00,0.00,0.00,1.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,0,0.00
WTON,0.00,0.00,0.00,0.00,0.00,0.000000,0.00,0,0.00,0.00,0.00,0.00,0,0.000000,0.00,0.00,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Spain.
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Spanish Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            International Energy Agency - Spain 2021: Energy Policy Review (2021).
            <br>
            <a href="https://www.iea.org/reports/spain-2021" style="color:skyblue">https://www.iea.org/reports/spain-2021</a>
        </li>
        <li>
            Red Eléctrica de España - El sistema eléctrico español 2022 (2023).
            <br>
            <a href="https://www.ree.es/es/datos/publicaciones" style="color:skyblue">https://www.ree.es/es/datos/publicaciones</a>
        </li>
        <li>
            Red Eléctrica de España - Series estadísticas nacionales (Accessed: 2025-09-30).
            <br>
            <a href="https://www.ree.es/es/datos/aldia" style="color:skyblue">https://www.ree.es/es/datos/aldia</a>
        </li>
        <li>
            Spanish Ministry for the Ecological Transition and the Demographic Challenge - Plan Nacional Integrado de Energía y Clima (PNIEC) 2021-2030 (2020).
            <br>
            <a href="https://www.miteco.gob.es/es/prensa/pniec.aspx" style="color:skyblue">https://www.miteco.gob.es/es/prensa/pniec.aspx</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [51]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
ES_fuel_technologies_match = {
    'AIR': [0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0.08, 0.2, 0, 0, 0, 0.35, 0.15, 0, 1, 0, 0, 0, 0.35, 0.15, 0, 0, 0, 0, 0.1, 0.05, 0.1, 0.1, 0.1, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0.1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0],
    'ELE': [0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0.85, 1, 1, 0.05, 1, 0, 1, 1, 0, 0.05, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.85, 0.7, 0, 0, 0, 0.50, 0.7, 0, 0, 0, 0, 0, 0.49, 0.65, 0, 0, 0, 0, 0, 0.4, 0.5, 0.8, 0.8, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0.8, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0.05, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0.05, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.75, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0, 0, 0, 0.08, 0.1, 0, 0, 0, 0, 0, 0.45, 0.3, 0.1, 0.1, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0.05, 0, 0, 0.03, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.07, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
ES_fuel_technologies_match_df = pd.DataFrame(ES_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(ES_fuel_technologies_match_df)
ES_fuel_technologies_match_df

        AIR   AMO   BIO   ELE   GAS  GEO   HRD  HYD   LIG   NUC   OIL   OTH  \
ABHP   0.05  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
ALFC   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
ALKE   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
ASHP   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
BATS   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
BEVS   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
BSPG   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
CAES   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
COMC   0.00  0.00  0.08  0.00  0.85    0  0.02    0  0.05  0.00  0.00  0.00
COMCX  0.00  0.00  0.20  0.00  0.70    0  0.05    0  0.05  0.00  0.00  0.00
DMFC   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  1.00
GETH   0.00  0.00  0.00  0.00  0.00    1  0.00    0  0.00  0.00  0.00  0.00
GSHP   0.00  0.00  0.00  0.00  0.00    1  0.00    0  0.00  0.00  0.00  0.00
GTUR   0.00  0.00  0.35  0.00  0.50    0  0.00    0  0.00  0.00  0.10  0.00
GTURX  0.00  0.00  0.15  0.00  0.70    0  0.00    0  0.00  0.00  0.15  0.00
H2ST   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HBBS   0.00  0.00  1.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HDAM   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HDAMC  0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HDLZ   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HOBO   0.00  0.00  0.35  0.00  0.49    0  0.01    0  0.00  0.00  0.08  0.07
HOBOX  0.00  0.00  0.15  0.00  0.65    0  0.05    0  0.00  0.00  0.10  0.00
HPHS   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HPHSC  0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HROR   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HRORC  0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
HYHP   0.00  0.00  0.10  0.90  0.00    0  0.00    0  0.00  0.00  0.00  0.00
ICEN   0.00  0.00  0.05  0.00  0.40    0  0.10    0  0.00  0.00  0.45  0.00
ICENX  0.00  0.00  0.10  0.00  0.50    0  0.10    0  0.00  0.00  0.30  0.00
MCFC   0.00  0.00  0.10  0.00  0.80    0  0.00    0  0.00  0.00  0.10  0.00
PAFC   0.00  0.00  0.10  0.00  0.80    0  0.00    0  0.00  0.00  0.10  0.00
P2BS   0.00  0.15  0.00  0.85  0.00    0  0.00    0  0.00  0.00  0.00  0.00
P2GS   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
P2HT   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
PEFC   0.00  0.00  0.10  0.05  0.80    0  0.00    0  0.00  0.00  0.05  0.00
PEME   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
PHOT   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
REFC   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
REHE   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
SCSP   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
SOFC   0.00  0.00  0.10  0.05  0.80    0  0.00    0  0.00  0.00  0.05  0.00
SOTH   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
SOXE   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
STUR   0.00  0.00  0.05  0.00  0.10    0  0.02    0  0.00  0.80  0.03  0.00
STURX  0.00  0.00  0.05  0.00  0.15    0  0.05    0  0.00  0.75  0.00  0.00
THMS   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
WAVE   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
WHEN   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
WTOF   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
WSHP   0.00  0.00  0.00  1.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00
WTON   0.00  0.00  0.00  0.00  0.00    0  0.00    0  0.00  0.00  0.00  0.00

       PEA  SUN   THE  WAT  WHT  WIN   WST
ABHP     0    0  0.95    0    0    0  0.00
ALFC     0    0  0.00    0    0    0  0.00
ALKE     0    0  0.00    0    0    0  0.00
ASHP     0    0  0.00    0    0    0  0.00
BATS     0    0  0.00    0    0    0  0.00
BEVS     0    0  0.00    0    0    0  0.00
BSPG     0    1  0.00    0    0    0  0.00
CAES     0    0  0.00    0    0    0  0.00
COMC     0    0  0.00    0    0    0  0.00
COMCX    0    0  0.00    0    0    0  0.00
DMFC     0    0  0.00    0    0    0  0.00
GETH     0    0  0.00    0    0    0  0.00
GSHP     0    0  0.00    0    0    0  0.00
GTUR     0    0  0.00    0    0    0  0.00
GTURX    0    0  0.00    0    0    0  0.00
H2ST     0    0  0.00    0    0    0  0.00
HBBS     0    0  0.00    0    0    0  0.00
HDAM     0    0  0.00    1    0    0  0.00
HDAMC    0    0  0.00    1    0    0  0.00
HDLZ     0    0  0.00    1    0    0  0.00
HOBO     0    0  0.00    0    0    0  0.00
HOBOX    0    0  0.00    0    0    0  0.05
HPHS     0    0  0.00    1    0    0  0.00
HPHSC    0    0  0.00    1    0    0  0.00
HROR     0    0  0.00    1    0    0  0.00
HRORC    0    0  0.00    1    0    0  0.00
HYHP     0    0  0.00    0    0    0  0.00
ICEN     0    0  0.00    0    0    0  0.00
ICENX    0    0  0.00    0    0    0  0.00
MCFC     0    0  0.00    0    0    0  0.00
PAFC     0    0  0.00    0    0    0  0.00
P2BS     0    0  0.00    0    0    0  0.00
P2GS     0    0  0.00    0    0    0  0.00
P2HT     0    0  0.00    0    0    0  0.00
PEFC     0    0  0.00    0    0    0  0.00
PEME     0    0  0.00    0    0    0  0.00
PHOT     0    1  0.00    0    0    0  0.00
REFC     0    0  0.00    0    0    0  0.00
REHE     0    0  0.00    0    0    0  0.00
SCSP     0    1  0.00    0    0    0  0.00
SOFC     0    0  0.00    0    0    0  0.00
SOTH     0    1  0.00    0    0    0  0.00
SOXE     0    0  0.00    0    0    0  0.00
STUR     0    0  0.00    0    0    0  0.00
STURX    0    0  0.00    0    0    0  0.00
THMS     0    0  1.00    0    0    0  0.00
WAVE     0    0  0.00    1    0    0  0.00
WHEN     0    0  0.00    0    1    0  0.00
WTOF     0    0  0.00    0    0    1  0.00
WSHP     0    0  0.00    0    0    0  0.00
WTON     0    0  0.00    0    0    1  0.00

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.05,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.95,0,0,0,0.00
ALFC,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
ALKE,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
ASHP,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
BATS,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
BEVS,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
BSPG,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,1,0.00,0,0,0,0.00
CAES,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
COMC,0.00,0.00,0.08,0.00,0.85,0,0.02,0,0.05,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
COMCX,0.00,0.00,0.20,0.00,0.70,0,0.05,0,0.05,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
DMFC,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,1.00,0,0,0.00,0,0,0,0.00
GETH,0.00,0.00,0.00,0.00,0.00,1,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
GSHP,0.00,0.00,0.00,0.00,0.00,1,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
GTUR,0.00,0.00,0.35,0.00,0.50,0,0.00,0,0.00,0.00,0.10,0.00,0,0,0.00,0,0,0,0.00
GTURX,0.00,0.00,0.15,0.00,0.70,0,0.00,0,0.00,0.00,0.15,0.00,0,0,0.00,0,0,0,0.00
H2ST,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
HBBS,0.00,0.00,1.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
HDAM,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HDAMC,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HDLZ,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HOBO,0.00,0.00,0.35,0.00,0.49,0,0.01,0,0.00,0.00,0.08,0.07,0,0,0.00,0,0,0,0.00
HOBOX,0.00,0.00,0.15,0.00,0.65,0,0.05,0,0.00,0.00,0.10,0.00,0,0,0.00,0,0,0,0.05
HPHS,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HPHSC,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HROR,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HRORC,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
HYHP,0.00,0.00,0.10,0.90,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
ICEN,0.00,0.00,0.05,0.00,0.40,0,0.10,0,0.00,0.00,0.45,0.00,0,0,0.00,0,0,0,0.00
ICENX,0.00,0.00,0.10,0.00,0.50,0,0.10,0,0.00,0.00,0.30,0.00,0,0,0.00,0,0,0,0.00
MCFC,0.00,0.00,0.10,0.00,0.80,0,0.00,0,0.00,0.00,0.10,0.00,0,0,0.00,0,0,0,0.00
PAFC,0.00,0.00,0.10,0.00,0.80,0,0.00,0,0.00,0.00,0.10,0.00,0,0,0.00,0,0,0,0.00
P2BS,0.00,0.15,0.00,0.85,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
P2GS,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
P2HT,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
PEFC,0.00,0.00,0.10,0.05,0.80,0,0.00,0,0.00,0.00,0.05,0.00,0,0,0.00,0,0,0,0.00
PEME,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
PHOT,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,1,0.00,0,0,0,0.00
REFC,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
REHE,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
SCSP,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,1,0.00,0,0,0,0.00
SOFC,0.00,0.00,0.10,0.05,0.80,0,0.00,0,0.00,0.00,0.05,0.00,0,0,0.00,0,0,0,0.00
SOTH,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,1,0.00,0,0,0,0.00
SOXE,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
STUR,0.00,0.00,0.05,0.00,0.10,0,0.02,0,0.00,0.80,0.03,0.00,0,0,0.00,0,0,0,0.00
STURX,0.00,0.00,0.05,0.00,0.15,0,0.05,0,0.00,0.75,0.00,0.00,0,0,0.00,0,0,0,0.00
THMS,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,1.00,0,0,0,0.00
WAVE,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,1,0,0,0.00
WHEN,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,1,0,0.00
WTOF,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,1,0.00
WSHP,0.00,0.00,0.00,1.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,0,0.00
WTON,0.00,0.00,0.00,0.00,0.00,0,0.00,0,0.00,0.00,0.00,0.00,0,0,0.00,0,0,1,0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The Dispa-SET Technology - Fuel matching table for Luxembourg.
    <br>
<div style="text-align: justify; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Luxembourg Energy System.
    The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            International Energy Agency - Luxembourg 2020: Energy Policy Review (2020).
            <br>
            <a href="https://www.iea.org/reports/luxembourg-2020" style="color:skyblue">https://www.iea.org/reports/luxembourg-2020</a>
        </li>
        <li>
            STATEC - Energy (Accessed: 2025-09-30).
            <br>
            <a href="https://statistiques.public.lu/en.html" style="color:skyblue">https://statistiques.public.lu/en.html</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [52]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
LU_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.05, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.066892464, 0.25, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 1, 0.75, 0, 0, 0, 1, 0.95, 0, 0, 0, 0, 0, 0.76, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.082133785, 0.7, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.008467401, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.32938188, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0.000084674, 0, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.210838273, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.116850127, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0.15, 0.1, 0, 0, 0, 0, 0, 0.7, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.123624047, 0.05, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.02, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00084674, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.014394581, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0.00592718, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.00084674, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.038950042, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
LU_fuel_technologies_match_df = pd.DataFrame(LU_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(LU_fuel_technologies_match_df)
LU_fuel_technologies_match_df

        AIR  AMO       BIO   ELE       GAS       GEO       HRD       HYD  \
ABHP   0.95    0  0.000000  0.05  0.000000  0.000000  0.000000  0.000000
ALFC   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
ALKE   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
ASHP   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
BATS   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
BEVS   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
BSPG   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
CAES   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
COMC   0.00    0  0.000000  0.00  1.000000  0.000000  0.000000  0.000000
COMCX  0.00    0  0.200000  0.00  0.750000  0.000000  0.000000  0.000000
DMFC   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
GETH   0.00    0  0.000000  0.00  0.000000  1.000000  0.000000  0.000000
GSHP   0.00    0  0.000000  0.00  0.000000  1.000000  0.000000  0.000000
GTUR   0.00    0  0.000000  0.00  1.000000  0.000000  0.000000  0.000000
GTURX  0.00    0  0.000000  0.00  0.950000  0.000000  0.000000  0.000000
H2ST   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
HBBS   0.00    0  1.000000  0.00  0.000000  0.000000  0.000000  0.000000
HDAM   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HDAMC  0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HDLZ   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HOBO   0.00    0  0.050000  0.00  0.760000  0.000000  0.010000  0.000000
HOBOX  0.00    0  0.250000  0.00  0.650000  0.000000  0.000000  0.000000
HPHS   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HPHSC  0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HROR   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HRORC  0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
HYHP   0.90    0  0.000000  0.10  0.000000  0.000000  0.000000  0.000000
ICEN   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
ICENX  0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
MCFC   0.00    0  0.000000  0.00  1.000000  0.000000  0.000000  0.000000
PAFC   0.00    0  0.000000  0.00  1.000000  0.000000  0.000000  0.000000
P2BS   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
P2GS   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
P2HT   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
PEFC   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
PEME   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
PHOT   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
REFC   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  1.000000
REHE   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
SCSP   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
SOFC   0.00    0  0.000000  0.00  1.000000  0.000000  0.000000  0.000000
SOTH   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
SOXE   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
STUR   0.00    0  0.066892  0.00  0.082134  0.008467  0.329382  0.000085
STURX  0.00    0  0.250000  0.00  0.700000  0.000000  0.000000  0.000000
THMS   0.00    0  0.000000  1.00  0.000000  0.000000  0.000000  0.000000
WAVE   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WHEN   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WTOF   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000
WSHP   0.95    0  0.000000  0.05  0.000000  0.000000  0.000000  0.000000
WTON   0.00    0  0.000000  0.00  0.000000  0.000000  0.000000  0.000000

            LIG      NUC       OIL       OTH       PEA       SUN  THE  \
ABHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
ALFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
ALKE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
ASHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
BATS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
BEVS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
BSPG   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000    0
CAES   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
COMC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
COMCX  0.000000  0.00000  0.050000  0.000000  0.000000  0.000000    0
DMFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
GETH   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
GSHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
GTUR   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
GTURX  0.000000  0.00000  0.050000  0.000000  0.000000  0.000000    0
H2ST   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HBBS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HDAM   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HDAMC  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HDLZ   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HOBO   0.010000  0.00000  0.150000  0.020000  0.000000  0.000000    0
HOBOX  0.000000  0.00000  0.100000  0.000000  0.000000  0.000000    0
HPHS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HPHSC  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HROR   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HRORC  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
HYHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
ICEN   0.000000  0.00000  0.700000  0.000000  0.000000  0.000000    0
ICENX  0.000000  0.00000  0.800000  0.000000  0.000000  0.000000    0
MCFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
PAFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
P2BS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
P2GS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
P2HT   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
PEFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
PEME   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
PHOT   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000    0
REFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
REHE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
SCSP   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000    0
SOFC   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
SOTH   0.000000  0.00000  0.000000  0.000000  0.000000  1.000000    0
SOXE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
STUR   0.210838  0.11685  0.123624  0.000847  0.014395  0.005927    0
STURX  0.000000  0.00000  0.050000  0.000000  0.000000  0.000000    0
THMS   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
WAVE   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
WHEN   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    1
WTOF   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
WSHP   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0
WTON   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000    0

            WAT  WHT  WIN      WST
ABHP   0.000000    0    0  0.00000
ALFC   0.000000    0    0  0.00000
ALKE   0.000000    0    0  0.00000
ASHP   0.000000    0    0  0.00000
BATS   0.000000    0    0  0.00000
BEVS   0.000000    0    0  0.00000
BSPG   0.000000    0    0  0.00000
CAES   0.000000    0    0  0.00000
COMC   0.000000    0    0  0.00000
COMCX  0.000000    0    0  0.00000
DMFC   0.000000    0    0  0.00000
GETH   0.000000    0    0  0.00000
GSHP   0.000000    0    0  0.00000
GTUR   0.000000    0    0  0.00000
GTURX  0.000000    0    0  0.00000
H2ST   0.000000    0    0  0.00000
HBBS   0.000000    0    0  0.00000
HDAM   1.000000    0    0  0.00000
HDAMC  1.000000    0    0  0.00000
HDLZ   1.000000    0    0  0.00000
HOBO   0.000000    0    0  0.00000
HOBOX  0.000000    0    0  0.00000
HPHS   1.000000    0    0  0.00000
HPHSC  1.000000    0    0  0.00000
HROR   1.000000    0    0  0.00000
HRORC  1.000000    0    0  0.00000
HYHP   0.000000    0    0  0.00000
ICEN   0.000000    0    0  0.30000
ICENX  0.000000    0    0  0.20000
MCFC   0.000000    0    0  0.00000
PAFC   0.000000    0    0  0.00000
P2BS   0.000000    0    0  0.00000
P2GS   0.000000    0    0  0.00000
P2HT   0.000000    0    0  0.00000
PEFC   0.000000    0    0  0.00000
PEME   0.000000    0    0  0.00000
PHOT   0.000000    0    0  0.00000
REFC   0.000000    0    0  0.00000
REHE   0.000000    0    0  0.00000
SCSP   0.000000    0    0  0.00000
SOFC   0.000000    0    0  0.00000
SOTH   0.000000    0    0  0.00000
SOXE   0.000000    0    0  0.00000
STUR   0.000847    0    0  0.03895
STURX  0.000000    0    0  0.00000
THMS   0.000000    0    0  0.00000
WAVE   1.000000    0    0  0.00000
WHEN   0.000000    0    0  0.00000
WTOF   0.000000    0    1  0.00000
WSHP   0.000000    0    0  0.00000
WTON   0.000000    0    1  0.00000

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
ALFC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
ALKE,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
ASHP,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
BATS,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
BEVS,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
BSPG,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0,0.000000,0,0,0.00000
CAES,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
COMC,0.00,0,0.000000,0.00,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
COMCX,0.00,0,0.200000,0.00,0.750000,0.000000,0.000000,0.000000,0.000000,0.00000,0.050000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
DMFC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
GETH,0.00,0,0.000000,0.00,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
GSHP,0.00,0,0.000000,0.00,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
GTUR,0.00,0,0.000000,0.00,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
GTURX,0.00,0,0.000000,0.00,0.950000,0.000000,0.000000,0.000000,0.000000,0.00000,0.050000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
H2ST,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
HBBS,0.00,0,1.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
HDAM,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HDAMC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HDLZ,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HOBO,0.00,0,0.050000,0.00,0.760000,0.000000,0.010000,0.000000,0.010000,0.00000,0.150000,0.020000,0.000000,0.000000,0,0.000000,0,0,0.00000
HOBOX,0.00,0,0.250000,0.00,0.650000,0.000000,0.000000,0.000000,0.000000,0.00000,0.100000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
HPHS,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HPHSC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HROR,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HRORC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
HYHP,0.90,0,0.000000,0.10,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
ICEN,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.700000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.30000
ICENX,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.800000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.20000
MCFC,0.00,0,0.000000,0.00,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
PAFC,0.00,0,0.000000,0.00,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
P2BS,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
P2GS,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
P2HT,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
PEFC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
PEME,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
PHOT,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0,0.000000,0,0,0.00000
REFC,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
REHE,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
SCSP,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0,0.000000,0,0,0.00000
SOFC,0.00,0,0.000000,0.00,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
SOTH,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0,0.000000,0,0,0.00000
SOXE,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
STUR,0.00,0,0.066892,0.00,0.082134,0.008467,0.329382,0.000085,0.210838,0.11685,0.123624,0.000847,0.014395,0.005927,0,0.000847,0,0,0.03895
STURX,0.00,0,0.250000,0.00,0.700000,0.000000,0.000000,0.000000,0.000000,0.00000,0.050000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
THMS,0.00,0,0.000000,1.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
WAVE,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,1.000000,0,0,0.00000
WHEN,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1,0.000000,0,0,0.00000
WTOF,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,1,0.00000
WSHP,0.95,0,0.000000,0.05,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,0,0.00000
WTON,0.00,0,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0,0.000000,0,1,0.00000

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Italy.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Italian Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    <ol style="margin-top: 0; padding-left: 1.5em;">
        <li>
            Gestore dei Servizi Energetici (GSE). (2023). Rapporto Statistico 2022: Energia da Fonti Rinnovabili in Italia.
            <br>
            <a href="https://www.gse.it/dati-e-scenari/rapporti" style="color:skyblue">https://www.gse.it/dati-e-scenari/rapporti</a>
        </li>
        <li>
            International Energy Agency. (2023). Italy 2023: Energy Policy Review. IEA.
            <br>
            <a href="https://www.iea.org/reports/italy-2023" style="color:skyblue">https://www.iea.org/reports/italy-2023</a>
        </li>
        <li>
            Terna S.p.A. (2023). Dati statistici sull'energia elettrica in Italia.
            <br>
            <a href="https://www.terna.it/it/sistema-elettrico/statistiche" style="color:skyblue">https://www.terna.it/it/sistema-elettrico/statistiche</a>
        </li>
        <li>
            Italian Ministry of the Environment and Energy Security. (2023). Piano Nazionale Integrato per l'Energia e il Clima (PNIEC).
            <br>
            <a href="https://www.mase.gov.it/portale/home" style="color:skyblue">https://www.mase.gov.it/portale/home</a>
        </li>
    </ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [53]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
IT_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.25, 0.15, 0, 0, 0, 0, 0, 0.2, 0.25, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.2, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.04, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0.7, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0.75, 0, 0, 0, 0.85, 0.8, 0, 0, 0, 0, 0, 0.50, 0.7, 0, 0, 0, 0, 0, 0.4, 0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.4, 0.65, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.15, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0.15, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.08, 0.15, 0, 0, 0, 0, 0, 0.3, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.35, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
IT_fuel_technologies_match_df = pd.DataFrame(IT_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(IT_fuel_technologies_match_df)
IT_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO   HRD   HYD  LIG  NUC   OIL   OTH  \
ABHP   0.95    0  0.00  0.05  0.00  0.0  0.00  0.00    0    0  0.00  0.00
ALFC   0.00    0  0.00  0.00  0.00  0.0  0.00  1.00    0    0  0.00  0.00
ALKE   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
ASHP   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
BATS   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
BEVS   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
BSPG   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
CAES   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
COMC   0.00    0  0.00  0.00  0.90  0.0  0.00  0.00    0    0  0.10  0.00
COMCX  0.00    0  0.20  0.00  0.75  0.0  0.00  0.00    0    0  0.05  0.00
DMFC   0.00    0  0.00  0.00  0.00  0.0  0.00  1.00    0    0  0.00  0.00
GETH   0.00    0  0.00  0.00  0.00  1.0  0.00  0.00    0    0  0.00  0.00
GSHP   0.00    0  0.00  0.00  0.00  1.0  0.00  0.00    0    0  0.00  0.00
GTUR   0.00    0  0.00  0.00  0.85  0.0  0.00  0.15    0    0  0.00  0.00
GTURX  0.00    0  0.00  0.00  0.80  0.0  0.00  0.20    0    0  0.00  0.00
H2ST   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HBBS   0.00    0  1.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HDAM   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HDAMC  0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HDLZ   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HOBO   0.00    0  0.25  0.04  0.50  0.0  0.01  0.00    0    0  0.08  0.12
HOBOX  0.00    0  0.15  0.00  0.70  0.0  0.00  0.00    0    0  0.15  0.00
HPHS   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HPHSC  0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HROR   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HRORC  0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
HYHP   0.90    0  0.00  0.10  0.00  0.0  0.00  0.00    0    0  0.00  0.00
ICEN   0.00    0  0.20  0.00  0.40  0.0  0.00  0.10    0    0  0.30  0.00
ICENX  0.00    0  0.25  0.00  0.50  0.0  0.00  0.15    0    0  0.10  0.00
MCFC   0.00    0  0.00  0.00  1.00  0.0  0.00  0.00    0    0  0.00  0.00
PAFC   0.00    0  0.00  0.00  1.00  0.0  0.00  0.00    0    0  0.00  0.00
P2BS   0.00    0  0.15  0.70  0.00  0.0  0.00  0.15    0    0  0.00  0.00
P2GS   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
P2HT   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
PEFC   0.00    0  0.00  0.00  0.00  0.0  0.00  1.00    0    0  0.00  0.00
PEME   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
PHOT   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
REFC   0.00    0  0.00  0.00  0.00  0.0  0.00  1.00    0    0  0.00  0.00
REHE   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
SCSP   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
SOFC   0.00    0  0.00  0.00  1.00  0.0  0.00  0.00    0    0  0.00  0.00
SOTH   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
SOXE   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
STUR   0.00    0  0.15  0.00  0.40  0.1  0.00  0.00    0    0  0.35  0.00
STURX  0.00    0  0.20  0.00  0.65  0.0  0.00  0.15    0    0  0.00  0.00
THMS   0.00    0  0.00  1.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
WAVE   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
WHEN   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
WTOF   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00
WSHP   0.95    0  0.00  0.05  0.00  0.0  0.00  0.00    0    0  0.00  0.00
WTON   0.00    0  0.00  0.00  0.00  0.0  0.00  0.00    0    0  0.00  0.00

       PEA  SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0    0
ALFC     0    0    0    0    0    0    0
ALKE     0    0    0    0    0    0    0
ASHP     0    0    0    0    0    0    0
BATS     0    0    0    0    0    0    0
BEVS     0    0    0    0    0    0    0
BSPG     0    1    0    0    0    0    0
CAES     0    0    0    0    0    0    0
COMC     0    0    0    0    0    0    0
COMCX    0    0    0    0    0    0    0
DMFC     0    0    0    0    0    0    0
GETH     0    0    0    0    0    0    0
GSHP     0    0    0    0    0    0    0
GTUR     0    0    0    0    0    0    0
GTURX    0    0    0    0    0    0    0
H2ST     0    0    0    0    0    0    0
HBBS     0    0    0    0    0    0    0
HDAM     0    0    0    1    0    0    0
HDAMC    0    0    0    1    0    0    0
HDLZ     0    0    0    1    0    0    0
HOBO     0    0    0    0    0    0    0
HOBOX    0    0    0    0    0    0    0
HPHS     0    0    0    1    0    0    0
HPHSC    0    0    0    1    0    0    0
HROR     0    0    0    1    0    0    0
HRORC    0    0    0    1    0    0    0
HYHP     0    0    0    0    0    0    0
ICEN     0    0    0    0    0    0    0
ICENX    0    0    0    0    0    0    0
MCFC     0    0    0    0    0    0    0
PAFC     0    0    0    0    0    0    0
P2BS     0    0    0    0    0    0    0
P2GS     0    0    0    0    0    0    0
P2HT     0    0    0    0    0    0    0
PEFC     0    0    0    0    0    0    0
PEME     0    0    0    0    0    0    0
PHOT     0    1    0    0    0    0    0
REFC     0    0    0    0    0    0    0
REHE     0    0    0    0    0    0    0
SCSP     0    1    0    0    0    0    0
SOFC     0    0    0    0    0    0    0
SOTH     0    1    0    0    0    0    0
SOXE     0    0    0    0    0    0    0
STUR     0    0    0    0    0    0    0
STURX    0    0    0    0    0    0    0
THMS     0    0    0    0    0    0    0
WAVE     0    0    0    1    0    0    0
WHEN     0    0    1    0    0    0    0
WTOF     0    0    0    0    0    1    0
WSHP     0    0    0    0    0    0    0
WTON     0    0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0.0,0.00,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
CAES,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.90,0.0,0.00,0.00,0,0,0.10,0.00,0,0,0,0,0,0,0
COMCX,0.00,0,0.20,0.00,0.75,0.0,0.00,0.00,0,0,0.05,0.00,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0.0,0.00,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.85,0.0,0.00,0.15,0,0,0.00,0.00,0,0,0,0,0,0,0
GTURX,0.00,0,0.00,0.00,0.80,0.0,0.00,0.20,0,0,0.00,0.00,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HOBO,0.00,0,0.25,0.04,0.50,0.0,0.01,0.00,0,0,0.08,0.12,0,0,0,0,0,0,0
HOBOX,0.00,0,0.15,0.00,0.70,0.0,0.00,0.00,0,0,0.15,0.00,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HPHSC,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ICEN,0.00,0,0.20,0.00,0.40,0.0,0.00,0.10,0,0,0.30,0.00,0,0,0,0,0,0,0
ICENX,0.00,0,0.25,0.00,0.50,0.0,0.00,0.15,0,0,0.10,0.00,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
P2BS,0.00,0,0.15,0.70,0.00,0.0,0.00,0.15,0,0,0.00,0.00,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0.0,0.00,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0.0,0.00,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
STUR,0.00,0,0.15,0.00,0.40,0.1,0.00,0.00,0,0,0.35,0.00,0,0,0,0,0,0,0
STURX,0.00,0,0.20,0.00,0.65,0.0,0.00,0.15,0,0,0.00,0.00,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0.0,0.00,0.00,0,0,0.00,0.00,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Sweden.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Sweden Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
    <li>
        Energy in Sweden - Facts and Figures 2023 
        <br>
        <a href="https://www.energimyndigheten.se/en/news/2023/energy-in-sweden---facts-and-figures-2023/" style="color:skyblue">https://www.energimyndigheten.se/en/news/2023/energy-in-sweden---facts-and-figures-2023/</a>
    </li>
    <li>
        [PDF] Energy in Sweden 2022 – An overview - Energimyndigheten 
        <br>
        <a href="https://energimyndigheten.a-w2m.se/Arkitektkopia/GetTemplateResource/121?id=5cec65f476d74e0e98a0eb814d1daf1a&res=5dc13196322d4cb3b08dafacec06d733&lr=False&fn=ET%202022_04_webb.pdf&elp=portal&elt=t&eloid=5cec65f476d74e0e98a0eb814d1daf1a" style="color:skyblue">https://energimyndigheten.a-w2m.se/...</a>
    </li>
    <li>
        [XLS] Innehåll - Energimyndigheten 
        <br>
        <a href="http://www.energimyndigheten.se/48d848/globalassets/statistik/energilaget/energy-in-sweden-facts-and-figures-20242.xlsx" style="color:skyblue">http://www.energimyndigheten.se/48d848/globalassets/statistik/...</a>
    </li>
    <li>
        Sweden 2024 – Analysis - IEA 
        <br>
        <a href="https://www.iea.org/reports/sweden-2024" style="color:skyblue">https://www.iea.org/reports/sweden-2024</a>
    </li>
    <li>
        Ny rapport: Nordic Grid Development Perspective 2023 
        <br>
        <a href="https://www.svk.se/press-och-nyheter/nyheter/allmanna-nyheter/2023/ny-rapport-nordic-grid-development-perspective-2023/" style="color:skyblue">https://www.svk.se/press-och-nyheter/nyheter/...</a>
    </li>
    <li>
        Shedding light on energy in Europe – 2024 edition - EC Europa 
        <br>
        <a href="https://ec.europa.eu/eurostat/web/interactive-publications/energy-2024" style="color:skyblue">https://ec.europa.eu/eurostat/web/interactive-publications/energy-2024</a>
    </li>
    <li>
        EU Energy in Figures: statistical data on EU energy sector 
        <br>
        <a href="https://energy.ec.europa.eu/news/eu-energy-figures-statistical-data-eu-energy-sector-2024-10-14_en" style="color:skyblue">https://energy.ec.europa.eu/news/eu-energy-figures-statistical-data...</a>
    </li>
    <li>
        Database - Energy - Eurostat - EC Europa 
        <br>
        <a href="https://ec.europa.eu/eurostat/web/energy/database" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/database</a>
    </li>
    <li>
        Renewable energy statistics - Statistics Explained - Eurostat 
        <br>
        <a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Renewable_energy_statistics" style="color:skyblue">https://ec.europa.eu/eurostat/statistics-explained/index.php/Renewable_energy_statistics</a>
    </li>
    <li>
        Energy statistics - an overview - EC Europa - European Union 
        <br>
        <a href="https://ec.europa.eu/eurostat/statistics-explained/index.php/Energy_statistics_-_an_overview" style="color:skyblue">https://ec.europa.eu/eurostat/statistics-explained/index.php/Energy_statistics_-_an_overview</a>
    </li>
    <li>
        [PDF] Sweden's draft integrated national energy and climate plan 
        <br>
        <a href="https://www.government.se/contentassets/e731726022cd4e0b8ffa0f8229893115/swedens-draft-integrated-national-energy-and-climate-plan/" style="color:skyblue">https://www.government.se/contentassets/...</a>
    </li>
    <li>
        [PDF] Draft updated National Energy and Climate Plan (NECP) for Sweden 
        <br>
        <a href="https://commission.europa.eu/system/files/2023-07/EN_SWEDEN%20DRAFT%20UPDATED%20NECP.pdf" style="color:skyblue">https://commission.europa.eu/system/files/2023-07/EN_SWEDEN%20DRAFT%20UPDATED%20NECP.pdf</a>
    </li>
    <li>
        The Swedish offer to support ambitious climate plans - Government.se 
        <br>
        <a href="https://www.government.se/articles/2025/05/the-swedish-offer-to-support-ambitious-climate-plans/" style="color:skyblue">https://www.government.se/articles/2025/05/the-swedish-offer-to-support-ambitious-climate-plans/</a>
    </li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [54]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
SE_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.6, 0, 0, 0, 0, 0.5, 0, 1, 0, 0, 0, 0.90, 0.6, 0, 0, 0, 0, 0, 0.3, 0.5, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.5, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.5, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.9, 0.3, 0, 0, 0, 0.8, 0.4, 0, 0, 0, 0, 0, 0.02, 0.3, 0, 0, 0, 0, 0, 0.2, 0.3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.2, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.2, 0, 0, 0.1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0.1, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
SE_fuel_technologies_match_df = pd.DataFrame(SE_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(SE_fuel_technologies_match_df)
SE_fuel_technologies_match_df

        AIR  AMO  BIO   ELE   GAS  GEO  HRD  HYD  LIG  NUC   OIL  OTH  PEA  \
ABHP   0.95    0  0.0  0.05  0.00    0    0  0.0    0  0.0  0.00    0    0
ALFC   0.00    0  0.0  0.00  0.00    0    0  1.0    0  0.0  0.00    0    0
ALKE   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
ASHP   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
BATS   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
BEVS   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
BSPG   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
CAES   0.00    0  0.0  0.65  0.35    0    0  0.0    0  0.0  0.00    0    0
COMC   0.00    0  0.0  0.00  0.90    0    0  0.0    0  0.0  0.10    0    0
COMCX  0.00    0  0.6  0.00  0.30    0    0  0.0    0  0.0  0.10    0    0
DMFC   0.00    0  0.0  0.00  0.00    0    0  1.0    0  0.0  0.00    0    0
GETH   0.00    0  0.0  0.00  0.00    1    0  0.0    0  0.0  0.00    0    0
GSHP   0.00    0  0.0  0.00  0.00    1    0  0.0    0  0.0  0.00    0    0
GTUR   0.00    0  0.0  0.00  0.80    0    0  0.2    0  0.0  0.00    0    0
GTURX  0.00    0  0.5  0.00  0.40    0    0  0.1    0  0.0  0.00    0    0
H2ST   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HBBS   0.00    0  1.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HDAM   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HDAMC  0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HDLZ   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HOBO   0.00    0  0.9  0.00  0.02    0    0  0.0    0  0.0  0.01    0    0
HOBOX  0.00    0  0.6  0.00  0.30    0    0  0.0    0  0.0  0.10    0    0
HPHS   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HPHSC  0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HROR   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HRORC  0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
HYHP   0.90    0  0.0  0.10  0.00    0    0  0.0    0  0.0  0.00    0    0
ICEN   0.00    0  0.3  0.00  0.20    0    0  0.1    0  0.0  0.40    0    0
ICENX  0.00    0  0.5  0.00  0.30    0    0  0.2    0  0.0  0.00    0    0
MCFC   0.00    0  0.0  0.00  1.00    0    0  0.0    0  0.0  0.00    0    0
PAFC   0.00    0  0.0  0.00  1.00    0    0  0.0    0  0.0  0.00    0    0
P2BS   0.00    0  0.4  0.50  0.00    0    0  0.1    0  0.0  0.00    0    0
P2GS   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
P2HT   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
PEFC   0.00    0  0.0  0.00  0.00    0    0  1.0    0  0.0  0.00    0    0
PEME   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
PHOT   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
REFC   0.00    0  0.0  0.00  0.00    0    0  1.0    0  0.0  0.00    0    0
REHE   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
SCSP   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
SOFC   0.00    0  0.0  0.00  1.00    0    0  0.0    0  0.0  0.00    0    0
SOTH   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
SOXE   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
STUR   0.00    0  0.2  0.00  0.00    0    0  0.0    0  0.8  0.00    0    0
STURX  0.00    0  0.5  0.00  0.30    0    0  0.2    0  0.0  0.00    0    0
THMS   0.00    0  0.0  1.00  0.00    0    0  0.0    0  0.0  0.00    0    0
WAVE   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
WHEN   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
WTOF   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0
WSHP   0.95    0  0.0  0.05  0.00    0    0  0.0    0  0.0  0.00    0    0
WTON   0.00    0  0.0  0.00  0.00    0    0  0.0    0  0.0  0.00    0    0

       SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0
ALFC     0    0    0    0    0    0
ALKE     0    0    0    0    0    0
ASHP     0    0    0    0    0    0
BATS     0    0    0    0    0    0
BEVS     0    0    0    0    0    0
BSPG     1    0    0    0    0    0
CAES     0    0    0    0    0    0
COMC     0    0    0    0    0    0
COMCX    0    0    0    0    0    0
DMFC     0    0    0    0    0    0
GETH     0    0    0    0    0    0
GSHP     0    0    0    0    0    0
GTUR     0    0    0    0    0    0
GTURX    0    0    0    0    0    0
H2ST     0    0    0    0    0    0
HBBS     0    0    0    0    0    0
HDAM     0    0    1    0    0    0
HDAMC    0    0    1    0    0    0
HDLZ     0    0    1    0    0    0
HOBO     0    0    0    0    0    0
HOBOX    0    0    0    0    0    0
HPHS     0    0    0    0    0    0
HPHSC    0    0    0    0    0    0
HROR     0    0    1    0    0    0
HRORC    0    0    1    0    0    0
HYHP     0    0    0    0    0    0
ICEN     0    0    0    0    0    0
ICENX    0    0    0    0    0    0
MCFC     0    0    0    0    0    0
PAFC     0    0    0    0    0    0
P2BS     0    0    0    0    0    0
P2GS     0    0    0    0    0    0
P2HT     0    0    0    0    0    0
PEFC     0    0    0    0    0    0
PEME     0    0    0    0    0    0
PHOT     1    0    0    0    0    0
REFC     0    0    0    0    0    0
REHE     0    0    0    0    0    0
SCSP     1    0    0    0    0    0
SOFC     0    0    0    0    0    0
SOTH     1    0    0    0    0    0
SOXE     0    0    0    0    0    0
STUR     0    0    0    0    0    0
STURX    0    0    0    0    0    0
THMS     0    0    0    0    0    0
WAVE     0    0    1    0    0    0
WHEN     0    1    0    0    0    0
WTOF     0    0    0    0    1    0
WSHP     0    0    0    0    0    0
WTON     0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.0,0.05,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
ALFC,0.00,0,0.0,0.00,0.00,0,0,1.0,0,0.0,0.00,0,0,0,0,0,0,0,0
ALKE,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
ASHP,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
BATS,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
BEVS,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
BSPG,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,1,0,0,0,0,0
CAES,0.00,0,0.0,0.65,0.35,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
COMC,0.00,0,0.0,0.00,0.90,0,0,0.0,0,0.0,0.10,0,0,0,0,0,0,0,0
COMCX,0.00,0,0.6,0.00,0.30,0,0,0.0,0,0.0,0.10,0,0,0,0,0,0,0,0
DMFC,0.00,0,0.0,0.00,0.00,0,0,1.0,0,0.0,0.00,0,0,0,0,0,0,0,0
GETH,0.00,0,0.0,0.00,0.00,1,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
GSHP,0.00,0,0.0,0.00,0.00,1,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
GTUR,0.00,0,0.0,0.00,0.80,0,0,0.2,0,0.0,0.00,0,0,0,0,0,0,0,0
GTURX,0.00,0,0.5,0.00,0.40,0,0,0.1,0,0.0,0.00,0,0,0,0,0,0,0,0
H2ST,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
HBBS,0.00,0,1.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
HDAM,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,1,0,0,0
HDAMC,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,1,0,0,0
HDLZ,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,1,0,0,0
HOBO,0.00,0,0.9,0.00,0.02,0,0,0.0,0,0.0,0.01,0,0,0,0,0,0,0,0
HOBOX,0.00,0,0.6,0.00,0.30,0,0,0.0,0,0.0,0.10,0,0,0,0,0,0,0,0
HPHS,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
HPHSC,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
HROR,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,1,0,0,0
HRORC,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,1,0,0,0
HYHP,0.90,0,0.0,0.10,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
ICEN,0.00,0,0.3,0.00,0.20,0,0,0.1,0,0.0,0.40,0,0,0,0,0,0,0,0
ICENX,0.00,0,0.5,0.00,0.30,0,0,0.2,0,0.0,0.00,0,0,0,0,0,0,0,0
MCFC,0.00,0,0.0,0.00,1.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
PAFC,0.00,0,0.0,0.00,1.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
P2BS,0.00,0,0.4,0.50,0.00,0,0,0.1,0,0.0,0.00,0,0,0,0,0,0,0,0
P2GS,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
P2HT,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
PEFC,0.00,0,0.0,0.00,0.00,0,0,1.0,0,0.0,0.00,0,0,0,0,0,0,0,0
PEME,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
PHOT,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,1,0,0,0,0,0
REFC,0.00,0,0.0,0.00,0.00,0,0,1.0,0,0.0,0.00,0,0,0,0,0,0,0,0
REHE,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
SCSP,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,1,0,0,0,0,0
SOFC,0.00,0,0.0,0.00,1.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
SOTH,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,1,0,0,0,0,0
SOXE,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
STUR,0.00,0,0.2,0.00,0.00,0,0,0.0,0,0.8,0.00,0,0,0,0,0,0,0,0
STURX,0.00,0,0.5,0.00,0.30,0,0,0.2,0,0.0,0.00,0,0,0,0,0,0,0,0
THMS,0.00,0,0.0,1.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
WAVE,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,1,0,0,0
WHEN,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,1,0,0,0,0
WTOF,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,1,0
WSHP,0.95,0,0.0,0.05,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,0,0
WTON,0.00,0,0.0,0.00,0.00,0,0,0.0,0,0.0,0.00,0,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Switzerland.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Swiss Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
    <li>
        Bundesamt für Energie (BFE). (2023). Schweizerische Gesamtenergiestatistik 2022.
        <br>
        <a href="https://www.bfe.admin.ch/bfe/en/home/supply/statistics-and-geodata/energy-statistics/overall-energy-statistics.html" style="color:skyblue">https://www.bfe.admin.ch/bfe/en/home/supply/statistics-and-geodata/energy-statistics/overall-energy-statistics.html</a>
    </li>
    <li>
        Swiss Federal Office of Energy (SFOE). (2023). Swiss Energy Strategy 2050.
        <br>
        <a href="https://www.bfe.admin.ch/bfe/en/home/policy/energy-strategy-2050.html" style="color:skyblue">https://www.bfe.admin.ch/bfe/en/home/policy/energy-strategy-2050.html</a>
    </li>
    <li>
        International Energy Agency (IEA). (2022). Switzerland 2022: Energy Policy Review.
        <br>
        <a href="https://www.iea.org/reports/switzerland-2023" style="color:skyblue">https://www.iea.org/reports/switzerland-2023</a>
    </li>
    <li>
        Swissgrid. (2023). Grid and infrastructure data.
        <br>
        <a href="https://www.swissgrid.ch/en/home/newsroom/newsfeed/20240416-01.html" style="color:skyblue">https://www.swissgrid.ch/en/home/newsroom/newsfeed/20240416-01.html</a>
    </li>
    <li>
        Eurostat. (2024). Energy database. European Commission.
        <br>
        <a href="https://ec.europa.eu/eurostat/web/energy/database" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/database</a>
    </li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [55]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
CH_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0.2, 0, 1, 0, 0, 0, 0.35, 0.25, 0, 0, 0, 0, 0, 0.25, 0.35, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.25, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0.15, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.6, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 1, 0.7, 0, 0, 0, 0.9, 0.75, 0, 0, 0, 0, 0, 0.25, 0.65, 0, 0, 0, 0, 0, 0.4, 0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.1, 0.6, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.1, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0.15, 0, 0, 0.2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.75, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0.1, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
CH_fuel_technologies_match_df = pd.DataFrame(CH_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(CH_fuel_technologies_match_df)
CH_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO  HRD   HYD  LIG   NUC   OIL  OTH  PEA  \
ABHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0  0.00  0.00    0    0
ALFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.00    0    0
ALKE   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
ASHP   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
BATS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
BEVS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
BSPG   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
CAES   0.00    0  0.00  0.65  0.35    0    0  0.00    0  0.00  0.00    0    0
COMC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.00    0    0
COMCX  0.00    0  0.25  0.00  0.70    0    0  0.00    0  0.00  0.05    0    0
DMFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.00    0    0
GETH   0.00    0  0.00  0.00  0.00    1    0  0.00    0  0.00  0.00    0    0
GSHP   0.00    0  0.00  0.00  0.00    1    0  0.00    0  0.00  0.00    0    0
GTUR   0.00    0  0.00  0.00  0.90    0    0  0.10    0  0.00  0.00    0    0
GTURX  0.00    0  0.20  0.00  0.75    0    0  0.05    0  0.00  0.00    0    0
H2ST   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HBBS   0.00    0  1.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HDAM   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HDAMC  0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HDLZ   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HOBO   0.00    0  0.35  0.15  0.25    0    0  0.00    0  0.00  0.25    0    0
HOBOX  0.00    0  0.25  0.00  0.65    0    0  0.00    0  0.00  0.10    0    0
HPHS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HPHSC  0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HROR   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HRORC  0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
HYHP   0.90    0  0.00  0.10  0.00    0    0  0.00    0  0.00  0.00    0    0
ICEN   0.00    0  0.25  0.00  0.40    0    0  0.10    0  0.00  0.25    0    0
ICENX  0.00    0  0.35  0.00  0.50    0    0  0.15    0  0.00  0.00    0    0
MCFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.00    0    0
PAFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.00    0    0
P2BS   0.00    0  0.20  0.60  0.00    0    0  0.20    0  0.00  0.00    0    0
P2GS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
P2HT   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
PEFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.00    0    0
PEME   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
PHOT   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
REFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0  0.00  0.00    0    0
REHE   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
SCSP   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
SOFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0  0.00  0.00    0    0
SOTH   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
SOXE   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
STUR   0.00    0  0.15  0.00  0.10    0    0  0.00    0  0.75  0.00    0    0
STURX  0.00    0  0.25  0.00  0.60    0    0  0.15    0  0.00  0.00    0    0
THMS   0.00    0  0.00  1.00  0.00    0    0  0.00    0  0.00  0.00    0    0
WAVE   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
WHEN   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
WTOF   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0
WSHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0  0.00  0.00    0    0
WTON   0.00    0  0.00  0.00  0.00    0    0  0.00    0  0.00  0.00    0    0

       SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0
ALFC     0    0    0    0    0    0
ALKE     0    0    0    0    0    0
ASHP     0    0    0    0    0    0
BATS     0    0    0    0    0    0
BEVS     0    0    0    0    0    0
BSPG     1    0    0    0    0    0
CAES     0    0    0    0    0    0
COMC     0    0    0    0    0    0
COMCX    0    0    0    0    0    0
DMFC     0    0    0    0    0    0
GETH     0    0    0    0    0    0
GSHP     0    0    0    0    0    0
GTUR     0    0    0    0    0    0
GTURX    0    0    0    0    0    0
H2ST     0    0    0    0    0    0
HBBS     0    0    0    0    0    0
HDAM     0    0    1    0    0    0
HDAMC    0    0    1    0    0    0
HDLZ     0    0    1    0    0    0
HOBO     0    0    0    0    0    0
HOBOX    0    0    0    0    0    0
HPHS     0    0    0    0    0    0
HPHSC    0    0    0    0    0    0
HROR     0    0    1    0    0    0
HRORC    0    0    1    0    0    0
HYHP     0    0    0    0    0    0
ICEN     0    0    0    0    0    0
ICENX    0    0    0    0    0    0
MCFC     0    0    0    0    0    0
PAFC     0    0    0    0    0    0
P2BS     0    0    0    0    0    0
P2GS     0    0    0    0    0    0
P2HT     0    0    0    0    0    0
PEFC     0    0    0    0    0    0
PEME     0    0    0    0    0    0
PHOT     1    0    0    0    0    0
REFC     0    0    0    0    0    0
REHE     0    0    0    0    0    0
SCSP     1    0    0    0    0    0
SOFC     0    0    0    0    0    0
SOTH     1    0    0    0    0    0
SOXE     0    0    0    0    0    0
STUR     0    0    0    0    0    0
STURX    0    0    0    0    0    0
THMS     0    0    0    0    0    0
WAVE     0    0    1    0    0    0
WHEN     0    1    0    0    0    0
WTOF     0    0    0    0    1    0
WSHP     0    0    0    0    0    0
WTON     0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.00,0,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.65,0.35,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
COMCX,0.00,0,0.25,0.00,0.70,0,0,0.00,0,0.00,0.05,0,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.00,0,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.90,0,0,0.10,0,0.00,0.00,0,0,0,0,0,0,0,0
GTURX,0.00,0,0.20,0.00,0.75,0,0,0.05,0,0.00,0.00,0,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,1,0,0,0
HOBO,0.00,0,0.35,0.15,0.25,0,0,0.00,0,0.00,0.25,0,0,0,0,0,0,0,0
HOBOX,0.00,0,0.25,0.00,0.65,0,0,0.00,0,0.00,0.10,0,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
ICEN,0.00,0,0.25,0.00,0.40,0,0,0.10,0,0.00,0.25,0,0,0,0,0,0,0,0
ICENX,0.00,0,0.35,0.00,0.50,0,0,0.15,0,0.00,0.00,0,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
P2BS,0.00,0,0.20,0.60,0.00,0,0,0.20,0,0.00,0.00,0,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.00,0,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0.00,0.00,0,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
STUR,0.00,0,0.15,0.00,0.10,0,0,0.00,0,0.75,0.00,0,0,0,0,0,0,0,0
STURX,0.00,0,0.25,0.00,0.60,0,0,0.15,0,0.00,0.00,0,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0.00,0.00,0,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Austria.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Austrian Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
    <li>
        Bundesministerium für Klimaschutz, Umwelt, Energie, Mobilität, Innovation und Technologie (BMK). (2023). Integrated National Energy and Climate Plan for Austria 2021-2030.
        <br>
        <a href="https://www.bmk.gv.at/en.html" style="color:skyblue">https://www.bmk.gv.at/en.html</a>
    </li>
    <li>
        E-Control Austria. (2023). Energy statistics and data.
        <br>
        <a href="https://www.e-control.at/en/" style="color:skyblue">https://www.e-control.at/en/</a>
    </li>
    <li>
        International Energy Agency. (2020). Austria 2020: Energy Policy Review.
        <br>
        <a href="https://www.iea.org/reports/austria-2020" style="color:skyblue">https://www.iea.org/reports/austria-2020</a>
    </li>
    <li>
        Eurostat. (2024). Energy database. European Commission.
        <br>
        <a href="https://ec.europa.eu/eurostat/web/energy/database" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/database</a>
    </li>
    <li>
        Statistics Austria. (2023). Energy statistics.
        <br>
        <a href="https://www.statistik.at/en/statistics/energy-and-environment/energy" style="color:skyblue">https://www.statistik.at/en/statistics/energy-and-environment/energy</a>
    </li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [56]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
AT_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.45, 0, 0, 0, 0, 0.4, 0, 1, 0, 0, 0, 0.6, 0.5, 0, 0, 0, 0, 0, 0.35, 0.45, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0.45, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.45, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.85, 0.5, 0, 0, 0, 0.8, 0.55, 0, 0, 0, 0, 0, 0.20, 0.4, 0, 0, 0, 0, 0, 0.25, 0.4, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.4, 0.5, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.2, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.15, 0, 0, 0.15, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.1, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.35, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
AT_fuel_technologies_match_df = pd.DataFrame(AT_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(AT_fuel_technologies_match_df)
AT_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO  HRD   HYD  LIG  NUC   OIL   OTH  PEA  \
ABHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0    0  0.00  0.00    0
ALFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00  0.00    0
ALKE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
ASHP   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
BATS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
BEVS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
BSPG   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
CAES   0.00    0  0.00  0.65  0.35    0    0  0.00    0    0  0.00  0.00    0
COMC   0.00    0  0.00  0.00  0.85    0    0  0.00    0    0  0.15  0.00    0
COMCX  0.00    0  0.45  0.00  0.50    0    0  0.00    0    0  0.05  0.00    0
DMFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00  0.00    0
GETH   0.00    0  0.00  0.00  0.00    1    0  0.00    0    0  0.00  0.00    0
GSHP   0.00    0  0.00  0.00  0.00    1    0  0.00    0    0  0.00  0.00    0
GTUR   0.00    0  0.00  0.00  0.80    0    0  0.20    0    0  0.00  0.00    0
GTURX  0.00    0  0.40  0.00  0.55    0    0  0.05    0    0  0.00  0.00    0
H2ST   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HBBS   0.00    0  1.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HDAM   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HDAMC  0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HDLZ   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HOBO   0.00    0  0.60  0.00  0.20    0    0  0.00    0    0  0.15  0.05    0
HOBOX  0.00    0  0.50  0.00  0.40    0    0  0.00    0    0  0.10  0.00    0
HPHS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HPHSC  0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HROR   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HRORC  0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
HYHP   0.90    0  0.00  0.10  0.00    0    0  0.00    0    0  0.00  0.00    0
ICEN   0.00    0  0.35  0.00  0.25    0    0  0.15    0    0  0.25  0.00    0
ICENX  0.00    0  0.45  0.00  0.40    0    0  0.15    0    0  0.00  0.00    0
MCFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.00  0.00    0
PAFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.00  0.00    0
P2BS   0.00    0  0.40  0.45  0.00    0    0  0.15    0    0  0.00  0.00    0
P2GS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
P2HT   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
PEFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00  0.00    0
PEME   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
PHOT   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
REFC   0.00    0  0.00  0.00  0.00    0    0  1.00    0    0  0.00  0.00    0
REHE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
SCSP   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
SOFC   0.00    0  0.00  0.00  1.00    0    0  0.00    0    0  0.00  0.00    0
SOTH   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
SOXE   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
STUR   0.00    0  0.25  0.00  0.40    0    0  0.00    0    0  0.35  0.00    0
STURX  0.00    0  0.45  0.00  0.50    0    0  0.05    0    0  0.00  0.00    0
THMS   0.00    0  0.00  1.00  0.00    0    0  0.00    0    0  0.00  0.00    0
WAVE   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
WHEN   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
WTOF   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0
WSHP   0.95    0  0.00  0.05  0.00    0    0  0.00    0    0  0.00  0.00    0
WTON   0.00    0  0.00  0.00  0.00    0    0  0.00    0    0  0.00  0.00    0

       SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0
ALFC     0    0    0    0    0    0
ALKE     0    0    0    0    0    0
ASHP     0    0    0    0    0    0
BATS     0    0    0    0    0    0
BEVS     0    0    0    0    0    0
BSPG     1    0    0    0    0    0
CAES     0    0    0    0    0    0
COMC     0    0    0    0    0    0
COMCX    0    0    0    0    0    0
DMFC     0    0    0    0    0    0
GETH     0    0    0    0    0    0
GSHP     0    0    0    0    0    0
GTUR     0    0    0    0    0    0
GTURX    0    0    0    0    0    0
H2ST     0    0    0    0    0    0
HBBS     0    0    0    0    0    0
HDAM     0    0    1    0    0    0
HDAMC    0    0    1    0    0    0
HDLZ     0    0    1    0    0    0
HOBO     0    0    0    0    0    0
HOBOX    0    0    0    0    0    0
HPHS     0    0    0    0    0    0
HPHSC    0    0    0    0    0    0
HROR     0    0    1    0    0    0
HRORC    0    0    1    0    0    0
HYHP     0    0    0    0    0    0
ICEN     0    0    0    0    0    0
ICENX    0    0    0    0    0    0
MCFC     0    0    0    0    0    0
PAFC     0    0    0    0    0    0
P2BS     0    0    0    0    0    0
P2GS     0    0    0    0    0    0
P2HT     0    0    0    0    0    0
PEFC     0    0    0    0    0    0
PEME     0    0    0    0    0    0
PHOT     1    0    0    0    0    0
REFC     0    0    0    0    0    0
REHE     0    0    0    0    0    0
SCSP     1    0    0    0    0    0
SOFC     0    0    0    0    0    0
SOTH     1    0    0    0    0    0
SOXE     0    0    0    0    0    0
STUR     0    0    0    0    0    0
STURX    0    0    0    0    0    0
THMS     0    0    0    0    0    0
WAVE     0    0    1    0    0    0
WHEN     0    1    0    0    0    0
WTOF     0    0    0    0    1    0
WSHP     0    0    0    0    0    0
WTON     0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.65,0.35,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.85,0,0,0.00,0,0,0.15,0.00,0,0,0,0,0,0,0
COMCX,0.00,0,0.45,0.00,0.50,0,0,0.00,0,0,0.05,0.00,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.80,0,0,0.20,0,0,0.00,0.00,0,0,0,0,0,0,0
GTURX,0.00,0,0.40,0.00,0.55,0,0,0.05,0,0,0.00,0.00,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HOBO,0.00,0,0.60,0.00,0.20,0,0,0.00,0,0,0.15,0.05,0,0,0,0,0,0,0
HOBOX,0.00,0,0.50,0.00,0.40,0,0,0.00,0,0,0.10,0.00,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
ICEN,0.00,0,0.35,0.00,0.25,0,0,0.15,0,0,0.25,0.00,0,0,0,0,0,0,0
ICENX,0.00,0,0.45,0.00,0.40,0,0,0.15,0,0,0.00,0.00,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
P2BS,0.00,0,0.40,0.45,0.00,0,0,0.15,0,0,0.00,0.00,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0,1.00,0,0,0.00,0.00,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
STUR,0.00,0,0.25,0.00,0.40,0,0,0.00,0,0,0.35,0.00,0,0,0,0,0,0,0
STURX,0.00,0,0.45,0.00,0.50,0,0,0.05,0,0,0.00,0.00,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0,0.00,0,0,0.00,0.00,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Poland.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the PolaK Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
Ministerstwo Klimatu i Środowiska. (2021). Energy policy of Poland until 2040 (PEP2040). 
<br>
<a href="https://www.gov.pl/web/klimat/polityka-energetyczna-polski" style="color:skyblue">https://www.gov.pl/web/klimat/polityka-energetyczna-polski</a>
</li>
<li>
Polskie Sieci Elektroenergetyczne (PSE). (2023). 
Dane statystyczne [Statistical data]. 
<br>
<a href="https://www.pse.pl/dane-systemowe" style="color:skyblue">https://www.pse.pl/dane-systemowe</a>
</li>
<li>
Główny Urząd Statystyczny (Statistics Poland). (2023). 
Energy statistics. 
<br>
<a href="https://stat.gov.pl/en/topics/environment-energy/energy/" style="color:skyblue">https://stat.gov.pl/en/topics/environment-energy/energy/</a>
</li>
<li>
International Energy Agency. (2022). 
Poland 2022: Energy Policy Review. 
<br>
<a href="https://www.iea.org/reports/poland-2022" style="color:skyblue">https://www.iea.org/reports/poland-2022</a>
</li>
<li>
Eurostat. (2024). 
Energy database. European Commission.
<br>
<a href="https://ec.europa.eu/eurostat/web/energy/database" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/database</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [57]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
PL_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0.2, 0, 1, 0, 0, 0, 0.35, 0.25, 0, 0, 0, 0, 0, 0.15, 0.2, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.2, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.6, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0, 0.6, 0.7, 0, 0, 0, 0.7, 0.65, 0, 0, 0, 0, 0, 0.20, 0.4, 0, 0, 0, 0, 0, 0.2, 0.35, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.2, 0.45, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0.1, 0, 0, 0, 0, 0, 0.2, 0.25, 0, 0, 0, 0, 0, 0.45, 0.35, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.55, 0.3, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.20, 0.1, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}

index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
PL_fuel_technologies_match_df = pd.DataFrame(PL_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(PL_fuel_technologies_match_df)
PL_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO   HRD   HYD   LIG  NUC   OIL  OTH  \
ABHP   0.95    0  0.00  0.05  0.00    0  0.00  0.00  0.00    0  0.00    0
ALFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00  0.00    0  0.00    0
ALKE   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
ASHP   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
BATS   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
BEVS   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
BSPG   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
CAES   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
COMC   0.00    0  0.00  0.00  0.60    0  0.00  0.00  0.40    0  0.00    0
COMCX  0.00    0  0.15  0.00  0.70    0  0.00  0.00  0.00    0  0.15    0
DMFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00  0.00    0  0.00    0
GETH   0.00    0  0.00  0.00  0.00    1  0.00  0.00  0.00    0  0.00    0
GSHP   0.00    0  0.00  0.00  0.00    1  0.00  0.00  0.00    0  0.00    0
GTUR   0.00    0  0.00  0.00  0.70    0  0.25  0.05  0.00    0  0.00    0
GTURX  0.00    0  0.20  0.00  0.65    0  0.10  0.05  0.00    0  0.00    0
H2ST   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HBBS   0.00    0  1.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HDAM   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HDAMC  0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HDLZ   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HOBO   0.00    0  0.35  0.00  0.20    0  0.20  0.00  0.20    0  0.05    0
HOBOX  0.00    0  0.25  0.00  0.40    0  0.25  0.00  0.10    0  0.00    0
HPHS   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HPHSC  0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HROR   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HRORC  0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
HYHP   0.90    0  0.00  0.10  0.00    0  0.00  0.00  0.00    0  0.00    0
ICEN   0.00    0  0.15  0.00  0.20    0  0.45  0.05  0.15    0  0.00    0
ICENX  0.00    0  0.20  0.00  0.35    0  0.35  0.10  0.00    0  0.00    0
MCFC   0.00    0  0.00  0.00  1.00    0  0.00  0.00  0.00    0  0.00    0
PAFC   0.00    0  0.00  0.00  1.00    0  0.00  0.00  0.00    0  0.00    0
P2BS   0.00    0  0.25  0.60  0.00    0  0.15  0.00  0.00    0  0.00    0
P2GS   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
P2HT   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
PEFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00  0.00    0  0.00    0
PEME   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
PHOT   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
REFC   0.00    0  0.00  0.00  0.00    0  0.00  1.00  0.00    0  0.00    0
REHE   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
SCSP   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
SOFC   0.00    0  0.00  0.00  1.00    0  0.00  0.00  0.00    0  0.00    0
SOTH   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
SOXE   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
STUR   0.00    0  0.15  0.00  0.20    0  0.55  0.00  0.10    0  0.00    0
STURX  0.00    0  0.20  0.00  0.45    0  0.30  0.05  0.00    0  0.00    0
THMS   0.00    0  0.00  1.00  0.00    0  0.00  0.00  0.00    0  0.00    0
WAVE   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
WHEN   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
WTOF   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0
WSHP   0.95    0  0.00  0.05  0.00    0  0.00  0.00  0.00    0  0.00    0
WTON   0.00    0  0.00  0.00  0.00    0  0.00  0.00  0.00    0  0.00    0

       PEA  SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0    0
ALFC     0    0    0    0    0    0    0
ALKE     0    0    0    0    0    0    0
ASHP     0    0    0    0    0    0    0
BATS     0    0    0    0    0    0    0
BEVS     0    0    0    0    0    0    0
BSPG     0    1    0    0    0    0    0
CAES     0    0    0    0    0    0    0
COMC     0    0    0    0    0    0    0
COMCX    0    0    0    0    0    0    0
DMFC     0    0    0    0    0    0    0
GETH     0    0    0    0    0    0    0
GSHP     0    0    0    0    0    0    0
GTUR     0    0    0    0    0    0    0
GTURX    0    0    0    0    0    0    0
H2ST     0    0    0    0    0    0    0
HBBS     0    0    0    0    0    0    0
HDAM     0    0    0    1    0    0    0
HDAMC    0    0    0    1    0    0    0
HDLZ     0    0    0    1    0    0    0
HOBO     0    0    0    0    0    0    0
HOBOX    0    0    0    0    0    0    0
HPHS     0    0    0    0    0    0    0
HPHSC    0    0    0    0    0    0    0
HROR     0    0    0    1    0    0    0
HRORC    0    0    0    1    0    0    0
HYHP     0    0    0    0    0    0    0
ICEN     0    0    0    0    0    0    0
ICENX    0    0    0    0    0    0    0
MCFC     0    0    0    0    0    0    0
PAFC     0    0    0    0    0    0    0
P2BS     0    0    0    0    0    0    0
P2GS     0    0    0    0    0    0    0
P2HT     0    0    0    0    0    0    0
PEFC     0    0    0    0    0    0    0
PEME     0    0    0    0    0    0    0
PHOT     0    1    0    0    0    0    0
REFC     0    0    0    0    0    0    0
REHE     0    0    0    0    0    0    0
SCSP     0    1    0    0    0    0    0
SOFC     0    0    0    0    0    0    0
SOTH     0    1    0    0    0    0    0
SOXE     0    0    0    0    0    0    0
STUR     0    0    0    0    0    0    0
STURX    0    0    0    0    0    0    0
THMS     0    0    0    0    0    0    0
WAVE     0    0    0    1    0    0    0
WHEN     0    0    1    0    0    0    0
WTOF     0    0    0    0    0    1    0
WSHP     0    0    0    0    0    0    0
WTON     0    0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0.00,0,0.00,0,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.60,0,0.00,0.00,0.40,0,0.00,0,0,0,0,0,0,0,0
COMCX,0.00,0,0.15,0.00,0.70,0,0.00,0.00,0.00,0,0.15,0,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0.00,0,0.00,0,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,0.00,0.00,1,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.70,0,0.25,0.05,0.00,0,0.00,0,0,0,0,0,0,0,0
GTURX,0.00,0,0.20,0.00,0.65,0,0.10,0.05,0.00,0,0.00,0,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,1,0,0,0
HOBO,0.00,0,0.35,0.00,0.20,0,0.20,0.00,0.20,0,0.05,0,0,0,0,0,0,0,0
HOBOX,0.00,0,0.25,0.00,0.40,0,0.25,0.00,0.10,0,0.00,0,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
ICEN,0.00,0,0.15,0.00,0.20,0,0.45,0.05,0.15,0,0.00,0,0,0,0,0,0,0,0
ICENX,0.00,0,0.20,0.00,0.35,0,0.35,0.10,0.00,0,0.00,0,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
P2BS,0.00,0,0.25,0.60,0.00,0,0.15,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0.00,0,0.00,0,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0.00,1.00,0.00,0,0.00,0,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
STUR,0.00,0,0.15,0.00,0.20,0,0.55,0.00,0.10,0,0.00,0,0,0,0,0,0,0,0
STURX,0.00,0,0.20,0.00,0.45,0,0.30,0.05,0.00,0,0.00,0,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0.00,0.00,0.00,0,0.00,0,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Slovenia.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Slove Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [58]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
SI_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
SI_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(SI_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(SI_fuel_technologies_match_df)
SI_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Turkey.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Turk Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
International Energy Agency (IEA) - Comprehensive Analysis
<br>
International Energy Agency. (2021). Turkey 2021: Energy Policy Review. IEA. <a href="https://www.iea.org/reports/turkey-2021" style="color:skyblue">https://www.iea.org/reports/turkey-2021</a>
<br>
Provides detailed analysis of Turkey's entire energy system, policies, and future outlook.
</li>
<li>
Turkish Statistical Institute (TurkStat) - Official National Statistics
<br>
Turkish Statistical Institute. (2024). Energy statistics. <a href="https://data.tuik.gov.tr/Kategori/GetKategori?p=cevre-ve-enerji-116" style="color:skyblue">https://data.tuik.gov.tr/Kategori/GetKategori?p=cevre-ve-enerji-116</a>
<br>
Official source for comprehensive energy balance, consumption, and import/export data.
</li>
<li>
Ministry of Energy and Natural Resources - Policy Context
<br>
Ministry of Energy and Natural Resources. (2024). Energy policies and strategies. <a href="https://enerji.gov.tr/bilgi-merkezi-enerji-politikalari" style="color:skyblue">https://enerji.gov.tr/bilgi-merkezi-enerji-politikalari</a>
<br>
Provides the policy framework and strategic direction for Turkey's energy sector.
</li>
<li>
Eurostat - Comparative European Data
<br>
Eurostat. (2024). Energy database. European Commission. <a href="https://ec.europa.eu/eurostat/web/energy/data/database" style="color:skyblue">https://ec.europa.eu/eurostat/web/energy/data/database</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [59]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
TR_fuel_technologies_match = {
    'AIR': [0.95, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.95, 0],
    'AMO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'BIO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0.2, 0, 1, 0, 0, 0, 0.12, 0.3, 0, 0, 0, 0, 0, 0.2, 0.25, 0, 0, 0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0.25, 0, 0, 0, 0, 0, 0],
    'ELE': [0.05, 0, 1, 1, 1, 1, 0, 0.65, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0.1, 0, 0, 0, 0, 0.6, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0.05, 0],
    'GAS': [0, 0, 0, 0, 0, 0, 0, 0.35, 0.85, 0.75, 0, 0, 0, 0.8, 0.65, 0, 0, 0, 0, 0, 0.59, 0.55, 0, 0, 0, 0, 0, 0.35, 0.5, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.45, 0.6, 0, 0, 0, 0, 0, 0],
    'GEO': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'HRD': [0, 0, 0, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0.15, 0.1, 0, 0, 0, 0, 0, 0.125, 0.1, 0, 0, 0, 0, 0, 0.25, 0.2, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0.1, 0, 0, 0, 0, 0, 0],
    'HYD': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.05, 0.05, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0.05, 0, 0, 0, 0, 0, 0],
    'LIG': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.125, 0.05, 0, 0, 0, 0, 0, 0.15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0],
    'NUC': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OIL': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'OTH': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.03, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'PEA': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'SUN': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'THE': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    'WAT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    'WHT': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    'WIN': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    'WST': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
TR_fuel_technologies_match_df = pd.DataFrame(TR_fuel_technologies_match, index=index)

# 3. ************************************************************************************************************* Done
print(TR_fuel_technologies_match_df)
TR_fuel_technologies_match_df

        AIR  AMO   BIO   ELE   GAS  GEO    HRD   HYD    LIG  NUC   OIL   OTH  \
ABHP   0.95    0  0.00  0.05  0.00    0  0.000  0.00  0.000    0  0.00  0.00
ALFC   0.00    0  0.00  0.00  0.00    0  0.000  1.00  0.000    0  0.00  0.00
ALKE   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
ASHP   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
BATS   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
BEVS   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
BSPG   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
CAES   0.00    0  0.00  0.65  0.35    0  0.000  0.00  0.000    0  0.00  0.00
COMC   0.00    0  0.00  0.00  0.85    0  0.150  0.00  0.000    0  0.00  0.00
COMCX  0.00    0  0.15  0.00  0.75    0  0.000  0.00  0.000    0  0.10  0.00
DMFC   0.00    0  0.00  0.00  0.00    0  0.000  1.00  0.000    0  0.00  0.00
GETH   0.00    0  0.00  0.00  0.00    1  0.000  0.00  0.000    0  0.00  0.00
GSHP   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
GTUR   0.00    0  0.00  0.00  0.80    0  0.150  0.05  0.000    0  0.00  0.00
GTURX  0.00    0  0.20  0.00  0.65    0  0.100  0.05  0.000    0  0.00  0.00
H2ST   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HBBS   0.00    0  1.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HDAM   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HDAMC  0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HDLZ   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HOBO   0.00    0  0.12  0.00  0.59    0  0.125  0.00  0.125    0  0.01  0.03
HOBOX  0.00    0  0.30  0.00  0.55    0  0.100  0.00  0.050    0  0.00  0.00
HPHS   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HPHSC  0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HROR   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HRORC  0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
HYHP   0.90    0  0.00  0.10  0.00    0  0.000  0.00  0.000    0  0.00  0.00
ICEN   0.00    0  0.20  0.00  0.35    0  0.250  0.05  0.150    0  0.00  0.00
ICENX  0.00    0  0.25  0.00  0.50    0  0.200  0.05  0.000    0  0.00  0.00
MCFC   0.00    0  0.00  0.00  1.00    0  0.000  0.00  0.000    0  0.00  0.00
PAFC   0.00    0  0.00  0.00  1.00    0  0.000  0.00  0.000    0  0.00  0.00
P2BS   0.00    0  0.25  0.60  0.00    0  0.150  0.00  0.000    0  0.00  0.00
P2GS   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
P2HT   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
PEFC   0.00    0  0.00  0.00  0.00    0  0.000  1.00  0.000    0  0.00  0.00
PEME   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
PHOT   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
REFC   0.00    0  0.00  0.00  0.00    0  0.000  1.00  0.000    0  0.00  0.00
REHE   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
SCSP   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
SOFC   0.00    0  0.00  0.00  1.00    0  0.000  0.00  0.000    0  0.00  0.00
SOTH   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
SOXE   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
STUR   0.00    0  0.15  0.00  0.45    0  0.300  0.00  0.100    0  0.00  0.00
STURX  0.00    0  0.25  0.00  0.60    0  0.100  0.05  0.000    0  0.00  0.00
THMS   0.00    0  0.00  1.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
WAVE   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
WHEN   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
WTOF   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00
WSHP   0.95    0  0.00  0.05  0.00    0  0.000  0.00  0.000    0  0.00  0.00
WTON   0.00    0  0.00  0.00  0.00    0  0.000  0.00  0.000    0  0.00  0.00

       PEA  SUN  THE  WAT  WHT  WIN  WST
ABHP     0    0    0    0    0    0    0
ALFC     0    0    0    0    0    0    0
ALKE     0    0    0    0    0    0    0
ASHP     0    0    0    0    0    0    0
BATS     0    0    0    0    0    0    0
BEVS     0    0    0    0    0    0    0
BSPG     0    1    0    0    0    0    0
CAES     0    0    0    0    0    0    0
COMC     0    0    0    0    0    0    0
COMCX    0    0    0    0    0    0    0
DMFC     0    0    0    0    0    0    0
GETH     0    0    0    0    0    0    0
GSHP     0    0    0    0    0    0    0
GTUR     0    0    0    0    0    0    0
GTURX    0    0    0    0    0    0    0
H2ST     0    0    0    0    0    0    0
HBBS     0    0    0    0    0    0    0
HDAM     0    0    0    1    0    0    0
HDAMC    0    0    0    1    0    0    0
HDLZ     0    0    0    1    0    0    0
HOBO     0    0    0    0    0    0    0
HOBOX    0    0    0    0    0    0    0
HPHS     0    0    0    0    0    0    0
HPHSC    0    0    0    0    0    0    0
HROR     0    0    0    1    0    0    0
HRORC    0    0    0    1    0    0    0
HYHP     0    0    0    0    0    0    0
ICEN     0    0    0    0    0    0    0
ICENX    0    0    0    0    0    0    0
MCFC     0    0    0    0    0    0    0
PAFC     0    0    0    0    0    0    0
P2BS     0    0    0    0    0    0    0
P2GS     0    0    0    0    0    0    0
P2HT     0    0    0    0    0    0    0
PEFC     0    0    0    0    0    0    0
PEME     0    0    0    0    0    0    0
PHOT     0    1    0    0    0    0    0
REFC     0    0    0    0    0    0    0
REHE     0    0    0    0    0    0    0
SCSP     0    1    0    0    0    0    0
SOFC     0    0    0    0    0    0    0
SOTH     0    1    0    0    0    0    0
SOXE     0    0    0    0    0    0    0
STUR     0    0    0    0    0    0    0
STURX    0    0    0    0    0    0    0
THMS     0    0    0    0    0    0    0
WAVE     0    0    0    1    0    0    0
WHEN     0    0    1    0    0    0    0
WTOF     0    0    0    0    0    1    0
WSHP     0    0    0    0    0    0    0
WTON     0    0    0    0    0    1    0

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,0.95,0,0.00,0.05,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
ALFC,0.00,0,0.00,0.00,0.00,0,0.000,1.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
ALKE,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
ASHP,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
BATS,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
BEVS,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
BSPG,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,1,0,0,0,0,0
CAES,0.00,0,0.00,0.65,0.35,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
COMC,0.00,0,0.00,0.00,0.85,0,0.150,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
COMCX,0.00,0,0.15,0.00,0.75,0,0.000,0.00,0.000,0,0.10,0.00,0,0,0,0,0,0,0
DMFC,0.00,0,0.00,0.00,0.00,0,0.000,1.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
GETH,0.00,0,0.00,0.00,0.00,1,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
GSHP,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
GTUR,0.00,0,0.00,0.00,0.80,0,0.150,0.05,0.000,0,0.00,0.00,0,0,0,0,0,0,0
GTURX,0.00,0,0.20,0.00,0.65,0,0.100,0.05,0.000,0,0.00,0.00,0,0,0,0,0,0,0
H2ST,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
HBBS,0.00,0,1.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
HDAM,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,1,0,0,0
HDAMC,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,1,0,0,0
HDLZ,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,1,0,0,0
HOBO,0.00,0,0.12,0.00,0.59,0,0.125,0.00,0.125,0,0.01,0.03,0,0,0,0,0,0,0
HOBOX,0.00,0,0.30,0.00,0.55,0,0.100,0.00,0.050,0,0.00,0.00,0,0,0,0,0,0,0
HPHS,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
HPHSC,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
HROR,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,1,0,0,0
HRORC,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,1,0,0,0
HYHP,0.90,0,0.00,0.10,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
ICEN,0.00,0,0.20,0.00,0.35,0,0.250,0.05,0.150,0,0.00,0.00,0,0,0,0,0,0,0
ICENX,0.00,0,0.25,0.00,0.50,0,0.200,0.05,0.000,0,0.00,0.00,0,0,0,0,0,0,0
MCFC,0.00,0,0.00,0.00,1.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
PAFC,0.00,0,0.00,0.00,1.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
P2BS,0.00,0,0.25,0.60,0.00,0,0.150,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
P2GS,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
P2HT,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
PEFC,0.00,0,0.00,0.00,0.00,0,0.000,1.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
PEME,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
PHOT,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,1,0,0,0,0,0
REFC,0.00,0,0.00,0.00,0.00,0,0.000,1.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
REHE,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
SCSP,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,1,0,0,0,0,0
SOFC,0.00,0,0.00,0.00,1.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
SOTH,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,1,0,0,0,0,0
SOXE,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
STUR,0.00,0,0.15,0.00,0.45,0,0.300,0.00,0.100,0,0.00,0.00,0,0,0,0,0,0,0
STURX,0.00,0,0.25,0.00,0.60,0,0.100,0.05,0.000,0,0.00,0.00,0,0,0,0,0,0,0
THMS,0.00,0,0.00,1.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
WAVE,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,1,0,0,0
WHEN,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,1,0,0,0,0
WTOF,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,1,0
WSHP,0.95,0,0.00,0.05,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,0,0
WTON,0.00,0,0.00,0.00,0.00,0,0.000,0.00,0.000,0,0.00,0.00,0,0,0,0,0,1,0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The Dispa-SET Technology - Fuel matching table for Ukraine.
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Although the previous table can be used as support for all countries since it provides overall values from around the world, the following table specifically focuses on the Ukra Energy System.
The same was built using the following additional sources:
</div>
<div style="text-align: justify; margin-left: 5em; font-weight: normal; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
xxxxxxxxxxxxxxxxxxxxxx. 
<br>
<a href="xxxxxxxxxxxxxxxxxxx" style="color:skyblue">xxxxxxxxxxxxxxxxxxxxxxi</a>
</li>
</ol>
</div>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [60]:
# 1. ***************************************************** Data with 19 values for each column to match the index length
UA_fuel_technologies_match = {
    'AIR': [],
    'AMO': [],
    'BIO': [],
    'ELE': [],
    'GAS': [],
    'GEO': [],
    'HRD': [],
    'HYD': [],
    'LIG': [],
    'NUC': [],
    'OIL': [],
    'OTH': [],
    'PEA': [],
    'SUN': [],
    'THE': [],
    'WAT': [],
    'WHT': [],
    'WIN': [],
    'WST': []
}
index = ['ABHP','ALFC','ALKE','ASHP','BATS','BEVS','BSPG','CAES','COMC','COMCX','DMFC','GETH','GSHP','GTUR','GTURX','H2ST','HBBS','HDAM','HDAMC','HDLZ','HOBO','HOBOX','HPHS','HPHSC','HROR','HRORC','HYHP','ICEN','ICENX','MCFC','PAFC','P2BS','P2GS','P2HT','PEFC','PEME','PHOT','REFC','REHE','SCSP','SOFC','SOTH','SOXE','STUR','STURX','THMS','WAVE','WHEN','WTOF','WSHP','WTON']

# 2. ************************************************************************************************* Create DataFrame
UA_fuel_technologies_match_df = pd.DataFrame('N/A', index=index, columns=list(UA_fuel_technologies_match.keys()))

# 3. ************************************************************************************************************* Done
print(UA_fuel_technologies_match_df)
UA_fuel_technologies_match_df

       AIR  AMO  BIO  ELE  GAS  GEO  HRD  HYD  LIG  NUC  OIL  OTH  PEA  SUN  \
ABHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A  N/A

       THE  WAT  WHT  WIN  WST
ABHP   N/A  N/A  N/A  N/A  N/A
ALFC   N/A  N/A  N/A  N/A  N/A
ALKE   N/A  N/A  N/A  N/A  N/A
ASHP   N/A  N/A  N/A  N/A  N/A
BATS   N/A  N/A  N/A  N/A  N/A
BEVS   N/A  N/A  N/A  N/A  N/A
BSPG   N/A  N/A  N/A  N/A  N/A
CAES   N/A  N/A  N/A  N/A  N/A
COMC   N/A  N/A  N/A  N/A  N/A
COMCX  N/A  N/A  N/A  N/A  N/A
DMFC   N/A  N/A  N/A  N/A  N/A
GETH   N/A  N/A  N/A  N/A  N/A
GSHP   N/A  N/A  N/A  N/A  N/A
GTUR   N/A  N/A  N/A  N/A  N/A
GTURX  N/A  N/A  N/A  N/A  N/A
H2ST   N/A  N/A  N/A  N/A  N/A
HBBS   N/A  N/A  N/A  N/A  N/A
HDAM   N/A  N/A  N/A  N/A  N/A
HDAMC  N/A  N/A  N/A  N/A  N/A
HDLZ   N/A  N/A  N/A  N/A  N/A
HOBO   N/A  N/A  N/A  N/A  N/A
HOBOX  N/A  N/A  N/A  N/A  N/A
HPHS   N/A  N/A  N/A  N/A  N/A
HPHSC  N/A  N/A  N/A  N/A  N/A
HROR   N/A  N/A  N/A  N/A  N/A
HRORC  N/A  N/A  N/A  N/A  N/A
HYHP   N/A  N/A  N/A  N/A  N/A
ICEN   N/A  N/A  N/A  N/A  N/A
ICENX  N/A  N/A  N/A  N/A  N/A
MCFC   N/A  N/A  N/A  N/A  N/A
PAFC   N/A  N/A  N/A  N/A  N/A
P2BS   N/A  N/A  N/A  N/A  N/A
P2GS   N/A  N/A  N/A  N/A  N/A
P2HT   N/A  N/A  N/A  N/A  N/A
PEFC   N/A  N/A  N/A  N/A  N/A
PEME   N/A  N/A  N/A  N/A  N/A
PHOT   N/A  N/A  N/A  N/A  N/A
REFC   N/A  N/A  N/A  N/A  N/A
REHE   N/A  N/A  N/A  N/A  N/A
SCSP   N/A  N/A  N/A  N/A  N/A
SOFC   N/A  N/A  N/A  N/A  N/A
SOTH   N/A  N/A  N/A  N/A  N/A
SOXE   N/A  N/A  N/A  N/A  N/A
STUR   N/A  N/A  N/A  N/A  N/A
STURX  N/A  N/A  N/A  N/A  N/A
THMS   N/A  N/A  N/A  N/A  N/A
WAVE   N/A  N/A  N/A  N/A  N/A
WHEN   N/A  N/A  N/A  N/A  N/A
WTOF   N/A  N/A  N/A  N/A  N/A
WSHP   N/A  N/A  N/A  N/A  N/A
WTON   N/A  N/A  N/A  N/A  N/A

,AIR,AMO,BIO,ELE,GAS,GEO,HRD,HYD,LIG,NUC,OIL,OTH,PEA,SUN,THE,WAT,WHT,WIN,WST
ABHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ALKE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ASHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BATS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BEVS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
BSPG,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
CAES,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
COMCX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
DMFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GETH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
GTURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
H2ST,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HBBS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAM,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDAMC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HDLZ,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBO,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HOBOX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HPHSC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HROR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HRORC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
HYHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
ICENX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
MCFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PAFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2BS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2GS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
P2HT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PEME,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
PHOT,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
REHE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SCSP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOFC,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOTH,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
SOXE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STUR,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
STURX,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
THMS,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WAVE,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WHEN,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTOF,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WSHP,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A
WTON,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A,N/A

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman', serif; color: skyblue;">
6.5. Technology Match by Country Dictionary
</div>
<div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
All the data frame of Fuel type proportions by Technology for each modeled counties is joining into a single dictionary.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [61]:
# 1. ************************************************************************* Set the fuel technology match dictionary 
fuel_technologies_match_dict = {
    zone: globals()[f"{zone}_fuel_technologies_match_df"]
    for zone in zone_names
}

# 2. ************************************************************************************************************* Done
print(fuel_technologies_match_dict)

{'BE':         AIR  AMO   BIO   ELE   GAS  GEO  HRD  HYD  LIG  NUC   OIL  OTH  PEA  \
ABHP   0.05  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
ALFC   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
ALKE   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
ASHP   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
BATS   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
BEVS   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
BSPG   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
CAES   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
COMC   0.00  0.0  0.05  0.00  0.95    0    0    0    0  0.0  0.00    0    0
COMCX  0.00  0.0  0.15  0.00  0.80    0    0    0    0  0.0  0.00    0    0
DMFC   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    1    0
GETH   0.00  0.0  0.00  0.00  0.00    1    1    0    0  0.0  0.00    0    0
GSHP   0.00  0.0  0.00  0.00  0.00    1    0    0    0  0.0  0.00    0    0
GTUR   0.00  0.0  0.05  0.00  0.90    0    0    0    0  0.0  0.05    0    0
GTURX  0.00  0.0  0.10  0.00  0.85    0    0    0    0  0.0  0.05    0    0
H2ST   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
HBBS   0.00  0.0  1.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HDAM   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HDAMC  0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HDLZ   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HOBO   0.00  0.0  0.10  0.00  0.75    0    0    0    0  0.0  0.15    0    0
HOBOX  0.00  0.0  0.20  0.00  0.65    0    0    0    0  0.0  0.05    0    0
HPHS   0.00  0.0  0.00  0.95  0.00    0    0    0    0  0.0  0.00    0    0
HPHSC  0.00  0.0  0.00  0.95  0.00    0    0    0    0  0.0  0.00    0    0
HROR   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HRORC  0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
HYHP   0.00  0.0  0.10  0.90  0.00    0    0    0    0  0.0  0.00    0    0
ICEN   0.00  0.0  0.05  0.00  0.60    0    0    0    0  0.0  0.35    0    0
ICENX  0.00  0.0  0.10  0.00  0.65    0    0    0    0  0.0  0.25    0    0
MCFC   0.00  0.0  0.10  0.00  0.85    0    0    0    0  0.0  0.05    0    0
PAFC   0.00  0.0  0.10  0.00  0.85    0    0    0    0  0.0  0.05    0    0
P2BS   0.00  0.1  0.00  0.90  0.00    0    0    0    0  0.0  0.00    0    0
P2GS   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
P2HT   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
PEFC   0.00  0.0  0.00  0.10  0.90    0    0    0    0  0.0  0.00    0    0
PEME   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
PHOT   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
REFC   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
REHE   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
SCSP   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
SOFC   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
SOTH   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
SOXE   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
STUR   0.00  0.0  0.00  0.00  0.10    0    0    0    0  0.8  0.05    0    0
STURX  0.00  0.0  0.00  0.00  0.20    0    0    0    0  0.8  0.00    0    0
THMS   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WAVE   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WHEN   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WTOF   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0
WSHP   0.00  0.0  0.00  1.00  0.00    0    0    0    0  0.0  0.00    0    0
WTON   0.00  0.0  0.00  0.00  0.00    0    0    0    0  0.0  0.00    0    0

       SUN   THE   WAT  WHT  WIN   WST
ABHP     0  0.95  0.00    0    0  0.00
ALFC     0  0.00  0.00    0    0  0.00
ALKE     0  0.00  0.00    0    0  0.00
ASHP     0  0.00  0.00    0    0  0.00
BATS     0  0.00  0.00    0    0  0.00
BEVS     0  0.00  0.00    0    0  0.00
BSPG     1  0.00  0.00    0    0  0.00
CAES     0  0.00  0.00    0    0  0.00
COMC     0  0.00  0.00    0    0  0.00
COMCX    0  0.00  0.00    0    0  0.00
DMFC     0  0.00  0.00    0    0  0.00
GETH     0  0.00  0.00    0    0  0.00
GSHP     0  0.00  0.00    0    0  0.00
GTUR     0  0.00  0.00    0    0  0.00
GTURX    0  0.00  0.00    0    0  0.00
H2ST     0  0.00  0.00    0    0  0.00
HBBS     0  0.00  0.00    0    0  0.00
HDAM     0  0.00  1.00    0    0  0.00
HDAMC    0  0.00  1.00    0    0  0.00
HDLZ     0  0.00  1.00    0    0  0.00
HOBO     0  0.00  0.00    0    0  0.00
HOBOX    0  0.00  0.00    0    0  0.05
HPHS     0  0.00  0.05    0    0  0.00
HPHSC    0  0.00  0.05    0    0  0.00
HROR     0  0.00  1.00    0    0  0.00
HRORC    0  0.00  1.00    0    0  0.00
HYHP     0  0.00  0.00    0    0  0.00
ICEN     0  0.00  0.00    0    0  0.00
ICENX    0  0.00  0.00    0    0  0.00
MCFC     0  0.00  0.00    0    0  0.00
PAFC     0  0.00  0.00    0    0  0.00
P2BS     0  0.00  0.00    0    0  0.00
P2GS     0  0.00  0.00    0    0  0.00
P2HT     0  0.00  0.00    0    0  0.00
PEFC     0  0.00  0.00    0    0  0.00
PEME     0  0.00  0.00    0    0  0.00
PHOT     1  0.00  0.00    0    0  0.00
REFC     0  0.00  0.00    0    0  0.00
REHE     0  0.00  0.00    0    0  0.00
SCSP     1  0.00  0.00    0    0  0.00
SOFC     1  0.00  0.00    0    0  0.00
SOTH     1  0.00  0.00    0    0  0.00
SOXE     0  0.00  0.00    0    0  0.00
STUR     0  0.00  0.00    0    0  0.00
STURX    0  0.00  0.00    0    0  0.00
THMS     0  1.00  0.00    0    0  0.00
WAVE     0  0.00  1.00    0    0  0.00
WHEN     0  0.00  0.00    0    0  1.00
WTOF     0  0.00  0.00    0    1  0.00
WSHP     0  0.00  0.00    0    0  0.00
WTON     0  0.00  0.00    0    1  0.00  , 'FR':         AIR  AMO   BIO   ELE   GAS  GEO    HRD  HYD    LIG   NUC   OIL   OTH  \
ABHP   0.05  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ALFC   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ALKE   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ASHP   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
BATS   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
BEVS   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
BSPG   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
CAES   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
COMC   0.00  0.0  0.03  0.00  0.10    0  0.020    0  0.000  0.80  0.05  0.00
COMCX  0.00  0.0  0.10  0.00  0.15    0  0.050    0  0.000  0.65  0.05  0.00
DMFC   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  1.00
GETH   0.00  0.0  0.00  0.00  0.00    1  0.000    0  0.000  0.00  0.00  0.00
GSHP   0.00  0.0  0.00  0.00  0.00    1  0.000    0  0.000  0.00  0.00  0.00
GTUR   0.00  0.0  0.05  0.00  0.40    0  0.000    0  0.000  0.50  0.05  0.00
GTURX  0.00  0.0  0.10  0.00  0.35    0  0.000    0  0.000  0.50  0.05  0.00
H2ST   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HBBS   0.00  0.0  1.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HDAM   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HDAMC  0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HDLZ   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HOBO   0.00  0.0  0.20  0.00  0.45    0  0.005    0  0.005  0.00  0.30  0.04
HOBOX  0.00  0.0  0.20  0.00  0.25    0  0.050    0  0.000  0.00  0.45  0.00
HPHS   0.00  0.0  0.00  0.95  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HPHSC  0.00  0.0  0.00  0.95  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HROR   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HRORC  0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
HYHP   0.00  0.0  0.10  0.90  0.00    0  0.000    0  0.000  0.00  0.00  0.00
ICEN   0.00  0.0  0.05  0.00  0.25    0  0.100    0  0.000  0.00  0.60  0.00
ICENX  0.00  0.0  0.10  0.00  0.30    0  0.150    0  0.000  0.00  0.45  0.00
MCFC   0.00  0.0  0.10  0.00  0.70    0  0.000    0  0.000  0.00  0.20  0.00
PAFC   0.00  0.0  0.10  0.00  0.70    0  0.000    0  0.000  0.00  0.20  0.00
P2BS   0.00  0.1  0.00  0.90  0.00    0  0.000    0  0.000  0.00  0.00  0.00
P2GS   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
P2HT   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
PEFC   0.00  0.0  0.10  0.10  0.75    0  0.000    0  0.000  0.00  0.05  0.00
PEME   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
PHOT   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
REFC   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
REHE   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
SCSP   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
SOFC   0.00  0.0  0.10  0.10  0.75    0  0.000    0  0.000  0.00  0.05  0.00
SOTH   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
SOXE   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
STUR   0.00  0.0  0.05  0.00  0.05    0  0.050    0  0.050  0.80  0.00  0.00
STURX  0.00  0.0  0.05  0.00  0.10    0  0.100    0  0.100  0.65  0.00  0.00
THMS   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WAVE   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WHEN   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WTOF   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WSHP   0.00  0.0  0.00  1.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00
WTON   0.00  0.0  0.00  0.00  0.00    0  0.000    0  0.000  0.00  0.00  0.00

       PEA  SUN   THE   WAT  WHT  WIN   WST
ABHP     0    0  0.95  0.00    0    0  0.00
ALFC     0    0  0.00  0.00    0    0  0.00
ALKE     0    0  0.00  0.00    0    0  0.00
ASHP     0    0  0.00  0.00    0    0  0.00
BATS     0    0  0.00  0.00    0    0  0.00
BEVS     0    0  0.00  0.00    0    0  0.00
BSPG     0    1  0.00  0.00    0    0  0.00
CAES     0    0  0.00  0.00    0    0  0.00
COMC     0    0  0.00  0.00    0    0  0.00
COMCX    0    0  0.00  0.00    0    0  0.00
DMFC     0    0  0.00  0.00    0    0  0.00
GETH     0    0  0.00  0.00    0    0  0.00
GSHP     0    0  0.00  0.00    0    0  0.00
GTUR     0    0  0.00  0.00    0    0  0.00
GTURX    0    0  0.00  0.00    0    0  0.00
H2ST     0    0  0.00  0.00    0    0  0.00
HBBS     0    0  0.00  0.00    0    0  0.00
HDAM     0    0  0.00  1.00    0    0  0.00
HDAMC    0    0  0.00  1.00    0    0  0.00
HDLZ     0    0  0.00  1.00    0    0  0.00
HOBO     0    0  0.00  0.00    0    0  0.00
HOBOX    0    0  0.00  0.00    0    0  0.05
HPHS     0    0  0.00  0.05    0    0  0.00
HPHSC    0    0  0.00  0.05    0    0  0.00
HROR     0    0  0.00  1.00    0    0  0.00
HRORC    0    0  0.00  1.00    0    0  0.00
HYHP     0    0  0.00  0.00    0    0  0.00
ICEN     0    0  0.00  0.00    0    0  0.00
ICENX    0    0  0.00  0.00    0    0  0.00
MCFC     0    0  0.00  0.00    0    0  0.00
PAFC     0    0  0.00  0.00    0    0  0.00
P2BS     0    0  0.00  0.00    0    0  0.00
P2GS     0    0  0.00  0.00    0    0  0.00
P2HT     0    0  0.00  0.00    0    0  0.00
PEFC     0    0  0.00  0.00    0    0  0.00
PEME     0    0  0.00  0.00    0    0  0.00
PHOT     0    1  0.00  0.00    0    0  0.00
REFC     0    0  0.00  0.00    0    0  0.00
REHE     0    0  0.00  0.00    0    0  0.00
SCSP     0    1  0.00  0.00    0    0  0.00
SOFC     0    0  0.00  0.00    0    0  0.00
SOTH     0    1  0.00  0.00    0    0  0.00
SOXE     0    0  0.00  0.00    0    0  0.00
STUR     0    0  0.00  0.00    0    0  0.00
STURX    0    0  0.00  0.00    0    0  0.00
THMS     0    0  1.00  0.00    0    0  0.00
WAVE     0    0  0.00  1.00    0    0  0.00
WHEN     0    0  0.00  0.00    1    0  0.00
WTOF     0    0  0.00  0.00    0    1  0.00
WSHP     0    0  0.00  0.00    0    0  0.00
WTON     0    0  0.00  0.00    0    1  0.00  , 'DE':         AIR   AMO   BIO   ELE   GAS  GEO    HRD  HYD    LIG  NUC   OIL   OTH  \
ABHP   0.05  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
ALFC   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
ALKE   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
ASHP   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
BATS   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
BEVS   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
BSPG   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
CAES   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
COMC   0.00  0.00  0.08  0.00  0.85    0  0.050    0  0.020    0  0.00  0.00
COMCX  0.00  0.00  0.20  0.00  0.70    0  0.050    0  0.050    0  0.00  0.00
DMFC   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  1.00
GETH   0.00  0.00  0.00  0.00  0.00    1  0.000    0  0.000    0  0.00  0.00
GSHP   0.00  0.00  0.00  0.00  0.00    1  0.000    0  0.000    0  0.00  0.00
GTUR   0.00  0.00  0.05  0.00  0.80    0  0.000    0  0.000    0  0.15  0.00
GTURX  0.00  0.00  0.15  0.00  0.70    0  0.000    0  0.000    0  0.15  0.00
H2ST   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HBBS   0.00  0.00  1.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HDAM   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HDAMC  0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HDLZ   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HOBO   0.00  0.00  0.17  0.00  0.55    0  0.015    0  0.015    0  0.24  0.01
HOBOX  0.00  0.00  0.25  0.00  0.50    0  0.100    0  0.050    0  0.05  0.00
HPHS   0.00  0.00  0.00  0.95  0.00    0  0.000    0  0.000    0  0.00  0.00
HPHSC  0.00  0.00  0.00  0.95  0.00    0  0.000    0  0.000    0  0.00  0.00
HROR   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HRORC  0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
HYHP   0.00  0.00  0.15  0.85  0.00    0  0.000    0  0.000    0  0.00  0.00
ICEN   0.00  0.00  0.05  0.00  0.25    0  0.100    0  0.050    0  0.55  0.00
ICENX  0.00  0.00  0.10  0.00  0.30    0  0.150    0  0.100    0  0.35  0.00
MCFC   0.00  0.00  0.15  0.00  0.80    0  0.000    0  0.000    0  0.05  0.00
PAFC   0.00  0.00  0.15  0.00  0.80    0  0.000    0  0.000    0  0.05  0.00
P2BS   0.00  0.15  0.00  0.85  0.00    0  0.000    0  0.000    0  0.00  0.00
P2GS   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
P2HT   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
PEFC   0.00  0.00  0.15  0.10  0.75    0  0.000    0  0.000    0  0.00  0.00
PEME   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
PHOT   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
REFC   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
REHE   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
SCSP   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
SOFC   0.00  0.00  0.10  0.10  0.75    0  0.000    0  0.000    0  0.05  0.00
SOTH   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
SOXE   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
STUR   0.00  0.00  0.05  0.00  0.10    0  0.400    0  0.450    0  0.00  0.00
STURX  0.00  0.00  0.05  0.00  0.15    0  0.500    0  0.300    0  0.00  0.00
THMS   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WAVE   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WHEN   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WTOF   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WSHP   0.00  0.00  0.00  1.00  0.00    0  0.000    0  0.000    0  0.00  0.00
WTON   0.00  0.00  0.00  0.00  0.00    0  0.000    0  0.000    0  0.00  0.00

       PEA  SUN   THE   WAT  WHT  WIN   WST
ABHP     0    0  0.95  0.00    0    0  0.00
ALFC     0    0  0.00  0.00    0    0  0.00
ALKE     0    0  0.00  0.00    0    0  0.00
ASHP     0    0  0.00  0.00    0    0  0.00
BATS     0    0  0.00  0.00    0    0  0.00
BEVS     0    0  0.00  0.00    0    0  0.00
BSPG     0    1  0.00  0.00    0    0  0.00
CAES     0    0  0.00  0.00    0    0  0.00
COMC     0    0  0.00  0.00    0    0  0.00
COMCX    0    0  0.00  0.00    0    0  0.00
DMFC     0    0  0.00  0.00    0    0  0.00
GETH     0    0  0.00  0.00    0    0  0.00
GSHP     0    0  0.00  0.00    0    0  0.00
GTUR     0    0  0.00  0.00    0    0  0.00
GTURX    0    0  0.00  0.00    0    0  0.00
H2ST     0    0  0.00  0.00    0    0  0.00
HBBS     0    0  0.00  0.00    0    0  0.00
HDAM     0    0  0.00  1.00    0    0  0.00
HDAMC    0    0  0.00  1.00    0    0  0.00
HDLZ     0    0  0.00  1.00    0    0  0.00
HOBO     0    0  0.00  0.00    0    0  0.00
HOBOX    0    0  0.00  0.00    0    0  0.05
HPHS     0    0  0.00  0.05    0    0  0.00
HPHSC    0    0  0.00  0.05    0    0  0.00
HROR     0    0  0.00  1.00    0    0  0.00
HRORC    0    0  0.00  1.00    0    0  0.00
HYHP     0    0  0.00  0.00    0    0  0.00
ICEN     0    0  0.00  0.00    0    0  0.00
ICENX    0    0  0.00  0.00    0    0  0.00
MCFC     0    0  0.00  0.00    0    0  0.00
PAFC     0    0  0.00  0.00    0    0  0.00
P2BS     0    0  0.00  0.00    0    0  0.00
P2GS     0    0  0.00  0.00    0    0  0.00
P2HT     0    0  0.00  0.00    0    0  0.00
PEFC     0    0  0.00  0.00    0    0  0.00
PEME     0    0  0.00  0.00    0    0  0.00
PHOT     0    1  0.00  0.00    0    0  0.00
REFC     0    0  0.00  0.00    0    0  0.00
REHE     0    0  0.00  0.00    0    0  0.00
SCSP     0    1  0.00  0.00    0    0  0.00
SOFC     0    0  0.00  0.00    0    0  0.00
SOTH     0    1  0.00  0.00    0    0  0.00
SOXE     0    0  0.00  0.00    0    0  0.00
STUR     0    0  0.00  0.00    0    0  0.00
STURX    0    0  0.00  0.00    0    0  0.00
THMS     0    0  1.00  0.00    0    0  0.00
WAVE     0    0  0.00  1.00    0    0  0.00
WHEN     0    0  0.00  0.00    1    0  0.00
WTOF     0    0  0.00  0.00    0    1  0.00
WSHP     0    0  0.00  0.00    0    0  0.00
WTON     0    0  0.00  0.00    0    1  0.00  , 'NL':         AIR  AMO   BIO   ELE    GAS  GEO     HRD  HYD     LIG  NUC   OIL  \
ABHP   0.05  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
ALFC   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
ALKE   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
ASHP   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
BATS   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
BEVS   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
BSPG   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
CAES   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
COMC   0.00  0.0  0.10  0.00  0.850    0  0.0500    0  0.0000    0  0.00
COMCX  0.00  0.0  0.20  0.00  0.750    0  0.0500    0  0.0000    0  0.00
DMFC   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
GETH   0.00  0.0  0.00  0.00  0.000    1  0.0000    0  0.0000    0  0.00
GSHP   0.00  0.0  0.00  0.00  0.000    1  0.0000    0  0.0000    0  0.00
GTUR   0.00  0.0  0.05  0.00  0.850    0  0.0000    0  0.0000    0  0.10
GTURX  0.00  0.0  0.10  0.00  0.750    0  0.0000    0  0.0000    0  0.15
H2ST   0.00  0.0  0.00  1.00  0.000    0  0.0000    0  0.0000    0  0.00
HBBS   0.00  0.0  1.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00
HDAM   0.00  0.0  0.00  0.00  0.000    0  0.0000    0  0.0000    0  0.00

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables.
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [62]:
print (f"Name of the DispaSET Unleash folder:                       {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                       {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                 {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                 {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:            {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                         {zone_names}\n")
print (f"Target year:                                               {data_target_year}\n")
print (f"Name of the Power Plant DataFrames (dictionary):           {list(power_plants_dfs_dict.keys())}\n")
print (f"Name of the zone_names_equivalences_dictionary):           {[value['Acronym'] for value in selected_zone_names_equivalences_dict.values()]}\n")
print (f"Name of the Overall Fuel Technology Match DataFrame:       overal_fuel_technologies_match_df\n")
print (f"Name of the Fuel Technology Match Dictionary:              fuel_technologies_match_dict\n")

Name of the DispaSET Unleash folder:                       Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                       /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                 PowerPlants

Path to the Power Plants Base data folder:                 /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                PowerPlants

Path to the Power Plants_Pypsa Raw data folder:            /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:       PowerPlants

Path to the Power Plants_Pypsa Formated data folder:       /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                         ['BE', 'FR', 'DE', 'NL', 'UK']

Target year:                                               2050

Name of the Power Plant DataFrames (dictionary):           ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

Name of the zone_names_equivalences_dictionary):           [['  '], ['  '], ['  '], ['  '], ['GB']]

Name of the Overall Fuel Technology Match DataFrame:       overal_fuel_technologies_match_df

Name of the Fuel Technology Match Dictionary:              fuel_technologies_match_dict

<div style="background-color: black;">
    <hr style="border: 2px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    7. Raw Data Uploading
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The nodal capacities PyPSA outputs are converted into data frame for its management.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [63]:
# 1. ************************************************************************************ Set the nodal capacities data 
file_path = os.path.join(power_plants_pypsa_raw_data_folder_path, "nodal_capacities.csv")
nodal_capacities_df = pd.read_csv(file_path)

# 2. ************************************************************************************************************* Done
print(nodal_capacities_df)
nodal_capacities_df

              cluster Unnamed: 1                               Unnamed: 2  \
0                  ll        NaN                                      NaN
1                 opt        NaN                                      NaN
2    planning_horizon        NaN                                      NaN
3          generators        NaN                                     coal
4          generators        NaN                                  lignite
..                ...        ...                                      ...
639            stores      NL1 0  residential urban decentral water tanks
640            stores      NL1 0               services rural water tanks
641            stores      NL1 0     services urban decentral water tanks
642            stores      NL1 0                            solid biomass
643            stores      NL1 0                urban central water tanks

                       6                 6.1                    6.2
0                   vopt                vopt                   vopt
1     1H-T-H-B-I-A-dist1  1H-T-H-B-I-A-dist1     1H-T-H-B-I-A-dist1
2                   2030                2040                   2050
3     16142.062287845038  43.385395809824374  6.751345150558055e-05
4      16733.20844217989   25.83309882120808  9.109242711250394e-05
..                   ...                 ...                    ...
639   0.1566953462354908   1.170379650802651     1.1816026156188018
640  0.11535139556354965  13.568632438446299      13.57676239020483
641  0.13093036423706436   0.451523589032377     0.4624791693633672
642   17227013.353615463   19944981.65140599      22871222.67498187
643   1528037.4068906663  2221612.5014556665     2393605.7563187466

[644 rows x 6 columns]

,cluster,Unnamed: 1,Unnamed: 2,6,6.1,6.2
0,ll,NaN,NaN,vopt,vopt,vopt
1,opt,NaN,NaN,1H-T-H-B-I-A-dist1,1H-T-H-B-I-A-dist1,1H-T-H-B-I-A-dist1
2,planning_horizon,NaN,NaN,2030,2040,2050
3,generators,NaN,coal,16142.062287845038,43.385395809824374,6.751345150558055e-05
4,generators,NaN,lignite,16733.20844217989,25.83309882120808,9.109242711250394e-05
...,...,...,...,...,...,...
639,stores,NL1 0,residential urban decentral water tanks,0.1566953462354908,1.170379650802651,1.1816026156188018
640,stores,NL1 0,services rural water tanks,0.11535139556354965,13.568632438446299,13.57676239020483
641,stores,NL1 0,services urban decentral water tanks,0.13093036423706436,0.451523589032377,0.4624791693633672
642,stores,NL1 0,solid biomass,17227013.353615463,19944981.65140599,22871222.67498187
643,stores,NL1 0,urban central water tanks,1528037.4068906663,2221612.5014556665,2393605.7563187466

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Setting the target year row as columns index.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [64]:
# 1.  ------------------------------------------------------------------------ Convert year variable to numeric integer
target_int = int(data_target_year)

# 2. ----------------------------------------------------------- Convert row to numeric where possible, check for match
def row_contains_target_year(row):
    # convert row to numeric where possible
    numeric_row = pd.to_numeric(row, errors='coerce')
    if (numeric_row == target_int).any():
        return True
        
# 2.1. -------------------------------------------------------------------------------- fallback: check string equality
    str_row = row.astype(str).str.strip()
    if (str_row == data_target_year).any():
        return True
    return False

# 3. ------------------------------------------------------------------------------------- Find the first matching row 
first_year_row_index = nodal_capacities_df.apply(row_contains_target_year, axis=1).idxmax()

# 4. ------------------------------------------------------------------------------------- Use that row as new headers 
new_columns = nodal_capacities_df.loc[first_year_row_index].astype(str).tolist()

# 5. -------------------------------------------------------------------------------- Drop the row and set new headers 
df_with_new_headers = nodal_capacities_df.drop(first_year_row_index).copy()
df_with_new_headers.columns = new_columns
nodal_capacities_df = df_with_new_headers.reset_index(drop=True)

# 6. ------------------------------------------------------------------------------------------------------------ Done 
nodal_capacities_df

,planning_horizon,nan,nan,2030,2040,2050
0,ll,NaN,NaN,vopt,vopt,vopt
1,opt,NaN,NaN,1H-T-H-B-I-A-dist1,1H-T-H-B-I-A-dist1,1H-T-H-B-I-A-dist1
2,generators,NaN,coal,16142.062287845038,43.385395809824374,6.751345150558055e-05
3,generators,NaN,lignite,16733.20844217989,25.83309882120808,9.109242711250394e-05
4,generators,NaN,load,1000000.0,1000000.0,1000000.0
...,...,...,...,...,...,...
638,stores,NL1 0,residential urban decentral water tanks,0.1566953462354908,1.170379650802651,1.1816026156188018
639,stores,NL1 0,services rural water tanks,0.11535139556354965,13.568632438446299,13.57676239020483
640,stores,NL1 0,services urban decentral water tanks,0.13093036423706436,0.451523589032377,0.4624791693633672
641,stores,NL1 0,solid biomass,17227013.353615463,19944981.65140599,22871222.67498187
642,stores,NL1 0,urban central water tanks,1528037.4068906663,2221612.5014556665,2393605.7563187466

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Naming undefined columns.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [65]:
# 1. ---------------------------------------------- Check if a column label is a placeholder (NaN, empty, or 'Unnamed')
def is_unnamed_label(label):
    """Return True for NaN/empty/'nan'/'Unnamed...' column labels."""
    if pd.isna(label):
        return True
    s = str(label).strip()
    if s == '' or s.lower() == 'nan':
        return True
    if re.match(r'Unnamed', s):
        return True
    return False

# 2. ------------------------------------------ Assuming nodal_capacities_df is the DataFrame and zone_names is defined
cols = list(nodal_capacities_df.columns)
new_cols = []
zone_count = 0
tech_count = 0

for i, col_label in enumerate(cols):
    if is_unnamed_label(col_label):
        
# 2.1. --------------------------------------------------- read the column by position to avoid issues with NaN labels 
        col_series = nodal_capacities_df.iloc[:, i].dropna().astype(str)

# 2.2. ---------------------------------------------------------------------- find any zone substring (case-sensitive) 
        found_zone = False
        for val in col_series:
            
# 2.2.1. --------------------------------------------------------------------------------- skip obvious 'nan' strings
            if val.strip().lower() == 'nan':
                continue
            for zone in zone_names:
                if zone in val:      # case-sensitive substring match
                    found_zone = True
                    break
            if found_zone:
                break

        if found_zone:
            zone_count += 1
            new_name = 'zone' if zone_count == 1 else f'zone_{zone_count}'
        else:
            tech_count += 1
            new_name = 'tech' if tech_count == 1 else f'tech_{tech_count}'

        new_cols.append(new_name)
    else:
        new_cols.append(col_label)

# 3. -------------------------------------------------------------------- apply the new column names determined above 
nodal_capacities_df.columns = new_cols

# 4. --------------------------------------------------- Change the header of the first column (index 0) to 'Element' 
nodal_capacities_df.columns.values[0] = 'Element'

# 5. ---------------------------------------------------------------------------------------------------------- Done 
print(list(zip(cols, nodal_capacities_df.columns)))
nodal_capacities_df

[('planning_horizon', 'Element'), ('nan', 'zone'), ('nan', 'tech'), ('2030', '2030'), ('2040', '2040'), ('2050', '2050')]

,Element,zone,tech,2030,2040,2050
0,ll,NaN,NaN,vopt,vopt,vopt
1,opt,NaN,NaN,1H-T-H-B-I-A-dist1,1H-T-H-B-I-A-dist1,1H-T-H-B-I-A-dist1
2,generators,NaN,coal,16142.062287845038,43.385395809824374,6.751345150558055e-05
3,generators,NaN,lignite,16733.20844217989,25.83309882120808,9.109242711250394e-05
4,generators,NaN,load,1000000.0,1000000.0,1000000.0
...,...,...,...,...,...,...
638,stores,NL1 0,residential urban decentral water tanks,0.1566953462354908,1.170379650802651,1.1816026156188018
639,stores,NL1 0,services rural water tanks,0.11535139556354965,13.568632438446299,13.57676239020483
640,stores,NL1 0,services urban decentral water tanks,0.13093036423706436,0.451523589032377,0.4624791693633672
641,stores,NL1 0,solid biomass,17227013.353615463,19944981.65140599,22871222.67498187
642,stores,NL1 0,urban central water tanks,1528037.4068906663,2221612.5014556665,2393605.7563187466

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Filtering all the rows not related with the selected countries.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [66]:
# 1. ------------------------------------------------ Build acronym → canonical zone mapping from the equivalences dict
acronym_to_zone = {}

for zone, data in zone_names_equivalences_dict.items():
    for ac in data.get("Acronym", []):
        ac = ac.strip()
        if ac:  # ignore empty strings
            acronym_to_zone[ac] = zone

# 2. ---------------------------------------------- Function to check if a row contains a zone OR an equivalent acronym
def row_contains_zone_or_equivalent(row, zones, acronym_map):
    for val in row.astype(str):
        # 2.1 Direct zone match
        for zone in zones:
            if zone in val:
                return True

        # 2.2 Acronym match
        for ac in acronym_map:
            if ac in val:
                return True

    return False

# 3. ----------------------------------------------------------------------------- Apply row filtering to the DataFrame
mask = nodal_capacities_df.apply(
    lambda row: row_contains_zone_or_equivalent(
        row,
        zone_names,
        acronym_to_zone
    ),
    axis=1
)

nodal_capacities_df = nodal_capacities_df[mask].reset_index(drop=True)

# 5. ------------------------------------------------------------------------------------------------------------- Done 
nodal_capacities_df

,Element,zone,tech,2030,2040,2050
0,generators,BE1 0,gas,39563.050946355725,39563.050946355725,39563.050946355725
1,generators,BE1 0,load,31000000.0,30000000.0,29000000.0
2,generators,BE1 0,offwind,2261.8,2261.8,1549.8000000000002
3,generators,BE1 0,offwind-ac,1738.1990459051528,1738.1990459051528,1738.1990459051528
4,generators,BE1 0,offwind-dc,1999.999106794187,4000.000445154381,4712.000935360555
...,...,...,...,...,...,...
613,stores,NL1 0,residential urban decentral water tanks,0.1566953462354908,1.170379650802651,1.1816026156188018
614,stores,NL1 0,services rural water tanks,0.11535139556354965,13.568632438446299,13.57676239020483
615,stores,NL1 0,services urban decentral water tanks,0.13093036423706436,0.451523589032377,0.4624791693633672
616,stores,NL1 0,solid biomass,17227013.353615463,19944981.65140599,22871222.67498187
617,stores,NL1 0,urban central water tanks,1528037.4068906663,2221612.5014556665,2393605.7563187466

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Combining the columnes 'Element' and 'tech' to adequate with the Technologies Dictionary nomenclature.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [67]:
# 1. -------------------------------------------------------------------------- Join 'Element' and 'tech' with a space 
nodal_capacities_df['tech'] = nodal_capacities_df['Element'] + ' ' + nodal_capacities_df['tech']

# 2. --------------------------------------------------------------------------------------- Drop the 'Element' column 
nodal_capacities_df = nodal_capacities_df.drop(columns=['Element'])

# 3. ----------------------------------------------------------------------------------------------------------- Donde 
nodal_capacities_df

,zone,tech,2030,2040,2050
0,BE1 0,generators gas,39563.050946355725,39563.050946355725,39563.050946355725
1,BE1 0,generators load,31000000.0,30000000.0,29000000.0
2,BE1 0,generators offwind,2261.8,2261.8,1549.8000000000002
3,BE1 0,generators offwind-ac,1738.1990459051528,1738.1990459051528,1738.1990459051528
4,BE1 0,generators offwind-dc,1999.999106794187,4000.000445154381,4712.000935360555
...,...,...,...,...,...
613,NL1 0,stores residential urban decentral water tanks,0.1566953462354908,1.170379650802651,1.1816026156188018
614,NL1 0,stores services rural water tanks,0.11535139556354965,13.568632438446299,13.57676239020483
615,NL1 0,stores services urban decentral water tanks,0.13093036423706436,0.451523589032377,0.4624791693633672
616,NL1 0,stores solid biomass,17227013.353615463,19944981.65140599,22871222.67498187
617,NL1 0,stores urban central water tanks,1528037.4068906663,2221612.5014556665,2393605.7563187466

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Filtering the target year.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [68]:
# 1. ----------------------------------------------------------------------------------------- list of columns to keep 
cols_to_keep = [col for col in nodal_capacities_df.columns 
                if str(col).startswith("zone") 
                or str(col).startswith("tech") 
                or str(col) == str(data_target_year)]

# 2. ------------------------------------------------------------------------------------------------ filter dataframe 
nodal_capacities_df = nodal_capacities_df[cols_to_keep].copy()

# 3. ------------------------------------------------------------------------------------------------------------ Done 
nodal_capacities_df

      zone                                            tech                2050
0    BE1 0                                  generators gas  39563.050946355725
1    BE1 0                                 generators load          29000000.0
2    BE1 0                              generators offwind  1549.8000000000002
3    BE1 0                           generators offwind-ac  1738.1990459051528
4    BE1 0                           generators offwind-dc   4712.000935360555
..     ...                                             ...                 ...
613  NL1 0  stores residential urban decentral water tanks  1.1816026156188018
614  NL1 0               stores services rural water tanks   13.57676239020483
615  NL1 0     stores services urban decentral water tanks  0.4624791693633672
616  NL1 0                            stores solid biomass   22871222.67498187
617  NL1 0                stores urban central water tanks  2393605.7563187466

[618 rows x 3 columns]

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left:0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Cleaning the zone names.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [69]:
# 1. ------------------------------------------------------- Replace cell with zone using names or acronym equivalences
def replace_with_zone_or_acronym(cell, zone_names, zone_equiv_dict):
    cell_str = str(cell)  # ensure string for substring checks

# 1.1 ----------------------------------------------------------------------------- First: direct match with zone names
    for zone in zone_names:
        if zone in cell_str:
            return zone

# 1.2 ------------------------------------------------------------------------ Second: match using acronym equivalences
    for zone_key, zone_data in zone_equiv_dict.items():
        acronyms = zone_data.get("Acronym", [])
        for ac in acronyms:
            ac = ac.strip()
            if ac and ac in cell_str:
                return zone_key

# 1.3 -------------------------------------------------------------------------------------------------- No match found
    return cell

# 2. ---------------------------------------------------------------------------------- Apply only to the 'zone' column
nodal_capacities_df["zone"] = nodal_capacities_df["zone"].apply(
    lambda x: replace_with_zone_or_acronym(
        x,
        zone_names,
        zone_names_equivalences_dict
    )
)

# 3. ------------------------------------------------------------------------------------------------------------- Done
nodal_capacities_df

    zone                                            tech                2050
0     BE                                  generators gas  39563.050946355725
1     BE                                 generators load          29000000.0
2     BE                              generators offwind  1549.8000000000002
3     BE                           generators offwind-ac  1738.1990459051528
4     BE                           generators offwind-dc   4712.000935360555
..   ...                                             ...                 ...
613   NL  stores residential urban decentral water tanks  1.1816026156188018
614   NL               stores services rural water tanks   13.57676239020483
615   NL     stores services urban decentral water tanks  0.4624791693633672
616   NL                            stores solid biomass   22871222.67498187
617   NL                stores urban central water tanks  2393605.7563187466

[618 rows x 3 columns]

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Dividing the capacities file into the selected countries.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [70]:
# 1. --------------------------------------------------------------- Create dictionary to store the derived DataFrames 
nodal_capacities_dfs_dict = {}
for zone in zone_names:
    
# 1.1. ------------------------------------------------------------- Filter rows where 'zone' matches the current zone
    df_zone = nodal_capacities_df[nodal_capacities_df['zone'] == zone].copy()
    
# 1.2. ------------------------------------------------------------------- Save into dictionary with a descriptive key
    nodal_capacities_dfs_dict[f"{zone}_nodal_capacities_df"] = df_zone

# 2. ------------------------------------------------------------------------------------------------------------ Done 
nodal_capacities_dfs_dict

{'BE_nodal_capacities_df':     zone                                            tech                2050
 0     BE                                  generators gas  39563.050946355725
 1     BE                                 generators load          29000000.0
 2     BE                              generators offwind  1549.8000000000002
 3     BE                           generators offwind-ac  1738.1990459051528
 4     BE                           generators offwind-dc   4712.000935360555
 ..   ...                                             ...                 ...
 548   BE  stores residential urban decentral water tanks  11.697425589410711
 549   BE               stores services rural water tanks  1.6064024732106708
 550   BE     stores services urban decentral water tanks  0.5102403429975626
 551   BE                            stores solid biomass   26476318.32756942
 552   BE                stores urban central water tanks  1020676.4921655245

 [104 rows x 3 columns],
 'FR_nodal_capacities_df':     zone                                            tech                 2050
 30    FR                                  generators gas   104414.45841838072
 31    FR                                 generators load           29000000.0
 32    FR                              generators offwind                480.0
 33    FR                           generators offwind-ac    24631.59540566057
 34    FR                           generators offwind-dc   4617.9103327755765
 ..   ...                                             ...                  ...
 574   FR  stores residential urban decentral water tanks   0.5706341656515044
 575   FR               stores services rural water tanks  0.44943354708984007
 576   FR     stores services urban decentral water tanks  0.43122130122395874
 577   FR                            stores solid biomass    152193495.6324154
 578   FR                stores urban central water tanks   3573412.9924988006

 [105 rows x 3 columns],
 'DE_nodal_capacities_df':     zone                                            tech                2050
 15    DE                                  generators gas   266384.4541222907
 16    DE                                 generators load          29000000.0
 17    DE                              generators offwind              4846.0
 18    DE                           generators offwind-ac   5072.330383475864
 19    DE                           generators offwind-dc  21136.976422195796
 ..   ...                                             ...                 ...
 561   DE  stores residential urban decentral water tanks     2052.9744601283
 562   DE               stores services rural water tanks   157.4396142698585
 563   DE     stores services urban decentral water tanks   165.5623441287704
 564   DE                            stores solid biomass   192110868.5689423
 565   DE                stores urban central water tanks   5528765.805511597

 [107 rows x 3 columns],
 'NL_nodal_capacities_df':     zone                                            tech                2050
 74    NL                                  generators gas    75342.2763646117
 75    NL                                 generators load          29000000.0
 76    NL                              generators offwind              2214.0
 77    NL                           generators offwind-ac    3218.26223653978
 78    NL                           generators offwind-dc   50152.60768756087
 ..   ...                                             ...                 ...
 613   NL  stores residential urban decentral water tanks  1.1816026156188018
 614   NL               stores services rural water tanks   13.57676239020483
 615   NL     stores services urban decentral water tanks  0.4624791693633672
 616   NL                            stores solid biomass   22871222.67498187
 617   NL                stores urban central water tanks  2393605.7563187466

 [99 rows x 3 columns],
 'UK_nodal_capacities_df':     zone                                            tech                 2050
 45    UK                                  generators gas    312452.0105837874
 46    UK                                 generators load           29000000.0
 47    UK                              generators offwind    4243.306752243057
 48    UK                           generators offwind-ac    28632.97672762162
 49    UK                           generators offwind-dc  0.16804896762482277
 ..   ...                                             ...                  ...
 600   UK  stores residential urban decentral water tanks   33.979671779330786
 601   UK               stores services rural water tanks   3.9485487692675014
 602   UK     stores services urban decentral water tanks   1.3395133588205572
 603   UK                            stores solid biomass    877564.4648121595
 604   UK                stores urban central water tanks    82582.74539850504

 [203 rows x 3 columns]}

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Aggregating repeated tech items.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [71]:
# 1. --------------------------------------------------- Convert the integer year to a string to match the column name 
data_target_year_str = str(data_target_year)

# 2. ------------------------------------------------- Create an empty DataFrame to store the rows that will be erased 
erased_rows_df = pd.DataFrame()

for df_name in nodal_capacities_dfs_dict:
    df = nodal_capacities_dfs_dict[df_name]

# 2.1. ------------------------------------------------ Convert the target year column to numeric, ignoring the header
    df[data_target_year_str] = pd.to_numeric(df[data_target_year_str], errors='coerce')

# 2.2. ------------------------------ Identify duplicate rows based on 'zone' and 'tech', keeping the first occurrence
    duplicates = df.duplicated(subset=['zone', 'tech'], keep='first')

# 2.3. ------------------------------------------------ Select the rows that are duplicates (i.e., those to be erased)
    erased_part = df[duplicates].copy()

# 2.4. ----------------------------------------------------------------- Append these erased rows to the new DataFrame
    erased_rows_df = pd.concat([erased_rows_df, erased_part], ignore_index=True)

# 2.5. --------------------------------------------------- Group by 'zone' and 'tech', then sum the target year column
    grouped_df = df.groupby(['zone', 'tech'], as_index=False)[data_target_year_str].sum()

# 2.6. ------------------------------------------------------------ Update the dictionary with the processed DataFrame
    nodal_capacities_dfs_dict[df_name] = grouped_df

# 3. ----------------------------------------------------------------------------------------------- Verify the result 
print("\n--- Processed DataFrames ---")
for df_name, df in nodal_capacities_dfs_dict.items():
    print(f"\nDataFrame: {df_name}")
    print(df)

# 4. ------------------------------------------------------------------------------------------------------------ Done 
print("\n--- Erased Rows DataFrame ---")
print(erased_rows_df)

--- Processed DataFrames ---

DataFrame: BE_nodal_capacities_df
    zone                                            tech          2050
0     BE                                  generators gas  3.956305e+04
1     BE                                 generators load  2.900000e+07
2     BE                              generators offwind  1.549800e+03
3     BE                           generators offwind-ac  1.738199e+03
4     BE                           generators offwind-dc  4.712001e+03
..   ...                                             ...           ...
99    BE  stores residential urban decentral water tanks  1.169743e+01
100   BE               stores services rural water tanks  1.606402e+00
101   BE     stores services urban decentral water tanks  5.102403e-01
102   BE                            stores solid biomass  2.647632e+07
103   BE                stores urban central water tanks  1.020676e+06

[104 rows x 3 columns]

DataFrame: FR_nodal_capacities_df
    zone                                            tech          2050
0     FR                                  generators gas  1.044145e+05
1     FR                                 generators load  2.900000e+07
2     FR                              generators offwind  4.800000e+02
3     FR                           generators offwind-ac  2.463160e+04
4     FR                           generators offwind-dc  4.617910e+03
..   ...                                             ...           ...
100   FR  stores residential urban decentral water tanks  5.706342e-01
101   FR               stores services rural water tanks  4.494335e-01
102   FR     stores services urban decentral water tanks  4.312213e-01
103   FR                            stores solid biomass  1.521935e+08
104   FR                stores urban central water tanks  3.573413e+06

[105 rows x 3 columns]

DataFrame: DE_nodal_capacities_df
    zone                                            tech          2050
0     DE                                  generators gas  2.663845e+05
1     DE                                 generators load  2.900000e+07
2     DE                              generators offwind  4.846000e+03
3     DE                           generators offwind-ac  5.072330e+03
4     DE                           generators offwind-dc  2.113698e+04
..   ...                                             ...           ...
102   DE  stores residential urban decentral water tanks  2.052974e+03
103   DE               stores services rural water tanks  1.574396e+02
104   DE     stores services urban decentral water tanks  1.655623e+02
105   DE                            stores solid biomass  1.921109e+08
106   DE                stores urban central water tanks  5.528766e+06

[107 rows x 3 columns]

DataFrame: NL_nodal_capacities_df
   zone                                            tech          2050
0    NL                                  generators gas  7.534228e+04
1    NL                                 generators load  2.900000e+07
2    NL                              generators offwind  2.214000e+03
3    NL                           generators offwind-ac  3.218262e+03
4    NL                           generators offwind-dc  5.015261e+04
..  ...                                             ...           ...
94   NL  stores residential urban decentral water tanks  1.181603e+00
95   NL               stores services rural water tanks  1.357676e+01
96   NL     stores services urban decentral water tanks  4.624792e-01
97   NL                            stores solid biomass  2.287122e+07
98   NL                stores urban central water tanks  2.393606e+06

[99 rows x 3 columns]

DataFrame: UK_nodal_capacities_df
    zone                                            tech          2050
0     UK                                  generators gas  3.124520e+05
1     UK                                 generators load  5.800000e+07
2     UK                              generators offwind  8.835000e+03
3     UK                           generators offwind-ac  2.863307e+04
4     UK                           generators offwind-dc  2.291411e-01
..   ...                                             ...           ...
99    UK  stores residential urban decentral water tanks  1.889545e+03
100   UK               stores services rural water tanks  1.056812e+02
101   UK     stores services urban decentral water tanks  3.236992e+02
102   UK                            stores solid biomass  4.099552e+07
103   UK                stores urban central water tanks  7.695198e+06

[104 rows x 3 columns]

--- Erased Rows DataFrame ---
   zone                                            tech          2050
0    UK                                  generators gas  0.000000e+00
1    UK                                 generators load  2.900000e+07
2    UK                              generators offwind  4.591693e+03
3    UK                           generators offwind-ac  8.895826e-02
4    UK                           generators offwind-dc  6.109210e-02
..  ...                                             ...           ...
94   UK  stores residential urban decentral water tanks  3.397967e+01
95   UK               stores services rural water tanks  3.948549e+00
96   UK     stores services urban decentral water tanks  1.339513e+00
97   UK                            stores solid biomass  8.775645e+05
98   UK                stores urban central water tanks  8.258275e+04

[99 rows x 3 columns]

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables.
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [72]:
print (f"Name of the DispaSET Unleash folder:                       {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                       {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                 {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                 {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:            {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                         {zone_names}\n")
print (f"Target year:                                               {data_target_year}\n")
print (f"Name of the Power Plant DataFrames (dictionary):           {list(power_plants_dfs_dict.keys())}\n")
print (f"Name of the zone_names_equivalences_dictionary):           {[value['Acronym'] for value in selected_zone_names_equivalences_dict.values()]}\n")
print (f"Name of the Overall Fuel Technology Match DataFrame:       overal_fuel_technologies_match_df\n")
print (f"Name of the Fuel Technology Match Dictionary:              fuel_technologies_match_dict\n")
print (f"Name of the PyPSA Nodal Capacities DataFrames (dictionary):{list(nodal_capacities_dfs_dict.keys())}\n")

Name of the DispaSET Unleash folder:                       Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                       /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                 PowerPlants

Path to the Power Plants Base data folder:                 /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                PowerPlants

Path to the Power Plants_Pypsa Raw data folder:            /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:       PowerPlants

Path to the Power Plants_Pypsa Formated data folder:       /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                         ['BE', 'FR', 'DE', 'NL', 'UK']

Target year:                                               2050

Name of the Power Plant DataFrames (dictionary):           ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

Name of the zone_names_equivalences_dictionary):           [['  '], ['  '], ['  '], ['  '], ['GB']]

Name of the Overall Fuel Technology Match DataFrame:       overal_fuel_technologies_match_df

Name of the Fuel Technology Match Dictionary:              fuel_technologies_match_dict

Name of the PyPSA Nodal Capacities DataFrames (dictionary):['BE_nodal_capacities_df', 'FR_nodal_capacities_df', 'DE_nodal_capacities_df', 'NL_nodal_capacities_df', 'UK_nodal_capacities_df']

<div style="background-color: black;">
    <hr style="border: 2px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
    8. PyPSA to Dispa-SET Power Plants Data Formatting
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The power plants dataframe start to be formatting.
    </div>
    <hr style="border: 1px dashed skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
    8.1. Unit, PowerCapacity, Nunits and Zone Data Clasification
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
The columns Unit, PowerCapacity, Nunits, Zone, Technology and Fuel of the final Power Plants inputs are added to the final Power Plant sheet.
    <br>
    Just the Unit, PowerCapacity, Nunits, Zone are correctly filtered at this stage.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [73]:
# 1. ------------------------------ Map and append nodal capacity data to power plant DataFrames by zone and technology
for zone in zone_names:

# 1.1. --------------------------------------------------------------------------- Construct keys for both dictionaries 
    nodal_key = f"{zone}_nodal_capacities_df"
    power_key = f"{zone}_{data_target_year}"

# 1.2. ------------------------------------------------------------------------------- Get the corresponding dataframes
    nodal_df = nodal_capacities_dfs_dict.get(nodal_key)
    power_df = power_plants_dfs_dict.get(power_key)

    if nodal_df is not None and power_df is not None:
        new_rows = []

        for _, row in nodal_df.iterrows():
            tech = row['tech']
            
# 1.2.1. --------------------------------------------------------------- Check if tech is in the equivalence dictionary
            if tech in tech_equivalences_dict:
                # Safely access the column using .loc
                power_capacity = row.loc[str(data_target_year)]

# 1.2.1.1. ----------------------------------------------------------------- Create a new row with the required values
                new_row = {
                    'Unit': tech,
                    'PowerCapacity': power_capacity,
                    'Nunits': 1,
                    'Zone': row['zone'],
                    
# 1.2.1.1.1. ----------------------------------------------------------------------------------- MODIFIED LINES BELOW:
                    'Technology': ' '.join(tech_equivalences_dict[tech]['tech']) if isinstance(tech_equivalences_dict[tech]['tech'], list) else tech_equivalences_dict[tech]['tech'],
                    'Fuel': ' '.join(tech_equivalences_dict[tech]['fuel']) if isinstance(tech_equivalences_dict[tech]['fuel'], list) else tech_equivalences_dict[tech]['fuel']
                }

                new_rows.append(new_row)

# 1.3. ---------------------------------------------------------------- Concatenate new rows to the existing dataframe
        if new_rows:
            power_df = pd.concat([power_df, pd.DataFrame(new_rows)], ignore_index=True)

# 1.4. ------------------------------------------------------------- Update the dictionary with the modified dataframe
        power_plants_dfs_dict[power_key] = power_df

# 2. ------------------------------------------------------------------------------------------------------------ Done 
power_plants_dfs_dict

/tmp/ipykernel_294897/2049252288.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  power_df = pd.concat([power_df, pd.DataFrame(new_rows)], ignore_index=True)
/tmp/ipykernel_294897/2049252288.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  power_df = pd.concat([power_df, pd.DataFrame(new_rows)], ignore_index=True)
/tmp/ipykernel_294897/2049252288.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  power_df = pd.concat([power_df, pd.DataFrame(new_rows)], ignore_index=True)
/tmp/ipykernel_294897/2049252288.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  power_df = pd.concat([power_df, pd.DataFrame(new_rows)], ignore_index=True)
/tmp/ipykernel_294897/2049252288.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  power_df = pd.concat([power_df, pd.DataFrame(new_rows)], ignore_index=True)

{'BE_2050':    Unnamed: 0                                               Unit  \
 0         NaN                                 generators offwind
 1         NaN                              generators offwind-ac
 2         NaN                              generators offwind-dc
 3         NaN                                  generators onwind
 4         NaN                                     generators ror
 5         NaN                                   generators solar
 6         NaN                           generators solar rooftop
 7         NaN                                         links CCGT
 8         NaN                              links H2 Electrolysis
 9         NaN                                 links H2 Fuel Cell
 10        NaN                                   links H2 turbine
 11        NaN                                  links Haber-Bosch
 12        NaN                                         links OCGT
 13        NaN                                          links V2G
 14        NaN                              links ammonia cracker
 15        NaN                           links battery discharger
 16        NaN                              links methanolisation
 17        NaN                                      links nuclear
 18        NaN              links residential rural air heat pump
 19        NaN           links residential rural ground heat pump
 20        NaN           links residential rural resistive heater
 21        NaN    links residential urban decentral air heat pump
 22        NaN  links residential urban decentral resistive he...
 23        NaN                 links services rural air heat pump
 24        NaN              links services rural ground heat pump
 25        NaN              links services rural resistive heater
 26        NaN       links services urban decentral air heat pump
 27        NaN    links services urban decentral resistive heater
 28        NaN                  links urban central air heat pump
 29        NaN                        links urban central gas CHP
 30        NaN                     links urban central gas CHP CC
 31        NaN               links urban central resistive heater
 32        NaN              links urban central solid biomass CHP
 33        NaN           links urban central solid biomass CHP CC
 34        NaN                                  storage_units PHS
 35        NaN                                storage_units hydro

     PowerCapacity Nunits Zone Zone_th Zone_h2                     Technology  \
 0     1549.800000      1   BE     NaN     NaN                           WTOF
 1     1738.199046      1   BE     NaN     NaN                           WTOF
 2     4712.000935      1   BE     NaN     NaN                           WTOF
 3     7247.152421      1   BE     NaN     NaN                           WTON
 4       59.015340      1   BE     NaN     NaN                           HROR
 5    12000.040687      1   BE     NaN     NaN                           PHOT
 6    36199.942807      1   BE     NaN     NaN                           PHOT
 7     2651.162228      1   BE     NaN     NaN                           COMC
 8     6061.648864      1   BE     NaN     NaN                 PEME ALKE SOXE
 9     3776.902309      1   BE     NaN     NaN  PEFC SOFC MCFC PAFC ALFC REFC
 10    3341.090816      1   BE     NaN     NaN                 GTUR COMC ICEN
 11       0.012563      1   BE     NaN     NaN                           HBBS
 12    5297.172700      1   BE     NaN     NaN                           GTUR
 13   34022.652950      1   BE     NaN     NaN                           BEVS
 14       2.106993      1   BE     NaN     NaN                           P2BS
 15   10503.691027      1   BE     NaN     NaN                           BATS
 16     941.731454      1   BE     NaN     NaN                           P2BS
 17       0.077127      1   BE     NaN     NaN                           STUR
 18       0.016804      1   BE     NaN     NaN                           ASHP
 19     148.409598      1   BE     NaN     NaN                           GSHP
 20      53.877530      1   BE     NaN     NaN                           REHE
 21    1752.152824      1   BE     NaN     NaN                           ASHP
 22    1865.287169      1   BE     NaN     NaN                           REHE
 23       0.018477      1   BE     NaN     NaN                           ASHP
 24     160.364599      1   BE     NaN     NaN                           GSHP
 25      44.623008      1   BE     NaN     NaN                           REHE
 26     441.106458      1   BE     NaN     NaN                           ASHP
 27     698.614651      1   BE     NaN     NaN                           REHE
 28      97.131676      1   BE     NaN     NaN                           ASHP
 29    3226.538194      1   BE     NaN     NaN            COMC GTUR STUR ICEN
 30       0.000000      1   BE     NaN     NaN                           COMC
 31    7197.184446      1   BE     NaN     NaN                           REHE
 32    2010.056049      1   BE     NaN     NaN                      STUR ICEN
 33       0.000000      1   BE     NaN     NaN                      STUR ICEN
 34    1308.000000      1   BE     NaN     NaN                           HPHS
 35      12.735669      1   BE     NaN     NaN                           HDAM

                            Fuel Efficiency  ... STOMaxChargingPower  \
 0                           WIN        NaN  ...                 NaN
 1                           WIN        NaN  ...                 NaN
 2                           WIN        NaN  ...                 NaN
 3                           WIN        NaN  ...                 NaN
 4                           WAT        NaN  ...                 NaN
 5                           SUN        NaN  ...                 NaN
 6                           SUN        NaN  ...                 NaN
 7                   GAS HYD BIO        NaN  ...                 NaN
 8                           ELE        NaN  ...                 NaN
 9                           HYD        NaN  ...                 NaN
 10                          HYD        NaN  ...                 NaN
 11                          ELE        NaN  ...                 NaN
 12  GAS HYD OIL AMO BIO WST OTH        NaN  ...                 NaN
 13                          ELE        NaN  ...                 NaN
 14                          ELE        NaN  ...                 NaN
 15                          ELE        NaN  ...                 NaN
 16                          ELE        NaN  ...                 NaN
 17                          NUC        NaN  ...                 NaN
 18                          ELE        NaN  ...                 NaN
 19                          ELE        NaN  ...                 NaN
 20                          ELE        NaN  ...                 NaN
 21                          ELE        NaN  ...                 NaN
 22                          ELE        NaN  ...                 NaN
 23                          ELE        NaN  ...                 NaN
 24                          ELE        NaN  ...                 NaN
 25                          ELE        NaN  ...                 NaN
 26                          ELE        NaN  ...                 NaN
 27                          ELE        NaN  ...                 NaN
 28                          ELE        NaN  ...                 NaN
 29                          GAS        NaN  ...                 NaN
 30                          GAS        NaN  ...                 NaN
 31                          ELE        NaN  ...                 NaN
 32                          BIO        NaN  ...                 NaN
 33                          BIO        NaN  ...                 NaN
 34                          WAT        NaN  ...                 NaN
 35                          WAT        NaN  ...                 NaN

    STOChargingEfficiency WaterWithdrawal WaterConsumption Status Source  \
 0                    NaN             NaN              NaN    NaN    NaN
 1                    NaN             NaN              NaN    NaN    NaN
 2                    NaN             NaN              NaN    NaN    NaN
 3                    NaN             NaN              NaN    NaN    NaN
 4                    NaN             NaN              NaN    NaN    NaN
 5                    NaN             NaN              NaN    NaN    NaN
 6                    NaN             NaN              NaN    NaN    NaN
 7                    NaN             NaN              NaN    NaN    NaN
 8                    NaN             NaN              NaN    NaN    NaN
 9                    NaN             NaN              NaN    NaN    NaN
 10                   NaN             NaN              NaN    NaN    NaN
 11                   NaN             NaN              NaN    NaN    NaN
 12                   NaN             NaN              NaN    NaN    NaN
 13                   NaN             NaN              NaN    NaN    NaN
 14                   NaN             NaN              NaN    NaN    NaN
 15                   NaN             NaN              NaN    NaN    NaN
 16                   NaN             NaN              NaN    NaN    NaN
 17                   NaN             NaN              NaN    NaN    NaN
 18                   NaN             NaN              NaN    NaN    NaN
 19                   NaN             NaN              NaN    NaN    NaN
 20                   NaN             NaN              NaN    NaN    NaN
 21                   NaN             NaN              NaN    NaN    NaN
 22                   NaN             NaN              NaN    NaN    NaN
 23                   NaN             NaN              NaN    NaN    NaN
 24                   NaN             NaN              NaN    NaN    NaN
 25                   NaN             NaN              NaN    NaN    NaN
 26                   NaN             NaN              NaN    NaN    NaN
 27                   NaN             NaN              NaN    NaN    NaN
 28                   NaN             NaN              NaN    NaN    NaN
 29                   NaN             NaN              NaN    NaN    NaN
 30                   NaN             NaN              NaN    NaN    NaN
 31                   NaN             NaN              NaN    NaN    NaN
 32                   NaN             NaN              NaN    NaN    NaN
 33                   NaN             NaN              NaN    NaN    NaN
 34                   NaN             NaN              NaN    NaN    NaN
 35                   NaN             NaN              NaN    NaN    NaN

    Company  Lat  Lon Lat/Lon
 0      NaN  NaN  NaN     NaN
 1      NaN  NaN  NaN     NaN
 2      NaN  NaN  NaN     NaN
 3      NaN  NaN  NaN     NaN
 4      NaN  NaN  NaN     NaN
 5      NaN  NaN  NaN     NaN
 6      NaN  NaN  NaN     NaN
 7      NaN  NaN  NaN     NaN
 8      NaN  NaN  NaN     NaN
 9      NaN  NaN  NaN     NaN
 10     NaN  NaN  NaN     NaN
 11     NaN  NaN  NaN     NaN
 12     NaN  NaN  NaN     NaN
 13     NaN  NaN  NaN     NaN
 14     NaN  NaN  NaN     NaN
 15     NaN  NaN  NaN     NaN
 16     NaN  NaN  NaN     NaN
 17     NaN  NaN  NaN     NaN
 18     NaN  NaN  NaN     NaN
 19     NaN  NaN  NaN     NaN
 20     NaN  NaN  NaN     NaN
 21     NaN  NaN  NaN     NaN
 22     NaN  NaN  NaN     NaN
 23     NaN  NaN  NaN     NaN
 24     NaN  NaN  NaN     NaN
 25     NaN  NaN  NaN     NaN
 26     NaN  NaN  NaN     NaN
 27     NaN  NaN  NaN     NaN
 28     NaN  NaN  NaN     NaN
 29     NaN  NaN  NaN     NaN
 30     NaN  NaN  NaN     NaN
 31     NaN  NaN  NaN     NaN
 32     NaN  NaN  NaN     NaN
 33     NaN  NaN  NaN     NaN
 34     NaN  NaN  NaN     NaN
 35     NaN  NaN  NaN     NaN

 [36 rows x 41 columns],
 'FR_2050':    Unnamed: 0                                               Unit  \
 0         NaN                                 generators offwind
 1         NaN                              generators offwind-ac
 2         NaN                              generators offwind-dc
 3         NaN                                  generators onwind
 4         NaN                                     generators ror
 5         NaN                                   generators solar
 6         NaN                           generators solar rooftop
 7         NaN                                         links CCGT
 8         NaN                              links H2 Electrolysis
 9         NaN                                 links H2 Fuel Cell
 10        NaN                                   links H2 turbine
 11        NaN                                  links Haber-Bosch
 12        NaN                                         links OCGT
 13        NaN                                          links V2G
 14        NaN                              links ammonia cracker
 15        NaN                           links battery discharger
 16        NaN                              links methanolisation
 17        NaN                                      links nuclear
 18        NaN                                          links oil
 19        NaN              links residential rural air heat pump
 20        NaN           links residential rural ground heat pump
 21        NaN           links residential rural resistive heater
 22        NaN    links residential urban decentral air heat pump
 23        NaN  links residential urban decentral resistive he...
 24        NaN                 links services rural air heat pump
 25        NaN              links services rural ground heat pump
 26        NaN              links services rural resistive heater
 27        NaN       links services urban decentral air heat pump
 28        NaN    links services urban decentral resistive heater
 29        NaN                  links urban central air heat pump
 30        NaN                        links urban central gas CHP
 31        NaN                     links urban central gas CHP CC
 32        NaN               links urban central resistive heater
 33        NaN              links urban central solid biomass CHP
 34        NaN           links urban central solid biomass CHP CC
 35        NaN                                  storage_units PHS
 36        NaN                                storage_units hydro

     PowerCapacity Nunits Zone Zone_th Zone_h2                     Technology  \
 0      480.000000      1   FR     NaN     NaN                           WTOF
 1    24631.595406      1   FR     NaN     NaN                           WTOF
 2     4617.910333      1   FR     NaN     NaN                           WTOF
 3    63322.378275      1   FR     NaN     NaN                           WTON
 4     6870.649149      1   FR     NaN     NaN                           HROR
 5    17024.222292      1   FR     NaN     NaN                           PHOT
 6   175286.554430      1   FR     NaN     NaN                           PHOT
 7     6491.318795      1   FR     NaN     NaN                           COMC
 8     4415.782019      1   FR     NaN     NaN                 PEME ALKE SOXE
 9     4565.396149      1   FR     NaN     NaN  PEFC SOFC MCFC PAFC ALFC REFC
 10       0.146899      1   FR     NaN     NaN                 GTUR COMC ICEN
 11       0.018230      1   FR     NaN     NaN                           HBBS
 12   20295.814479      1   FR     NaN     NaN                           GTUR
 13  195572.300000      1   FR     NaN     NaN                           BEVS
 14     362.476758      1   FR     NaN     NaN                           P2BS
 15   36968.817334      1   FR     NaN     NaN                           BATS
 16     741.038767      1   FR     NaN     NaN                           P2BS
 17    2660.044043      1   FR     NaN     NaN                           STUR
 18       0.000000      1   FR     NaN     NaN                 GTUR ICEN STUR
 19       0.019334      1   FR     NaN     NaN                           ASHP
 20    1486.186677      1   FR     NaN     NaN                           GSHP
 21    1658.694287      1   FR     NaN     NaN                           REHE
 22    4696.162671      1   FR     NaN     NaN                           ASHP
 23    8480.087629      1   FR     NaN     NaN                           REHE
 24       0.020127      1   FR     NaN     NaN                           ASHP
 25    1182.671448      1   FR     NaN     NaN                           GSHP
 26     595.618742      1   FR     NaN     NaN                           REHE
 27    2074.740155      1   FR     NaN     NaN                           ASHP
 28    3761.933894      1   FR     NaN     NaN                           REHE
 29       0.045062      1   FR     NaN     NaN                           ASHP
 30   15517.950168      1   FR     NaN     NaN            COMC GTUR STUR ICEN
 31       0.000000      1   FR     NaN     NaN                           COMC
 32   26834.374737      1   FR     NaN     NaN                           REHE
 33    5800.808393      1   FR     NaN     NaN                      STUR ICEN
 34       0.000000      1   FR     NaN     NaN                      STUR ICEN
 35    5236.300000      1   FR     NaN     NaN                           HPHS
 36    8573.492994      1   FR     NaN     NaN                           HDAM

                            Fuel Efficiency  ... STOMaxChargingPower  \
 0                           WIN        NaN  ...                 NaN
 1                           WIN        NaN  ...                 NaN
 2                           WIN        NaN  ...                 NaN
 3                           WIN        NaN  ...                 NaN
 4                           WAT        NaN  ...                 NaN
 5                           SUN        NaN  ...                 NaN
 6                           SUN        NaN  ...                 NaN
 7                   GAS HYD BIO        NaN  ...                 NaN
 8                           ELE        NaN  ...                 NaN
 9                           HYD        NaN  ...                 NaN
 10                          HYD        NaN  ...                 NaN
 11                          ELE        NaN  ...                 NaN
 12  GAS HYD OIL AMO BIO WST OTH        NaN  ...                 NaN
 13                          ELE        NaN  ...                 NaN
 14                          ELE        NaN  ...                 NaN
 15                          ELE        NaN  ...                 NaN
 16                          ELE        NaN  ...                 NaN
 17                          NUC        NaN  ...                 NaN
 18                          OIL        NaN  ...                 NaN
 19                          ELE        NaN  ...                 NaN
 20                          ELE        NaN  ...                 NaN
 21                          ELE        NaN  ...                 NaN
 22                          ELE        NaN  ...                 NaN
 23                          ELE        NaN  ...                 NaN
 24                          ELE        NaN  ...                 NaN
 25                          ELE        NaN  ...                 NaN
 26                          ELE        NaN  ...                 NaN
 27                          ELE        NaN  ...                 NaN
 28                          ELE        NaN  ...                 NaN
 29                          ELE        NaN  ...                 NaN
 30                          GAS        NaN  ...                 NaN
 31                          GAS        NaN  ...                 NaN
 32                          ELE        NaN  ...                 NaN
 33                          BIO        NaN  ...                 NaN
 34                          BIO        NaN  ...                 NaN
 35                          WAT        NaN  ...                 NaN
 36                          WAT        NaN  ...                 NaN

    STOChargingEfficiency WaterWithdrawal WaterConsumption Status Source  \

<div style="background-color: black;">
    <hr style="border: 1px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
    8.2. Technology Data Clasification
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The column technology is separating for all those units that can be matched with more than one technology.
    <br>
    The desegregation of the power capacity will be done according the following rule / proportion.
    </div>
    <div style="text-align: center; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue; margin-top: 10px; margin-bottom: 10px;">
    $E_k = \frac{2^{N-k}}{2^N - 1}$
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Where $k$ is the position of the element / Technology, $k=1$ is the first, $k=N$ is the last
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [74]:
# 1. ------------------------------------------------------------------------- Function to compute proportional weights
def compute_proportions(n):
    weights = [2**(n - k - 1) for k in range(n)]
    total = sum(weights)
    return [w / total for w in weights]

# 2. ------------------------------------------------------------------------- Process each DataFrame in the dictionary
for zone in zone_names:
    key = f"{zone}_{data_target_year}"
    df = power_plants_dfs_dict.get(key)

    if df is not None:
        new_rows = []

        for _, row in df.iterrows():
            techs = str(row['Technology']).split()
            if len(techs) > 1:
                proportions = compute_proportions(len(techs))
                for idx, (tech, prop) in enumerate(zip(techs, proportions), start=1):
                    new_row = row.copy()
                    new_row['Technology'] = tech
                    new_row['Unit'] = f"{row['Unit']}_{idx}"
                    new_row['PowerCapacity'] = row['PowerCapacity'] * prop
                    new_rows.append(new_row)
            else:
                new_rows.append(row)

# 2.1. ------------------------------------------------------------Replace the original DataFrame with the expanded one
        power_plants_dfs_dict[key] = pd.DataFrame(new_rows)

# 3. ------------------------------------------------------------------------------------------------------------- Done 
power_plants_dfs_dict

{'BE_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                                         links CCGT
 8          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 8          NaN                            links H2 Electrolysis_3
 9          NaN                               links H2 Fuel Cell_1
 9          NaN                               links H2 Fuel Cell_2
 9          NaN                               links H2 Fuel Cell_3
 9          NaN                               links H2 Fuel Cell_4
 9          NaN                               links H2 Fuel Cell_5
 9          NaN                               links H2 Fuel Cell_6
 10         NaN                                 links H2 turbine_1
 10         NaN                                 links H2 turbine_2
 10         NaN                                 links H2 turbine_3
 11         NaN                                  links Haber-Bosch
 12         NaN                                         links OCGT
 13         NaN                                          links V2G
 14         NaN                              links ammonia cracker
 15         NaN                           links battery discharger
 16         NaN                              links methanolisation
 17         NaN                                      links nuclear
 18         NaN              links residential rural air heat pump
 19         NaN           links residential rural ground heat pump
 20         NaN           links residential rural resistive heater
 21         NaN    links residential urban decentral air heat pump
 22         NaN  links residential urban decentral resistive he...
 23         NaN                 links services rural air heat pump
 24         NaN              links services rural ground heat pump
 25         NaN              links services rural resistive heater
 26         NaN       links services urban decentral air heat pump
 27         NaN    links services urban decentral resistive heater
 28         NaN                  links urban central air heat pump
 29         NaN                      links urban central gas CHP_1
 29         NaN                      links urban central gas CHP_2
 29         NaN                      links urban central gas CHP_3
 29         NaN                      links urban central gas CHP_4
 30         NaN                     links urban central gas CHP CC
 31         NaN               links urban central resistive heater
 32         NaN            links urban central solid biomass CHP_1
 32         NaN            links urban central solid biomass CHP_2
 33         NaN         links urban central solid biomass CHP CC_1
 33         NaN         links urban central solid biomass CHP CC_2
 34         NaN                                  storage_units PHS
 35         NaN                                storage_units hydro

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology  \
 0     1549.800000       1   BE      NaN      NaN       WTOF
 1     1738.199046       1   BE      NaN      NaN       WTOF
 2     4712.000935       1   BE      NaN      NaN       WTOF
 3     7247.152421       1   BE      NaN      NaN       WTON
 4       59.015340       1   BE      NaN      NaN       HROR
 5    12000.040687       1   BE      NaN      NaN       PHOT
 6    36199.942807       1   BE      NaN      NaN       PHOT
 7     2651.162228       1   BE      NaN      NaN       COMC
 8     3463.799351       1   BE      NaN      NaN       PEME
 8     1731.899675       1   BE      NaN      NaN       ALKE
 8      865.949838       1   BE      NaN      NaN       SOXE
 9     1918.426570       1   BE      NaN      NaN       PEFC
 9      959.213285       1   BE      NaN      NaN       SOFC
 9      479.606642       1   BE      NaN      NaN       MCFC
 9      239.803321       1   BE      NaN      NaN       PAFC
 9      119.901661       1   BE      NaN      NaN       ALFC
 9       59.950830       1   BE      NaN      NaN       REFC
 10    1909.194752       1   BE      NaN      NaN       GTUR
 10     954.597376       1   BE      NaN      NaN       COMC
 10     477.298688       1   BE      NaN      NaN       ICEN
 11       0.012563       1   BE      NaN      NaN       HBBS
 12    5297.172700       1   BE      NaN      NaN       GTUR
 13   34022.652950       1   BE      NaN      NaN       BEVS
 14       2.106993       1   BE      NaN      NaN       P2BS
 15   10503.691027       1   BE      NaN      NaN       BATS
 16     941.731454       1   BE      NaN      NaN       P2BS
 17       0.077127       1   BE      NaN      NaN       STUR
 18       0.016804       1   BE      NaN      NaN       ASHP
 19     148.409598       1   BE      NaN      NaN       GSHP
 20      53.877530       1   BE      NaN      NaN       REHE
 21    1752.152824       1   BE      NaN      NaN       ASHP
 22    1865.287169       1   BE      NaN      NaN       REHE
 23       0.018477       1   BE      NaN      NaN       ASHP
 24     160.364599       1   BE      NaN      NaN       GSHP
 25      44.623008       1   BE      NaN      NaN       REHE
 26     441.106458       1   BE      NaN      NaN       ASHP
 27     698.614651       1   BE      NaN      NaN       REHE
 28      97.131676       1   BE      NaN      NaN       ASHP
 29    1720.820370       1   BE      NaN      NaN       COMC
 29     860.410185       1   BE      NaN      NaN       GTUR
 29     430.205093       1   BE      NaN      NaN       STUR
 29     215.102546       1   BE      NaN      NaN       ICEN
 30       0.000000       1   BE      NaN      NaN       COMC
 31    7197.184446       1   BE      NaN      NaN       REHE
 32    1340.037366       1   BE      NaN      NaN       STUR
 32     670.018683       1   BE      NaN      NaN       ICEN
 33       0.000000       1   BE      NaN      NaN       STUR
 33       0.000000       1   BE      NaN      NaN       ICEN
 34    1308.000000       1   BE      NaN      NaN       HPHS
 35      12.735669       1   BE      NaN      NaN       HDAM

                            Fuel  Efficiency  ...  STOMaxChargingPower  \
 0                           WIN         NaN  ...                  NaN
 1                           WIN         NaN  ...                  NaN
 2                           WIN         NaN  ...                  NaN
 3                           WIN         NaN  ...                  NaN
 4                           WAT         NaN  ...                  NaN
 5                           SUN         NaN  ...                  NaN
 6                           SUN         NaN  ...                  NaN
 7                   GAS HYD BIO         NaN  ...                  NaN
 8                           ELE         NaN  ...                  NaN
 8                           ELE         NaN  ...                  NaN
 8                           ELE         NaN  ...                  NaN
 9                           HYD         NaN  ...                  NaN
 9                           HYD         NaN  ...                  NaN
 9                           HYD         NaN  ...                  NaN
 9                           HYD         NaN  ...                  NaN
 9                           HYD         NaN  ...                  NaN
 9                           HYD         NaN  ...                  NaN
 10                          HYD         NaN  ...                  NaN
 10                          HYD         NaN  ...                  NaN
 10                          HYD         NaN  ...                  NaN
 11                          ELE         NaN  ...                  NaN
 12  GAS HYD OIL AMO BIO WST OTH         NaN  ...                  NaN
 13                          ELE         NaN  ...                  NaN
 14                          ELE         NaN  ...                  NaN
 15                          ELE         NaN  ...                  NaN
 16                          ELE         NaN  ...                  NaN
 17                          NUC         NaN  ...                  NaN
 18                          ELE         NaN  ...                  NaN
 19                          ELE         NaN  ...                  NaN
 20                          ELE         NaN  ...                  NaN
 21                          ELE         NaN  ...                  NaN
 22                          ELE         NaN  ...                  NaN
 23                          ELE         NaN  ...                  NaN
 24                          ELE         NaN  ...                  NaN
 25                          ELE         NaN  ...                  NaN
 26                          ELE         NaN  ...                  NaN
 27                          ELE         NaN  ...                  NaN
 28                          ELE         NaN  ...                  NaN
 29                          GAS         NaN  ...                  NaN
 29                          GAS         NaN  ...                  NaN
 29                          GAS         NaN  ...                  NaN
 29                          GAS         NaN  ...                  NaN
 30                          GAS         NaN  ...                  NaN
 31                          ELE         NaN  ...                  NaN
 32                          BIO         NaN  ...                  NaN
 32                          BIO         NaN  ...                  NaN
 33                          BIO         NaN  ...                  NaN
 33                          BIO         NaN  ...                  NaN
 34                          WAT         NaN  ...                  NaN
 35                          WAT         NaN  ...                  NaN

     STOChargingEfficiency  WaterWithdrawal  WaterConsumption  Status  Source  \
 0                     NaN              NaN               NaN     NaN     NaN
 1                     NaN              NaN               NaN     NaN     NaN
 2                     NaN              NaN               NaN     NaN     NaN
 3                     NaN              NaN               NaN     NaN     NaN
 4                     NaN              NaN               NaN     NaN     NaN
 5                     NaN              NaN               NaN     NaN     NaN
 6                     NaN              NaN               NaN     NaN     NaN
 7                     NaN              NaN               NaN     NaN     NaN
 8                     NaN              NaN               NaN     NaN     NaN
 8                     NaN              NaN               NaN     NaN     NaN
 8                     NaN              NaN               NaN     NaN     NaN
 9                     NaN              NaN               NaN     NaN     NaN
 9                     NaN              NaN               NaN     NaN     NaN
 9                     NaN              NaN               NaN     NaN     NaN
 9                     NaN              NaN               NaN     NaN     NaN
 9                     NaN              NaN               NaN     NaN     NaN
 9                     NaN              NaN               NaN     NaN     NaN
 10                    NaN              NaN               NaN     NaN     NaN
 10                    NaN              NaN               NaN     NaN     NaN
 10                    NaN              NaN               NaN     NaN     NaN
 11                    NaN              NaN               NaN     NaN     NaN
 12                    NaN              NaN               NaN     NaN     NaN
 13                    NaN              NaN               NaN     NaN     NaN
 14                    NaN              NaN               NaN     NaN     NaN
 15                    NaN              NaN               NaN     NaN     NaN
 16                    NaN              NaN               NaN     NaN     NaN
 17                    NaN              NaN               NaN     NaN     NaN
 18                    NaN              NaN               NaN     NaN     NaN
 19                    NaN              NaN               NaN     NaN     NaN
 20                    NaN              NaN               NaN     NaN     NaN
 21                    NaN              NaN               NaN     NaN     NaN
 22                    NaN              NaN               NaN     NaN     NaN
 23                    NaN              NaN               NaN     NaN     NaN
 24                    NaN              NaN               NaN     NaN     NaN
 25                    NaN              NaN               NaN     NaN     NaN
 26                    NaN              NaN               NaN     NaN     NaN
 27                    NaN              NaN               NaN     NaN     NaN
 28                    NaN              NaN               NaN     NaN     NaN
 29                    NaN              NaN               NaN     NaN     NaN
 29                    NaN              NaN               NaN     NaN     NaN
 29                    NaN              NaN               NaN     NaN     NaN
 29                    NaN              NaN               NaN     NaN     NaN
 30                    NaN              NaN               NaN     NaN     NaN
 31                    NaN              NaN               NaN     NaN     NaN
 32                    NaN              NaN               NaN     NaN     NaN
 32                    NaN              NaN               NaN     NaN     NaN
 33                    NaN              NaN               NaN     NaN     NaN
 33                    NaN              NaN               NaN     NaN     NaN
 34                    NaN              NaN               NaN     NaN     NaN
 35                    NaN              NaN               NaN     NaN     NaN

     Company  Lat  Lon  Lat/Lon
 0       NaN  NaN  NaN      NaN
 1       NaN  NaN  NaN      NaN
 2       NaN  NaN  NaN      NaN
 3       NaN  NaN  NaN      NaN
 4       NaN  NaN  NaN      NaN
 5       NaN  NaN  NaN      NaN
 6       NaN  NaN  NaN      NaN
 7       NaN  NaN  NaN      NaN
 8       NaN  NaN  NaN      NaN
 8       NaN  NaN  NaN      NaN
 8       NaN  NaN  NaN      NaN
 9       NaN  NaN  NaN      NaN
 9       NaN  NaN  NaN      NaN
 9       NaN  NaN  NaN      NaN
 9       NaN  NaN  NaN      NaN
 9       NaN  NaN  NaN      NaN
 9       NaN  NaN  NaN      NaN
 10      NaN  NaN  NaN      NaN
 10      NaN  NaN  NaN      NaN
 10      NaN  NaN  NaN      NaN
 11      NaN  NaN  NaN      NaN
 12      NaN  NaN  NaN      NaN
 13      NaN  NaN  NaN      NaN
 14      NaN  NaN  NaN      NaN
 15      NaN  NaN  NaN      NaN
 16      NaN  NaN  NaN      NaN
 17      NaN  NaN  NaN      NaN
 18      NaN  NaN  NaN      NaN
 19      NaN  NaN  NaN      NaN
 20      NaN  NaN  NaN      NaN
 21      NaN  NaN  NaN      NaN
 22      NaN  NaN  NaN      NaN
 23      NaN  NaN  NaN      NaN
 24      NaN  NaN  NaN      NaN
 25      NaN  NaN  NaN      NaN
 26      NaN  NaN  NaN      NaN
 27      NaN  NaN  NaN      NaN
 28      NaN  NaN  NaN      NaN
 29      NaN  NaN  NaN      NaN
 29      NaN  NaN  NaN      NaN
 29      NaN  NaN  NaN      NaN
 29      NaN  NaN  NaN      NaN
 30      NaN  NaN  NaN      NaN
 31      NaN  NaN  NaN      NaN
 32      NaN  NaN  NaN      NaN
 32      NaN  NaN  NaN      NaN
 33      NaN  NaN  NaN      NaN
 33      NaN  NaN  NaN      NaN
 34      NaN  NaN  NaN      NaN
 35      NaN  NaN  NaN      NaN

 [50 rows x 41 columns],
 'FR_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                                         links CCGT
 8          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 8          NaN                            links H2 Electrolysis_3
 9          NaN                               links H2 Fuel Cell_1
 9          NaN                               links H2 Fuel Cell_2
 9          NaN                               links H2 Fuel Cell_3
 9          NaN                               links H2 Fuel Cell_4
 9          NaN                               links H2 Fuel Cell_5
 9          NaN                               links H2 Fuel Cell_6
 10         NaN                                 links H2 turbine_1
 10         NaN                                 links H2 turbine_2
 10         NaN                                 links H2 turbine_3
 11         NaN                                  links Haber-Bosch
 12         NaN                                         links OCGT
 13         NaN                                          links V2G
 14         NaN                              links ammonia cracker
 15         NaN                           links battery discharger
 16         NaN                              links methanolisation
 17         NaN                                      links nuclear
 18         NaN                                        links oil_1
 18         NaN                                        links oil_2
 18         NaN                                        links oil_3
 19         NaN              links residential rural air heat pump
 20         NaN           links residential rural ground heat pump
 21         NaN           links residential rural resistive heater
 22         NaN    links residential urban decentral air heat pump
 23         NaN  links residential urban decentral resistive he...
 24         NaN                 links services rural air heat pump
 25         NaN              links services rural ground heat pump
 26         NaN              links services rural resistive heater
 27         NaN       links services urban decentral air heat pump
 28         NaN    links services urban decentral resistive heater
 29         NaN                  links urban central air heat pump
 30         NaN                      links urban central gas CHP_1
 30         NaN                      links urban central gas CHP_2
 30         NaN                      links urban central gas CHP_3
 30         NaN                      links urban central gas CHP_4
 31         NaN                     links urban central gas CHP CC
 32         NaN               links urban central resistive heater
 33         NaN            links urban central solid biomass CHP_1
 33         NaN            links urban central solid biomass CHP_2
 34         NaN         links urban central solid biomass CHP CC_1
 34         NaN         links urban central solid biomass CHP CC_2
 35         NaN                                  storage_units PHS
 36         NaN                                storage_units hydro

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology  \
 0      480.000000       1   FR      NaN      NaN       WTOF
 1    24631.595406       1   FR      NaN      NaN       WTOF
 2     4617.910333       1   FR      NaN      NaN       WTOF
 3    63322.378275       1   FR      NaN      NaN       WTON
 4     6870.649149       1   FR      NaN      NaN       HROR
 5    17024.222292       1   FR      NaN      NaN       PHOT
 6   175286.554430       1   FR      NaN      NaN       PHOT
 7     6491.318795       1   FR      NaN      NaN       COMC

<div style="background-color: black;">
    <hr style="border: 1px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: TimesNewRoman; color:skyblue">
    8.3. Fuel Data Clasification
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The column Feul is separating for all those units that can be matched with more than one fuel.
    <br>
    The desegregation of the power capacity will be done according the proportional technology - fuel tables for the corresponding country .
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [75]:
# 1. ------------------- Split multi-fuel power plant units into separate entries based on technology-fuel multipliers 
processed_power_plants_dfs_dict = {}

for zone in zone_names:

# 1.1. --------------------------------------------------------------------------------- Data Retrieval and Validation
    power_key = f"{zone}_{data_target_year}"
    fuel_key = zone
    power_df = power_plants_dfs_dict.get(power_key)
    fuel_df = fuel_technologies_match_dict.get(fuel_key, overal_fuel_technologies_match_df)

    if power_df is None:
        print(f"⚠️ No power plant DataFrame found for {power_key}")
        continue

    df = power_df.copy()
    new_rows = []
    rows_to_drop = []

# 1.2. ------------------------------------------------------------------------- Iterate and Identify Multi-Fuel Units
    for idx, row in df.iterrows():
        tech = str(row["Technology"]).strip()
        fuel_str = str(row["Fuel"]).strip()
        fuels = fuel_str.split()

# 1.2.1. ------------------------------------ Skip units that only have a single fuel or are missing from the mapping
        if len(fuels) <= 1:
            continue

        if tech not in fuel_df.index:
            rows_to_drop.append(idx)
            continue

        original_capacity = row["PowerCapacity"]
        new_capacities = []
        new_rows_for_this_row = []

# 1.2.2. -------------------------------------------------------------------- Split Unit and Calculate New Capacities 
        for i, fuel in enumerate(fuels, start=1):
            if fuel not in fuel_df.columns:
                continue
            multiplier = fuel_df.loc[tech, fuel]
            if pd.isna(multiplier):
                continue
            new_row = row.copy()
            new_row["Unit"] = f"{row['Unit']}_{i}"
            new_row["Fuel"] = fuel
            new_row["PowerCapacity"] = original_capacity * multiplier
            new_rows_for_this_row.append(new_row)
            new_capacities.append(new_row["PowerCapacity"])

        if not new_rows_for_this_row:
            rows_to_drop.append(idx)
            continue

# 1.2.3. ---------------------------------------------------------------------- Capacity Balancing (Residual Handling)
        sum_new_capacities = sum(new_capacities)
        
# 1.2.4. ------------------------ If the sum is less than the original, add the difference to the largest new capacity
        if sum_new_capacities < original_capacity:
            
# 1.2.4.1. ------------------------------------------------ Assign the remainder to the unit with the largest capacity
            max_capacity_idx = max(range(len(new_capacities)), key=lambda i: new_capacities[i])
            new_rows_for_this_row[max_capacity_idx]["PowerCapacity"] += (original_capacity - sum_new_capacities)

        new_rows.extend(new_rows_for_this_row)
        rows_to_drop.append(idx)

# 1.3. ----------------------------------------------------------------------------- Clean Up and Save Final DataFrame 
    df = df.drop(rows_to_drop, errors="ignore")
    if new_rows:
        df = pd.concat([df, pd.DataFrame(new_rows)], ignore_index=True)

    processed_power_plants_dfs_dict[power_key] = df

# 2. ------------------------------------------------------------------------------------------------------------ Done 
print("✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.")
processed_power_plants_dfs_dict

✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.

{'BE_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 25         NaN              links residential rural air heat pump
 26         NaN           links residential rural ground heat pump
 27         NaN           links residential rural resistive heater
 28         NaN    links residential urban decentral air heat pump
 29         NaN  links residential urban decentral resistive he...
 30         NaN                 links services rural air heat pump
 31         NaN              links services rural ground heat pump
 32         NaN              links services rural resistive heater
 33         NaN       links services urban decentral air heat pump
 34         NaN    links services urban decentral resistive heater
 35         NaN                  links urban central air heat pump
 36         NaN                      links urban central gas CHP_1
 37         NaN                      links urban central gas CHP_2
 38         NaN                      links urban central gas CHP_3
 39         NaN                      links urban central gas CHP_4
 40         NaN                     links urban central gas CHP CC
 41         NaN               links urban central resistive heater
 42         NaN            links urban central solid biomass CHP_1
 43         NaN            links urban central solid biomass CHP_2
 44         NaN         links urban central solid biomass CHP CC_1
 45         NaN         links urban central solid biomass CHP CC_2
 46         NaN                                  storage_units PHS
 47         NaN                                storage_units hydro
 48         NaN                                       links CCGT_1
 49         NaN                                       links CCGT_2
 50         NaN                                       links CCGT_3
 51         NaN                                       links OCGT_1
 52         NaN                                       links OCGT_2
 53         NaN                                       links OCGT_3
 54         NaN                                       links OCGT_4
 55         NaN                                       links OCGT_5
 56         NaN                                       links OCGT_6
 57         NaN                                       links OCGT_7

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0     1549.800000       1   BE      NaN      NaN       WTOF  WIN         NaN
 1     1738.199046       1   BE      NaN      NaN       WTOF  WIN         NaN
 2     4712.000935       1   BE      NaN      NaN       WTOF  WIN         NaN
 3     7247.152421       1   BE      NaN      NaN       WTON  WIN         NaN
 4       59.015340       1   BE      NaN      NaN       HROR  WAT         NaN
 5    12000.040687       1   BE      NaN      NaN       PHOT  SUN         NaN
 6    36199.942807       1   BE      NaN      NaN       PHOT  SUN         NaN
 7     3463.799351       1   BE      NaN      NaN       PEME  ELE         NaN
 8     1731.899675       1   BE      NaN      NaN       ALKE  ELE         NaN
 9      865.949838       1   BE      NaN      NaN       SOXE  ELE         NaN
 10    1918.426570       1   BE      NaN      NaN       PEFC  HYD         NaN
 11     959.213285       1   BE      NaN      NaN       SOFC  HYD         NaN
 12     479.606642       1   BE      NaN      NaN       MCFC  HYD         NaN
 13     239.803321       1   BE      NaN      NaN       PAFC  HYD         NaN
 14     119.901661       1   BE      NaN      NaN       ALFC  HYD         NaN
 15      59.950830       1   BE      NaN      NaN       REFC  HYD         NaN
 16    1909.194752       1   BE      NaN      NaN       GTUR  HYD         NaN
 17     954.597376       1   BE      NaN      NaN       COMC  HYD         NaN
 18     477.298688       1   BE      NaN      NaN       ICEN  HYD         NaN
 19       0.012563       1   BE      NaN      NaN       HBBS  ELE         NaN
 20   34022.652950       1   BE      NaN      NaN       BEVS  ELE         NaN
 21       2.106993       1   BE      NaN      NaN       P2BS  ELE         NaN
 22   10503.691027       1   BE      NaN      NaN       BATS  ELE         NaN
 23     941.731454       1   BE      NaN      NaN       P2BS  ELE         NaN
 24       0.077127       1   BE      NaN      NaN       STUR  NUC         NaN
 25       0.016804       1   BE      NaN      NaN       ASHP  ELE         NaN
 26     148.409598       1   BE      NaN      NaN       GSHP  ELE         NaN
 27      53.877530       1   BE      NaN      NaN       REHE  ELE         NaN
 28    1752.152824       1   BE      NaN      NaN       ASHP  ELE         NaN
 29    1865.287169       1   BE      NaN      NaN       REHE  ELE         NaN
 30       0.018477       1   BE      NaN      NaN       ASHP  ELE         NaN
 31     160.364599       1   BE      NaN      NaN       GSHP  ELE         NaN
 32      44.623008       1   BE      NaN      NaN       REHE  ELE         NaN
 33     441.106458       1   BE      NaN      NaN       ASHP  ELE         NaN
 34     698.614651       1   BE      NaN      NaN       REHE  ELE         NaN
 35      97.131676       1   BE      NaN      NaN       ASHP  ELE         NaN
 36    1720.820370       1   BE      NaN      NaN       COMC  GAS         NaN
 37     860.410185       1   BE      NaN      NaN       GTUR  GAS         NaN
 38     430.205093       1   BE      NaN      NaN       STUR  GAS         NaN
 39     215.102546       1   BE      NaN      NaN       ICEN  GAS         NaN
 40       0.000000       1   BE      NaN      NaN       COMC  GAS         NaN
 41    7197.184446       1   BE      NaN      NaN       REHE  ELE         NaN
 42    1340.037366       1   BE      NaN      NaN       STUR  BIO         NaN
 43     670.018683       1   BE      NaN      NaN       ICEN  BIO         NaN
 44       0.000000       1   BE      NaN      NaN       STUR  BIO         NaN
 45       0.000000       1   BE      NaN      NaN       ICEN  BIO         NaN
 46    1308.000000       1   BE      NaN      NaN       HPHS  WAT         NaN
 47      12.735669       1   BE      NaN      NaN       HDAM  WAT         NaN
 48    2518.604117       1   BE      NaN      NaN       COMC  GAS         NaN
 49       0.000000       1   BE      NaN      NaN       COMC  HYD         NaN
 50     132.558111       1   BE      NaN      NaN       COMC  BIO         NaN
 51    4767.455430       1   BE      NaN      NaN       GTUR  GAS         NaN
 52       0.000000       1   BE      NaN      NaN       GTUR  HYD         NaN
 53     264.858635       1   BE      NaN      NaN       GTUR  OIL         NaN
 54       0.000000       1   BE      NaN      NaN       GTUR  AMO         NaN
 55     264.858635       1   BE      NaN      NaN       GTUR  BIO         NaN
 56       0.000000       1   BE      NaN      NaN       GTUR  WST         NaN
 57       0.000000       1   BE      NaN      NaN       GTUR  OTH         NaN

     ...  STOMaxChargingPower  STOChargingEfficiency  WaterWithdrawal  \
 0   ...                  NaN                    NaN              NaN
 1   ...                  NaN                    NaN              NaN
 2   ...                  NaN                    NaN              NaN
 3   ...                  NaN                    NaN              NaN
 4   ...                  NaN                    NaN              NaN
 5   ...                  NaN                    NaN              NaN
 6   ...                  NaN                    NaN              NaN
 7   ...                  NaN                    NaN              NaN
 8   ...                  NaN                    NaN              NaN
 9   ...                  NaN                    NaN              NaN
 10  ...                  NaN                    NaN              NaN
 11  ...                  NaN                    NaN              NaN
 12  ...                  NaN                    NaN              NaN
 13  ...                  NaN                    NaN              NaN
 14  ...                  NaN                    NaN              NaN
 15  ...                  NaN                    NaN              NaN
 16  ...                  NaN                    NaN              NaN
 17  ...                  NaN                    NaN              NaN
 18  ...                  NaN                    NaN              NaN
 19  ...                  NaN                    NaN              NaN
 20  ...                  NaN                    NaN              NaN
 21  ...                  NaN                    NaN              NaN
 22  ...                  NaN                    NaN              NaN
 23  ...                  NaN                    NaN              NaN
 24  ...                  NaN                    NaN              NaN
 25  ...                  NaN                    NaN              NaN
 26  ...                  NaN                    NaN              NaN
 27  ...                  NaN                    NaN              NaN
 28  ...                  NaN                    NaN              NaN
 29  ...                  NaN                    NaN              NaN
 30  ...                  NaN                    NaN              NaN
 31  ...                  NaN                    NaN              NaN
 32  ...                  NaN                    NaN              NaN
 33  ...                  NaN                    NaN              NaN
 34  ...                  NaN                    NaN              NaN
 35  ...                  NaN                    NaN              NaN
 36  ...                  NaN                    NaN              NaN
 37  ...                  NaN                    NaN              NaN
 38  ...                  NaN                    NaN              NaN
 39  ...                  NaN                    NaN              NaN
 40  ...                  NaN                    NaN              NaN
 41  ...                  NaN                    NaN              NaN
 42  ...                  NaN                    NaN              NaN
 43  ...                  NaN                    NaN              NaN
 44  ...                  NaN                    NaN              NaN
 45  ...                  NaN                    NaN              NaN
 46  ...                  NaN                    NaN              NaN
 47  ...                  NaN                    NaN              NaN
 48  ...                  NaN                    NaN              NaN
 49  ...                  NaN                    NaN              NaN
 50  ...                  NaN                    NaN              NaN
 51  ...                  NaN                    NaN              NaN
 52  ...                  NaN                    NaN              NaN
 53  ...                  NaN                    NaN              NaN
 54  ...                  NaN                    NaN              NaN
 55  ...                  NaN                    NaN              NaN
 56  ...                  NaN                    NaN              NaN
 57  ...                  NaN                    NaN              NaN

     WaterConsumption  Status  Source  Company  Lat  Lon  Lat/Lon
 0                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 1                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 2                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 3                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 4                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 5                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 6                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 7                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 8                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 9                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 10               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 11               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 12               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 13               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 14               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 15               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 16               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 17               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 18               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 19               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 20               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 21               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 22               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 23               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 24               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 25               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 26               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 27               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 28               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 29               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 30               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 31               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 32               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 33               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 34               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 35               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 36               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 37               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 38               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 39               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 40               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 41               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 42               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 43               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 44               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 45               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 46               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 47               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 48               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 49               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 50               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 51               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 52               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 53               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 54               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 55               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 56               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 57               NaN     NaN     NaN      NaN  NaN  NaN      NaN

 [58 rows x 41 columns],
 'FR_2050':     Unnamed: 0                   Unit  PowerCapacity  Nunits Zone  Zone_th  \
 0          NaN     generators offwind     480.000000       1   FR      NaN
 1          NaN  generators offwind-ac   24631.595406       1   FR      NaN
 2          NaN  generators offwind-dc    4617.910333       1   FR      NaN
 3          NaN      generators onwind   63322.378275       1   FR      NaN
 4          NaN         generators ror    6870.649149       1   FR      NaN
 ..         ...                    ...            ...     ...  ...      ...
 56         NaN           links OCGT_3    1014.790724       1   FR      NaN
 57         NaN           links OCGT_4       0.000000       1   FR      NaN
 58         NaN           links OCGT_5    1014.790724       1   FR      NaN
 59         NaN           links OCGT_6       0.000000       1   FR      NaN
 60         NaN           links OCGT_7       0.000000       1   FR      NaN

     Zone_h2 Technology Fuel  Efficiency  ...  STOMaxChargingPower  \
 0       NaN       WTOF  WIN         NaN  ...                  NaN
 1       NaN       WTOF  WIN         NaN  ...                  NaN
 2       NaN       WTOF  WIN         NaN  ...                  NaN
 3       NaN       WTON  WIN         NaN  ...                  NaN
 4       NaN       HROR  WAT         NaN  ...                  NaN
 ..      ...        ...  ...         ...  ...                  ...
 56      NaN       GTUR  OIL         NaN  ...                  NaN
 57      NaN       GTUR  AMO         NaN  ...                  NaN
 58      NaN       GTUR  BIO         NaN  ...                  NaN
 59      NaN       GTUR  WST         NaN  ...                  NaN
 60      NaN       GTUR  OTH         NaN  ...                  NaN

     STOChargingEfficiency  WaterWithdrawal  WaterConsumption  Status  Source  \
 0                     NaN              NaN               NaN     NaN     NaN
 1                     NaN              NaN               NaN     NaN     NaN
 2                     NaN              NaN               NaN     NaN     NaN
 3                     NaN              NaN               NaN     NaN     NaN
 4                     NaN              NaN               NaN     NaN     NaN
 ..                    ...              ...               ...     ...     ...
 56                    NaN              NaN               NaN     NaN     NaN
 57                    NaN              NaN               NaN     NaN     NaN
 58                    NaN              NaN               NaN     NaN     NaN
 59                    NaN              NaN               NaN     NaN     NaN
 60                    NaN              NaN               NaN     NaN     NaN

     Company  Lat  Lon  Lat/Lon
 0       NaN  NaN  NaN      NaN
 1       NaN  NaN  NaN      NaN
 2       NaN  NaN  NaN      NaN
 3       NaN  NaN  NaN      NaN
 4       NaN  NaN  NaN      NaN
 ..      ...  ...  ...      ...
 56      NaN  NaN  NaN      NaN
 57      NaN  NaN  NaN      NaN
 58      NaN  NaN  NaN      NaN
 59      NaN  NaN  NaN      NaN
 60      NaN  NaN  NaN      NaN

 [61 rows x 41 columns],
 'DE_2050':     Unnamed: 0                   Unit  PowerCapacity  Nunits Zone  Zone_th  \
 0          NaN     generators offwind    4846.000000       1   DE      NaN
 1          NaN  generators offwind-ac    5072.330383       1   DE      NaN

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: bold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables.
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [76]:
print (f"Name of the DispaSET Unleash folder:                       {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                       {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                 {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                 {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:            {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:       {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                         {zone_names}\n")
print (f"Target year:                                               {data_target_year}\n")
print (f"Name of the Power Plant DataFrames (dictionary):           {list(power_plants_dfs_dict.keys())}\n")
print (f"Name of the zone_names_equivalences_dictionary):           {[value['Acronym'] for value in selected_zone_names_equivalences_dict.values()]}\n")
print (f"Name of the Overall Fuel Technology Match DataFrame:       overal_fuel_technologies_match_df\n")
print (f"Name of the Fuel Technology Match Dictionary:              fuel_technologies_match_dict\n")
print (f"Name of the PyPSA Nodal Capacities DataFrames (dictionary):{list(nodal_capacities_dfs_dict.keys())}\n")
print (f"Name of the Processed Power Plant DataFrames (dictionary): {list(processed_power_plants_dfs_dict.keys())}\n")

Name of the DispaSET Unleash folder:                       Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                       /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                 PowerPlants

Path to the Power Plants Base data folder:                 /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                PowerPlants

Path to the Power Plants_Pypsa Raw data folder:            /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:       PowerPlants

Path to the Power Plants_Pypsa Formated data folder:       /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                         ['BE', 'FR', 'DE', 'NL', 'UK']

Target year:                                               2050

Name of the Power Plant DataFrames (dictionary):           ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

Name of the zone_names_equivalences_dictionary):           [['  '], ['  '], ['  '], ['  '], ['GB']]

Name of the Overall Fuel Technology Match DataFrame:       overal_fuel_technologies_match_df

Name of the Fuel Technology Match Dictionary:              fuel_technologies_match_dict

Name of the PyPSA Nodal Capacities DataFrames (dictionary):['BE_nodal_capacities_df', 'FR_nodal_capacities_df', 'DE_nodal_capacities_df', 'NL_nodal_capacities_df', 'UK_nodal_capacities_df']

Name of the Processed Power Plant DataFrames (dictionary): ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Erasing rows whit nule Power Capacity.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [77]:
# 1. -------------------------------------------------------------------------- Iterate over each key in the dictionary
for key in list(processed_power_plants_dfs_dict.keys()):
    # Filter out rows where 'PowerCapacity' is 0
    processed_power_plants_dfs_dict[key] = processed_power_plants_dfs_dict[key][
        processed_power_plants_dfs_dict[key]['PowerCapacity'] != 0
    ]

# 2. ------------------------------------------------------------------------------------------------------------- Done
print("✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.")
processed_power_plants_dfs_dict

✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.

{'BE_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 25         NaN              links residential rural air heat pump
 26         NaN           links residential rural ground heat pump
 27         NaN           links residential rural resistive heater
 28         NaN    links residential urban decentral air heat pump
 29         NaN  links residential urban decentral resistive he...
 30         NaN                 links services rural air heat pump
 31         NaN              links services rural ground heat pump
 32         NaN              links services rural resistive heater
 33         NaN       links services urban decentral air heat pump
 34         NaN    links services urban decentral resistive heater
 35         NaN                  links urban central air heat pump
 36         NaN                      links urban central gas CHP_1
 37         NaN                      links urban central gas CHP_2
 38         NaN                      links urban central gas CHP_3
 39         NaN                      links urban central gas CHP_4
 41         NaN               links urban central resistive heater
 42         NaN            links urban central solid biomass CHP_1
 43         NaN            links urban central solid biomass CHP_2
 46         NaN                                  storage_units PHS
 47         NaN                                storage_units hydro
 48         NaN                                       links CCGT_1
 50         NaN                                       links CCGT_3
 51         NaN                                       links OCGT_1
 53         NaN                                       links OCGT_3
 55         NaN                                       links OCGT_5

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0     1549.800000       1   BE      NaN      NaN       WTOF  WIN         NaN
 1     1738.199046       1   BE      NaN      NaN       WTOF  WIN         NaN
 2     4712.000935       1   BE      NaN      NaN       WTOF  WIN         NaN
 3     7247.152421       1   BE      NaN      NaN       WTON  WIN         NaN
 4       59.015340       1   BE      NaN      NaN       HROR  WAT         NaN
 5    12000.040687       1   BE      NaN      NaN       PHOT  SUN         NaN
 6    36199.942807       1   BE      NaN      NaN       PHOT  SUN         NaN
 7     3463.799351       1   BE      NaN      NaN       PEME  ELE         NaN
 8     1731.899675       1   BE      NaN      NaN       ALKE  ELE         NaN
 9      865.949838       1   BE      NaN      NaN       SOXE  ELE         NaN
 10    1918.426570       1   BE      NaN      NaN       PEFC  HYD         NaN
 11     959.213285       1   BE      NaN      NaN       SOFC  HYD         NaN
 12     479.606642       1   BE      NaN      NaN       MCFC  HYD         NaN
 13     239.803321       1   BE      NaN      NaN       PAFC  HYD         NaN
 14     119.901661       1   BE      NaN      NaN       ALFC  HYD         NaN
 15      59.950830       1   BE      NaN      NaN       REFC  HYD         NaN
 16    1909.194752       1   BE      NaN      NaN       GTUR  HYD         NaN
 17     954.597376       1   BE      NaN      NaN       COMC  HYD         NaN
 18     477.298688       1   BE      NaN      NaN       ICEN  HYD         NaN
 19       0.012563       1   BE      NaN      NaN       HBBS  ELE         NaN
 20   34022.652950       1   BE      NaN      NaN       BEVS  ELE         NaN
 21       2.106993       1   BE      NaN      NaN       P2BS  ELE         NaN
 22   10503.691027       1   BE      NaN      NaN       BATS  ELE         NaN
 23     941.731454       1   BE      NaN      NaN       P2BS  ELE         NaN
 24       0.077127       1   BE      NaN      NaN       STUR  NUC         NaN
 25       0.016804       1   BE      NaN      NaN       ASHP  ELE         NaN
 26     148.409598       1   BE      NaN      NaN       GSHP  ELE         NaN
 27      53.877530       1   BE      NaN      NaN       REHE  ELE         NaN
 28    1752.152824       1   BE      NaN      NaN       ASHP  ELE         NaN
 29    1865.287169       1   BE      NaN      NaN       REHE  ELE         NaN
 30       0.018477       1   BE      NaN      NaN       ASHP  ELE         NaN
 31     160.364599       1   BE      NaN      NaN       GSHP  ELE         NaN
 32      44.623008       1   BE      NaN      NaN       REHE  ELE         NaN
 33     441.106458       1   BE      NaN      NaN       ASHP  ELE         NaN
 34     698.614651       1   BE      NaN      NaN       REHE  ELE         NaN
 35      97.131676       1   BE      NaN      NaN       ASHP  ELE         NaN
 36    1720.820370       1   BE      NaN      NaN       COMC  GAS         NaN
 37     860.410185       1   BE      NaN      NaN       GTUR  GAS         NaN
 38     430.205093       1   BE      NaN      NaN       STUR  GAS         NaN
 39     215.102546       1   BE      NaN      NaN       ICEN  GAS         NaN
 41    7197.184446       1   BE      NaN      NaN       REHE  ELE         NaN
 42    1340.037366       1   BE      NaN      NaN       STUR  BIO         NaN
 43     670.018683       1   BE      NaN      NaN       ICEN  BIO         NaN
 46    1308.000000       1   BE      NaN      NaN       HPHS  WAT         NaN
 47      12.735669       1   BE      NaN      NaN       HDAM  WAT         NaN
 48    2518.604117       1   BE      NaN      NaN       COMC  GAS         NaN
 50     132.558111       1   BE      NaN      NaN       COMC  BIO         NaN
 51    4767.455430       1   BE      NaN      NaN       GTUR  GAS         NaN
 53     264.858635       1   BE      NaN      NaN       GTUR  OIL         NaN
 55     264.858635       1   BE      NaN      NaN       GTUR  BIO         NaN

     ...  STOMaxChargingPower  STOChargingEfficiency  WaterWithdrawal  \
 0   ...                  NaN                    NaN              NaN
 1   ...                  NaN                    NaN              NaN
 2   ...                  NaN                    NaN              NaN
 3   ...                  NaN                    NaN              NaN
 4   ...                  NaN                    NaN              NaN
 5   ...                  NaN                    NaN              NaN
 6   ...                  NaN                    NaN              NaN
 7   ...                  NaN                    NaN              NaN
 8   ...                  NaN                    NaN              NaN
 9   ...                  NaN                    NaN              NaN
 10  ...                  NaN                    NaN              NaN
 11  ...                  NaN                    NaN              NaN
 12  ...                  NaN                    NaN              NaN
 13  ...                  NaN                    NaN              NaN
 14  ...                  NaN                    NaN              NaN
 15  ...                  NaN                    NaN              NaN
 16  ...                  NaN                    NaN              NaN
 17  ...                  NaN                    NaN              NaN
 18  ...                  NaN                    NaN              NaN
 19  ...                  NaN                    NaN              NaN
 20  ...                  NaN                    NaN              NaN
 21  ...                  NaN                    NaN              NaN
 22  ...                  NaN                    NaN              NaN
 23  ...                  NaN                    NaN              NaN
 24  ...                  NaN                    NaN              NaN
 25  ...                  NaN                    NaN              NaN
 26  ...                  NaN                    NaN              NaN
 27  ...                  NaN                    NaN              NaN
 28  ...                  NaN                    NaN              NaN
 29  ...                  NaN                    NaN              NaN
 30  ...                  NaN                    NaN              NaN
 31  ...                  NaN                    NaN              NaN
 32  ...                  NaN                    NaN              NaN
 33  ...                  NaN                    NaN              NaN
 34  ...                  NaN                    NaN              NaN
 35  ...                  NaN                    NaN              NaN
 36  ...                  NaN                    NaN              NaN
 37  ...                  NaN                    NaN              NaN
 38  ...                  NaN                    NaN              NaN
 39  ...                  NaN                    NaN              NaN
 41  ...                  NaN                    NaN              NaN
 42  ...                  NaN                    NaN              NaN
 43  ...                  NaN                    NaN              NaN
 46  ...                  NaN                    NaN              NaN
 47  ...                  NaN                    NaN              NaN
 48  ...                  NaN                    NaN              NaN
 50  ...                  NaN                    NaN              NaN
 51  ...                  NaN                    NaN              NaN
 53  ...                  NaN                    NaN              NaN
 55  ...                  NaN                    NaN              NaN

     WaterConsumption  Status  Source  Company  Lat  Lon  Lat/Lon
 0                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 1                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 2                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 3                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 4                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 5                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 6                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 7                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 8                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 9                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 10               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 11               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 12               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 13               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 14               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 15               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 16               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 17               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 18               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 19               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 20               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 21               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 22               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 23               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 24               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 25               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 26               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 27               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 28               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 29               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 30               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 31               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 32               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 33               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 34               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 35               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 36               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 37               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 38               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 39               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 41               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 42               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 43               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 46               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 47               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 48               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 50               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 51               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 53               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 55               NaN     NaN     NaN      NaN  NaN  NaN      NaN

 [50 rows x 41 columns],
 'FR_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 28         NaN              links residential rural air heat pump
 29         NaN           links residential rural ground heat pump
 30         NaN           links residential rural resistive heater
 31         NaN    links residential urban decentral air heat pump
 32         NaN  links residential urban decentral resistive he...
 33         NaN                 links services rural air heat pump
 34         NaN              links services rural ground heat pump
 35         NaN              links services rural resistive heater
 36         NaN       links services urban decentral air heat pump
 37         NaN    links services urban decentral resistive heater
 38         NaN                  links urban central air heat pump
 39         NaN                      links urban central gas CHP_1
 40         NaN                      links urban central gas CHP_2
 41         NaN                      links urban central gas CHP_3
 42         NaN                      links urban central gas CHP_4
 44         NaN               links urban central resistive heater
 45         NaN            links urban central solid biomass CHP_1
 46         NaN            links urban central solid biomass CHP_2
 49         NaN                                  storage_units PHS
 50         NaN                                storage_units hydro
 51         NaN                                       links CCGT_1
 53         NaN                                       links CCGT_3
 54         NaN                                       links OCGT_1
 56         NaN                                       links OCGT_3
 58         NaN                                       links OCGT_5

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0      480.000000       1   FR      NaN      NaN       WTOF  WIN         NaN
 1    24631.595406       1   FR      NaN      NaN       WTOF  WIN         NaN
 2     4617.910333       1   FR      NaN      NaN       WTOF  WIN         NaN
 3    63322.378275       1   FR      NaN      NaN       WTON  WIN         NaN
 4     6870.649149       1   FR      NaN      NaN       HROR  WAT         NaN
 5    17024.222292       1   FR      NaN      NaN       PHOT  SUN         NaN
 6   175286.554430       1   FR      NaN      NaN       PHOT  SUN         NaN
 7     2523.304011       1   FR      NaN      NaN       PEME  ELE         NaN
 8     1261.652005       1   FR      NaN      NaN       ALKE  ELE         NaN
 9      630.826003       1   FR      NaN      NaN       SOXE  ELE         NaN
 10    2318.931377       1   FR      NaN      NaN       PEFC  HYD         NaN
 11    1159.465689       1   FR      NaN      NaN       SOFC  HYD         NaN
 12     579.732844       1   FR      NaN      NaN       MCFC  HYD         NaN
 13     289.866422       1   FR      NaN      NaN       PAFC  HYD         NaN
 14     144.933211       1   FR      NaN      NaN       ALFC  HYD         NaN
 15      72.466606       1   FR      NaN      NaN       REFC  HYD         NaN
 16       0.083942       1   FR      NaN      NaN       GTUR  HYD         NaN
 17       0.041971       1   FR      NaN      NaN       COMC  HYD         NaN
 18       0.020986       1   FR      NaN      NaN       ICEN  HYD         NaN
 19       0.018230       1   FR      NaN      NaN       HBBS  ELE         NaN
 20  195572.300000       1   FR      NaN      NaN       BEVS  ELE         NaN
 21     362.476758       1   FR      NaN      NaN       P2BS  ELE         NaN
 22   36968.817334       1   FR      NaN      NaN       BATS  ELE         NaN
 23     741.038767       1   FR      NaN      NaN       P2BS  ELE         NaN
 24    2660.044043       1   FR      NaN      NaN       STUR  NUC         NaN
 28       0.019334       1   FR      NaN      NaN       ASHP  ELE         NaN
 29    1486.186677       1   FR      NaN      NaN       GSHP  ELE         NaN

<div style="background-color: black;">
  <hr style="border: 1px solid skyblue;">
  <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman'; color: skyblue;">
    8.4. CHP Units Classification
  </div>
  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman'; color: skyblue;">
    The CHP units in Dispaset have the following features:
  </div>
    
  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 11px; font-family: 'Times New Roman'; color: skyblue;">
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue">CHPType</span>
    : This defines the operational characteristic of the CHP plant. It determines how the plant can vary its electricity and heat output.
    <br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">CHPPowerToHeat</span>
    : Also known as the Power-to-Heat Ratio; σ. It's the ratio of electrical power output to useful heat output.
$$ \sigma = \frac{\text{Power Output}}{\text{Heat Output}} $$
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">CHPPowerLossFactor</span>
    : It quantifies the amount of electrical power lost per unit of increased heat extraction. It represents the trade-off, i.e., producing more heat—by extracting steam—results in a loss of potential electricity generation.
    <br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">CHPMaxHeat</span>
    : The highest amount of useful thermal energy—in MWth—that the unit can produce, determined by the size of its heat exchangers and district heating connections.
  </div>

<hr style="border: 2px dashed skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.4.1. CHP Units Nomenclature - CHP Technology List
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The following technologies can be set as CHP units:
<div style="text-align: justify; margin-left:2em; font-weight: unbold; font-size: 11px; font-family: TimesNewRoman; color:skyblue">
    <span style="display: inline-block; width: 6em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue">* Notes</span>
    The CHP technology list may be expanded to cover additional options, e.g. PEME, ALKE and other technologies.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [78]:
# 1. ---------------- Define all the Dispa-SET CHP technology lists from the common.py script of Dispa-SET core scripts
chp_technologies_set = ['COMC', 'COMCX', 'GTUR', 'GTURX', 'ICEN', 'ICENX', 'STUR', 'STURX', 'MCFC', 'PAFC', 'PEFC', 'SOFC' ,
                        'ASHP', 'GSHP' , 'REHE'
                       ]

# 2. ---------------------------------------------------------------------------- Convert the set back to a sorted list
chp_technologies_list = sorted(list(chp_technologies_set))

# 3. ------------------------------------------------------------------------ Create a DataFrame with the single column
dispaSET_chp_tech_list = pd.DataFrame(chp_technologies_list, columns=['Dispa-SET CHP Technologies'])

# 4. -------------------------------------------------------------------------------------------------------------- Done
print(dispaSET_chp_tech_list)

   Dispa-SET CHP Technologies
0                        ASHP
1                        COMC
2                       COMCX
3                        GSHP
4                        GTUR
5                       GTURX
6                        ICEN
7                       ICENX
8                        MCFC
9                        PAFC
10                       PEFC
11                       REHE
12                       SOFC
13                       STUR
14                      STURX

<div style="background-color: black;">
  <hr style="border: 1px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.4.2. CHP Units Nomenclature - CHPType Dictionary
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The dispa-SET CHP technologies nomenclature are loaded from: 
    <br>
    <span style="display: inline-block; margin-left: 2.0em; font-size: 11px">
    "<a href="https://github.com/energy-modelling-toolkit/Dispa-SET/blob/master/dispaset/common.py" style="color:skyblue">https://github.com/energy-modelling-toolkit/Dispa-SET/blob/master/dispaset/common.py</a>"
    </span>
    <br>
    The same is homogenized by the dictionary built in the next cell:   
    <div style="text-align: justify; margin-left:2em; font-weight: unbold; font-size: 11px; font-family: TimesNewRoman; color:skyblue">
    <span style="display: inline-block; width: 6em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue">* Notes</span>
        Keep values of the first column identical to the 'List of CHP types', since it depends of the Dipsa-SET core code.
    <br>
    <span style="display: inline-block; width: 6em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue"></span>
        If the list in the <code>commons.py</code> script changes, the 'chp_type_dictionary' has to be updated accordingly.
    <br>
    <span style="display: inline-block; width: 6em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue"></span>
        This equivalence dictionary is currently limited and requires updating with additional values.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [79]:
# 1. ----------------------------------------- Dictionary mapping CHP types to descriptions and equivalent technologies
chp_type_dict = {
    
"extraction"    :   {"Description": "Extraction Condensing Turbine; Can vary power/heat output flexibly",     "Equivalent_CHPType":  ["-"                                                      ]}  ,
    
"back-pressure" :   {"Description": "Back-Pressure Turbine; Produces power and heat in a fixed ratio"   ,     "Equivalent_CHPType":  ["links urban central gas CHP"                          ,
                                                                                                                                      "links urban central gas CHP CC"                       , 
                                                                                                                                      "links urban central solid biomass CHP"                ,
                                                                                                                                      "links urban central solid biomass CHP CC"               ]}  ,
    
"p2h"           :   {"Description": "Power-to-Heat Unit; Converts electrical energy into heat"          ,     "Equivalent_CHPType":  ["links residential rural air heat pump"                ,          
                                                                                                                                      "links services rural air heat pump"                   ,          
                                                                                                                                      "links residential urban decentral air heat pump"      ,
                                                                                                                                      "links services urban decentral air heat pump"         ,
                                                                                                                                      "links urban central air heat pump"                    , 
                                                                                                                                      "links residential rural ground heat pump"             ,
                                                                                                                                      "links services rural ground heat pump"                ,
                                                                                                                                      "links residential rural resistive heater"            
                                                                                                                                      "links services rural resistive heater"               
                                                                                                                                      "links residential urban decentral resistive heater"   ,
                                                                                                                                      "links services urban decentral resistive heater"      ,  
                                                                                                                                      "links urban central resistive heater"                   ]}

}

# 2. ------------------------------------------------------------------------------------------------------------- Done
print(json.dumps(chp_type_dict, indent=4))

{
    "extraction": {
        "Description": "Extraction Condensing Turbine; Can vary power/heat output flexibly",
        "Equivalent_CHPType": [
            "-"
        ]
    },
    "back-pressure": {
        "Description": "Back-Pressure Turbine; Produces power and heat in a fixed ratio",
        "Equivalent_CHPType": [
            "links urban central gas CHP",
            "links urban central gas CHP CC",
            "links urban central solid biomass CHP",
            "links urban central solid biomass CHP CC"
        ]
    },
    "p2h": {
        "Description": "Power-to-Heat Unit; Converts electrical energy into heat",
        "Equivalent_CHPType": [
            "links residential rural air heat pump",
            "links services rural air heat pump",
            "links residential urban decentral air heat pump",
            "links services urban decentral air heat pump",
            "links urban central air heat pump",
            "links residential rural ground heat pump",
            "links services rural ground heat pump",
            "links residential rural resistive heaterlinks services rural resistive heaterlinks residential urban decentral resistive heater",
            "links services urban decentral resistive heater",
            "links urban central resistive heater"
        ]
    }
}

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Classifying the CHP unit type.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [80]:
# 1. ---------------------------- Assign CHP types to units identified as CHP technologies based on name prefix matches
for key, df in processed_power_plants_dfs_dict.items():
    for index, row in df.iterrows():
        if row['Technology'] in dispaSET_chp_tech_list['Dispa-SET CHP Technologies'].values:
            unit = row['Unit']
            for chp_key, chp_value in chp_type_dict.items():
                
                # 1.1. ------------------------- Check if the unit starts with any of the values in Equivalent_CHPType
                if any(unit.startswith(equivalent) for equivalent in chp_value['Equivalent_CHPType']):
                    df.at[index, 'CHPType'] = chp_key
                    break

# 2. --------------------------------------------------------------------- Print the updated column from the DataFrame
for key, df in processed_power_plants_dfs_dict.items():
    print(f"CHPType column for {key}:")

# 3. ------------------------------------------------------------------------------------------------------------ Done
    print("✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.")
    print(df[['CHPType']])

CHPType column for BE_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
          CHPType
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            NaN
25            p2h
26            p2h
27            NaN
28            p2h
29            NaN
30            p2h
31            p2h
32            NaN
33            p2h
34            p2h
35            p2h
36  back-pressure
37  back-pressure
38  back-pressure
39  back-pressure
41            p2h
42  back-pressure
43  back-pressure
46            NaN
47            NaN
48            NaN
50            NaN
51            NaN
53            NaN
55            NaN
CHPType column for FR_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
          CHPType
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            NaN
28            p2h
29            p2h
30            NaN
31            p2h
32            NaN
33            p2h
34            p2h
35            NaN
36            p2h
37            p2h
38            p2h
39  back-pressure
40  back-pressure
41  back-pressure
42  back-pressure
44            p2h
45  back-pressure
46  back-pressure
49            NaN
50            NaN
51            NaN
53            NaN
54            NaN
56            NaN
58            NaN
CHPType column for DE_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
          CHPType
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            NaN
25            NaN
26            NaN
27            NaN
28            p2h
29            p2h
30            NaN
31            p2h
32            NaN
33            p2h
34            p2h
35            NaN
36            p2h
37            p2h
38            p2h
39  back-pressure
40  back-pressure
41  back-pressure
42  back-pressure
44            p2h
45  back-pressure
46  back-pressure
49            NaN
50            NaN
51            NaN
53            NaN
54            NaN
56            NaN
58            NaN
61            NaN
63            NaN
65            NaN
CHPType column for NL_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
          CHPType
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            p2h
25            p2h
26            NaN
27            p2h
28            NaN
29            p2h
30            p2h
31            NaN
32            p2h
33            p2h
34            p2h
35  back-pressure
36  back-pressure
37  back-pressure
38  back-pressure
40            p2h
41  back-pressure
42  back-pressure
45            NaN
47            NaN
48            NaN
50            NaN
52            NaN
CHPType column for UK_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
          CHPType
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
5             NaN
6             NaN
7             NaN
8             NaN
9             NaN
10            NaN
11            NaN
12            NaN
13            NaN
14            NaN
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20            NaN
21            NaN
22            NaN
23            NaN
24            NaN
25            p2h
26            p2h
27            NaN
28            p2h
29            NaN
30            p2h
31            p2h
32            NaN
33            p2h
34            p2h
35            p2h
36  back-pressure
37  back-pressure
38  back-pressure
39  back-pressure
41            p2h
42  back-pressure
43  back-pressure
46            NaN
47            NaN
48            NaN
50            NaN
51            NaN
53            NaN
55            NaN

/tmp/ipykernel_294897/3509237474.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'p2h' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'CHPType'] = chp_key
/tmp/ipykernel_294897/3509237474.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'p2h' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'CHPType'] = chp_key
/tmp/ipykernel_294897/3509237474.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'p2h' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'CHPType'] = chp_key
/tmp/ipykernel_294897/3509237474.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'p2h' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'CHPType'] = chp_key
/tmp/ipykernel_294897/3509237474.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'p2h' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'CHPType'] = chp_key

<div style="background-color: black;">
  <hr style="border: 1px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.4.3. CHP Units Nomenclature - CHP Features Dictionary
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The CHP features values—CHPPowerToHeat; CHPPowerLossFactor; CHPMaxHeat; COP—are updated into the dictionary from the following sources:
    <br>
    <span style="display: inline-block; margin-left: 2.0em; font-size: 11px">
    1. UROSEVIC, D. et al., 2013: "<a href="https://www.sciencedirect.com/science/article/pii/S0360544213005975" style="color:skyblue">https://www.sciencedirect.com/science/article/pii/S0360544213005975</a>"
    </span>
    <br>
    <span style="display: inline-block; margin-left: 2.0em; font-size: 11px">
    2. LECOMTE, T. et al., 2017: "<a href="https://publications.jrc.ec.europa.eu/repository/handle/JRC107769" style="color:skyblue">https://publications.jrc.ec.europa.eu/repository/handle/JRC107769</a>"
    </span>
    <br>
    <span style="display: inline-block; margin-left: 2.0em; font-size: 11px">
    3. EPA Catalog of CHP Technologies, 2017: "<a href="https://www.epa.gov/sites/default/files/2015-07/documents/catalog_of_chp_technologies.pdf" style="color:skyblue">https://www.epa.gov/sites/default/files/2015-07/documents/catalog_of_chp_technologies.pdf</a>"
    </span>
<hr style="border: 0.5px solid skyblue;">
</div>

In [81]:
# 1. -------------------------------------------------------------------- Dictionary mapping CHP technologies features 
chp_parameters_dict = pd.DataFrame({
    
    'Technology'         :   [  'COMC'                          , 'GTUR'                          , 'STUR'                          , 'ICEN'                          ,
                                'SOXE'                          , 'SOFC'                          , 'MCFC'                          , 'HBBS'                          ,
                                'COMC'                          , 'GTUR'                          , 'STUR'                          , 'ICEN'                          , 
                                'PEME'                          , 'ALKE'                          , 'PEFC'                          , 'PAFC'                          ,
                                'DMFC'                          , 'REFC'                          ,
                                'ASHP'                          , 'GSHP'                          , 'WSHP'                          , 'REHE'                             ],
    
    'CHPType'            :   [  'extraction'                    , 'extraction'                    , 'extraction'                    , 'extraction'                    ,
                                'extraction'                    , 'extraction'                    , 'extraction'                    , 'extraction'                    ,
                                'back-pressure'                 , 'back-pressure'                 , 'back-pressure'                 , 'back-pressure'                 , 
                                'back-pressure'                 , 'back-pressure'                 , 'back-pressure'                 , 'back-pressure'                 ,
                                'back-pressure'                 , 'back-pressure'                 ,
                                'p2h'                           , 'p2h'                           , 'p2h'                           , 'p2h'                              ],
    
    'CHPPowerToHeat'     :   [  0.55                            , 0.45                            , 0.40                            , 0.5                             ,
                                0.20                            , 0.25                            , 0.20                            , 0.20                            ,
                                0.65                            , 0.55                            , 0.6                             , 0.45                            , 
                                0.30                            , 0.35                            , 0.40                            , 0.35                            ,
                                0.45                            , 0.40                            ,
                                None                            , None                            , None                            , None                              ],
    
    'CHPPowerLossFactor' :   [  0.25                            , 0.35                            , 0.3                             , 0.2                             ,
                                0.15                            , 0.12                            , 0.08                            , 0.15                            ,
                                0.00                            , 0.00                            , 0.00                            , 0.00                            , 
                                0.00                            , 0.00                            , 0.00                            , 0.00                            ,
                                0.00                            , 0.00                            ,
                                0.00                            , 0.00                            , 0.00                            , 0.00                              ],
    
    'CHPMaxHeat'         :   [  'PowerCapacity * 1.2'           , 'PowerCapacity * 1.2'           , 'PowerCapacity * 1.2'           , 'PowerCapacity * 1.2'           ,
                                'PowerCapacity * 1.5'           , 'PowerCapacity * 1.5'           , 'PowerCapacity * 1.8'           , 'PowerCapacity * 1.8'           ,
                                'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 
                                'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat',
                                'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat',
                                'PowerCapacity * COP'           , 'PowerCapacity * COP'           , 'PowerCapacity * COP'           , 'PowerCapacity * COP'             ],
                                                                  
    'COP'                :   [  None                            , None                            , None                            , None                            ,
                                None                            , None                            , None                            , None                            ,
                                None                            , None                            , None                            , None                            , 
                                None                            , None                            , None                            , None                            ,
                                None                            , None                            ,
                                2.8                             , 3.5                             , 4.0                             , 1.00                             ]
})

# 2. ------------------------------------------------------------------------------------------------------------ Done
chp_parameters_dict

,Technology,CHPType,CHPPowerToHeat,CHPPowerLossFactor,CHPMaxHeat,COP
0,COMC,extraction,0.55,0.25,PowerCapacity * 1.2,NaN
1,GTUR,extraction,0.45,0.35,PowerCapacity * 1.2,NaN
2,STUR,extraction,0.40,0.30,PowerCapacity * 1.2,NaN
3,ICEN,extraction,0.50,0.20,PowerCapacity * 1.2,NaN
4,SOXE,extraction,0.20,0.15,PowerCapacity * 1.5,NaN
5,SOFC,extraction,0.25,0.12,PowerCapacity * 1.5,NaN
6,MCFC,extraction,0.20,0.08,PowerCapacity * 1.8,NaN
7,HBBS,extraction,0.20,0.15,PowerCapacity * 1.8,NaN
8,COMC,back-pressure,0.65,0.00,PowerCapacity / CHPPowerToHeat,NaN
9,GTUR,back-pressure,0.55,0.00,PowerCapacity / CHPPowerToHeat,NaN
10,STUR,back-pressure,0.60,0.00,PowerCapacity / CHPPowerToHeat,NaN
11,ICEN,back-pressure,0.45,0.00,PowerCapacity / CHPPowerToHeat,NaN
12,PEME,back-pressure,0.30,0.00,PowerCapacity / CHPPowerToHeat,NaN
13,ALKE,back-pressure,0.35,0.00,PowerCapacity / CHPPowerToHeat,NaN
14,PEFC,back-pressure,0.40,0.00,PowerCapacity / CHPPowerToHeat,NaN
15,PAFC,back-pressure,0.35,0.00,PowerCapacity / CHPPowerToHeat,NaN
16,DMFC,back-pressure,0.45,0.00,PowerCapacity / CHPPowerToHeat,NaN
17,REFC,back-pressure,0.40,0.00,PowerCapacity / CHPPowerToHeat,NaN
18,ASHP,p2h,NaN,0.00,PowerCapacity * COP,2.8
19,GSHP,p2h,NaN,0.00,PowerCapacity * COP,3.5
20,WSHP,p2h,NaN,0.00,PowerCapacity * COP,4.0
21,REHE,p2h,NaN,0.00,PowerCapacity * COP,1.0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Fullfilling the CHP features—CHPPowerToHeat; CHPPowerLossFactor; COP—from the CHP parameters dictionary.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [82]:
# 1. ------------------------------------------------------------------ Columns to bring from chp_parameters_dictionary
merge_cols = ['Technology'     , 'CHPType']
param_cols = ['CHPPowerToHeat' , 'CHPPowerLossFactor' , 'CHPMaxHeat' , 'COP']

for zone in zone_names:
    key = f"{zone}_{data_target_year}"
    df = processed_power_plants_dfs_dict[key]

# 1.1. ------------------------------------------------------------------------ Keep only rows with a non-empty CHPType
    mask = df['CHPType'].notna() & (df['CHPType'] != "")

# 1.2. ---------------------------------------------------------------------- Merge only the rows where merge is needed
    df_merge = df.loc[mask, merge_cols].merge(
        chp_parameters_dict,
        on=merge_cols,
        how='left'
    )

# 1.3. ---------------------------------------------------- Assign merged parameter values back into the main dataframe
    df.loc[mask, param_cols] = df_merge[param_cols].values

# 1.4. ---------------------------------------------------------------------------------- Save back into the dictionary
    processed_power_plants_dfs_dict[key] = df

# 2. --------------------------------------------------------------------- Print the updated columns from the DataFrame
for key, df in processed_power_plants_dfs_dict.items():
    print(f"CHPPowerToHeat,	CHPPowerLossFactor, CHPMaxHeat and COP columns for {key}:")

# 3. ------------------------------------------------------------------------------------------------------------- Done
    print("✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.")
    print(df[['CHPPowerToHeat' , 'CHPPowerLossFactor' , 'CHPMaxHeat' , 'COP']])

CHPPowerToHeat,	CHPPowerLossFactor, CHPMaxHeat and COP columns for BE_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
    CHPPowerToHeat  CHPPowerLossFactor                      CHPMaxHeat  COP
0              NaN                 NaN                             NaN  NaN
1              NaN                 NaN                             NaN  NaN
2              NaN                 NaN                             NaN  NaN
3              NaN                 NaN                             NaN  NaN
4              NaN                 NaN                             NaN  NaN
5              NaN                 NaN                             NaN  NaN
6              NaN                 NaN                             NaN  NaN
7              NaN                 NaN                             NaN  NaN
8              NaN                 NaN                             NaN  NaN
9              NaN                 NaN                             NaN  NaN
10             NaN                 NaN                             NaN  NaN
11             NaN                 NaN                             NaN  NaN
12             NaN                 NaN                             NaN  NaN
13             NaN                 NaN                             NaN  NaN
14             NaN                 NaN                             NaN  NaN
15             NaN                 NaN                             NaN  NaN
16             NaN                 NaN                             NaN  NaN
17             NaN                 NaN                             NaN  NaN
18             NaN                 NaN                             NaN  NaN
19             NaN                 NaN                             NaN  NaN
20             NaN                 NaN                             NaN  NaN
21             NaN                 NaN                             NaN  NaN
22             NaN                 NaN                             NaN  NaN
23             NaN                 NaN                             NaN  NaN
24             NaN                 NaN                             NaN  NaN
25             NaN                 0.0             PowerCapacity * COP  2.8
26             NaN                 0.0             PowerCapacity * COP  3.5
27             NaN                 NaN                             NaN  NaN
28             NaN                 0.0             PowerCapacity * COP  2.8
29             NaN                 NaN                             NaN  NaN
30             NaN                 0.0             PowerCapacity * COP  2.8
31             NaN                 0.0             PowerCapacity * COP  3.5
32             NaN                 NaN                             NaN  NaN
33             NaN                 0.0             PowerCapacity * COP  2.8
34             NaN                 0.0             PowerCapacity * COP  1.0
35             NaN                 0.0             PowerCapacity * COP  2.8
36            0.65                 0.0  PowerCapacity / CHPPowerToHeat  NaN
37            0.55                 0.0  PowerCapacity / CHPPowerToHeat  NaN
38            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
39            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
41             NaN                 0.0             PowerCapacity * COP  1.0
42            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
43            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
46             NaN                 NaN                             NaN  NaN
47             NaN                 NaN                             NaN  NaN
48             NaN                 NaN                             NaN  NaN
50             NaN                 NaN                             NaN  NaN
51             NaN                 NaN                             NaN  NaN
53             NaN                 NaN                             NaN  NaN
55             NaN                 NaN                             NaN  NaN
CHPPowerToHeat,	CHPPowerLossFactor, CHPMaxHeat and COP columns for FR_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
    CHPPowerToHeat  CHPPowerLossFactor                      CHPMaxHeat  COP
0              NaN                 NaN                             NaN  NaN
1              NaN                 NaN                             NaN  NaN
2              NaN                 NaN                             NaN  NaN
3              NaN                 NaN                             NaN  NaN
4              NaN                 NaN                             NaN  NaN
5              NaN                 NaN                             NaN  NaN
6              NaN                 NaN                             NaN  NaN
7              NaN                 NaN                             NaN  NaN
8              NaN                 NaN                             NaN  NaN
9              NaN                 NaN                             NaN  NaN
10             NaN                 NaN                             NaN  NaN
11             NaN                 NaN                             NaN  NaN
12             NaN                 NaN                             NaN  NaN
13             NaN                 NaN                             NaN  NaN
14             NaN                 NaN                             NaN  NaN
15             NaN                 NaN                             NaN  NaN
16             NaN                 NaN                             NaN  NaN
17             NaN                 NaN                             NaN  NaN
18             NaN                 NaN                             NaN  NaN
19             NaN                 NaN                             NaN  NaN
20             NaN                 NaN                             NaN  NaN
21             NaN                 NaN                             NaN  NaN
22             NaN                 NaN                             NaN  NaN
23             NaN                 NaN                             NaN  NaN
24             NaN                 NaN                             NaN  NaN
28             NaN                 0.0             PowerCapacity * COP  2.8
29             NaN                 0.0             PowerCapacity * COP  3.5
30             NaN                 NaN                             NaN  NaN
31             NaN                 0.0             PowerCapacity * COP  2.8
32             NaN                 NaN                             NaN  NaN
33             NaN                 0.0             PowerCapacity * COP  2.8
34             NaN                 0.0             PowerCapacity * COP  3.5
35             NaN                 NaN                             NaN  NaN
36             NaN                 0.0             PowerCapacity * COP  2.8
37             NaN                 0.0             PowerCapacity * COP  1.0
38             NaN                 0.0             PowerCapacity * COP  2.8
39            0.65                 0.0  PowerCapacity / CHPPowerToHeat  NaN
40            0.55                 0.0  PowerCapacity / CHPPowerToHeat  NaN
41            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
42            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
44             NaN                 0.0             PowerCapacity * COP  1.0
45            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
46            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
49             NaN                 NaN                             NaN  NaN
50             NaN                 NaN                             NaN  NaN
51             NaN                 NaN                             NaN  NaN
53             NaN                 NaN                             NaN  NaN
54             NaN                 NaN                             NaN  NaN
56             NaN                 NaN                             NaN  NaN
58             NaN                 NaN                             NaN  NaN
CHPPowerToHeat,	CHPPowerLossFactor, CHPMaxHeat and COP columns for DE_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
    CHPPowerToHeat  CHPPowerLossFactor                      CHPMaxHeat  COP
0              NaN                 NaN                             NaN  NaN
1              NaN                 NaN                             NaN  NaN
2              NaN                 NaN                             NaN  NaN
3              NaN                 NaN                             NaN  NaN
4              NaN                 NaN                             NaN  NaN
5              NaN                 NaN                             NaN  NaN
6              NaN                 NaN                             NaN  NaN
7              NaN                 NaN                             NaN  NaN
8              NaN                 NaN                             NaN  NaN
9              NaN                 NaN                             NaN  NaN
10             NaN                 NaN                             NaN  NaN
11             NaN                 NaN                             NaN  NaN
12             NaN                 NaN                             NaN  NaN
13             NaN                 NaN                             NaN  NaN
14             NaN                 NaN                             NaN  NaN
15             NaN                 NaN                             NaN  NaN
16             NaN                 NaN                             NaN  NaN
17             NaN                 NaN                             NaN  NaN
18             NaN                 NaN                             NaN  NaN
19             NaN                 NaN                             NaN  NaN
20             NaN                 NaN                             NaN  NaN
21             NaN                 NaN                             NaN  NaN
22             NaN                 NaN                             NaN  NaN
23             NaN                 NaN                             NaN  NaN
24             NaN                 NaN                             NaN  NaN
25             NaN                 NaN                             NaN  NaN
26             NaN                 NaN                             NaN  NaN
27             NaN                 NaN                             NaN  NaN
28             NaN                 0.0             PowerCapacity * COP  2.8
29             NaN                 0.0             PowerCapacity * COP  3.5
30             NaN                 NaN                             NaN  NaN
31             NaN                 0.0             PowerCapacity * COP  2.8
32             NaN                 NaN                             NaN  NaN
33             NaN                 0.0             PowerCapacity * COP  2.8
34             NaN                 0.0             PowerCapacity * COP  3.5
35             NaN                 NaN                             NaN  NaN
36             NaN                 0.0             PowerCapacity * COP  2.8
37             NaN                 0.0             PowerCapacity * COP  1.0
38             NaN                 0.0             PowerCapacity * COP  2.8
39            0.65                 0.0  PowerCapacity / CHPPowerToHeat  NaN
40            0.55                 0.0  PowerCapacity / CHPPowerToHeat  NaN
41            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
42            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
44             NaN                 0.0             PowerCapacity * COP  1.0
45            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
46            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
49             NaN                 NaN                             NaN  NaN
50             NaN                 NaN                             NaN  NaN
51             NaN                 NaN                             NaN  NaN
53             NaN                 NaN                             NaN  NaN
54             NaN                 NaN                             NaN  NaN
56             NaN                 NaN                             NaN  NaN
58             NaN                 NaN                             NaN  NaN
61             NaN                 NaN                             NaN  NaN
63             NaN                 NaN                             NaN  NaN
65             NaN                 NaN                             NaN  NaN
CHPPowerToHeat,	CHPPowerLossFactor, CHPMaxHeat and COP columns for NL_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
    CHPPowerToHeat  CHPPowerLossFactor                      CHPMaxHeat  COP
0              NaN                 NaN                             NaN  NaN
1              NaN                 NaN                             NaN  NaN
2              NaN                 NaN                             NaN  NaN
3              NaN                 NaN                             NaN  NaN
4              NaN                 NaN                             NaN  NaN
5              NaN                 NaN                             NaN  NaN
6              NaN                 NaN                             NaN  NaN
7              NaN                 NaN                             NaN  NaN
8              NaN                 NaN                             NaN  NaN
9              NaN                 NaN                             NaN  NaN
10             NaN                 NaN                             NaN  NaN
11             NaN                 NaN                             NaN  NaN
12             NaN                 NaN                             NaN  NaN
13             NaN                 NaN                             NaN  NaN
14             NaN                 NaN                             NaN  NaN
15             NaN                 NaN                             NaN  NaN
16             NaN                 NaN                             NaN  NaN
17             NaN                 NaN                             NaN  NaN
18             NaN                 NaN                             NaN  NaN
19             NaN                 NaN                             NaN  NaN
20             NaN                 NaN                             NaN  NaN
21             NaN                 NaN                             NaN  NaN
22             NaN                 NaN                             NaN  NaN
23             NaN                 NaN                             NaN  NaN
24             NaN                 0.0             PowerCapacity * COP  2.8
25             NaN                 0.0             PowerCapacity * COP  3.5
26             NaN                 NaN                             NaN  NaN
27             NaN                 0.0             PowerCapacity * COP  2.8
28             NaN                 NaN                             NaN  NaN
29             NaN                 0.0             PowerCapacity * COP  2.8
30             NaN                 0.0             PowerCapacity * COP  3.5
31             NaN                 NaN                             NaN  NaN
32             NaN                 0.0             PowerCapacity * COP  2.8
33             NaN                 0.0             PowerCapacity * COP  1.0
34             NaN                 0.0             PowerCapacity * COP  2.8
35            0.65                 0.0  PowerCapacity / CHPPowerToHeat  NaN
36            0.55                 0.0  PowerCapacity / CHPPowerToHeat  NaN
37            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
38            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
40             NaN                 0.0             PowerCapacity * COP  1.0
41            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
42            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
45             NaN                 NaN                             NaN  NaN
47             NaN                 NaN                             NaN  NaN
48             NaN                 NaN                             NaN  NaN
50             NaN                 NaN                             NaN  NaN
52             NaN                 NaN                             NaN  NaN
CHPPowerToHeat,	CHPPowerLossFactor, CHPMaxHeat and COP columns for UK_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
    CHPPowerToHeat  CHPPowerLossFactor                      CHPMaxHeat  COP
0              NaN                 NaN                             NaN  NaN
1              NaN                 NaN                             NaN  NaN
2              NaN                 NaN                             NaN  NaN
3              NaN                 NaN                             NaN  NaN
4              NaN                 NaN                             NaN  NaN
5              NaN                 NaN                             NaN  NaN
6              NaN                 NaN                             NaN  NaN
7              NaN                 NaN                             NaN  NaN
8              NaN                 NaN                             NaN  NaN
9              NaN                 NaN                             NaN  NaN
10             NaN                 NaN                             NaN  NaN
11             NaN                 NaN                             NaN  NaN
12             NaN                 NaN                             NaN  NaN
13             NaN                 NaN                             NaN  NaN
14             NaN                 NaN                             NaN  NaN
15             NaN                 NaN                             NaN  NaN
16             NaN                 NaN                             NaN  NaN
17             NaN                 NaN                             NaN  NaN
18             NaN                 NaN                             NaN  NaN
19             NaN                 NaN                             NaN  NaN
20             NaN                 NaN                             NaN  NaN
21             NaN                 NaN                             NaN  NaN
22             NaN                 NaN                             NaN  NaN
23             NaN                 NaN                             NaN  NaN
24             NaN                 NaN                             NaN  NaN
25             NaN                 0.0             PowerCapacity * COP  2.8
26             NaN                 0.0             PowerCapacity * COP  3.5
27             NaN                 NaN                             NaN  NaN
28             NaN                 0.0             PowerCapacity * COP  2.8
29             NaN                 NaN                             NaN  NaN
30             NaN                 0.0             PowerCapacity * COP  2.8
31             NaN                 0.0             PowerCapacity * COP  3.5
32             NaN                 NaN                             NaN  NaN
33             NaN                 0.0             PowerCapacity * COP  2.8
34             NaN                 0.0             PowerCapacity * COP  1.0
35             NaN                 0.0             PowerCapacity * COP  2.8
36            0.65                 0.0  PowerCapacity / CHPPowerToHeat  NaN
37            0.55                 0.0  PowerCapacity / CHPPowerToHeat  NaN
38            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
39            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
41             NaN                 0.0             PowerCapacity * COP  1.0
42            0.60                 0.0  PowerCapacity / CHPPowerToHeat  NaN
43            0.45                 0.0  PowerCapacity / CHPPowerToHeat  NaN
46             NaN                 NaN                             NaN  NaN

/tmp/ipykernel_294897/1903880499.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, param_cols] = df_merge[param_cols].values
/tmp/ipykernel_294897/1903880499.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, param_cols] = df_merge[param_cols].values
/tmp/ipykernel_294897/1903880499.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, param_cols] = df_merge[param_cols].values
/tmp/ipykernel_294897/1903880499.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, param_cols] = df_merge[param_cols].values
/tmp/ipykernel_294897/1903880499.py:20: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity * COP', 'PowerCapacity / CHPPowerToHeat', 'PowerCapacity / CHPPowerToHeat']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[mask, param_cols] = df_merge[param_cols].values

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Fullfilling the CHP features—CHPMaxHeat—from the CHP parameters dictionary formulas.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [83]:
# 1. --------------------------------------------------------------- Pattern to detect words (potential variable names)
formula_pattern = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

for zone in zone_names:
    key = f"{zone}_{data_target_year}"
    df = processed_power_plants_dfs_dict[key]

    for idx, row in df.iterrows():

        cell = row["CHPMaxHeat"]

# 1.1. --------------------------------------------------------------------------------- Skip empty or non-string cells
        if pd.isna(cell) or not isinstance(cell, str) or cell.strip() == "":
            continue

        expression = cell.strip()

# 1.2. -------------------------------------------------------------------------------- Extract possible variable names
        tokens = set(formula_pattern.findall(expression))
        columns_used = [t for t in tokens if t in df.columns]

        if not columns_used:
            
# 1.2.1. ------------------------------------------------------------------------ No valid column names → not a formula
            continue

# 1.3. --------------------------------------------------------------------------- Build evaluation dictionary from row
        local_vars = {}
        valid = True

        for col in columns_used:
            val = row[col]
            if pd.isna(val):
                valid = False
                break
            local_vars[col] = float(val)

        if not valid:
            continue

# 1.4. ------------------------------------------------------------------------------------------------ Safe evaluation
        try:
            
# 1.4.1. ------------------------------------------------------------- Evaluate with NO builtins and ONLY our variables
            result = eval(
                expression,
                {"__builtins__": None},   # Disable all built-ins
                local_vars                # Only allow numeric column values
            )

            df.at[idx, "CHPMaxHeat"] = float(result)

        except Exception as e:
            print(f"⚠️ Error evaluating formula in {key}, row {idx}: '{expression}' → {e}")
            continue

    processed_power_plants_dfs_dict[key] = df

# 2. ---------------------------------------------------------------------- Print the updated column from the DataFrame
for key, df in processed_power_plants_dfs_dict.items():
    print(f"CHPMaxHeat column for {key}:")

# 3. ------------------------------------------------------------------------------------------------------------- Done
    print("✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.")
    print(df[['CHPMaxHeat']])

CHPMaxHeat column for BE_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
     CHPMaxHeat
0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20          NaN
21          NaN
22          NaN
23          NaN
24          NaN
25     0.047052
26   519.433594
27          NaN
28  4906.027908
29          NaN
30     0.051734
31   561.276096
32          NaN
33  1235.098083
34   698.614651
35   271.968693
36  2647.415954
37  1564.382155
38   717.008488
39   478.005658
41  7197.184446
42   2233.39561
43  1488.930406
46          NaN
47          NaN
48          NaN
50          NaN
51          NaN
53          NaN
55          NaN
CHPMaxHeat column for FR_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
      CHPMaxHeat
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
28      0.054134
29    5201.65337
30           NaN
31   13149.25548
32           NaN
33      0.056354
34   4139.350067
35           NaN
36   5809.272433
37   3761.933894
38      0.126174
39  12732.677061
40   7523.854627
41   3448.433371
42    2298.95558
44  26834.374737
45   6445.342659
46   4296.895106
49           NaN
50           NaN
51           NaN
53           NaN
54           NaN
56           NaN
58           NaN
CHPMaxHeat column for DE_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
      CHPMaxHeat
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28      0.043917
29  14836.002251
30           NaN
31  31689.216542
32           NaN
33      0.044305
34   7289.554462
35           NaN
36  11776.136039
37   3298.068412
38      0.079056
39  29044.581067
40  17162.706994
41   7866.240706
42    5244.16047
44  24130.697955
45   9371.250306
46   6247.500204
49           NaN
50           NaN
51           NaN
53           NaN
54           NaN
56           NaN
58           NaN
61           NaN
63           NaN
65           NaN
CHPMaxHeat column for NL_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
      CHPMaxHeat
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24      0.050137
25   1316.286405
26           NaN
27   7842.464298
28           NaN
29      0.025099
30   3289.777963
31           NaN
32   3672.644973
33   1915.203806
34    972.363417
35      0.138746
36      0.081986
37      0.037577
38      0.025051
40  11799.325918
41      0.088609
42      0.059073
45           NaN
47           NaN
48           NaN
50           NaN
52           NaN
CHPMaxHeat column for UK_2050:
✅ Processing complete. Updated DataFrames stored in 'processed_power_plants_dfs_dict'.
      CHPMaxHeat
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
25      0.193416
26   7554.385748
27           NaN
28  29532.188071
29           NaN
30      0.191077
31   2673.433501
32           NaN
33   7850.391312
34    3292.08751
35   3821.752929
36  11874.374392
37   7016.675777
38   3215.976398
39   2143.984265
41  31265.044786
42   2344.249247
43   1562.832831
46           NaN
47           NaN
48           NaN
50           NaN
51           NaN
53           NaN
55           NaN

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables.
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [84]:
print (f"Name of the DispaSET Unleash folder:                        {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                        {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                  {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                  {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                 {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:             {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:        {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:        {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                          {zone_names}\n")
print (f"Target year:                                                {data_target_year}\n")
print (f"Name of the Power Plant DataFrames (dictionary):            {list(power_plants_dfs_dict.keys())}\n")
print (f"Name of the zone_names_equivalences_dictionary):            {[value['Acronym'] for value in selected_zone_names_equivalences_dict.values()]}\n")
print (f"Name of the Overall Fuel Technology Match DataFrame:        overal_fuel_technologies_match_df\n")
print (f"Name of the Fuel Technology Match Dictionary:               fuel_technologies_match_dict\n")
print (f"Name of the PyPSA Nodal Capacities DataFrames (dictionary): {list(nodal_capacities_dfs_dict.keys())}\n")
print (f"Name of the Processed Power Plant DataFrames (dictionary):  {list(processed_power_plants_dfs_dict.keys())}\n")
print (f"name of the dispaSET CHP technologies list:                 dispaSET_chp_tech_list\n")
print (f"Keys of the CHP type dictionary:                            {list(chp_type_dict.keys())}\n")
print (f"Keys of the CHP parameters dictionady:                      {list(chp_parameters_dict.keys())}\n")

Name of the DispaSET Unleash folder:                        Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                        /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                  PowerPlants

Path to the Power Plants Base data folder:                  /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                 PowerPlants

Path to the Power Plants_Pypsa Raw data folder:             /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:        PowerPlants

Path to the Power Plants_Pypsa Formated data folder:        /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                          ['BE', 'FR', 'DE', 'NL', 'UK']

Target year:                                                2050

Name of the Power Plant DataFrames (dictionary):            ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

Name of the zone_names_equivalences_dictionary):            [['  '], ['  '], ['  '], ['  '], ['GB']]

Name of the Overall Fuel Technology Match DataFrame:        overal_fuel_technologies_match_df

Name of the Fuel Technology Match Dictionary:               fuel_technologies_match_dict

Name of the PyPSA Nodal Capacities DataFrames (dictionary): ['BE_nodal_capacities_df', 'FR_nodal_capacities_df', 'DE_nodal_capacities_df', 'NL_nodal_capacities_df', 'UK_nodal_capacities_df']

Name of the Processed Power Plant DataFrames (dictionary):  ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

name of the dispaSET CHP technologies list:                 dispaSET_chp_tech_list

Keys of the CHP type dictionary:                            ['extraction', 'back-pressure', 'p2h']

Keys of the CHP parameters dictionady:                      ['Technology', 'CHPType', 'CHPPowerToHeat', 'CHPPowerLossFactor', 'CHPMaxHeat', 'COP']

<div style="background-color: black;">
  <hr style="border: 1px solid skyblue;">
    
  <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman'; color: skyblue;">
    8.5. Techno-Economic Features Classification
  </div>

  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman'; color: skyblue;">
    The power units have the following features to be set:
  </div>
    
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 11px; font-family: 'Times New Roman'; color: skyblue;">
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">Efficiency</span>
    : Ratio (%) of useful energy output to energy input.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">MinEfficiency</span>
    : Minimum efficiency (%) at part-load operation.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">MinUpTime</span>
    : Minimum time (hours) a unit must remain ON once started before it can be shut down.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">MinDownTime</span>
    : Minimum time (hours) a unit must remain OFF once shut down before it can be restarted.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">RampUpRate</span>
    : Maximum rate (% of rated capacity/min) at which a unit can increase its output.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">RampDownRate</span>
    : Maximum rate (% of rated capacity/min) at which a unit can decrease its output.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">StartUpCost</span>
    : Cost (EUR) incurred when starting the unit from an OFF state.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">NoLoadCost_pu</span>
    : Cost (EUR/h) of keeping the unit ON at zero output.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">RampingCost</span>
    : Additional cost (EUR/MW) associated with changing output—ramping up or down.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">PartLoadMin</span>
    : Minimum output level (% of rated capacity) when the unit is ON.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">StartUpTime</span>
    : Time required (hours) to bring the unit from OFF to ON and ready to produce power.<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">CO2Intensity</span>
    : Amount of tons of CO₂ emitted per MWh of electricity generated.<br>
</div>

  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman'; color: skyblue;">
    To select these parameters, two stages of datasets were used.
      <br>  
    The first dataset was compiled from various sources within the available bibliographic literature:
  </div>

<div style="text-align: justify; margin-left: 2.0em; font-weight: normal; font-size: 11px; font-family: TimesNewRoman; color:skyblue">
<ol style="margin-top: 0; padding-left: 1.5em;">
<li>
DIW. (2013). Current and Prospective Costs of Electricity Generation until 2030.
<br>
<a href="https://www.diw.de/documents/publikationen/73/diw_01.c.424566.de/diw_datadoc_2013-068.pdf" style="color:skyblue">https://www.diw.de/documents/publikationen/73/diw_01.c.424566.de/diw_datadoc_2013-068.pdf</a>
</li>
<li>
DIW (2014). Electricity Sector Data for Policy-Relevant Modeling.
<br>
<a href="https://www.diw.de/documents/publikationen/73/diw_01.c.440963.de/diw_datadoc_2014-072.pdf" style="color:skyblue">https://www.diw.de/documents/publikationen/73/diw_01.c.440963.de/diw_datadoc_2014-072.pdf</a>
</li>
<li>
DIW. (2016). On Start-up Costs of Thermal Power Plants in Markets with Increasing Shares of Fluctuating Renewables.
<br>
<a href="https://d-nb.info/115301274X/34" style="color:skyblue">https://d-nb.info/115301274X/34</a>
</li>
<li>
Hentschel. (2016). Fraunhofer report on power plant flexibility.
<br>
<a href="https://doi.org/10.1016/j.egyr.2016.03.002" style="color:skyblue">https://doi.org/10.1016/j.egyr.2016.03.002</a>
</li>
<li>
Bertsch. (2016). Relevance of Grid Expansion.
<br>
<a href="https://www.ewi.uni-koeln.de/cms/wp-content/uploads/2016/12/WP_15_07-Relevance-of-Grid-Expansion.pdf" style="color:skyblue">https://www.ewi.uni-koeln.de/cms/wp-content/uploads/2016/12/WP_15_07-Relevance-of-Grid-Expansion.pdf</a>
</li>
<li>
IEA. (2011). Technology Roadmap.
<br>
<a href="https://www.iea.org/reports/world-energy-outlook-2011" style="color:skyblue">https://www.iea.org/reports/world-energy-outlook-2011</a>
</li>
<li>
Klobasa et al. (2009). Dynamic simulation of load management and integration of wind energy into an electricity grid.
<br>
<a href="https://publica-rest.fraunhofer.de/server/api/core/bitstreams/8dd2c2f3-d4ab-439b-811e-35c1c99d77d0/content" style="color:skyblue">https://publica-rest.fraunhofer.de/server/api/core/bitstreams/8dd2c2f3-d4ab-439b-811e-35c1c99d77d0/content</a>
</li>
<li>
Traber, Kemfert. (2011). Gone with the wind? — Electricity market prices and incentives to invest in thermal power plants under increasing wind energy supply.
<br>
<a href="https://doi.org/10.1016/j.eneco.2010.07.002" style="color:skyblue">https://doi.org/10.1016/j.eneco.2010.07.002</a>
</li>
<li>
Van der Bergh, Delarue. (2015). Cycling of conventional power plants: Technical limits and actual costs
<br>
<a href="https://doi.org/10.1016/j.enconman.2015.03.026" style="color:skyblue">https://doi.org/10.1016/j.enconman.2015.03.026</a>
</li>
<li>
Parsons Brinckerhoff - DECC. (2014). UK DECC power plant costs report.
<br>
<a href="https://webarchive.nationalarchives.gov.uk" style="color:skyblue">https://webarchive.nationalarchives.gov.uk</a>
</li>
<li>
Ecofys. (2014). Technical Assessment of the Operation of Coal and Gas Plant.
<br>
<a href="https://assets.publishing.service.gov.uk/media/5a7dfc11ed915d74e33ef4be/Technical_Assessment_of_the_Operation_of_Coal_and_Gas_Plant_PB_Power_FIN....pdf" style="color:skyblue">https://assets.publishing.service.gov.uk/media/5a7dfc11ed915d74e33ef4be/Technical_Assessment_of_the_Operation_of_Coal_and_Gas_Plant_PB_Power_FIN....pdf</a>
</li>
<li>
dena. (2005). Deutsche Energie-Agentur reports on efficiency.
<br>
<a href="https://www.dena.de/fileadmin/dena/Dokumente/Pdf/9113_dena-Netzstudie_I.pdf" style="color:skyblue">https://www.dena.de/fileadmin/dena/Dokumente/Pdf/9113_dena-Netzstudie_I.pdf</a>
</li>
<li>
dena. (2008). Energy planning for the grid integration of onshore and offshore wind energy in Germany up to the year 2020
<br> 
<a href="https://www.boell.de/sites/default/files/assets/boell.de/images/download_de/oekologie/Kurzanalyse_KuN_Planung_D_2020_2030_Kurzfassung.pdf" style="color:skyblue">https://www.boell.de/sites/default/files/assets/boell.de/images/download_de/oekologie/Kurzanalyse_KuN_Planung_D_2020_2030_Kurzfassung.pdf</a>
</li>
<li>
RWI. (1997). The International and German Economic Situation in Fall 1997.
<br>    
<a href="https://www.iwh-halle.de/en/publications/detail/the-international-and-german-economic-situation-in-fall-1997" style="color:skyblue">https://www.iwh-halle.de/en/publications/detail/the-international-and-german-economic-situation-in-fall-1997</a>
</li>
<li>
Grimm. (2007). Electricity Market Design: On the Design of Auction Rules at the Energy Exchange (EEX).
<br>
<a href="https://link.springer.com/content/pdf/10.1007/s12398-008-0020-7.pdf" style="color:skyblue">https://link.springer.com/content/pdf/10.1007/s12398-008-0020-7.pdf</a>
</li>
<li>
Kumar et al. (2012). Median cost studies.
<br>
<a href="https://docs.nrel.gov/docs/fy12osti/55433.pdf" style="color:skyblue">https://docs.nrel.gov/docs/fy12osti/55433.pdf</a>
</li>
</ol>
</div>
 
<hr style="border: 2px dashed skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.5.1. Techno-Economic Features Dictionary 1
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The full data for the difetent units, according the technolgy and subtechnology clasification (CHP), fuel type usage and the Power capacity range is loaded.
<div style="text-align: justify; margin-left:2em; font-weight: unbold; font-size: 11px; font-family: TimesNewRoman; color:skyblue">
    <span style="display: inline-block; width: 6em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue">* Notes</span>
    This dictionary is currently incomplete for some technologies and is therefore undergoing continuous revision and updating
    <br>
    <span style="display: inline-block; width: 6em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue"></span>
    Additionally, the sources for some of the recently updated technologies need to be verified and added to the reference sheet in the LookUp_Table file.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [85]:
# 1. ------ Get the path to the "TechnoEconomic_Features_Dictionary_1" and "TechnoEconomic_Features_Dictionary_2" files
additional_path_4 = "/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_1.csv"

technoeconomic_features_dictionary_1_file_path = dispaSET_unleash_folder_path + additional_path_4

print("technoeconomic_features_dictionary_1_file_path:", technoeconomic_features_dictionary_1_file_path)

# 2. -------- Upload the "TechnoEconomic_Features_Dictionary_1" and "TechnoEconomic_Features_Dictionary_2" dictionaries
technoeconomic_features_dictionary_1 = pd.read_csv(technoeconomic_features_dictionary_1_file_path)

# 3. ------------------------------------------------------------------------------------------------------------- Done 
technoeconomic_features_dictionary_1

technoeconomic_features_dictionary_1_file_path: /home/ray/Dispa-SET_Unleash/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_1.csv

,Fuel,Technology,Type / Class,Age bin,PowerCapacity,Efficiency,MinUpTime,MinDownTime,RampUpRate,RampDownRate,...,RampingCost,PartLoadMin,StartUpTime,CHPType,NoLoadCost_pu,MinEfficiency,CO2Intensity,STOSelfDischarge,STOMaxChargingPower,STOChargingEfficiency
0,HRD,STUR,Sub-critical,10.0,400.000,0.397207,9.500,2.250,0.0429,0.0429,...,1.65,0.35,3.70,NaN,NaN,NaN,0.88,NaN,NaN,NaN
1,HRD,STUR,Sub-critical,10.0,400.000,0.371743,9.500,2.250,0.0429,0.0429,...,1.65,0.35,3.70,NaN,NaN,NaN,0.88,NaN,NaN,NaN
2,HRD,STUR,Sub-critical,10.0,150.000,0.371743,9.500,2.250,0.0429,0.0429,...,1.65,0.35,3.70,NaN,NaN,NaN,0.88,NaN,NaN,NaN
3,HRD,STUR,Sub-critical,10.0,150.000,0.315249,9.500,2.250,0.0429,0.0429,...,1.65,0.35,3.70,NaN,NaN,NaN,0.88,NaN,NaN,NaN
4,HRD,STUR,Sub-critical,10.0,7.500,0.315249,9.500,2.250,0.0429,0.0429,...,1.65,0.35,3.70,NaN,NaN,NaN,0.88,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,ELE,GSHP,Services rural ground heat pump,NaN,0.100,1.000000,0.125,0.125,0.8000,0.8000,...,0.00,0.20,0.25,p2h,NaN,1.0,0.00,NaN,NaN,NaN
495,ELE,REHE,Residential rural resistive heater,NaN,0.006,1.000000,0.000,0.000,1.0000,1.0000,...,0.00,0.10,0.00,p2h,NaN,1.0,0.00,NaN,NaN,NaN
496,ELE,REHE,Residential urban decentral resistive heater,NaN,0.004,1.000000,0.000,0.000,1.0000,1.0000,...,0.00,0.10,0.00,p2h,NaN,1.0,0.00,NaN,NaN,NaN
497,ELE,REHE,Services rural resistive heater,NaN,0.100,1.000000,0.000,0.000,1.0000,1.0000,...,0.00,0.15,0.00,p2h,NaN,1.0,0.00,NaN,NaN,NaN
498,ELE,REHE,Services urban decentral resistive heater,NaN,0.020,1.000000,0.000,0.000,1.0000,1.0000,...,0.00,0.15,0.00,p2h,NaN,1.0,0.00,NaN,NaN,NaN

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Filtering the techno-economic parameters according the dictionary 1.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [86]:
# 1. ---------- Enrich power plant DataFrames with technoeconomic parameters by matching technology, fuel, and capacity
def update_dataframes(processed_power_plants_dfs_dict, technoeconomic_features_dictionary_1, zone_names, data_target_year):
    unmatched_rows = []
    numeric_cols = [
        'Efficiency'  , 'MinUpTime'   , 'MinDownTime' , 'RampUpRate'    , 'RampDownRate'  , 'StartUpCost'  , 
        'RampingCost' , 'PartLoadMin' , 'StartUpTime' , 'NoLoadCost_pu' , 'MinEfficiency' ,	'CO2Intensity'
    ]

# 1.2. -------------------------------------------------------------------------------- Iterate Through Zones and Units
    for zone in zone_names:
        key = f"{zone}_{data_target_year}"
        if key not in processed_power_plants_dfs_dict:
            continue

        df = processed_power_plants_dfs_dict[key]

        for idx, row in df.iterrows():
            tech = row['Technology']
            chp = row.get('CHPType', np.nan)
            fuel = row['Fuel']
            power_capacity = row['PowerCapacity']

# 1.3. ------------------------------------------------------------ Find matching rows in the technoeconomic dictionary
            matches = technoeconomic_features_dictionary_1[
                (technoeconomic_features_dictionary_1['Technology'] == tech) &
                (technoeconomic_features_dictionary_1['CHPType'].isna() if pd.isna(chp)
                 else (technoeconomic_features_dictionary_1['CHPType'] == chp)) &
                (technoeconomic_features_dictionary_1['Fuel'] == fuel)
            ]

            if matches.empty:
                unmatched_rows.append((key, idx))
                continue

# 1.4. --------------------------------------------------------------------------------- Find the closest PowerCapacity
            matches = matches.copy()
            matches['CapacityDiff'] = abs(matches['PowerCapacity'] - power_capacity)
            closest_matches = matches[matches['CapacityDiff'] == matches['CapacityDiff'].min()]

# 1.5. -------------------------------------------------------------------------- Calculate average for numeric columns
            for col in numeric_cols:
                if col in closest_matches.columns:
                    df.at[idx, col] = closest_matches[col].mean()

# 1.3. ----------------------------------------------------------------------- Return just the number of unmatched rows
    return len(unmatched_rows)

# 2. --------------------------------------------------------------------------------------------------- Example usage:
num_unmatched = update_dataframes(
    processed_power_plants_dfs_dict,
    technoeconomic_features_dictionary_1,
    zone_names,
    data_target_year
)

# 3. ------------------------------------------------------------------------------------------------------------- Done
print("Number of unmatched rows:", num_unmatched)

Number of unmatched rows: 72

<div style="background-color: black;">
<hr style="border: 1px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.5.2. Techno-Economic Features Dictionary 2
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    The full data for the different units from 30 EU countries in the Dispa-SET database are uploaded for use in a secondary filtering process for all those rows that cannot be found data in the first dictionary
<hr style="border: 0.5px solid skyblue;">
</div>

In [87]:
# 1. -------------------------------------------------- Get the path to the "TechnoEconomic_Features_Dictionary_12 file
additional_path_5 = "/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_2.csv"
technoeconomic_features_dictionary_2_file_path = dispaSET_unleash_folder_path + additional_path_5

print("technoeconomic_features_dictionary_2_file_path:", technoeconomic_features_dictionary_2_file_path)

# 2. ------------------------------------------------------ Upload the "TechnoEconomic_Features_Dictionary_1" dictionay
technoeconomic_features_dictionary_2 = pd.read_csv(technoeconomic_features_dictionary_2_file_path)

# 3. ------------------------------------------------------------------------------------------------------------- Done
technoeconomic_features_dictionary_2

technoeconomic_features_dictionary_2_file_path: /home/ray/Dispa-SET_Unleash/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_2.csv

,PowerCapacity,Unit,Zone,Technology,Fuel,Efficiency,MinUpTime,MinDownTime,RampUpRate,RampDownRate,...,CHPPowerLossFactor,CHPMaxHeat,InitialPower,Type,JRC_id,RampUpMax,RampDownMax,RampStartUpMaximum,RampShutDownMaximum,CostFixed
0,258.000000,Aghada Unit 1,IE,STUR,GAS,0.380,4.0,4.0,0.015000,0.014961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,444.000000,Aghada Unit 2,IE,COMC,GAS,0.530,4.0,1.0,0.019887,0.027883,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,90.000000,Aghada CT 1,IE,GTUR,GAS,0.270,4.0,1.0,0.055556,0.055556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90.000000,Aghada CT 2,IE,GTUR,GAS,0.260,4.0,1.0,0.055556,0.055556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,90.000000,Aghada CT 4,IE,GTUR,GAS,0.270,4.0,1.0,0.055556,0.055556,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,9.675118,HU_ICEN_GAS,HU,ICEN,GAS,0.490,0.0,0.0,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
982,503.265000,HU_STUR_LIG,HU,STUR,LIG,0.393,8.0,8.0,0.015210,0.017483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
983,943.395000,HU_STUR_NUC,HU,STUR,NUC,1.000,24.0,24.0,0.003333,0.003333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
984,49.000000,HU_PHOT_SUN,HU,PHOT,SUN,1.000,0.0,0.0,0.020000,0.020000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
985,328.000000,HU_WTON_WIN,HU,WTON,WIN,1.000,0.0,0.0,0.020000,0.020000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Filtering the techno-economic parameters according the dictionary 2.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [88]:
# 1. ---------- Enrich power plant DataFrames with technoeconomic parameters by matching technology, fuel, and capacity
def update_empty_dataframes(processed_power_plants_dfs_dict, technoeconomic_features_dictionary_2, zone_names, data_target_year):
    unmatched_rows = []
    numeric_cols = [
        'Efficiency'  , 'MinUpTime'   , 'MinDownTime' , 'RampUpRate'    , 'RampDownRate'  , 'StartUpCost'  ,
        'RampingCost' , 'PartLoadMin' , 'StartUpTime' , 'NoLoadCost_pu' , 'MinEfficiency' , 'CO2Intensity'
    ]

# 1.2. -------------------------------------------------------------------------------- Iterate Through Zones and Units    
    for zone in zone_names:
        key = f"{zone}_{data_target_year}"
        if key not in processed_power_plants_dfs_dict:
            continue

        df = processed_power_plants_dfs_dict[key]

        for idx, row in df.iterrows():
            
# 1.2.1. -------------------------------------------------------------- Check if all numeric columns are empty or NaN
            if not all(pd.isna(row[col]) or row[col] == '' for col in numeric_cols):
                continue  # Skip if any numeric column has a value

            tech = row['Technology']
            chp = row.get('CHPType', np.nan)
            fuel = row['Fuel']
            power_capacity = row['PowerCapacity']

# 1.2.2. -------------------------------------------------------- Find matching rows in the technoeconomic dictionary
            matches = technoeconomic_features_dictionary_2[
                (technoeconomic_features_dictionary_2['Technology'] == tech) &
                (technoeconomic_features_dictionary_2['CHPType'].isna()
                 if pd.isna(chp)
                 else (technoeconomic_features_dictionary_2['CHPType'] == chp)) &
                (technoeconomic_features_dictionary_2['Fuel'] == fuel)
            ]

            if matches.empty:
                unmatched_rows.append((key, idx))
                continue

# 1.2.3. ----------------------------------------------------------------------------- Find the closest PowerCapacity
            matches = matches.copy()
            matches['CapacityDiff'] = abs(matches['PowerCapacity'] - power_capacity)
            closest_matches = matches[matches['CapacityDiff'] == matches['CapacityDiff'].min()]

# 1.2.4. ---------------------------------------------------------------------- Calculate average for numeric columns
            for col in numeric_cols:
                if col in closest_matches.columns:
                    df.at[idx, col] = closest_matches[col].mean()

# 1.3. --------------------------------------------------------------------- Return just the number of unmatched rows
    return len(unmatched_rows)
    
# 2. -------------------------------------------------------------------------------------------------- Example usage:
num_unmatched = update_empty_dataframes(
    processed_power_plants_dfs_dict,
    technoeconomic_features_dictionary_2,
    zone_names,
    data_target_year
)

# 3. ------------------------------------------------------------------------------------------------------------ Done 
print("Number of unmatched rows:", num_unmatched)

Number of unmatched rows: 77

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Since the initial classification used 'Fuel', 'Technology', 'PowerCapacity', and 'CHPType' as discrimination parameters to find the most accurate unit data, and because the resulting dictionaries do not cover all possible parameter combinations, the next step will involve assigning techno-economic parameters based solely on the technology type category.
<br>
These parameters will be calculated as the average of all found matches within Dictionary 1.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [89]:
# 1. ---------- Enrich power plant DataFrames with technoeconomic parameters by matching technology, fuel, and capacity
def update_dataframes(processed_power_plants_dfs_dict, technoeconomic_features_dictionary_1, zone_names, data_target_year):
    unmatched_rows = []
    numeric_cols = [
        'Efficiency'  , 'MinUpTime'   , 'MinDownTime' , 'RampUpRate'    , 'RampDownRate'  , 'StartUpCost'  , 
        'RampingCost' , 'PartLoadMin' , 'StartUpTime' , 'NoLoadCost_pu' , 'MinEfficiency' ,	'CO2Intensity'
    ]
    
# 1.2. -------------------------------------------------------------------------------- Iterate Through Zones and Units    
    for zone in zone_names:
        key = f"{zone}_{data_target_year}"
        if key not in processed_power_plants_dfs_dict:
            continue

        df = processed_power_plants_dfs_dict[key]

        for idx, row in df.iterrows():
            tech = row['Technology']
            power_capacity = row['PowerCapacity']

# 1.2.1. --------------------------------------------------------------------------------- MATCH USING ONLY TECHNOLOGY
            matches = technoeconomic_features_dictionary_1[
                technoeconomic_features_dictionary_1['Technology'] == tech
            ]

            if matches.empty:
                unmatched_rows.append((key, idx))
                continue

# 1.2.2. ----------------------------------------------------------------------------- Find the closest PowerCapacity
            matches = matches.copy()
            matches['CapacityDiff'] = abs(matches['PowerCapacity'] - power_capacity)
            closest_matches = matches[matches['CapacityDiff'] == matches['CapacityDiff'].min()]

# 1.2.3. -------------------------------------------------------------------------- Fill numeric values with averages
            for col in numeric_cols:
                if col in closest_matches.columns:
                    df.at[idx, col] = closest_matches[col].mean()

# 1.3. ---------------------------------------------------------------------- Return just the number of unmatched rows    
    return len(unmatched_rows)

# 2. -------------------------------------------------------------------------------------------------- Example usage:
num_unmatched = update_dataframes(
    processed_power_plants_dfs_dict,
    technoeconomic_features_dictionary_1,
    zone_names,
    data_target_year
)

# 3. ------------------------------------------------------------------------------------------------------------ Done
print("Number of unmatched rows:", num_unmatched)

Number of unmatched rows: 0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
This step repeats the logic from the previous cell, but uses Dictionary 2.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [90]:
# 1. ---------- Enrich power plant DataFrames with technoeconomic parameters by matching technology, fuel, and capacity
def update_dataframes(processed_power_plants_dfs_dict, technoeconomic_features_dictionary_2, zone_names, data_target_year):
    unmatched_rows = []
    numeric_cols = [
        'Efficiency'  , 'MinUpTime'   , 'MinDownTime' , 'RampUpRate'    , 'RampDownRate'  , 'StartUpCost'  , 
        'RampingCost' , 'PartLoadMin' , 'StartUpTime' , 'NoLoadCost_pu' , 'MinEfficiency' ,	'CO2Intensity'
    ]

# 1.2. --------------------------------------------------------------------------------- Iterate Through Zones and Units    
    for zone in zone_names:
        key = f"{zone}_{data_target_year}"
        if key not in processed_power_plants_dfs_dict:
            continue

        df = processed_power_plants_dfs_dict[key]

        for idx, row in df.iterrows():
            tech = row['Technology']
            power_capacity = row['PowerCapacity']

# 1.2.1. ----------------------------------------------------------------------------------- MATCH USING ONLY TECHNOLOGY
            matches = technoeconomic_features_dictionary_2[
                technoeconomic_features_dictionary_2['Technology'] == tech
            ]

            if matches.empty:
                unmatched_rows.append((key, idx))
                continue

# 1.2.2. -------------------------------------------------------------------------------- Find the closest PowerCapacity
            matches = matches.copy()
            matches['CapacityDiff'] = abs(matches['PowerCapacity'] - power_capacity)
            closest_matches = matches[matches['CapacityDiff'] == matches['CapacityDiff'].min()]

# 1.2.3. ----------------------------------------------------------------------------- Fill numeric values with averages
            for col in numeric_cols:
                if col in closest_matches.columns:
                    df.at[idx, col] = closest_matches[col].mean()

# 1.3. ------------------------------------------------------------------------ Return just the number of unmatched rows    
    return len(unmatched_rows)

# 2. ---------------------------------------------------------------------------------------------------- Example usage:
num_unmatched = update_dataframes(
    processed_power_plants_dfs_dict,
    technoeconomic_features_dictionary_2,
    zone_names,
    data_target_year
)

# ----------------------------------------------------------------------------------------------------------------- Done
print("Number of unmatched rows:", num_unmatched)

Number of unmatched rows: 125

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Filling the remaining empty fields for all power units.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables | Parameters | Dictionaries | Lists | Others
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [91]:
print (f"Name of the DispaSET Unleash folder:                        {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                        {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                  {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                  {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                 {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:             {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:        {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:        {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                          {zone_names}\n")
print (f"Target year:                                                {data_target_year}\n")
print (f"Name of the Power Plant DataFrames (dictionary):            {list(power_plants_dfs_dict.keys())}\n")
print (f"Name of the zone_names_equivalences_dictionary):            {[value['Acronym'] for value in selected_zone_names_equivalences_dict.values()]}\n")
print (f"Name of the Overall Fuel Technology Match DataFrame:        overal_fuel_technologies_match_df\n")
print (f"Name of the Fuel Technology Match Dictionary:               fuel_technologies_match_dict\n")
print (f"Name of the PyPSA Nodal Capacities DataFrames (dictionary): {list(nodal_capacities_dfs_dict.keys())}\n")
print (f"Name of the Processed Power Plant DataFrames (dictionary):  {list(processed_power_plants_dfs_dict.keys())}\n")
print (f"name of the dispaSET CHP technologies list:                 dispaSET_chp_tech_list\n")
print (f"Keys of the CHP type dictionary:                            {list(chp_type_dict.keys())}\n")
print (f"Keys of the CHP parameters dictionady:                      {list(chp_parameters_dict.keys())}\n")
print (f"Path to the Technoeconomic Features Dictionary 1 file:      {technoeconomic_features_dictionary_1_file_path}\n")
print (f"Path to the Technoeconomic Features Dictionary 2 file:      {technoeconomic_features_dictionary_2_file_path}\n")

Name of the DispaSET Unleash folder:                        Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                        /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                  PowerPlants

Path to the Power Plants Base data folder:                  /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                 PowerPlants

Path to the Power Plants_Pypsa Raw data folder:             /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:        PowerPlants

Path to the Power Plants_Pypsa Formated data folder:        /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                          ['BE', 'FR', 'DE', 'NL', 'UK']

Target year:                                                2050

Name of the Power Plant DataFrames (dictionary):            ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

Name of the zone_names_equivalences_dictionary):            [['  '], ['  '], ['  '], ['  '], ['GB']]

Name of the Overall Fuel Technology Match DataFrame:        overal_fuel_technologies_match_df

Name of the Fuel Technology Match Dictionary:               fuel_technologies_match_dict

Name of the PyPSA Nodal Capacities DataFrames (dictionary): ['BE_nodal_capacities_df', 'FR_nodal_capacities_df', 'DE_nodal_capacities_df', 'NL_nodal_capacities_df', 'UK_nodal_capacities_df']

Name of the Processed Power Plant DataFrames (dictionary):  ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

name of the dispaSET CHP technologies list:                 dispaSET_chp_tech_list

Keys of the CHP type dictionary:                            ['extraction', 'back-pressure', 'p2h']

Keys of the CHP parameters dictionady:                      ['Technology', 'CHPType', 'CHPPowerToHeat', 'CHPPowerLossFactor', 'CHPMaxHeat', 'COP']

Path to the Technoeconomic Features Dictionary 1 file:      /home/ray/Dispa-SET_Unleash/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_1.csv

Path to the Technoeconomic Features Dictionary 2 file:      /home/ray/Dispa-SET_Unleash/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_2.csv

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
  <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 17px; font-family: 'Times New Roman'; color: skyblue;">
    8.6. Storage Features Classification
  </div>

  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman'; color: skyblue;">
    The power units have the following storage features to be set:
  </div>
    
<div style="text-align: justify; margin-left: 3.0em; font-weight: normal; font-size: 11px; font-family: 'Times New Roman'; color: skyblue;">
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">STOCapacity</span>
    : The maximum amount of energy (or fuel) that the storage unit can hold. This defines the overall size of the reservoir ($\text{e.g., MWh}$ or $\text{GJ}$).<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">STOSelfDischarge</span>
    : The rate at which stored energy is lost over time, even when the unit is not actively charging or discharging. This represents internal leakage or standby consumption ($\text{e.g., } \%/\text{day}$ or $\text{p.u.}$).<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">STOMaxChargingPower</span>
    : The maximum rate ($\text{e.g., MW}$) at which the storage unit can absorb energy (charge). This is limited by the capacity of the charging equipment (the converter).<br>
    <span style="display: inline-block; width: 12em; font-weight: bold; font-family: 'Times New Roman'; color: skyblue;">STOChargingEfficiency</span>
    : The ratio of energy added to the storage unit to the electrical energy input required to charge it. It accounts for losses during the charging process ($\text{e.g., } 0.90$ or $90\%$).<br>
</div>
<hr style="border: 2px dashed skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.6.1.  Storage Features Power Units List
    </div>
  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman'; color: skyblue;">
    To select these parameters—excluding STOCapacity at this stage—the following list identifies the power units that incorporate storage features, as defined by the Dispa-SET documentation.
</div>
<div style="text-align: justify; margin-left:2em; font-weight: unbold; font-size: 12px; font-family: TimesNewRoman; color:skyblue">
    * Notes: &nbsp;&nbsp; This list need to be updated according to the pending or implemented changes in the<code>commons.py</code> script.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [92]:
# 1. Define all the Dispa-SET power units whit storage features lists from the common.py script of Dispa-SET core scripts
dispaSET_storage_features_power_unit_list = [ 'HDAM' , 'HPHS' , 'BATS' , 'BEVS' , 'CAES' , 'SCSP' ]

# 2. -------------------------------------------------------------------------- Create a DataFrame with the single column 
dispaSET_storage_features_power_unit_list = pd.DataFrame(dispaSET_storage_features_power_unit_list, columns=['Dispa-SET Storage Features Power Units'])

# 3. --------------------------------------------------------------------------------------------------------------- Done
dispaSET_storage_features_power_unit_list

  Dispa-SET Storage Features Power Units
0                                   HDAM
1                                   HPHS
2                                   BATS
3                                   BEVS
4                                   CAES
5                                   SCSP

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
    Dictionary 1.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [93]:
# 1. ---------- Enrich power plant DataFrames with technoeconomic parameters by matching technology, fuel, and capacity
def update_dataframes(processed_power_plants_dfs_dict, technoeconomic_features_dictionary_1, zone_names, data_target_year, storage_tech_list):
    unmatched_rows = []
    numeric_cols = [
        'STOSelfDischarge' , 'STOMaxChargingPower' , 'STOChargingEfficiency'
    ]

# 1.2. -------------------------------------------------------------------------------- Iterate Through Zones and Units    
    for zone in zone_names:
        key = f"{zone}_{data_target_year}"
        if key not in processed_power_plants_dfs_dict:
            continue
        df = processed_power_plants_dfs_dict[key]
        for idx, row in df.iterrows():
            tech = row['Technology']
            
# 1.2.1. ----------------------------------------------- Only process rows where Technology is in the storage_tech_list
            if tech not in storage_tech_list.values:
                continue
            power_capacity = row['PowerCapacity']
            
# 1.2.2. ---------------------------------------------------------------------------------- Match using only Technology
            matches = technoeconomic_features_dictionary_1[
                technoeconomic_features_dictionary_1['Technology'] == tech
            ]
            if matches.empty:
                unmatched_rows.append((key, idx))
                continue
                
# 1.2.3. ------------------------------------------------------------------------------- Find the closest PowerCapacity
            matches = matches.copy()
            matches['CapacityDiff'] = abs(matches['PowerCapacity'] - power_capacity)
            closest_matches = matches[matches['CapacityDiff'] == matches['CapacityDiff'].min()]
            
# 1.2.4. ---------------------------------------------------------------------------- Fill numeric values with averages
            for col in numeric_cols:
                if col in closest_matches.columns:
                    df.at[idx, col] = closest_matches[col].mean()

# 1.3. ----------------------------------------------------------------------- Return just the number of unmatched rows    
    return len(unmatched_rows)

# 2. ---------------------------------------------------------------------------------------------------- Example usage:
num_unmatched = update_dataframes(
    processed_power_plants_dfs_dict,
    technoeconomic_features_dictionary_1,
    zone_names,
    data_target_year,
    dispaSET_storage_features_power_unit_list
)

# 3. -------------------------------------------------------------------------------------------------------------- Done
print("Number of unmatched rows:", num_unmatched)

Number of unmatched rows: 0

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Dictionary 2.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [94]:
# 1. ---------- Enrich power plant DataFrames with technoeconomic parameters by matching technology, fuel, and capacity
def update_dataframes(processed_power_plants_dfs_dict, technoeconomic_features_dictionary_2, zone_names, data_target_year, storage_tech_list):
    unmatched_rows = []
    numeric_cols = [
        'STOSelfDischarge' , 'STOMaxChargingPower' , 'STOChargingEfficiency'
    ]

    # 1.2. ---------------------------------------------------------------------------- Iterate Through Zones and Units    
    for zone in zone_names:
        key = f"{zone}_{data_target_year}"
        if key not in processed_power_plants_dfs_dict:
            continue
        df = processed_power_plants_dfs_dict[key]
        for idx, row in df.iterrows():
            tech = row['Technology']
            
            # 1.2.1. ----------------------------------- Only process rows where Technology is in the storage_tech_list
            if tech not in storage_tech_list.values:
                continue
            power_capacity = row['PowerCapacity']
            
            # 1.2.2. ---------------------------------------------------------------------- Match using only Technology
            matches = technoeconomic_features_dictionary_2[
                technoeconomic_features_dictionary_2['Technology'] == tech
            ]
            if matches.empty:
                unmatched_rows.append((key, idx))
                continue
                
            # 1.2.3. ------------------------------------------------------------------- Find the closest PowerCapacity
            matches = matches.copy()
            matches['CapacityDiff'] = abs(matches['PowerCapacity'] - power_capacity)
            closest_matches = matches[matches['CapacityDiff'] == matches['CapacityDiff'].min()]
            
            # 1.2.4. ---------------------------------------------------------------- Fill numeric values with averages
            for col in numeric_cols:
                if col in closest_matches.columns:
                    df.at[idx, col] = closest_matches[col].mean()

    # 1.3. ------------------------------------------------------------------- Return just the number of unmatched rows    
    return len(unmatched_rows)

# 2. ---------------------------------------------------------------------------------------------------- Example usage
num_unmatched = update_dataframes(
    processed_power_plants_dfs_dict,
    technoeconomic_features_dictionary_2,
    zone_names,
    data_target_year,
    dispaSET_storage_features_power_unit_list
)

# 3. ------------------------------------------------------------------------------------------------------------- Done
print("Number of unmatched rows:", num_unmatched)

Number of unmatched rows: 5

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
When a unit's exact Power Capacity value is not available in the lookup dictionaries, an average is calculated using data from the most closely matched units. Consequently, the calculated STOMaxChargingPower must be checked to ensure it is less than or equal to the unit's corresponding Power Capacity, and the calculated STOChargingEfficiency must be checked against its respective total Efficiency.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [95]:
# 1. ---------------------------------------------------------------------------------------- Iterate through the zones
for zone in zone_names:
    
    # 1.1. --------------------------------------------------------------------------------------------- Data Retrieval
    key = f"{zone}_{data_target_year}"
    if key in processed_power_plants_dfs_dict:
        df = processed_power_plants_dfs_dict[key]
        mismatch_count = 0

        # 1.1.2. --------------------------------------------------------------------- Consistency Check and Correction 
        for index, row in df.iterrows():
            if row['PowerCapacity'] < row['STOMaxChargingPower'] or row['Efficiency'] < row['STOChargingEfficiency']:
                mismatch_count += 1

                # 1.1.2.1. ------------------------------------------- Cap charging power at the maximum power capacity
                if row['PowerCapacity'] < row['STOMaxChargingPower']:
                    df.at[index, 'STOMaxChargingPower'] = row['PowerCapacity']

                # 1.1.2.2. ---------------------------------- Cap charging efficiency at the discharge efficiency level
                if row['Efficiency'] < row['STOChargingEfficiency']:
                    df.at[index, 'STOChargingEfficiency'] = row['Efficiency']

# 2. ------------------------------------------------------------------------------------------------------------- Done
        print(f"Found {mismatch_count} rows with mismatched values for {key}")

Found 0 rows with mismatched values for BE_2050
Found 0 rows with mismatched values for FR_2050
Found 2 rows with mismatched values for DE_2050
Found 0 rows with mismatched values for NL_2050
Found 2 rows with mismatched values for UK_2050

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 16px; font-family: TimesNewRoman; color:skyblue">
    8.6.2.  Power Units Storage Capacity
    </div>
  <div style="text-align: justify; margin-left: 0.0em; font-weight: normal; font-size: 14px; font-family: 'Times New Roman'; color: skyblue;">
    To select the 'STOCapacity' the follwing storage technology correlation will be used:
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [96]:
# 1. -------------------------------------------------------- Dictionary mapping Dispa-SET acronyms to PyPSA tech names
tech_storage_equivalences_dict = {
    
# -----------------------
# Renewable Power Units
# -----------------------
"generators offwind"                       :  {"tech": ["WTOF"                                                    ] ,   "fuel": ["WIN"                                                     ] ,   "storage": [" "                     ]}  ,
"generators offwind-ac"                    :  {"tech": ["WTOF"                                                    ] ,   "fuel": ["WIN"                                                     ] ,   "storage": [" "                     ]}  ,
"generators offwind-dc"                    :  {"tech": ["WTOF"                                                    ] ,   "fuel": ["WIN"                                                     ] ,   "storage": [" "                     ]}  ,
    
"generators onwind"                        :  {"tech": ["WTON"                                                    ] ,   "fuel": ["WIN"                                                     ] ,   "storage": [" "                     ]}  ,

"generators solar"                         :  {"tech": ["PHOT"                                                    ] ,   "fuel": ["SUN"                                                     ] ,   "storage": [" "                     ]}  ,
"generators solar rooftop"                 :  {"tech": ["PHOT"                                                    ] ,   "fuel": ["SUN"                                                     ] ,   "storage": [" "                     ]}  ,

"generators ror"                           :  {"tech": ["HROR"                                                    ] ,   "fuel": ["WAT"                                                     ] ,   "storage": [" "                     ]}  ,
# -----------------------
# Conventional Power Units
# -----------------------
"links Lignite"                            :  {"tech": ["STUR"                                                    ] ,   "fuel": ["LIG"                                                     ] ,   "storage": ["stores lignite"        ]}  ,
    
"links nuclear"                            :  {"tech": ["STUR"                                                    ] ,   "fuel": ["NUC"                                                     ] ,   "storage": ["stores uranium"        ]}  ,

"links CCGT"                               :  {"tech": ["COMC"                                                    ] ,   "fuel": ["GAS"  , "HYD"  , "BIO"                                   ] ,   "storage": ["stores gas"            ]}  ,
    
"links OCGT"                               :  {"tech": ["GTUR"                                                    ] ,   "fuel": ["GAS"  , "HYD"  , "OIL"  , "AMO" , "BIO" , "WST" , "OTH"  ] ,   "storage": ["stores gas"            ]}  ,

"links oil"                                :  {"tech": ["GTUR"  , "ICEN"  , "STUR"                                ] ,   "fuel": ["OIL"                                                     ] ,   "storage": ["stores oil"            ]}  ,

"links coal"                               :  {"tech": ["STUR"  , "COMC"  , "GTUR"                                ] ,   "fuel": ["HRD"  , "PEA"                                            ] ,   "storage": ["store coal"            ]}  ,
# -----------------------
# Storage Units
# -----------------------
"links V2G"                                :  {"tech": ["BEVS"                                                    ] ,   "fuel": ["ELE"                                                     ] ,   "storage": [" "                     ]}  ,
    
"links battery discharger"                 :  {"tech": ["BATS"                                                    ] ,   "fuel": ["ELE"                                                     ] ,   "storage": ["stores battery"        ]}  ,
    
"storage_units hydro"                      :  {"tech": ["HDAM"                                                    ] ,   "fuel": ["WAT"                                                     ] ,   "storage": [" "                     ]}  ,
    
"storage_units PHS"                        :  {"tech": ["HPHS"                                                    ] ,   "fuel": ["WAT"                                                     ] ,   "storage": [" "                     ]}  ,
# -----------------------
# Combined Heat and Power Units
# -----------------------
"links urban central gas CHP"              :  {"tech": ["COMC"  , "GTUR"  , "STUR"  , "ICEN"                      ] ,   "fuel": ["GAS"                                                     ] ,   "storage": ["stores gas"            ]}  ,
"links urban central gas CHP CC"           :  {"tech": ["COMC"                                                    ] ,   "fuel": ["GAS"                                                     ] ,   "storage": ["stores gas"            ]}  ,

"links urban central solid biomass CHP"    :  {"tech": ["STUR"  , "ICEN"                                          ] ,   "fuel": ["BIO"                                                     ] ,   "storage": ["stores solid biomass"  ]}  ,
"links urban central solid biomass CHP CC" :  {"tech": ["STUR"  , "ICEN"                                          ] ,   "fuel": ["BIO"                                                     ] ,   "storage": ["stores solid biomass"  ]}  ,
# -----------------------
# Sector X Units
# -----------------------
"links H2 Electrolysis"                    :  {"tech": ["PEME"  , "ALKE"  , "SOXE"                                ] ,   "fuel": ["HYD"                                                     ] ,   "storage": ["stores H2"             ]}  ,
    
"links H2 Fuel Cell"                       :  {"tech": ["PEFC"  , "SOFC"  , "MCFC"  , "PAFC"  , "ALFC"  , "REFC"  ] ,   "fuel": ["HYD"                                                     ] ,   "storage": ["stores H2"             ]}  ,
"links H2 turbine"                         :  {"tech": ["GTUR"  , "COMC"  , "ICEN"                                ] ,   "fuel": ["HYD"                                                     ] ,   "storage": ["stores H2"             ]}  ,

"links Haber-Bosch"                        :  {"tech": ["HBBS"                                                    ] ,   "fuel": ["AMO"                                                     ] ,   "storage": ["stores NH3"            ]}  ,
    
"links DAC"                                :  {"tech": ["P2GS"                                                    ] ,   "fuel": ["OTH"                                                     ] ,   "storage": ["stores co2 stored"     ]}  ,

"links methanolisation"                    :  {"tech": ["P2BS"                                                    ] ,   "fuel": ["OTH"                                                     ] ,   "storage": ["stores methanol"       ]}  ,
    
}

# 2. ------------------------------------------------------------------------------------------------------------- Done
tech_equivalences_dict

{'generators offwind': {'tech': ['WTOF'], 'fuel': ['WIN']},
 'generators offwind-ac': {'tech': ['WTOF'], 'fuel': ['WIN']},
 'generators offwind-dc': {'tech': ['WTOF'], 'fuel': ['WIN']},
 'generators onwind': {'tech': ['WTON'], 'fuel': ['WIN']},
 'generators solar': {'tech': ['PHOT'], 'fuel': ['SUN']},
 'generators solar rooftop': {'tech': ['PHOT'], 'fuel': ['SUN']},
 'generators ror': {'tech': ['HROR'], 'fuel': ['WAT']},
 'links Lignite': {'tech': ['STUR'], 'fuel': ['LIG']},
 'links nuclear': {'tech': ['STUR'], 'fuel': ['NUC']},
 'links CCGT': {'tech': ['COMC'], 'fuel': ['GAS', 'HYD', 'BIO']},
 'links OCGT': {'tech': ['GTUR'],
  'fuel': ['GAS', 'HYD', 'OIL', 'AMO', 'BIO', 'WST', 'OTH']},
 'links oil': {'tech': ['GTUR', 'ICEN', 'STUR'], 'fuel': ['OIL']},
 'links coal': {'tech': ['STUR', 'COMC', 'GTUR'], 'fuel': ['HRD', 'PEA']},
 'links V2G': {'tech': ['BEVS'], 'fuel': ['ELE']},
 'links battery discharger': {'tech': ['BATS'], 'fuel': ['ELE']},
 'storage_units hydro': {'tech': ['HDAM'], 'fuel': ['WAT']},
 'storage_units PHS': {'tech': ['HPHS'], 'fuel': ['WAT']},
 'links urban central gas CHP': {'tech': ['COMC', 'GTUR', 'STUR', 'ICEN'],
  'fuel': ['GAS']},
 'links urban central gas CHP CC': {'tech': ['COMC'], 'fuel': ['GAS']},
 'links urban central solid biomass CHP': {'tech': ['STUR', 'ICEN'],
  'fuel': ['BIO']},
 'links urban central solid biomass CHP CC': {'tech': ['STUR', 'ICEN'],
  'fuel': ['BIO']},
 'links residential rural air heat pump': {'tech': ['ASHP'], 'fuel': ['ELE']},
 'links services rural air heat pump': {'tech': ['ASHP'], 'fuel': ['ELE']},
 'links residential urban decentral air heat pump': {'tech': ['ASHP'],
  'fuel': ['ELE']},
 'links services urban decentral air heat pump': {'tech': ['ASHP'],
  'fuel': ['ELE']},
 'links urban central air heat pump': {'tech': ['ASHP'], 'fuel': ['ELE']},
 'links residential rural ground heat pump': {'tech': ['GSHP'],
  'fuel': ['ELE']},
 'links services rural ground heat pump': {'tech': ['GSHP'], 'fuel': ['ELE']},
 'links residential rural resistive heater': {'tech': ['REHE'],
  'fuel': ['ELE']},
 'links services rural resistive heater': {'tech': ['REHE'], 'fuel': ['ELE']},
 'links residential urban decentral resistive heater': {'tech': ['REHE'],
  'fuel': ['ELE']},
 'links services urban decentral resistive heater': {'tech': ['REHE'],
  'fuel': ['ELE']},
 'links urban central resistive heater': {'tech': ['REHE'], 'fuel': ['ELE']},
 'links H2 Electrolysis': {'tech': ['PEME', 'ALKE', 'SOXE'], 'fuel': ['ELE']},
 'links H2 Fuel Cell': {'tech': ['PEFC',
   'SOFC',
   'MCFC',
   'PAFC',
   'ALFC',
   'REFC'],
  'fuel': ['HYD']},
 'links H2 turbine': {'tech': ['GTUR', 'COMC', 'ICEN'], 'fuel': ['HYD']},
 'links Haber-Bosch': {'tech': ['HBBS'], 'fuel': ['ELE']},
 'links ammonia cracker': {'tech': ['P2BS'], 'fuel': ['ELE']},
 'links methanolisation': {'tech': ['P2BS'], 'fuel': ['ELE']}}

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Filling the 'STOCapacity' parameter.
    </div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [97]:
# 1. ---------------------------------------------------------------------------- Map storage capacities to power units
for zone in zone_names:

    # 1.1 --------------------------------------------------------------------------- Data Retrieval and Key Validation
    key_pp = f"{zone}_{data_target_year}"
    key_nodal = f"{zone}_nodal_capacities_df"

    if key_pp not in processed_power_plants_dfs_dict or key_nodal not in nodal_capacities_dfs_dict:
        print(f"Skipping {key_pp} or {key_nodal} not found.")
        continue

    df_pp = processed_power_plants_dfs_dict[key_pp]
    df_nodal = nodal_capacities_dfs_dict[key_nodal]

    for index, row in df_pp.iterrows():
        tech = row['Technology']
        unit = row['Unit']

        # 1.1.2. --------------------------------------------------------- Check if Technology is in the Dispa-SET list
        if tech not in dispaSET_storage_features_power_unit_list['Dispa-SET Storage Features Power Units'].values:
            print(f"Row {index} in {key_pp}: Technology '{tech}' not in Dispa-SET Storage Features Power Units list.")
            continue

        # 1.1.3. ---------------------------------------- Check if Unit matches a key in tech_storage_equivalences_dict
        if unit in tech_storage_equivalences_dict:
            storage = tech_storage_equivalences_dict[unit]['storage']
            if isinstance(storage, list) and len(storage) != 1:
                print(f"Row {index} in {key_pp}: Unit '{unit}' has invalid storage entries.")
                continue
            storage = storage if isinstance(storage, list) else [storage]
        else:
            # 1.1.3.1. ----------------------------------------------------- Find the closest match with numeric suffix
            base_unit = unit.split('_')[0]
            matches = get_close_matches(base_unit, tech_storage_equivalences_dict.keys(), n=1, cutoff=0.8)
            if not matches:
                print(f"Row {index} in {key_pp}: No close match for Unit '{unit}'.")
                continue
            closest_unit = matches[0]
            storage = tech_storage_equivalences_dict[closest_unit]['storage']
            if isinstance(storage, list) and len(storage) != 1:
                print(f"Row {index} in {key_pp}: Closest Unit '{closest_unit}' has invalid storage entries.")
                continue
            storage = storage if isinstance(storage, list) else [storage]

        # 1.1.4. ------------------------------------------------------ Get the capacity from nodal_capacities_dfs_dict
        tech_match = df_nodal[df_nodal['tech'] == storage[0]]
        if tech_match.empty:
            print(f"Row {index} in {key_pp}: No matching tech '{storage[0]}' in nodal capacities.")
            continue

        capacity = tech_match[str(data_target_year)].values[0]
        df_pp.at[index, 'STOCapacity'] = capacity

# 2. ------------------------------------------------------------------------------------ Output the updated DataFrames
for key, df in processed_power_plants_dfs_dict.items():
    print(f"\nUpdated DataFrame for {key}:")

# 3. ------------------------------------------------------------------------------------------------------------- Done
    print(df)

Row 0 in BE_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 1 in BE_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 2 in BE_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 3 in BE_2050: Technology 'WTON' not in Dispa-SET Storage Features Power Units list.
Row 4 in BE_2050: Technology 'HROR' not in Dispa-SET Storage Features Power Units list.
Row 5 in BE_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 6 in BE_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 7 in BE_2050: Technology 'PEME' not in Dispa-SET Storage Features Power Units list.
Row 8 in BE_2050: Technology 'ALKE' not in Dispa-SET Storage Features Power Units list.
Row 9 in BE_2050: Technology 'SOXE' not in Dispa-SET Storage Features Power Units list.
Row 10 in BE_2050: Technology 'PEFC' not in Dispa-SET Storage Features Power Units list.
Row 11 in BE_2050: Technology 'SOFC' not in Dispa-SET Storage Features Power Units list.
Row 12 in BE_2050: Technology 'MCFC' not in Dispa-SET Storage Features Power Units list.
Row 13 in BE_2050: Technology 'PAFC' not in Dispa-SET Storage Features Power Units list.
Row 14 in BE_2050: Technology 'ALFC' not in Dispa-SET Storage Features Power Units list.
Row 15 in BE_2050: Technology 'REFC' not in Dispa-SET Storage Features Power Units list.
Row 16 in BE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 17 in BE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 18 in BE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 19 in BE_2050: Technology 'HBBS' not in Dispa-SET Storage Features Power Units list.
Row 20 in BE_2050: No matching tech ' ' in nodal capacities.
Row 21 in BE_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 23 in BE_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 24 in BE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 25 in BE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 26 in BE_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 27 in BE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 28 in BE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 29 in BE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 30 in BE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 31 in BE_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 32 in BE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 33 in BE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 34 in BE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 35 in BE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 36 in BE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 37 in BE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 38 in BE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 39 in BE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 41 in BE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 42 in BE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 43 in BE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 46 in BE_2050: No matching tech ' ' in nodal capacities.
Row 47 in BE_2050: No matching tech ' ' in nodal capacities.
Row 48 in BE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 50 in BE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 51 in BE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 53 in BE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 55 in BE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 0 in FR_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 1 in FR_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 2 in FR_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 3 in FR_2050: Technology 'WTON' not in Dispa-SET Storage Features Power Units list.
Row 4 in FR_2050: Technology 'HROR' not in Dispa-SET Storage Features Power Units list.
Row 5 in FR_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 6 in FR_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 7 in FR_2050: Technology 'PEME' not in Dispa-SET Storage Features Power Units list.
Row 8 in FR_2050: Technology 'ALKE' not in Dispa-SET Storage Features Power Units list.
Row 9 in FR_2050: Technology 'SOXE' not in Dispa-SET Storage Features Power Units list.
Row 10 in FR_2050: Technology 'PEFC' not in Dispa-SET Storage Features Power Units list.
Row 11 in FR_2050: Technology 'SOFC' not in Dispa-SET Storage Features Power Units list.
Row 12 in FR_2050: Technology 'MCFC' not in Dispa-SET Storage Features Power Units list.
Row 13 in FR_2050: Technology 'PAFC' not in Dispa-SET Storage Features Power Units list.
Row 14 in FR_2050: Technology 'ALFC' not in Dispa-SET Storage Features Power Units list.
Row 15 in FR_2050: Technology 'REFC' not in Dispa-SET Storage Features Power Units list.
Row 16 in FR_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 17 in FR_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 18 in FR_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 19 in FR_2050: Technology 'HBBS' not in Dispa-SET Storage Features Power Units list.
Row 20 in FR_2050: No matching tech ' ' in nodal capacities.
Row 21 in FR_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 23 in FR_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 24 in FR_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 28 in FR_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 29 in FR_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 30 in FR_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 31 in FR_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 32 in FR_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 33 in FR_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 34 in FR_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 35 in FR_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 36 in FR_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 37 in FR_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 38 in FR_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 39 in FR_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 40 in FR_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 41 in FR_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 42 in FR_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 44 in FR_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 45 in FR_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 46 in FR_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 49 in FR_2050: No matching tech ' ' in nodal capacities.
Row 50 in FR_2050: No matching tech ' ' in nodal capacities.
Row 51 in FR_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 53 in FR_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 54 in FR_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 56 in FR_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 58 in FR_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 0 in DE_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 1 in DE_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 2 in DE_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 3 in DE_2050: Technology 'WTON' not in Dispa-SET Storage Features Power Units list.
Row 4 in DE_2050: Technology 'HROR' not in Dispa-SET Storage Features Power Units list.
Row 5 in DE_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 6 in DE_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 7 in DE_2050: Technology 'PEME' not in Dispa-SET Storage Features Power Units list.
Row 8 in DE_2050: Technology 'ALKE' not in Dispa-SET Storage Features Power Units list.
Row 9 in DE_2050: Technology 'SOXE' not in Dispa-SET Storage Features Power Units list.
Row 10 in DE_2050: Technology 'PEFC' not in Dispa-SET Storage Features Power Units list.
Row 11 in DE_2050: Technology 'SOFC' not in Dispa-SET Storage Features Power Units list.
Row 12 in DE_2050: Technology 'MCFC' not in Dispa-SET Storage Features Power Units list.
Row 13 in DE_2050: Technology 'PAFC' not in Dispa-SET Storage Features Power Units list.
Row 14 in DE_2050: Technology 'ALFC' not in Dispa-SET Storage Features Power Units list.
Row 15 in DE_2050: Technology 'REFC' not in Dispa-SET Storage Features Power Units list.
Row 16 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 17 in DE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 18 in DE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 19 in DE_2050: Technology 'HBBS' not in Dispa-SET Storage Features Power Units list.
Row 20 in DE_2050: No matching tech ' ' in nodal capacities.
Row 21 in DE_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 23 in DE_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 24 in DE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 25 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 26 in DE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 27 in DE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 28 in DE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 29 in DE_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 30 in DE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 31 in DE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 32 in DE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 33 in DE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 34 in DE_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 35 in DE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 36 in DE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 37 in DE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 38 in DE_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 39 in DE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 40 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 41 in DE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 42 in DE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 44 in DE_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 45 in DE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 46 in DE_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 49 in DE_2050: No matching tech ' ' in nodal capacities.
Row 50 in DE_2050: No matching tech ' ' in nodal capacities.
Row 51 in DE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 53 in DE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 54 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 56 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 58 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 61 in DE_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 63 in DE_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 65 in DE_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 0 in NL_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 1 in NL_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 2 in NL_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 3 in NL_2050: Technology 'WTON' not in Dispa-SET Storage Features Power Units list.
Row 4 in NL_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 5 in NL_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 6 in NL_2050: Technology 'PEME' not in Dispa-SET Storage Features Power Units list.
Row 7 in NL_2050: Technology 'ALKE' not in Dispa-SET Storage Features Power Units list.
Row 8 in NL_2050: Technology 'SOXE' not in Dispa-SET Storage Features Power Units list.
Row 9 in NL_2050: Technology 'PEFC' not in Dispa-SET Storage Features Power Units list.
Row 10 in NL_2050: Technology 'SOFC' not in Dispa-SET Storage Features Power Units list.
Row 11 in NL_2050: Technology 'MCFC' not in Dispa-SET Storage Features Power Units list.
Row 12 in NL_2050: Technology 'PAFC' not in Dispa-SET Storage Features Power Units list.
Row 13 in NL_2050: Technology 'ALFC' not in Dispa-SET Storage Features Power Units list.
Row 14 in NL_2050: Technology 'REFC' not in Dispa-SET Storage Features Power Units list.
Row 15 in NL_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 16 in NL_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 17 in NL_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 18 in NL_2050: Technology 'HBBS' not in Dispa-SET Storage Features Power Units list.
Row 19 in NL_2050: No matching tech ' ' in nodal capacities.
Row 20 in NL_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 22 in NL_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 23 in NL_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 24 in NL_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 25 in NL_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 26 in NL_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 27 in NL_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 28 in NL_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 29 in NL_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 30 in NL_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 31 in NL_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 32 in NL_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 33 in NL_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 34 in NL_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 35 in NL_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 36 in NL_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 37 in NL_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 38 in NL_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 40 in NL_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 41 in NL_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 42 in NL_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 45 in NL_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 47 in NL_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 48 in NL_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 50 in NL_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 52 in NL_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 0 in UK_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 1 in UK_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 2 in UK_2050: Technology 'WTOF' not in Dispa-SET Storage Features Power Units list.
Row 3 in UK_2050: Technology 'WTON' not in Dispa-SET Storage Features Power Units list.
Row 4 in UK_2050: Technology 'HROR' not in Dispa-SET Storage Features Power Units list.
Row 5 in UK_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 6 in UK_2050: Technology 'PHOT' not in Dispa-SET Storage Features Power Units list.
Row 7 in UK_2050: Technology 'PEME' not in Dispa-SET Storage Features Power Units list.
Row 8 in UK_2050: Technology 'ALKE' not in Dispa-SET Storage Features Power Units list.
Row 9 in UK_2050: Technology 'SOXE' not in Dispa-SET Storage Features Power Units list.
Row 10 in UK_2050: Technology 'PEFC' not in Dispa-SET Storage Features Power Units list.
Row 11 in UK_2050: Technology 'SOFC' not in Dispa-SET Storage Features Power Units list.
Row 12 in UK_2050: Technology 'MCFC' not in Dispa-SET Storage Features Power Units list.
Row 13 in UK_2050: Technology 'PAFC' not in Dispa-SET Storage Features Power Units list.
Row 14 in UK_2050: Technology 'ALFC' not in Dispa-SET Storage Features Power Units list.
Row 15 in UK_2050: Technology 'REFC' not in Dispa-SET Storage Features Power Units list.
Row 16 in UK_2050: Technology 'GTUR' not in Dispa-SET Storage Features Power Units list.
Row 17 in UK_2050: Technology 'COMC' not in Dispa-SET Storage Features Power Units list.
Row 18 in UK_2050: Technology 'ICEN' not in Dispa-SET Storage Features Power Units list.
Row 19 in UK_2050: Technology 'HBBS' not in Dispa-SET Storage Features Power Units list.
Row 20 in UK_2050: No matching tech ' ' in nodal capacities.
Row 21 in UK_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 23 in UK_2050: Technology 'P2BS' not in Dispa-SET Storage Features Power Units list.
Row 24 in UK_2050: Technology 'STUR' not in Dispa-SET Storage Features Power Units list.
Row 25 in UK_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 26 in UK_2050: Technology 'GSHP' not in Dispa-SET Storage Features Power Units list.
Row 27 in UK_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.
Row 28 in UK_2050: Technology 'ASHP' not in Dispa-SET Storage Features Power Units list.
Row 29 in UK_2050: Technology 'REHE' not in Dispa-SET Storage Features Power Units list.

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
For the specific case of hydro units (Hydro dams; Hydro pumped) technology, the following raw sources will be used:
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [98]:
# 1. ---------------------------- Get the path to the "Dispa-SET_Unleash_Reservoir_Levels" folder of the PyPSA raw data
additional_path_6 = os.path.join("RawData_PyPSA", pypsa_scenario, "HydroData/energy_stored")
reservoir_level_pypsa_raw_data_folder_path = dispaSET_unleash_folder_path + '/' + additional_path_6

# 2. ---------------------- Construct the Dispa-SET_Unleash_Reservoir_Levels_folder_name variable of the PyPSA raw data
reservoir_level_pypsa_raw_data_folder_name = os.path.basename(reservoir_level_pypsa_raw_data_folder_path)

# 3. ------------------------------------------------------------------------------------------------------------- Done
print("reservoir_level_pypsa_raw_data_folder_name:", reservoir_level_pypsa_raw_data_folder_name)
print("reservoir_level_pypsa_raw_data_folder_path:", reservoir_level_pypsa_raw_data_folder_path)

reservoir_level_pypsa_raw_data_folder_name: energy_stored
reservoir_level_pypsa_raw_data_folder_path: /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/HydroData/energy_stored

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
A dedicated dictionary for conventional hydro units is need to be defined.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [99]:
# 1. -------------------------------------------------------- Dictionary mapping Dispa-SET acronyms to PyPSA tech names
hydro_tech_equivalences_dict = {
    
                            # -----------------------
                            # Renewable Power Units
                            # -----------------------
                            "HPHS"  :  {"tech": ["PHS"    , ] ,   "fuel": ["WAT"    ]} ,
    
                            "HDAM"  :  {"tech": ["hydro"  , ] ,   "fuel": ["WAT"    ]} ,
       
                         }

# 2. ------------------------------------------------------------------------------------------------------------- Done
hydro_tech_equivalences_dict

{'HPHS': {'tech': ['PHS'], 'fuel': ['WAT']},
 'HDAM': {'tech': ['hydro'], 'fuel': ['WAT']}}

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
<div style="text-align: right; margin-left: 3.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman;color:skyblue">
    Tracking Variables | Parameters | Dictionaries | Lists | Others
</div>
    <div style="text-align: right; margin-left: 1.50em; font-weight: unbold; font-size: 13px; font-family: TimesNewRoman;color:skyblue">
    This cells are just to confirm all the file names, file paths and other information related to the data being processed.
    <br>
  Also are used to ensure the inputs for next cells in order to avoid to re-enter the same information each time.
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [100]:
print (f"Name of the DispaSET Unleash folder:                        {dispaSET_unleash_folder_name}\n")
print (f"Path to the DispaSET Unleash folder:                        {dispaSET_unleash_folder_path}\n")
print (f"Name of the Power Plants Base data folder:                  {power_plants_base_data_folder_name}\n")
print (f"Path to the Power Plants Base data folder:                  {power_plants_base_data_folder_path}\n")
print (f"Name of Power Plants_Pypsa Raw data folder:                 {power_plants_pypsa_raw_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Raw data folder:             {power_plants_pypsa_raw_data_folder_path}\n")
print (f"Name of the Power Plants_Pypsa Formated data folder:        {power_plants_pypsa_formated_data_folder_name}\n")
print (f"Path to the Power Plants_Pypsa Formated data folder:        {power_plants_pypsa_formated_data_folder_path}\n")
print (f"Name of the zones:                                          {zone_names}\n")
print (f"Target year:                                                {data_target_year}\n")
print (f"Name of the Power Plant DataFrames (dictionary):            {list(power_plants_dfs_dict.keys())}\n")
print (f"Name of the Technologies Equivalences Dictionary:           tech_equivalences_dict\n")
print (f"Name of the Overall Fuel Technology Match DataFrame:        overal_fuel_technologies_match_df\n")
print (f"Name of the Fuel Technology Match Dictionary:               fuel_technologies_match_dict\n")
print (f"Name of the PyPSA Nodal Capacities DataFrames (dictionary): {list(nodal_capacities_dfs_dict.keys())}\n")
print (f"Name of the Processed Power Plant DataFrames (dictionary):  {list(processed_power_plants_dfs_dict.keys())}\n")
print (f"name of the dispaSET CHP technologies list:                 dispaSET_chp_tech_list\n")
print (f"Keys of the CHP type dictionary:                            {list(chp_type_dict.keys())}\n")
print (f"Keys of the CHP parameters dictionady:                      {list(chp_parameters_dict.keys())}\n")
print (f"Path to the Technoeconomic Features Dictionary 1 file:      {technoeconomic_features_dictionary_1_file_path}\n")
print (f"Path to the Technoeconomic Features Dictionary 2 file:      {technoeconomic_features_dictionary_2_file_path}\n")
print (f"Name of the Storage Features Power Units list:              dispaSET_storage_features_power_unit_list\n")
print (f"Name of the Reservoir Levels_Pypsa Raw data folder:         {reservoir_level_pypsa_raw_data_folder_name}\n")
print (f"Path to the Reservoir Levels_Pypsa Raw data folder:         {reservoir_level_pypsa_raw_data_folder_path}\n")
print (f"Name of the Hydro Storage Technologies dictionary:          {list(hydro_tech_equivalences_dict.keys())}\n")

Name of the DispaSET Unleash folder:                        Dispa-SET_Unleash

Path to the DispaSET Unleash folder:                        /home/ray/Dispa-SET_Unleash

Name of the Power Plants Base data folder:                  PowerPlants

Path to the Power Plants Base data folder:                  /home/ray/Dispa-SET_Unleash/Database/PowerPlants

Name of Power Plants_Pypsa Raw data folder:                 PowerPlants

Path to the Power Plants_Pypsa Raw data folder:             /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the Power Plants_Pypsa Formated data folder:        PowerPlants

Path to the Power Plants_Pypsa Formated data folder:        /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants

Name of the zones:                                          ['BE', 'FR', 'DE', 'NL', 'UK']

Target year:                                                2050

Name of the Power Plant DataFrames (dictionary):            ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

Name of the Technologies Equivalences Dictionary:           tech_equivalences_dict

Name of the Overall Fuel Technology Match DataFrame:        overal_fuel_technologies_match_df

Name of the Fuel Technology Match Dictionary:               fuel_technologies_match_dict

Name of the PyPSA Nodal Capacities DataFrames (dictionary): ['BE_nodal_capacities_df', 'FR_nodal_capacities_df', 'DE_nodal_capacities_df', 'NL_nodal_capacities_df', 'UK_nodal_capacities_df']

Name of the Processed Power Plant DataFrames (dictionary):  ['BE_2050', 'FR_2050', 'DE_2050', 'NL_2050', 'UK_2050']

name of the dispaSET CHP technologies list:                 dispaSET_chp_tech_list

Keys of the CHP type dictionary:                            ['extraction', 'back-pressure', 'p2h']

Keys of the CHP parameters dictionady:                      ['Technology', 'CHPType', 'CHPPowerToHeat', 'CHPPowerLossFactor', 'CHPMaxHeat', 'COP']

Path to the Technoeconomic Features Dictionary 1 file:      /home/ray/Dispa-SET_Unleash/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_1.csv

Path to the Technoeconomic Features Dictionary 2 file:      /home/ray/Dispa-SET_Unleash/scripts/Unleash_PyPSA_DispaSET_Raw_Data_Processing/Coefficients_Sources/TechnoEconomic_Features_Dictionary_2.csv

Name of the Storage Features Power Units list:              dispaSET_storage_features_power_unit_list

Name of the Reservoir Levels_Pypsa Raw data folder:         energy_stored

Path to the Reservoir Levels_Pypsa Raw data folder:         /home/ray/Dispa-SET_Unleash/RawData_PyPSA/Sufficiency_Scenario/HydroData/energy_stored

Name of the Hydro Storage Technologies dictionary:          ['HPHS', 'HDAM']

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Updating the Storage Capacity values for the conventional Hydro units
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [101]:
# 1. ------------------------------------ Find the CSV file in the directory that contains data_target_year in its name
reservoir_level_file = None
for file in os.listdir(reservoir_level_pypsa_raw_data_folder_path):
    if file.endswith(".csv") and str(data_target_year) in file:
        reservoir_level_file = file
        break

if reservoir_level_file is None:
    raise FileNotFoundError(f"No CSV file found containing {data_target_year} in the directory.")

# 2. ------------------------------------------------------------------------------------------------ Load the CSV file
csv_file_path = os.path.join(reservoir_level_pypsa_raw_data_folder_path, reservoir_level_file)
reservoir_level_df = pd.read_csv(csv_file_path)

# 3. ----------------------------------------------------------------------------------- Process each column in the CSV
for col in reservoir_level_df.columns:
    
    # 3.1. ----------------------------------- Extract the zone part from the column name (e.g., "GB0" from "GB0 0 PHS")
    col_zone_part = col.split()[0]  # e.g., "GB0" or "BE1"

    # 3.2. --------------------- Map the extracted zone part to the correct zone name using zone_names_equivalences_dict
    mapped_zone = None
    for zone_key, zone_info in zone_names_equivalences_dict.items():
        
        # 3.2.1. ------------------------- Check if the column zone part starts with the zone key or any of its acronyms
        if col_zone_part.startswith(zone_key) or any(col_zone_part.startswith(acronym) for acronym in zone_info["Acronym"]):
            mapped_zone = zone_key
            break

    if mapped_zone is None:
        continue  # Skip if no mapping is found

    # 3.3. ------------------------------------------------------------------- Check if the mapped zone is in zone_names
    if mapped_zone not in zone_names:
        continue  # Skip if the mapped zone is not in zone_names

    # 3.4. ----------------------------------------------------------------------- Get the DataFrame for the mapped zone
    df_key = f"{mapped_zone}_{data_target_year}"
    if df_key not in processed_power_plants_dfs_dict:
        continue  # Skip if the DataFrame does not exist

    df = processed_power_plants_dfs_dict[df_key]

    # 3.5. ---------------------------------- Process the column: get max value, match tech part, and update STOCapacity
    max_value = reservoir_level_df[col].max()
    tech_part = col.split()[-1]  # e.g., "PHS" or "hydro"

    matching_key = None
    for key, value in hydro_tech_equivalences_dict.items():
        if tech_part in value.get("tech", []):
            matching_key = key
            break

    if matching_key is None:
        continue  # Skip if no matching key is found

    # 3.6. ------------------------------------------ Update STOCapacity for rows where Technology matches the tech part
    mask = df["Technology"] == matching_key
    if mask.any():
        df.loc[mask, "STOCapacity"] = max_value

    # 3.7. ---------------------------------------------------------------------- Update the DataFrame in the dictionary
    processed_power_plants_dfs_dict[df_key] = df

# 4. -------------------------------------------------------------------------------------------------------------- Done
processed_power_plants_dfs_dict

{'BE_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 25         NaN              links residential rural air heat pump
 26         NaN           links residential rural ground heat pump
 27         NaN           links residential rural resistive heater
 28         NaN    links residential urban decentral air heat pump
 29         NaN  links residential urban decentral resistive he...
 30         NaN                 links services rural air heat pump
 31         NaN              links services rural ground heat pump
 32         NaN              links services rural resistive heater
 33         NaN       links services urban decentral air heat pump
 34         NaN    links services urban decentral resistive heater
 35         NaN                  links urban central air heat pump
 36         NaN                      links urban central gas CHP_1
 37         NaN                      links urban central gas CHP_2
 38         NaN                      links urban central gas CHP_3
 39         NaN                      links urban central gas CHP_4
 41         NaN               links urban central resistive heater
 42         NaN            links urban central solid biomass CHP_1
 43         NaN            links urban central solid biomass CHP_2
 46         NaN                                  storage_units PHS
 47         NaN                                storage_units hydro
 48         NaN                                       links CCGT_1
 50         NaN                                       links CCGT_3
 51         NaN                                       links OCGT_1
 53         NaN                                       links OCGT_3
 55         NaN                                       links OCGT_5

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0     1549.800000       1   BE      NaN      NaN       WTOF  WIN      1.0000
 1     1738.199046       1   BE      NaN      NaN       WTOF  WIN      1.0000
 2     4712.000935       1   BE      NaN      NaN       WTOF  WIN      1.0000
 3     7247.152421       1   BE      NaN      NaN       WTON  WIN      1.0000
 4       59.015340       1   BE      NaN      NaN       HROR  WAT      1.0000
 5    12000.040687       1   BE      NaN      NaN       PHOT  SUN      1.0000
 6    36199.942807       1   BE      NaN      NaN       PHOT  SUN      1.0000
 7     3463.799351       1   BE      NaN      NaN       PEME  ELE      0.7000
 8     1731.899675       1   BE      NaN      NaN       ALKE  ELE      0.7875
 9      865.949838       1   BE      NaN      NaN       SOXE  ELE      0.9625
 10    1918.426570       1   BE      NaN      NaN       PEFC  HYD      0.7000
 11     959.213285       1   BE      NaN      NaN       SOFC  HYD      0.7500
 12     479.606642       1   BE      NaN      NaN       MCFC  HYD      0.7250
 13     239.803321       1   BE      NaN      NaN       PAFC  HYD      0.6750
 14     119.901661       1   BE      NaN      NaN       ALFC  HYD      0.7500
 15      59.950830       1   BE      NaN      NaN       REFC  HYD      0.6750
 16    1909.194752       1   BE      NaN      NaN       GTUR  HYD      0.4000
 17     954.597376       1   BE      NaN      NaN       COMC  HYD      0.5250
 18     477.298688       1   BE      NaN      NaN       ICEN  HYD      0.4210
 19       0.012563       1   BE      NaN      NaN       HBBS  ELE      0.8750
 20   34022.652950       1   BE      NaN      NaN       BEVS  ELE      0.9500
 21       2.106993       1   BE      NaN      NaN       P2BS  ELE      0.5000
 22   10503.691027       1   BE      NaN      NaN       BATS  ELE      0.9350
 23     941.731454       1   BE      NaN      NaN       P2BS  ELE      0.5500
 24       0.077127       1   BE      NaN      NaN       STUR  NUC      0.3800
 25       0.016804       1   BE      NaN      NaN       ASHP  ELE      1.0000
 26     148.409598       1   BE      NaN      NaN       GSHP  ELE      1.0000
 27      53.877530       1   BE      NaN      NaN       REHE  ELE      1.0000
 28    1752.152824       1   BE      NaN      NaN       ASHP  ELE      1.0000
 29    1865.287169       1   BE      NaN      NaN       REHE  ELE      1.0000
 30       0.018477       1   BE      NaN      NaN       ASHP  ELE      1.0000
 31     160.364599       1   BE      NaN      NaN       GSHP  ELE      1.0000
 32      44.623008       1   BE      NaN      NaN       REHE  ELE      1.0000
 33     441.106458       1   BE      NaN      NaN       ASHP  ELE      1.0000
 34     698.614651       1   BE      NaN      NaN       REHE  ELE      1.0000
 35      97.131676       1   BE      NaN      NaN       ASHP  ELE      1.0000
 36    1720.820370       1   BE      NaN      NaN       COMC  GAS      0.5250
 37     860.410185       1   BE      NaN      NaN       GTUR  GAS      0.4000
 38     430.205093       1   BE      NaN      NaN       STUR  GAS      0.4600
 39     215.102546       1   BE      NaN      NaN       ICEN  GAS      0.4210
 41    7197.184446       1   BE      NaN      NaN       REHE  ELE      1.0000
 42    1340.037366       1   BE      NaN      NaN       STUR  BIO      0.4050
 43     670.018683       1   BE      NaN      NaN       ICEN  BIO      0.4210
 46    1308.000000       1   BE      NaN      NaN       HPHS  WAT      0.8000
 47      12.735669       1   BE      NaN      NaN       HDAM  WAT      0.8000
 48    2518.604117       1   BE      NaN      NaN       COMC  GAS      0.5250
 50     132.558111       1   BE      NaN      NaN       COMC  BIO      0.5250
 51    4767.455430       1   BE      NaN      NaN       GTUR  GAS      0.4000
 53     264.858635       1   BE      NaN      NaN       GTUR  OIL      0.4000
 55     264.858635       1   BE      NaN      NaN       GTUR  BIO      0.4000

     ...  STOMaxChargingPower  STOChargingEfficiency  WaterWithdrawal  \
 0   ...                  NaN                    NaN              NaN
 1   ...                  NaN                    NaN              NaN
 2   ...                  NaN                    NaN              NaN
 3   ...                  NaN                    NaN              NaN
 4   ...                  NaN                    NaN              NaN
 5   ...                  NaN                    NaN              NaN
 6   ...                  NaN                    NaN              NaN
 7   ...                  NaN                    NaN              NaN
 8   ...                  NaN                    NaN              NaN
 9   ...                  NaN                    NaN              NaN
 10  ...                  NaN                    NaN              NaN
 11  ...                  NaN                    NaN              NaN
 12  ...                  NaN                    NaN              NaN
 13  ...                  NaN                    NaN              NaN
 14  ...                  NaN                    NaN              NaN
 15  ...                  NaN                    NaN              NaN
 16  ...                  NaN                    NaN              NaN
 17  ...                  NaN                    NaN              NaN
 18  ...                  NaN                    NaN              NaN
 19  ...                  NaN                    NaN              NaN
 20  ...               2276.0                  0.950              NaN
 21  ...                  NaN                    NaN              NaN
 22  ...                  5.0                  0.935              NaN
 23  ...                  NaN                    NaN              NaN
 24  ...                  NaN                    NaN              NaN
 25  ...                  NaN                    NaN              NaN
 26  ...                  NaN                    NaN              NaN
 27  ...                  NaN                    NaN              NaN
 28  ...                  NaN                    NaN              NaN
 29  ...                  NaN                    NaN              NaN
 30  ...                  NaN                    NaN              NaN
 31  ...                  NaN                    NaN              NaN
 32  ...                  NaN                    NaN              NaN
 33  ...                  NaN                    NaN              NaN
 34  ...                  NaN                    NaN              NaN
 35  ...                  NaN                    NaN              NaN
 36  ...                  NaN                    NaN              NaN
 37  ...                  NaN                    NaN              NaN
 38  ...                  NaN                    NaN              NaN
 39  ...                  NaN                    NaN              NaN
 41  ...                  NaN                    NaN              NaN
 42  ...                  NaN                    NaN              NaN
 43  ...                  NaN                    NaN              NaN
 46  ...               1308.0                  0.800              NaN
 47  ...                  0.0                  0.800              NaN
 48  ...                  NaN                    NaN              NaN
 50  ...                  NaN                    NaN              NaN
 51  ...                  NaN                    NaN              NaN
 53  ...                  NaN                    NaN              NaN
 55  ...                  NaN                    NaN              NaN

     WaterConsumption  Status  Source  Company  Lat  Lon  Lat/Lon
 0                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 1                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 2                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 3                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 4                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 5                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 6                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 7                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 8                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 9                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 10               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 11               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 12               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 13               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 14               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 15               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 16               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 17               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 18               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 19               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 20               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 21               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 22               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 23               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 24               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 25               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 26               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 27               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 28               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 29               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 30               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 31               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 32               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 33               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 34               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 35               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 36               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 37               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 38               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 39               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 41               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 42               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 43               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 46               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 47               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 48               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 50               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 51               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 53               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 55               NaN     NaN     NaN      NaN  NaN  NaN      NaN

 [50 rows x 41 columns],
 'FR_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 28         NaN              links residential rural air heat pump
 29         NaN           links residential rural ground heat pump
 30         NaN           links residential rural resistive heater
 31         NaN    links residential urban decentral air heat pump
 32         NaN  links residential urban decentral resistive he...
 33         NaN                 links services rural air heat pump
 34         NaN              links services rural ground heat pump
 35         NaN              links services rural resistive heater
 36         NaN       links services urban decentral air heat pump
 37         NaN    links services urban decentral resistive heater
 38         NaN                  links urban central air heat pump
 39         NaN                      links urban central gas CHP_1
 40         NaN                      links urban central gas CHP_2
 41         NaN                      links urban central gas CHP_3
 42         NaN                      links urban central gas CHP_4
 44         NaN               links urban central resistive heater
 45         NaN            links urban central solid biomass CHP_1
 46         NaN            links urban central solid biomass CHP_2
 49         NaN                                  storage_units PHS
 50         NaN                                storage_units hydro
 51         NaN                                       links CCGT_1
 53         NaN                                       links CCGT_3
 54         NaN                                       links OCGT_1
 56         NaN                                       links OCGT_3
 58         NaN                                       links OCGT_5

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0      480.000000       1   FR      NaN      NaN       WTOF  WIN      1.0000
 1    24631.595406       1   FR      NaN      NaN       WTOF  WIN      1.0000
 2     4617.910333       1   FR      NaN      NaN       WTOF  WIN      1.0000
 3    63322.378275       1   FR      NaN      NaN       WTON  WIN      1.0000
 4     6870.649149       1   FR      NaN      NaN       HROR  WAT      1.0000
 5    17024.222292       1   FR      NaN      NaN       PHOT  SUN      1.0000
 6   175286.554430       1   FR      NaN      NaN       PHOT  SUN      1.0000
 7     2523.304011       1   FR      NaN      NaN       PEME  ELE      0.7000
 8     1261.652005       1   FR      NaN      NaN       ALKE  ELE      0.7875
 9      630.826003       1   FR      NaN      NaN       SOXE  ELE      0.9625
 10    2318.931377       1   FR      NaN      NaN       PEFC  HYD      0.7000
 11    1159.465689       1   FR      NaN      NaN       SOFC  HYD      0.7500
 12     579.732844       1   FR      NaN      NaN       MCFC  HYD      0.7250
 13     289.866422       1   FR      NaN      NaN       PAFC  HYD      0.6750
 14     144.933211       1   FR      NaN      NaN       ALFC  HYD      0.7500
 15      72.466606       1   FR      NaN      NaN       REFC  HYD      0.6750
 16       0.083942       1   FR      NaN      NaN       GTUR  HYD      0.2400
 17       0.041971       1   FR      NaN      NaN       COMC  HYD      0.5250
 18       0.020986       1   FR      NaN      NaN       ICEN  HYD      0.4900
 19       0.018230       1   FR      NaN      NaN       HBBS  ELE      0.8750
 20  195572.300000       1   FR      NaN      NaN       BEVS  ELE      0.9500
 21     362.476758       1   FR      NaN      NaN       P2BS  ELE      0.5500
 22   36968.817334       1   FR      NaN      NaN       BATS  ELE      0.9350
 23     741.038767       1   FR      NaN      NaN       P2BS  ELE      0.5500
 24    2660.044043       1   FR      NaN      NaN       STUR  NUC      0.4050
 28       0.019334       1   FR      NaN      NaN       ASHP  ELE      1.0000
 29    1486.186677       1   FR      NaN      NaN       GSHP  ELE      1.0000

<div style="background-color: black;">
<hr style="border: 0.5px solid skyblue;">
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
For the specific case of Electric Vehicle (EV) technology, since no data was found in the PyPSA database, the STOCapacity value will be estimated using the following correlation:
\[
\text{STOCapacity} = P_{\text{EV}} \times \text{E/P}
\]
\[
\text{E/P} = 7 \ \text{h}
\]
where $P_{\text{EV}}$ is the aggregated charging/discharging power of the EV fleet (MW)
<br>
STOCapacity is the aggregated usable storage capacity of the EV fleet (MWh)
<br>
and E/P is the effective energy-to-power ratio of the EV fleet (h), here assumed to be 7 h.
<ol style="margin-top: 0; padding-left: 3.5em;">
<li>
Fraunhofer ISE & ISI. (2024). Potential of a full EV-power-system-integration in Europe and how to realise it.
<br>
<a href="https://www.transportenvironment.org/uploads/files/2024_10_Study_V2G_EU-Potential_Final.pdf" style="color:skyblue">https://www.transportenvironment.org/uploads/files/2024_10_Study_V2G_EU-Potential_Final.pdf</a>
</li>
</ol>
</div>
<hr style="border: 0.5px solid skyblue;">
</div>

In [102]:
# 1. ---------------------------------------------------------------------------------------- Iterate through the zones
for zone in zone_names:
    # 1.1 ------------------------------------------------------------------------ Construct the key for the dictionary
    key = f"{zone}_{data_target_year}"

    # 1.2. ------------------------------------------------------------------ Check if the key exists in the dictionary
    if key in processed_power_plants_dfs_dict:
        df = processed_power_plants_dfs_dict[key]

        # 1.2.1. ----------------------------------------------------------- Identify rows where 'Technology' is 'BEVS'
        bevs_mask = df['Technology'] == 'BEVS'

        # 1.2.2. ----------------------------------------------- Multiply 'PowerCapacity' by 7 and update 'STOCapacity'
        df.loc[bevs_mask, 'STOCapacity'] = df.loc[bevs_mask, 'PowerCapacity'] * 7

        # 1.2.3. --------------------------------------------------- Optionally, update the DataFrame in the dictionary
        processed_power_plants_dfs_dict[key] = df
        
# 2. ------------------------------------------------------------------------------------------------------------- Done
processed_power_plants_dfs_dict

{'BE_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 25         NaN              links residential rural air heat pump
 26         NaN           links residential rural ground heat pump
 27         NaN           links residential rural resistive heater
 28         NaN    links residential urban decentral air heat pump
 29         NaN  links residential urban decentral resistive he...
 30         NaN                 links services rural air heat pump
 31         NaN              links services rural ground heat pump
 32         NaN              links services rural resistive heater
 33         NaN       links services urban decentral air heat pump
 34         NaN    links services urban decentral resistive heater
 35         NaN                  links urban central air heat pump
 36         NaN                      links urban central gas CHP_1
 37         NaN                      links urban central gas CHP_2
 38         NaN                      links urban central gas CHP_3
 39         NaN                      links urban central gas CHP_4
 41         NaN               links urban central resistive heater
 42         NaN            links urban central solid biomass CHP_1
 43         NaN            links urban central solid biomass CHP_2
 46         NaN                                  storage_units PHS
 47         NaN                                storage_units hydro
 48         NaN                                       links CCGT_1
 50         NaN                                       links CCGT_3
 51         NaN                                       links OCGT_1
 53         NaN                                       links OCGT_3
 55         NaN                                       links OCGT_5

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0     1549.800000       1   BE      NaN      NaN       WTOF  WIN      1.0000
 1     1738.199046       1   BE      NaN      NaN       WTOF  WIN      1.0000
 2     4712.000935       1   BE      NaN      NaN       WTOF  WIN      1.0000
 3     7247.152421       1   BE      NaN      NaN       WTON  WIN      1.0000
 4       59.015340       1   BE      NaN      NaN       HROR  WAT      1.0000
 5    12000.040687       1   BE      NaN      NaN       PHOT  SUN      1.0000
 6    36199.942807       1   BE      NaN      NaN       PHOT  SUN      1.0000
 7     3463.799351       1   BE      NaN      NaN       PEME  ELE      0.7000
 8     1731.899675       1   BE      NaN      NaN       ALKE  ELE      0.7875
 9      865.949838       1   BE      NaN      NaN       SOXE  ELE      0.9625
 10    1918.426570       1   BE      NaN      NaN       PEFC  HYD      0.7000
 11     959.213285       1   BE      NaN      NaN       SOFC  HYD      0.7500
 12     479.606642       1   BE      NaN      NaN       MCFC  HYD      0.7250
 13     239.803321       1   BE      NaN      NaN       PAFC  HYD      0.6750
 14     119.901661       1   BE      NaN      NaN       ALFC  HYD      0.7500
 15      59.950830       1   BE      NaN      NaN       REFC  HYD      0.6750
 16    1909.194752       1   BE      NaN      NaN       GTUR  HYD      0.4000
 17     954.597376       1   BE      NaN      NaN       COMC  HYD      0.5250
 18     477.298688       1   BE      NaN      NaN       ICEN  HYD      0.4210
 19       0.012563       1   BE      NaN      NaN       HBBS  ELE      0.8750
 20   34022.652950       1   BE      NaN      NaN       BEVS  ELE      0.9500
 21       2.106993       1   BE      NaN      NaN       P2BS  ELE      0.5000
 22   10503.691027       1   BE      NaN      NaN       BATS  ELE      0.9350
 23     941.731454       1   BE      NaN      NaN       P2BS  ELE      0.5500
 24       0.077127       1   BE      NaN      NaN       STUR  NUC      0.3800
 25       0.016804       1   BE      NaN      NaN       ASHP  ELE      1.0000
 26     148.409598       1   BE      NaN      NaN       GSHP  ELE      1.0000
 27      53.877530       1   BE      NaN      NaN       REHE  ELE      1.0000
 28    1752.152824       1   BE      NaN      NaN       ASHP  ELE      1.0000
 29    1865.287169       1   BE      NaN      NaN       REHE  ELE      1.0000
 30       0.018477       1   BE      NaN      NaN       ASHP  ELE      1.0000
 31     160.364599       1   BE      NaN      NaN       GSHP  ELE      1.0000
 32      44.623008       1   BE      NaN      NaN       REHE  ELE      1.0000
 33     441.106458       1   BE      NaN      NaN       ASHP  ELE      1.0000
 34     698.614651       1   BE      NaN      NaN       REHE  ELE      1.0000
 35      97.131676       1   BE      NaN      NaN       ASHP  ELE      1.0000
 36    1720.820370       1   BE      NaN      NaN       COMC  GAS      0.5250
 37     860.410185       1   BE      NaN      NaN       GTUR  GAS      0.4000
 38     430.205093       1   BE      NaN      NaN       STUR  GAS      0.4600
 39     215.102546       1   BE      NaN      NaN       ICEN  GAS      0.4210
 41    7197.184446       1   BE      NaN      NaN       REHE  ELE      1.0000
 42    1340.037366       1   BE      NaN      NaN       STUR  BIO      0.4050
 43     670.018683       1   BE      NaN      NaN       ICEN  BIO      0.4210
 46    1308.000000       1   BE      NaN      NaN       HPHS  WAT      0.8000
 47      12.735669       1   BE      NaN      NaN       HDAM  WAT      0.8000
 48    2518.604117       1   BE      NaN      NaN       COMC  GAS      0.5250
 50     132.558111       1   BE      NaN      NaN       COMC  BIO      0.5250
 51    4767.455430       1   BE      NaN      NaN       GTUR  GAS      0.4000
 53     264.858635       1   BE      NaN      NaN       GTUR  OIL      0.4000
 55     264.858635       1   BE      NaN      NaN       GTUR  BIO      0.4000

     ...  STOMaxChargingPower  STOChargingEfficiency  WaterWithdrawal  \
 0   ...                  NaN                    NaN              NaN
 1   ...                  NaN                    NaN              NaN
 2   ...                  NaN                    NaN              NaN
 3   ...                  NaN                    NaN              NaN
 4   ...                  NaN                    NaN              NaN
 5   ...                  NaN                    NaN              NaN
 6   ...                  NaN                    NaN              NaN
 7   ...                  NaN                    NaN              NaN
 8   ...                  NaN                    NaN              NaN
 9   ...                  NaN                    NaN              NaN
 10  ...                  NaN                    NaN              NaN
 11  ...                  NaN                    NaN              NaN
 12  ...                  NaN                    NaN              NaN
 13  ...                  NaN                    NaN              NaN
 14  ...                  NaN                    NaN              NaN
 15  ...                  NaN                    NaN              NaN
 16  ...                  NaN                    NaN              NaN
 17  ...                  NaN                    NaN              NaN
 18  ...                  NaN                    NaN              NaN
 19  ...                  NaN                    NaN              NaN
 20  ...               2276.0                  0.950              NaN
 21  ...                  NaN                    NaN              NaN
 22  ...                  5.0                  0.935              NaN
 23  ...                  NaN                    NaN              NaN
 24  ...                  NaN                    NaN              NaN
 25  ...                  NaN                    NaN              NaN
 26  ...                  NaN                    NaN              NaN
 27  ...                  NaN                    NaN              NaN
 28  ...                  NaN                    NaN              NaN
 29  ...                  NaN                    NaN              NaN
 30  ...                  NaN                    NaN              NaN
 31  ...                  NaN                    NaN              NaN
 32  ...                  NaN                    NaN              NaN
 33  ...                  NaN                    NaN              NaN
 34  ...                  NaN                    NaN              NaN
 35  ...                  NaN                    NaN              NaN
 36  ...                  NaN                    NaN              NaN
 37  ...                  NaN                    NaN              NaN
 38  ...                  NaN                    NaN              NaN
 39  ...                  NaN                    NaN              NaN
 41  ...                  NaN                    NaN              NaN
 42  ...                  NaN                    NaN              NaN
 43  ...                  NaN                    NaN              NaN
 46  ...               1308.0                  0.800              NaN
 47  ...                  0.0                  0.800              NaN
 48  ...                  NaN                    NaN              NaN
 50  ...                  NaN                    NaN              NaN
 51  ...                  NaN                    NaN              NaN
 53  ...                  NaN                    NaN              NaN
 55  ...                  NaN                    NaN              NaN

     WaterConsumption  Status  Source  Company  Lat  Lon  Lat/Lon
 0                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 1                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 2                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 3                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 4                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 5                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 6                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 7                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 8                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 9                NaN     NaN     NaN      NaN  NaN  NaN      NaN
 10               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 11               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 12               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 13               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 14               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 15               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 16               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 17               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 18               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 19               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 20               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 21               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 22               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 23               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 24               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 25               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 26               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 27               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 28               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 29               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 30               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 31               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 32               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 33               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 34               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 35               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 36               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 37               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 38               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 39               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 41               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 42               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 43               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 46               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 47               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 48               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 50               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 51               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 53               NaN     NaN     NaN      NaN  NaN  NaN      NaN
 55               NaN     NaN     NaN      NaN  NaN  NaN      NaN

 [50 rows x 41 columns],
 'FR_2050':     Unnamed: 0                                               Unit  \
 0          NaN                                 generators offwind
 1          NaN                              generators offwind-ac
 2          NaN                              generators offwind-dc
 3          NaN                                  generators onwind
 4          NaN                                     generators ror
 5          NaN                                   generators solar
 6          NaN                           generators solar rooftop
 7          NaN                            links H2 Electrolysis_1
 8          NaN                            links H2 Electrolysis_2
 9          NaN                            links H2 Electrolysis_3
 10         NaN                               links H2 Fuel Cell_1
 11         NaN                               links H2 Fuel Cell_2
 12         NaN                               links H2 Fuel Cell_3
 13         NaN                               links H2 Fuel Cell_4
 14         NaN                               links H2 Fuel Cell_5
 15         NaN                               links H2 Fuel Cell_6
 16         NaN                                 links H2 turbine_1
 17         NaN                                 links H2 turbine_2
 18         NaN                                 links H2 turbine_3
 19         NaN                                  links Haber-Bosch
 20         NaN                                          links V2G
 21         NaN                              links ammonia cracker
 22         NaN                           links battery discharger
 23         NaN                              links methanolisation
 24         NaN                                      links nuclear
 28         NaN              links residential rural air heat pump
 29         NaN           links residential rural ground heat pump
 30         NaN           links residential rural resistive heater
 31         NaN    links residential urban decentral air heat pump
 32         NaN  links residential urban decentral resistive he...
 33         NaN                 links services rural air heat pump
 34         NaN              links services rural ground heat pump
 35         NaN              links services rural resistive heater
 36         NaN       links services urban decentral air heat pump
 37         NaN    links services urban decentral resistive heater
 38         NaN                  links urban central air heat pump
 39         NaN                      links urban central gas CHP_1
 40         NaN                      links urban central gas CHP_2
 41         NaN                      links urban central gas CHP_3
 42         NaN                      links urban central gas CHP_4
 44         NaN               links urban central resistive heater
 45         NaN            links urban central solid biomass CHP_1
 46         NaN            links urban central solid biomass CHP_2
 49         NaN                                  storage_units PHS
 50         NaN                                storage_units hydro
 51         NaN                                       links CCGT_1
 53         NaN                                       links CCGT_3
 54         NaN                                       links OCGT_1
 56         NaN                                       links OCGT_3
 58         NaN                                       links OCGT_5

     PowerCapacity  Nunits Zone  Zone_th  Zone_h2 Technology Fuel  Efficiency  \
 0      480.000000       1   FR      NaN      NaN       WTOF  WIN      1.0000
 1    24631.595406       1   FR      NaN      NaN       WTOF  WIN      1.0000
 2     4617.910333       1   FR      NaN      NaN       WTOF  WIN      1.0000
 3    63322.378275       1   FR      NaN      NaN       WTON  WIN      1.0000
 4     6870.649149       1   FR      NaN      NaN       HROR  WAT      1.0000
 5    17024.222292       1   FR      NaN      NaN       PHOT  SUN      1.0000
 6   175286.554430       1   FR      NaN      NaN       PHOT  SUN      1.0000
 7     2523.304011       1   FR      NaN      NaN       PEME  ELE      0.7000
 8     1261.652005       1   FR      NaN      NaN       ALKE  ELE      0.7875
 9      630.826003       1   FR      NaN      NaN       SOXE  ELE      0.9625
 10    2318.931377       1   FR      NaN      NaN       PEFC  HYD      0.7000
 11    1159.465689       1   FR      NaN      NaN       SOFC  HYD      0.7500
 12     579.732844       1   FR      NaN      NaN       MCFC  HYD      0.7250
 13     289.866422       1   FR      NaN      NaN       PAFC  HYD      0.6750
 14     144.933211       1   FR      NaN      NaN       ALFC  HYD      0.7500
 15      72.466606       1   FR      NaN      NaN       REFC  HYD      0.6750
 16       0.083942       1   FR      NaN      NaN       GTUR  HYD      0.2400
 17       0.041971       1   FR      NaN      NaN       COMC  HYD      0.5250
 18       0.020986       1   FR      NaN      NaN       ICEN  HYD      0.4900
 19       0.018230       1   FR      NaN      NaN       HBBS  ELE      0.8750
 20  195572.300000       1   FR      NaN      NaN       BEVS  ELE      0.9500
 21     362.476758       1   FR      NaN      NaN       P2BS  ELE      0.5500
 22   36968.817334       1   FR      NaN      NaN       BATS  ELE      0.9350
 23     741.038767       1   FR      NaN      NaN       P2BS  ELE      0.5500
 24    2660.044043       1   FR      NaN      NaN       STUR  NUC      0.4050
 28       0.019334       1   FR      NaN      NaN       ASHP  ELE      1.0000
 29    1486.186677       1   FR      NaN      NaN       GSHP  ELE      1.0000

<div style="background-color: black;">
    <hr style="border: 2px solid skyblue;">
    <div style="text-align: justify; margin-left: 3.0em; font-weight: bold; font-size: 18px; font-family: TimesNewRoman; color:skyblue">
9. Final Formatted Data Storage
    </div>
    <div style="text-align: justify; margin-left: 0.0em; font-weight: unbold; font-size: 14px; font-family: TimesNewRoman; color:skyblue">
Once the cleaned data has been obtained, it must be stored in the appropriate location within the Dispa-SET database file structure.
    <br>
A dedicated folder, named "Database_PyPSA", has been created to house all data related to the NEGAWAT project.
    <br>
This folder contains two primary subfolders corresponding to the project scenarios: "Reference_Scenario" and "Suficiency_Scenario".
        <br>
Each scenario subfolder contains nested sub-subfolders, each named using the acronym of a corresponding EU country.
        <br>
The processed and cleaned DataFrames are stored within their respective country sub-subfolders. Each DataFrame is converted into a .csv file and named after the processed year (e.g., `2030.csv`).
    </div>
    <hr style="border: 0.5px solid skyblue;">
</div>

In [103]:
# 1. --------------------------------------------------------------------------------- Ensure the base directory exists
os.makedirs(power_plants_pypsa_formated_data_folder_path, exist_ok=True)

# 2. --------------------------------------------------------------- Save each DataFrame to its corresponding subfolder
for key, df in processed_power_plants_dfs_dict.items():
    # Extract the zone from the key (e.g., 'BE_2030' -> 'BE')
    zone = key.split('_')[0]

    # 2.1. ---------------------------------------------------------------- Check if the zone is in the zone_names list
    if zone not in zone_names:
        print(f"Zone '{zone}' not in zone_names list. Skipping.")
        continue

    # 2.2. ---------------------------------------------------------------------------------- Create the subfolder path
    subfolder_path = os.path.join(power_plants_pypsa_formated_data_folder_path, zone)
    os.makedirs(subfolder_path, exist_ok=True)

    # 2.3. ---------------------------------------------------------------------------------------- Define the filename
    filename = f"{data_target_year}.csv"
    filepath = os.path.join(subfolder_path, filename)

    # 2.4. --------------------------------------------------------------------------- Save the DataFrame as a CSV file
    df.to_csv(filepath, index=False)

# 2. ------------------------------------------------------------------------------------------------------------- Done
    print(f"Saved {key} to {filepath}")

Saved BE_2050 to /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants/BE/2050.csv
Saved FR_2050 to /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants/FR/2050.csv
Saved DE_2050 to /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants/DE/2050.csv
Saved NL_2050 to /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants/NL/2050.csv
Saved UK_2050 to /home/ray/Dispa-SET_Unleash/Database_PyPSA/Sufficiency_Scenario/PowerPlants/UK/2050.csv

<div style="background-color: black;">
<hr style="border: 4px solid skyblue;">
</div>